ponylang/ponyc

README.md

I've created a new emacs mode for Pony and added a link to it in the README.

Added link to Emacs mode.

---

Makefile
packages/builtin/platform.pony
src/common/platform.h
src/libponyc/codegen/genexe.c
src/libponyc/pkg/package.c
src/libponyc/pkg/platformfuns.c
src/libponyc/pkg/platformfuns.h
src/libponyrt/asio/asio.h
src/libponyrt/asio/kqueue.c
src/libponyrt/lang/lsda.h
src/libponyrt/lang/socket.c
src/libponyrt/sched/cpu.c
test/libponyc/use.cc

Linking ponyc
build/debug/libponyrt.a(pool.o): In function `pool_push':
/home/ben/git-work/ponyc/src/libponyrt/mem/pool.c:111: undefined reference to `__atomic_compare_exchange'
build/debug/libponyrt.a(pool.o): In function `pool_pull':
/home/ben/git-work/ponyc/src/libponyrt/mem/pool.c:133: undefined reference to `__atomic_compare_exchange'
c++: error: linker command failed with exit code 1 (use -v to see invocation)
Makefile:392: recipe for target 'build/debug/ponyc' failed
gmake: *** [build/debug/ponyc] Error 1

Port to FreeBSD

---

README.md

Add Gentoo bug 457530 hotfix link to build instructions

---

.gitignore
packages/ponytest/helper.pony
packages/regex/match.pony
packages/regex/regex.pony
packages/regex/test.pony
packages/stdlib/test.pony

I am new to pony and haven't internalized its naming conventions yet, so I won't take offense if you pick on small details like naming.

Adds support for Regex.split() and helpers along the way

---

examples/delegates/main.pony

Add consolidated examples from the basic delegate tutorial

Add delegate example

---

CONTRIBUTION.md

Guide is created with a few goals in mind:
- It should be short and easy to read.
- GitHub's issues as main tool for coordination. They are close to the
code and maintain history.
- Encourage discussion to achieve best results and avoid unnecessary
work or rework. This improves satisfaction for both sides.
- Make contributions focused by agreeing on solution and scope.
#352

Describe basics for contributing to Pony

---

packages/builtin/string.pony

My very first tiny Pony commit to get myself unstuck from my writer's block :)
I did this in a way similar to String to I** conversions.
But I wonder if it would be better to have the String to X conversions included in the X classes

Added a bool() method to String to provide String to Bool conversion

---

README.md

Sean has taken over maintenance of the emacs ponylang mode.

Update to new canonical emacs ponylang-mode

---

packages/ponytest/helper.pony

These are the counterparts of `assert_is` and `assert_eq`.

Provide `assert_isnt` and `assert_ne`

---

packages/builtin_test/test.pony

- Simplified `Array.insert()` tests
- Tested for error when inserting at invalid index

Array insert improved tests

---

examples/ffi-struct/struct.c
examples/ffi-struct/struct.pony

Small example of Pony structs and how to pass them to C.

FFI struct example

---

packages/regex/regex.pony

These are incomplete but its a start.

Add regex package documentation

---

src/libponyc/pass/docgen.c

First steps towards making the generated
documentation more readable.

Spiff up documentation formatting

---

src/common/paths.h
src/libponyc/pass/docgen.c
src/libponyc/pkg/package.c
src/libponyc/platform/paths.c
src/libponyrt/lang/directory.c

use readdir instead of readdir_r

---

src/libponyc/ast/id.c
src/libponyc/ast/id.h
src/libponyc/ast/symtab.c
src/libponyc/expr/postfix.c
src/libponyc/expr/reference.c
src/libponyc/pass/docgen.c
src/libponyc/pass/import.c
src/libponyc/pass/names.c
src/libponyc/pass/names.h
src/libponyc/pass/sugar.c
src/libponyc/type/lookup.c
test/libponyc/id.cc

Fixes for issues addressed in PR #598 regarding changes there.

Fix and move name check predicates, and add tests for them

---

packages/random/random.pony

Also adds some basic docs on Random trait.

Add basic Random package documentation.

---

packages/math/fibonacci.pony

I *might* have played this one pretty tongue in cheek.

Add math package documentation

---

test/libponyc/literal_inference.cc
test/libponyc/util.cc

@andymcn - does this look like the kind of thing you want for #570 ?
Future extensions that I can think of
- other numeric types
- literals passed to functions
- literals in tuples
- generics

Additions to tests for literal inference

---

CHANGELOG.md
packages/collections/map.pony
packages/ini/ini.pony
packages/ini/inimap.pony
packages/ini/test.pony

* Also added contains() method to HashMap

Add support for empty sections to ini parser

---

CHANGELOG.md
packages/builtin/string.pony
packages/builtin_test/test.pony

Rewrite compare_sub to perform lexical comparison.

---

test/libponyc/literal_inference.cc

This PR covers
- tuples: simple, nested, combined with generics
- simple passing & failing cases for all numeric types, and some non-numeric
Failing or questionable cases are marked FIXME
- chasing through generic types (though this perhaps not too interesting as can't subclass?)
- let x: (U128 | F64) = 36000.0 fails, though @andymcn thought it should pass
- can't infer through generic in second element of tuple
Let me know if you'd prefer these as issues

More literal inference tests: tuples & poking harder at simple cases

---

README.md

Works for llvm-3.8 both debug and release versions.

Provide Debian Jesse install instructions

---

README.md

Minor changes for Debian Jessie install instructions.

Update Debian Jessie install instructions

---

src/libponyc/codegen/codegen.c
src/libponyc/codegen/genexe.c
src/libponyc/codegen/genlib.c
src/libponyc/codegen/genobj.c
src/libponyc/codegen/genopt.cc
src/libponyc/codegen/gentype.c
src/libponyc/pass/docgen.c
src/libponyc/pass/pass.c
src/libponyc/pass/pass.h

Modify verbosity levels for compiler messages per the discussion in #655.

modify verbosity levels for compiler messages per #655

---

CHANGELOG.md
packages/logger/logger.pony
packages/logger/test.pony

@sylvanc this is mostly your code. anything here that should change, code or docs wise?
don't merge this, I need to add tests. opening now for early review that I can update.

Simple logger

---

README.md

gmake needs to be used instead of make

Fix FreeBSD build instructions

---

CHANGELOG.md
packages/net/tcpconnection.pony
packages/net/tcplistener.pony

Work for https://github.com/ponylang/ponyc/issues/653

Size parameter in TCPConnection and TCPListener

---

src/libponyc/pass/docgen.c

The previous format was hard to parse.
This introduces a much easier to read & parse layout.
It features a code block of the complete method signature
that is much easier to read than what their was before.
However, code blocks can't have links in them so we have
additional sections for the parameters and return types
that can continue to have links to documentation for other
classes.

Improve method documentation format

---

src/libponyc/pass/docgen.c

And actor and primitive. Now matches more in format
to new method documentation format.

Improve formatting of class documentation

---

src/libponyc/ast/ast.c
src/libponyc/ast/ast.h
src/libponyc/ast/astbuild.h

This PR adds the `ast_from_float function` and `FLOAT` macro for AST building, which mirror the `ast_from_int` function and `INT` macro.

Add ast_from_float function and FLOAT macro for AST building.

---

src/libponyc/ast/ast.c
src/libponyc/ast/ast.h

This PR is just a refactoring for how AST printing is done internally, to open us up to options of printing to other streams and files besides just stdout.

Refactor ast_print to ast_fprint to allow streams other than stdout.

---

CHANGELOG.md
packages/collections/persistent/list.pony
packages/collections/persistent/map.pony
packages/collections/persistent/persistent.pony
packages/collections/persistent/test.pony

List is a relatively straightforward (Cons[A] | Nil[A]) persistent list. 
Map is a persistent map based on Bagwell's hash array mapped trie algorithm.

Add persistent List, Map, and associated tests

---

CONTRIBUTING.md

There are some new points around style that should help keep the code
consistent. The main points are around naming (when to use snake_case
vs CamelCase), and how to break up long parameter lists.

Add style tips to contributing documentation

---

packages/collections/persistent/map.pony
packages/collections/persistent/persistent.pony
packages/collections/persistent/test.pony

This resolves #753 and maintains the existing API for collections/persistent/Map

Update Persistent Map

---

README.md

Fix broken IRC link in README.

---

packages/ini/ini.pony

Example needs updating with capabilities.

Fix example in ini.pony by adding AmbientAuth

---

CHANGELOG.md
packages/collections/map.pony

Its a wonderful standard pattern, give me this key or else
give me this default value. I've loved using it with PersistentMap
and would like to be able to use it on HashMap so, here it is!

Add HashMap.get_or_else

---

README.md

As requested, I wrote some instructions on building Pony on MIPS and ARM platforms.

Add words about building on ARM and MIPS

---

packages/net/test.pony

This PR shaves some more complexity off of writing new TCP tests by adding the `_TestTCP` class, a common `TCPListenNotify` implementation. You create the `_TestTCP` instance anf pass it the two `TCPConnectionNotify` classes you want to use (for the client and server side) and it handles the creation of the listener and connection sockets, and passing of your notifiers to them in the appropriate places.
The hope is that this makes it easier to write additional TCP tests to cover currently untested behaviour.

Refactor net TCP tests to use a common TCPListenNotify class.

---

packages/stdlib/test.pony

This PR will test collections/persistent along with the rest of the standard library and should allow docs for the package to be generated.

add collections/persistent to stdlib

---

CHANGELOG.md
src/libponyc/ast/parserapi.c

Fix late detection of errors silently emitted in lexer/parser.

---

CHANGELOG.md
src/libponyc/type/sanitise.c
test/libponyc/sugar.cc

Fix compiler crash on type alias of a lambda type.

---

packages/process/process-monitor.pony

The example code presented in the header of process-monitor.pony
needs to use a FilePath parameter.

Fix broken example for process package

---

README.md

Introduce another Vim plugin

---

src/libponyc/codegen/genopt.cc

A Dispatch function has a `pony_ctx_t` in its parameters. This optimisation pass replaces `pony_ctx` calls in Dispatch functions (mostly generated by inlining user functions) with uses of the parameter.

Add DispatchPonyCtx optimisation pass

---

CHANGELOG.md
src/libponyc/ast/ast.c
src/libponyc/ast/token.c
src/libponyc/ast/token.h
test/libponyc/token.cc

Fix AST Printing of string literals with quote characters.

---

src/libponyc/codegen/genopt.cc

This pass merges successive reallocations of the same variable in a single allocation.

Add MergeRealloc optimisation pass

---

src/libponyc/codegen/genopt.cc

Calls to `pony_alloc` are replaced by calls to `pony_alloc_small/large` when possible. No-op allocations and successive reallocations are handled much better.

Improve MergeRealloc optimisation pass

---

CHANGELOG.md
src/libponyc/expr/reference.c
test/libponyc/badpony.cc

Fix runtime crash when Main.create is a function.

---

packages/ponytest/ponytest.pony
packages/ponytest/unit.pony

Still thinking if it would be useful to have array of labels in place of single label :)

#640 PonyTest CLI option to include/exclude test cases by tag

---

README.md

added doc
1. Install ponyc on archlinux
2. Builld from the source on archlinux
tested succesfully to build both:
make config=release
make config=debug
llvm version 3.8.0.1

added archlinux to readme

---

examples/producer-consumer/buffer.pony
examples/producer-consumer/consumer.pony
examples/producer-consumer/main.pony
examples/producer-consumer/producer.pony
examples/producer-consumer/product.pony

This is mostly @danielaRiesgo work with a couple small
changes. You can see the original PR at:
https://github.com/ponylang/ponyc/pull/881

Add producer-consumer example

---

src/libponyc/codegen/genopt.cc

Fix build error when size_t is 32 bits wide

---

examples/delegates/main.pony

Fix wombat example

---

examples/yield/main.pony

Create on an actor has to be a constructor. Aka
'new create' not 'be create'.

Fix yield example

---

CHANGELOG.md
packages/builtin/string.pony
packages/builtin_test/test.pony

Fix for #963 with tests and minor cleanup.

Fix #963, read_int failure with signed integer

---

packages/builtin_test/test.pony

These tests fail before Sylvan's #946 PR.
@jemc - was #943 left open simply to get some tests like these?

Test addc() on various bit widths as requested for #943

---

src/libponyrt/gc/gc.c

A false assumption was made that a mutable remote object must be
known. The counter-example is that an embedded field of an iso
won't have its own foreign reference count, but can be assigned
to a field and traced, at which point an independent foreign
reference count must be generated.

Don't assert on unknown mutable remote objects

---

examples/ffi-struct/struct.pony

Added a comment to show how to build a shared library and a line to add the current directory to the search path for libraries.  This way new users need not install the compiled shared library to their system path.

Added comment to help new Users.

---

src/libponyrt/lang/socket.c

Set SIG_IGN on SIGPIPE. Previously, individual sockets were marked
with SO_NOSIGPIPE on OSX and FreeBSD, and individual calls to send
were flagged with MSG_NOSIGNAL on Linux. This only works with calls
to send, and not with write or writev.
Now, SIGPIPE is ignored by default. If an application wants access
to SIGPIPE, it is still available via the signals package.

Ignore SIGPIPE

---

packages/process/process-monitor.pony

Many programs (like cat) cannot handle non-blocking file descriptors.
This was causing a sporadic failure in the process monitor tests:
```
**** FAILED: process/STDIN-STDOUT
dispose: child exit code: 1
dispose: stdout: one, two, three
dispose: stderr: cat: -: Resource temporarily unavailable
/(...)/packages/process/test.pony:155: Assert eq failed.  Expected () == (cat: -: Resource temporarily unavailable
)
/(...)/packages/process/test.pony:156: Assert eq failed.  Expected (0) == (1)
```
This is similar to issue #205.

Don't set O_NONBLOCK for child processes

---

packages/crypto/compare.pony
packages/crypto/crypto.pony
packages/crypto/digest.pony
packages/crypto/hash_functions.pony
packages/crypto/test.pony
packages/stdlib/test.pony

This RFC adds the crypto package to the standard library.

implement RFC #1

---

README.md

See https://github.com/ponylang/pony-tutorial/pull/138.

Add clarifications on how to compile using Docker.

---

packages/builtin/string.pony
packages/builtin_test/test.pony

So we can check for substrings in an intuitive way and throwing errors by using find().

Add contains() method on String and a test

---

CONTRIBUTING.md

The rules themselves are a direct copy from the RFC we adopted.

Add stdlib file name guidelines to CONTRIBUTING

---

src/libponyc/codegen/genexe.c

* Determine gcc version to call based on LLVM target triple. The
pattern seems to be that the LLVM triple is
`<arch>-<vendor>-<os>-<abi>` and gcc cross compilers are named
`<arch>-<os>-<abi>-gcc`.
* Use current host cpu for march argument to gcc instead of
compile time host cpu.
* Make use of `-mcx16` dynamic based on whether target platform
is 32 bit or not.

Make cross compiling easier by calling right gcc

---

packages/net/http/payload.pony
packages/net/http/status.pony

Implement RFC #6

---

src/libponyc/codegen/genexe.c

Revert "Make cross compiling easier by calling right gcc"

---

README.md

Please let me know if this is the right branch (didn't find a develop?) and whether you prefer the marketplace site or GitHub repository link!

Added Visual Studio Code Pony language extension to editor support list

---

src/libponyc/codegen/genexpr.c

Do not call llvm.lifetime.end after terminators

---

CHANGELOG.md
packages/process/_test.pony
packages/process/process_monitor.pony
packages/process/process_notify.pony

Pass ProcessMonitor to notifier

---

src/libponyc/expr/literal.c
src/libponyc/type/matchtype.c
test/libponyc/badpony.cc

Reject function types in is_x_match_nominal

---

CHANGELOG.md

Updates changelog entry for issue #1105

Update for Read/Write buffer changes

---

.appveyor.yml
.bintray.sh
.travis.yml
Makefile
README.md

_See below for updates!_
@jemc @SeanTAllen: here's another step.  😸 
This pull request configures the AppVeyor builds so that:
* on pull request builds / random pushed branch builds, artifacts will be made, but nothing deployed,
* on `master` and `monthly` branch builds, artifacts from each build job will be deployed to Bintray.
This required setup of a [ponyc-win](https://bintray.com/killerswan/ponyc-win) Bintray generic repo, containing [master](https://bintray.com/killerswan/ponyc-win/master) and [monthly](https://bintray.com/killerswan/ponyc-win/monthly) Bintray projects.  This commit 560de96 has been put on both those branches (in killerswan/ponyc) so there are now builds from [my AppVeyor project](https://ci.appveyor.com/project/killerswan/ponyc) for both branches shown on the …

Deploy AppVeyor (ZIP) and Travis (DEB / RPM / source) artifacts to Bintray

---

.appveyor.yml

For AppVeyor deployments to Bintray, specify pony-language instead of ponylang 

---

src/libponyc/codegen/codegen.c
src/libponyc/codegen/codegen.h
src/libponyc/codegen/host.cc

These new attributes describe what functions can do with memory and may help the optimiser.

Add more attributes to runtime functions in codegen

---

src/libponyc/expr/lambda.c

check type of lambda capture

---

packages/builtin/string.pony

Attempting to address #725 
Showing some example uses of some common string methods and how one might use them.

issue 725 - adding some String class level documentation with examples

---

CHANGELOG.md
packages/serialise/_test.pony
src/libponyrt/gc/serialise.c

* Amended test for array serialisation to add an empty array test

Fix for #1149 when serialising empty arrays

---

CHANGELOG.md
packages/ponybench/_auto_bench.pony
packages/ponybench/_bench.pony
packages/ponybench/_bench_async.pony
packages/ponybench/_test.pony
packages/ponybench/pony_bench.pony
packages/stdlib/_test.pony

Implement RFC #8

---

src/libponyc/codegen/genprim.c

In addition, this fix removes `tag` intrinsics handling from `box_function` as it is already handled by subordinate functions.
Closes #1083.

Correctly generate box compile_intrinsics

---

src/libponyc/pass/traits.c
src/libponyc/pkg/ifdef.c

add some quotes around names of things in errors

---

src/libponyc/expr/operator.c
test/libponyc/badpony.cc

Improve error message on tuple field reassign

---

src/libponyc/expr/reference.c
test/libponyc/badpony.cc

Fix bad error message in with block

---

packages/itertools/_test.pony

The issue referenced by the commented out test seems to have been resolved by #782.

Uncomment test in itertools

---

CHANGELOG.md
packages/collections/_test.pony
packages/collections/map.pony

Implements rfc 11
https://github.com/ponylang/rfcs/blob/master/text/0011-upsert-returns-value.md

Make Map.upsert return the new value of the key

---

Makefile

Expand expression immediately in Makefile

---

CHANGELOG.md
src/libponyc/pkg/package.c

Here we go. Hope this builds on all platforms (I am not certain about the availability of `strl{cpy,cat}` on Windows).
Cheers :)

Prevent buffer overflow in package.c (#1177)

---

Makefile
premake5.lua

Adds the commit number back into the pony version.

Add commit number to ponyc version

---

minimal-cases/issue-1222/1222.pony

This PR adds a minimal test case for #1222, as was discussed in #1232.

Add minimal test case for issue #1222.

---

packages/buffered/_test.pony
packages/stdlib/_test.pony

Seems like the tests were forgotten when the package was
extracted from net/

Re-enable buffered tests

---

RELEASE_PROCESS.md

Checklist on how to do pony releases.

Add RELEASE_PROCESS document

---

src/libponyrt/actor/actor.c
src/libponyrt/actor/messageq.c
src/libponyrt/asio/asio.c
src/libponyrt/asio/epoll.c
src/libponyrt/mem/pagemap.c
src/libponyrt/mem/pool.c
src/libponyrt/sched/mpmcq.c
src/libponyrt/sched/scheduler.c
src/libponyrt/sched/start.c

This one will need careful review. If anybody has any concern about a particular modification, please step in. I've put my reasoning in the commit message.

Relax the ordering for some atomic operations

---

CHANGELOG.md
src/libponyc/codegen/gencall.c
src/libponyc/expr/operator.c
test/libponyc/badpony.cc

Fix embed fields construction through tuples

---

src/libponyc/expr/reference.c
test/libponyc/badpony.cc

Improve error message for Main without constructor

---

CHANGELOG.md
packages/buffered/_test.pony
packages/buffered/reader.pony

Refs #1277 
I think it's ready for review, I'll squash when ready to merge.

Implement buffered read_until

---

CHANGELOG.md
packages/itertools/_test.pony
packages/itertools/iter.pony
packages/itertools/zip.pony

Implement RFC #30 (Extend itertools)

---

packages/builtin/std_stream.pony
src/libponyrt/lang/stdfd.c

Add pony_os_std_print

---

packages/promises/_test.pony
packages/stdlib/_test.pony

Note: This is not the most exhaustive test suite possible for the library.

Promises tests

---

README.md

This is what was discussed on the sync call yesterday.

Clarify platform support

---

packages/net/_test.pony

Run net/TCP.expect test on Windows

---

packages/net/_test.pony

Example intermittent failure:
https://travis-ci.org/ponylang/ponyc/jobs/167973110

Mark TCPBroadcast test as unreliable

---

README.md

Added a note about the binaries requiring AVX2 support.

Add AVX2 support requirement

---

packages/builtin_test/_test.pony

This adds tests that were waiting on some interdependent PRs
to merge.
Tests are for issues #1426 and #1435

Add tests for recent string package fixes

---

examples/yield/main.pony
src/libponyc/codegen/codegen.c
src/libponyc/codegen/codegen.h
src/libponyc/codegen/gencall.c
src/libponyc/codegen/genfun.c
src/libponyc/codegen/gentype.c
src/libponyc/pass/sugar.c
test/libponyc/sugar.cc
test/libponyc/sugar_expr.cc
test/libponyc/type_check_subtype.cc
test/libponyc/verify.cc

Behaviour calls return None instead of their receiver (RFC 28)

---

CHANGELOG.md

This change isn't released yet.

Fix changelog entry for #1466

---

packages/net/tcp_listener.pony

Include the Bool return value now needed in receive.

Fix documented example for TCPListener.

---

src/libponyc/codegen/gentrace.c

In a previous change (f9591b2), the tracing algorithm was changed to trace objects in the context of the sender. Although it is an optimisation regarding object types, it is a pessimisation regarding refcaps. This change resolves the issue by tracing with the sender's type context and the receiver's refcap context.

Trace message contents with the refcap of the receiver

---

CHANGELOG.md
src/common/platform.h
src/libponyrt/ds/fun.c
src/libponyrt/mem/pool.c
src/libponyrt/mem/pool.h
test/libponyrt/mem/pool.cc

@pdtwonotes Can you test this change and see if it fixes #1517 for you?

Fix pool index computing

---

benchmark/libponyrt/ds/hash.cc
src/common/platform.h
src/libponyrt/ds/hash.c
src/libponyrt/ds/hash.h
src/libponyrt/gc/actormap.c
src/libponyrt/gc/cycle.c
src/libponyrt/gc/gc.c
src/libponyrt/gc/objectmap.c
src/libponyrt/pony.h
test/libponyrt/ds/hash.cc

NOTE: This change trades additional memory usage for performance gains. As a result of the additional memory usage, functions like `resize` are more expensive.
-------
Change runtime hashmap implementation to use robin hood hashmap
algorithm with backward shift deletes instead of tombstones. See:
http://codecapsule.com/2013/11/17/robin-hood-hashing-backward-shift-deletion/
or http://www.sebastiansylvan.com/post/robin-hood-hashing-should-be-your-default-hash-table-implementation/
for details of hashmap algorithm including why it should perform better.
Update objectmap sweep and actormap sweep to use clearindex and
optimize.
Don't destroy/recreate `ctx->acquire` all the time.
Additionally, updated destroy and resize to use ponyint_hashmap_next
to efficiently scan items for freeing and …

Change runtime to use robin hood hashmap algorithm

---

src/libponyrt/ds/hash.c
src/libponyrt/ds/hash.h

This change was created and benchmarked due to @sylvanc's last comments on PR #1574.
This change helps decrease the time for `resize` and `init` but it increases the time for `search/put/remove` by about 2% - 3% because they all now require 2 memory accesses (the item bitmap and the bucket entry) instead of 1 (the bucket entry).
I'm not sure if it's worth the trade off or not but the information is here for evaluation. I lean towards leaving things as is since `search/put/remove` run significantly more often than `resize`.
-----------
Change hashmap to not have to zero out all memory on init
and resize but only the item bitmap.
This required changing all element validity tests to use
the item bitmap instead of checking if the `ptr` in the bucket is NULL or not.
------------
Before/after …

Hashmap optimization for resize

---

README.md

Moved the Arch and Gentoo install sections up so Linuxbrew is next to Homebrew

Add Linuxbrew instructions

---

src/libponyrt/gc/cycle.c

This change fixes a memory leak caused by the cycle detector not being entirely freed when stopping the runtime.

Free the cycle detector data structures

---

examples/httpget/httpget.pony
examples/httpserver/httpserver.pony
packages/net/http/_http_parser.pony
packages/net/http/client.pony
packages/net/http/http_notify.pony
packages/net/http/payload.pony

This change does not break existing code and I believe that it falls under the principle of least surprise.

Make HTTPSession type tag by default

---

release.sh

Remove trailing lines after removed section

---

Dockerfile

* sorted dependencies
* simplified tar file extraction
* remove unneccessary run command (`WORKDIR` makes dir if it doesn't exist)
* extracted `llvm` version into env variable

Cleaned up Dockerfile

---

Makefile
src/libponyrt/platform/ponyassert.c

Updates via andkem to get pony compiling on FreeBSD 11.
Replaces PR #1657

Fix FreeBSD 11 compilation

---

packages/collections/persistent/_bits.pony
packages/collections/persistent/_map_node.pony
packages/collections/persistent/map.pony

This PR separates out binary operations that may be used in future persistent data structures.

Separate common binary operations for persistent collections

---

RELEASE_PROCESS.md

Also, @Theodus and @SeanTAllen, I really love what you've put in `release.sh`!  🐰

Add some tiny grammar fixes and some hyperlinks to the notes on releasing.

---

README.md

Clarify prebuilt Windows installation instructions.

---

README.md

I was a tiny bit confused about what envvar to set for LLVM on Pony's `make` command, but pulling in this nifty `tar` command from the Dockerfile helped me.

Note how to extract and install LLVM for source compiling on Ubuntu

---

RELEASE_PROCESS.md
release.sh

Make merging CHANGELOG updates through script optional

---

src/libponyrt/mem/pool.c

The pool allocator now checks the largest free block size instead of the total size of all free blocks when looking for a free block of a given size. This avoids unnecessary traversals of the free block list.

Track largest pool allocator block size

---

src/libponyrt/mem/pool.c

The previous algorithm contained a data race which could cause some nodes of the list to be incorrectly discarded.

Use a more correct algorithm for the global pool block list

---

.travis.yml
README.md

As its now available again via homebrew.

Turn OSX LLVM 3.9 CI back on

---

.gitattributes

Fix shell script normalization in .gitattributes

---

.appveyor.yml
.travis.yml
.travis_install.bash
.travis_script.bash
CONTRIBUTING.md

@SeanTAllen What do you think of the case statements here on the tuple of (os, llvm)?

Create shell scripts for Travis 'install' and 'script' steps

---

src/libponyrt/mem/pool.c

The previous cleanup strategy (introduced in 43a6346) consisted in pushing every free blocks to a global free list, including the per-size free block. There was a problem with this strategy: blocks were pulled from that global list in `pool_alloc_pages`, and that function was always called with a requested allocation size greater than `POOL_ALIGN`. This means that the small blocks would never be pulled from the global list to be reused, resulting in lots of memory fragmentation and increased memory usage throughout multiple runs of the runtime.
This commit fixes this problem by using per-size global free block lists in addition to the global free block list for oversized blocks. When a thread exhausts its free block, it will now try to pull from the appropriate per-size global list before …

Use per-size lists when cleaning up the pool allocator

---

.travis_install.bash
.travis_script.bash

Flip bash settings ON

---

src/libponyc/reach/reach.c

This reduces the count of used type IDs.

Use the same type ID for equivalent unions/intersections

---

Makefile

* allow 'deploy' to work when config=debug
* beef up 'clean' to handle a broken 'deploy'
[skip ci]

Makefile tidying

---

.travis_script.bash
Makefile

Add a 'make docs' target and use it

---

packages/builtin/string.pony

This is the final part of RFC #4 to be implemented.
[skip ci]

Mention trim and trim_in_place in substring doc

---

README.md

Added instructions for installing using Docker for Windows

---

release.bash

I'm not entirely sure why this caused a problem, but it did.

Fix bug in release script

---

release.bash

Previous changelog empty entry removal was relying on an unsafe bash
side effect in order to work correctly. This in turn caused the
"correct" version of the script to fail when checked by "shell check".
This new version avoids the problem by narrowing the scope of sections
we are checking down to just those that are in the "unreleased" section
and then verifying that they are empty. Previously we checked "has
entry" and that was also more error prone than "has no entries". Seems
like it wouldn't be, but it is.
This has been tested extensively on OSX, Theo is testing Linux.
There are still issues herein where if the format deviates, it could go
bad, I opened an issue for those:
https://github.com/ponylang/ponyc/issues/1826
As they involve a much deeper rewrite/new approach.

More safely remove empty CHANGELOG entries

---

README.md

Shouldn't be merged until @sylvanc updates DNS

Update standard library location post netlify move

---

.travis_script.bash

Move standard library docs to their own repo

---

Makefile

Disable mcx16 on aarch64

---

src/libponyc/expr/reference.c
src/libponyc/pass/refer.c
test/libponyc/badpony.cc

Fix: assert failure on explicit reference to `this` in constructor.

---

src/libponyc/codegen/gencontrol.c
test/libponyc/badpony.cc

Fix compiler crash involving "dont care" symbol in an if or try block.

---

src/libponyc/expr/reference.c
test/libponyc/badpony.cc

Fix compiler crash for type errors in call arguments inside a tuple.

---

packages/itertools/chain.pony
packages/itertools/cycle.pony
packages/itertools/iter.pony
packages/itertools/itertools.pony
packages/itertools/take.pony
packages/itertools/zip.pony

Improvements include:
- Change non-existent reference of Limit class to Take class.
- Update array literal syntax in examples.
- Some examples code styling.
- Fix some examples.
- Spelling / removed some gratuitous words.

Improve Itertools docstrings

---

src/libponyc/expr/control.c
test/libponyc/badpony.cc

This PR fixes a compiler crash on type argument error inside an early return.

Fix compiler crash on type argument error inside an early return.

---

packages/collections/persistent/_test.pony
packages/collections/persistent/set.pony

This PR adds a persistent set to the standard library as part of [RFC 42](https://github.com/ponylang/rfcs/blob/master/text/0042-more-persistent-collections.md).

Add persistent set (RFC 42)

---

src/libponyrt/mem/pool.c

This change fixes two different race conditions:
- One that could occur when a load of the list header was reordered before the incrementation of the thread counter. This could only happen on ARM since x86 has very strong instruction reordering properties (in particular, loads can't be reordered with `LOCK`ed instructions such as an atomic increment).
- One that could occur when a block was added right after a block that was being removed at the same time. This couldn't actually happen in a real-world case since we never concurrently both push to and pull from the list.
I don't think this fix requires a release since it's only affecting ARM, and the bug could only happen during compiler tests, not in real-world code where these functions aren't used.

Fix race conditions in pool allocator global free list

---

packages/collections/persistent/_test.pony
packages/collections/persistent/_vec_node.pony
packages/collections/persistent/vec.pony

This PR completes RFC 42 by adding the persistent Vec to the standard library.
closes #1884

Add Persistent Vec (RFC 42)

---

src/libponyc/codegen/genident.c
test/libponyc/codegen_identity.cc

This was accidentally broken in b99d5b6.

Identity comparison of abstract types with no subtyping relationship

---

RELEASE_PROCESS.md

Include new "Release" blog post in release process

---

src/libponyc/type/typeparam.c
test/libponyc/iftype.cc

Fix iftype where the type variable appears as a type parameter.

---

src/libponyc/pass/syntax.c
test/libponyc/badpony.cc

Fix assert failure on lambda parameter missing type.

---

pony.g

The grammar was modified in a064d3a, but the file wasn't updated.

Update iftype grammar in pony.g [skip-ci]

---

src/common/pony/detail/atomics.h

The previous alignment was already correct because of platform guarantees on both x86 and ARM, but explicit is better for this kind of things.
Also add some compile-time checks on big atomic sizes for sanity.

Explicitly align atomics on object size on old compilers

---

src/libponyc/expr/call.c
src/libponyc/expr/operator.c
src/libponyc/expr/reference.c

Improve error message where this is not a subtype, and is incomplete.

---

src/libponyc/codegen/genmatch.c
test/libponyc/badpony.cc

Fix compiler crash on exhaustive match where last case is a union subset

---

.gitattributes

It's now required by `test-ci` make target
https://github.com/ponylang/ponyc/pull/2034

FIX include pony.g in archive files

---

README.md

These instructions assume that PR #2103 will be merged prior to this PR being merged.

Add Alpine build from source instructions.

---

src/libponyc/expr/match.c
test/libponyc/sugar_expr.cc

Fix compiler assert on match including structural equality on union type.

---

src/libponyrt/mem/pool.c

This change breaks down the thread-local free block into thread-local free list elements when cleaning up the memory pool-allocated by a thread instead of pushing the whole block in a specific global list.
This allows the removal of an allocation case in `pool_get` and reduces the amount of global free block lists to one.

Break down the local block at pool allocator cleanup

---

src/libponyc/codegen/gencall.c

The process has been moved into separate functions in order to reduce the size of gen_call itself. This doesn't introduce any logical changes.

Refactor receiver generation in gen_call

---

README.md

Add Debian Sid installation instructions

---

LICENSE

Per August 9 development sync discussion
[skip ci]

Update License copyright

---

README.md

Add Ubuntu Xenial from package specific install instructions

---

README.md

Update Xenial from source instructions

---

test/libponyc/codegen_trace.cc

These were accidentaly disabled in 54225e4.

Enable tests in codegen_trace.cc

---

README.md

Add install instructions for openSUSE Leap 42.3

---

README.md

Add instructions for prebuilt rpm on openSUSE

---

src/libponyc/expr/literal.c
test/libponyc/badpony.cc

Fix coercion for numeric literal through type arg with viewpoint.

---

src/libponyc/verify/fun.c
test/libponyc/verify.cc

Forbid struct finalisers

---

src/libponyc/codegen/genbox.c
test/libponyc/codegen.cc

Fix internal failure on compilation when boxing bool as union into tuple.

---

.travis_script.bash

Used to verify our changelogs on commit

Update to latest version of the changelog-tool

---

README.md

What we had was very out of date and reporting errors.

Update bintray public key

---

CHANGELOG.md
packages/builtin/array.pony
packages/builtin_test/_test.pony
packages/random/_test.pony
packages/random/random.pony

Add Array.swap_elements and various Random methods (RFC 46).

---

src/libponyc/pass/expr.c
test/libponyc/badpony.cc

Fix compiler crash related to inferred lambda argument in apply sugar.

---

src/libponyc/expr/array.c
test/libponyc/array.cc

Fix array inference from ReadSeq interface with tuple element type.

---

README.md

Having a quick way to run or test code is really good for beginners. Moreover it allows people reading pony on phones and tablets to try it out.

Add a link to the playground in Readme.md

---

README.md

Did a bad edit for the last pull request. Sorry about that.

Fix bullet being in wrong paragraph in readme

---

src/libponyrt/mem/pagemap.c

Do only one fence when extending the pagemap.

Optimise pagemap synchronisation

---

src/libponyc/codegen/genfun.c

The correct C interface for finalisers is functions returning void.

Make finalisers return void instead of None at codegen

---

Makefile

The config default is release not debug

Fix Makefile help configurations default

---

packages/builtin_test/_test.pony

Add tests for String trimming on already-trimmed strings

---

src/libponyrt/sched/mpmcq.c

This commit adds `mpmcq_size_debug` to be able to check the size
of the global and per scheduler actor queues.

Add mpmcq_size_debug for debugging purposes

---

packages/builtin/iterator.pony

which was agreed on during sync.
Take this as a starting point for discussion.
[skip ci]

add docs to Iterator to explicitly describe the Iterator protocol

---

.appveyor.yml

Update `appveyor.yml` to use the latest Visual Studio image.

Build with VS2017 on AppVeyor

---

Makefile

Add use=llvm_link_static which will link llvm statically with ponyc

Support linking llvm statically

---

Makefile

0.22.0 instead of 0.22.0-SOME-HASH-VALUE

Complete making ponyc bintray version user friendly

---

README.md

Add missing dot at end of sentence in Readme.

---

src/libponyc/options/options.c
src/libponyc/options/options.h
src/ponyc/main.c

Refactor the option processing code in main to libponyc/options. The hope
is that this will allow easier testing of standard ponyc options in the
future.

Create ponyc options

---

packages/time/timer_notify.pony

These are in response to questions that came up during the Pony
development sync. We decided that we should clarify the documentation a
bit.
[skip ci]

Improve TimerNotify documentation

---

packages/builtin/read_seq.pony

from older commit when they were correct: 1ff6d7e07056d2c6f0844ea4b5f084a1be2c1f01

update confusing ReadSeq comments

---

src/libponyc/codegen/genmatch.c
src/libponyc/type/matchtype.c
src/libponyc/type/subtype.c
src/libponyc/type/subtype.h
test/libponyc/matchtype.cc

Allow tuples to match empty interfaces

---

README.md
wscript

- Fixes #2533
- Also makes a few changes for clarity in the README.

Update the Windows build to support the latest Visual C++ Build Tools

---

src/libponyrt/ds/fun.c
src/libponyrt/ds/fun.h

Saw this on Twitter (https://twitter.com/ponylang/status/975871142908125185), naive fix, but seams to work...

Add a 32-bit implementation of the siphash hashing algorithm

---

src/libponyc/codegen/genmatch.c

Checking whether an object is a subtype of an union or intersection at runtime is now implemented as a single check of the trait bitmap, instead of a check for each element in the union/intersection.

Improve code generation of union/isect pattern matching

---

src/libponyrt/asio/kqueue.c

This is a very trivial change to remove a confusing looking preprocessor-ism.

Initialize new_action.sa_handler to default

---

packages/collections/persistent/_bits.pony
packages/collections/persistent/_map_node.pony
packages/collections/persistent/_vec_node.pony
packages/collections/persistent/map.pony
packages/collections/persistent/vec.pony

This commit includes various, incremental improvements that I have made to
the persistent vector algorithm over the past few months. The updated push,
pop, and update functions have been property tested.

Minor improvements to the persistent vector

---

RELEASE_PROCESS.md

The examples aren't always necessary but being new to releasing
I felt examples to follow to ensure I was doing things as others
had done previously would have been helpful.

Add examples for announcements and clarifications for some steps

---

src/libponyc/pass/expr.c
test/libponyc/codegen.cc

Fix compiler crash related to union types with duplicate members.

---

examples/httpserver/httpserver.pony

Added code to [httpserver.pony](https://github.com/kiwiMec/ponyc/blob/httpserver_example_body/examples/httpserver/httpserver.pony) to illustrate one way of handling POST request body data.  Code improvement based on example provided by Matthias in the [HTTPServer lacking real body](https://pony.groups.io/g/user/topic/20916362) conversation.

Update HTTPServer example to process request body data 

---

packages/builtin/stdin.pony

Not sure if this package index reference is the most helpful
replacement, but it's at least not a 404 ;)

fix dead readline package link

---

src/libponyc/codegen/gencontrol.c
test/libponyc/codegen.cc

Fix some edge cases in code generation for loops that jump away.

---

packages/net/ssl/_test.pony
packages/net/ssl/alpn.pony
packages/net/ssl/ssl.pony
packages/net/ssl/ssl_connection.pony
packages/net/ssl/ssl_context.pony

Implement [RFC 57](https://github.com/ponylang/rfcs/blob/master/text/0057-ssl-alpn.md)
([Issue](https://github.com/ponylang/ponyc/issues/2813))

Add SSL APLN support

---

.travis_commands.bash

Prior to this commit, the logic for Ubuntu Trusty and Debian Jessie
packaging for PPA and bintray deb using debuild explicitly disabled
pcre2/regex related functionality via sed magic.
This commit stops disabling that and will now compile/package
pcre2/regex functionality on Trusty and Jessie because the PPA
now has a backport of libpcre2-dev included for those distros.

Re-enable pcre2 for trusty/jessie deb packaging

---

.ci-dockerfiles/cross-llvm-3.9.1-freebsd11-x86_64/Dockerfile
.ci-dockerfiles/cross-llvm-3.9.1-freebsd11-x86_64/README.md
.ci-vagrantfiles/freebsd11-x86_64/Vagrantfile
.travis.yml
.travis_commands.bash
.travis_script.bash
Makefile

Cross compiles on linux and then runs the binaries in a virtual
machine via vagrant/libvirt.
The CI tests currently fail (and are allowed to fail) due to https://github.com/ponylang/ponyc/issues/2825. In theory once that issue is fixed they will pass.

Freebsd 11 x86-64 CI

---

README.md

Add Pony's prerequisites for CPU platforms

---

README.md

Plus, update "Ubuntu Artful" section to "Ubuntu Bionic" due to end-of-life.
Closes #2869.

Add Linux Mint installation instructions

---

Makefile

Fix installation of libponyrt.bc on Linux

---

.ci-dockerfiles/centos7-llvm-3.9.1/Dockerfile
.travis_commands.bash

Also, update CentOS Docker image to include missing `file` utility.

Fix appimage build by removing deprecated argument

---

README.md

Not everyone (including me!) might be aware of what AVX is, so this PR adds a friendly link to the Wikipedia page about it.

README.md: Link to AVX document

---

README.md

While going through the README I noticed a few minor typos.
Pretty trivial, but I figured it would be a good way to get my feet wet.

Fix a handful of minor typos in README.md

---

packages/process/_test.pony
packages/process/process_monitor.pony

This is just a bit of a cleanup; no functional changes or added tests.

packages/process: use array literals

---

CONTRIBUTING.md

Fixed typos in CONTRIBUTING.md

Update CONTRIBUTING Fixed Typos

---

packages/options/options.pony

[skip ci] Add a deprecation notice to the options package documentation

---

.circleci/config.yml
.gitmodules
Makefile-lib-llvm
Makefile-ponyc
README.md
lib/llvm/.gitignore
lib/llvm/Makefile
lib/llvm/README.md

This repo is the official github repo for LLVM.

Support canonical github.com/llvm/llvm-project repo

---

packages/process/_pipe.pony
packages/process/_process.pony
packages/process/_test.pony
packages/process/process_monitor.pony
src/libponyrt/lang/process.c
src/libponyrt/lang/process.h
src/libponyrt/sched/start.c

Uses anonymous pipes which are then setup using named pipe API to be non-blocking. (turns out that in Windows anon pipes are the same as named pipes with special names.)
Using Pony Timers to poll non-blocking pipes by peeking at them and using Windows file calls directly.
Process creation is even easier than posix with just a single CreateProcess call doing all the work.

Windows implementation of Process and Pipe.

---

Makefile-ponyc
src/libponyc/codegen/codegen.c
src/libponyc/codegen/codegen.h
src/libponyc/codegen/genbox.c
src/libponyc/codegen/gencall.c
src/libponyc/codegen/gendesc.c
src/libponyc/codegen/genfun.c
src/libponyc/codegen/genoperator.c
src/libponyc/codegen/genopt.cc
src/libponyc/codegen/genprim.c
src/libponyc/codegen/genreference.c
src/libponyc/codegen/gentype.c
src/libponyc/codegen/gentype.h

Resolves #2371.
See the notes in that issue for details of what is being done and why.

Restore Heap to Stack optimizations for LLVM >= 4

---

README.md

Note that dragonfly can't build and pass test suite

---

README.md

Remove incorrect LLVM 3.9.1 note from README

---

packages/builtin_test/_test.pony

it was failing sometimes for debug builds.
I need to still check this on a windows box myself, just want to see what @kulibali and appveyor think about it.

try to make Mod tests repeatable on windows

---

.cirrus.yml
.travis.yml
.travis_script.bash

We are currently able to get resource there MUCH sooner than we can on
TravisCI.

Run macOS CI on Cirrus

---

.packaging/deb/control
.packaging/rpm/ponyc.spec

We are going to be moving off of groups.io.
[skip ci]

Update the Pony buildbot email address

---

CONTRIBUTING.md
README.md
RELEASE_PROCESS.md
SUPPORT.md

Update docs to reflect move from Slack to Zulip

---

packages/collections/sort.pony

Please (please) comment on this and tell me how I can make this the best docs-contrib ever.  
(The theory is I'm going to use adding to the docs as a means to learn Pony so more should be coming and the simpler it is to get these merged for all concerned the better.)

Add example as per issue #3098

---

packages/collections/reverse.pony

More detailed documentation for collections.reverse

---

Makefile-lib-llvm
Makefile-ponyc
lib/llvm/Makefile

@SeanTAllen see if this fixes the need to delete the system provided llvm.

Build lib llvm dynamic lib

---

src/libponyrt/asio/epoll.c

Fixes the performance regression introduced in https://github.com/ponylang/ponyc/pull/2897. This change is really a single 1-liner, please a small change to make clear that edge triggering isn't used with one shot.

Don't turn off Epoll OneShot when resubscribing to OneShot events

---

packages/net/ssl/ssl_connection.pony

This PR just modify a  working as is, but incorrect indentation.
I think this may be too trivial, so I do not have any bad feelings if it is better to be included within another work and suspended until such work comes.

modify indentation

---

.circleci/config.yml
.dockerhub/alpine/Dockerfile
RELEASE_PROCESS.md

This resolves the first part of #3130. Once merged, someone with admin permissions in Docker Hub (possibly me) should set the [appropriate rules](https://github.com/ponylang/ponyc/issues/3130#issuecomment-481398480).

Add Alpine Docker image

---

packages/net/tcp_connection.pony

This fixes the failing SSL tests. Not sure why they had issues after the merge of the other PR but this fixes things.

Fix ssl tests

---

.github/delete-branch-on-merge.workflow

Will delete branches for PRs that have been merged.
[skip ci]

Create "delete branch on merge" GitHub action

---

STYLE_GUIDE.md

Add type parameters to style guide

---

src/libponyrt/gc/cycle.c

With the merge of #3254 the other call to `apply_delta` are
unnecessary and there is also no longer a need to temporarily
store the `deltamap*` as a part of `view_t`.
This commit removes the calls to `apply_delta` and the `delta`
field from `view_t`.

Remove unnecessary code related to apply_delta from cycle detector

---

README.md

Remove SSL from installation instructions in README

---

STYLE_GUIDE.md

Add Comments section to style guide

---

src/libponyrt/mem/alloc.c

Only freebsd provides it of the BSDs.

If MAP_ALIGNED_SUPER is not available, don't use it.

---

test/libponyc/badpony.cc

Fix spelling error in test name

---

Makefile-ponyc

My kingdom for a `$` where it should be!
Closes #3296

Fix error in starting benchmarks via the Makefile

---

README.md

Remove random tick

---

packages/builtin/array.pony

Pop the last item pushed.  LIFO.  It's a stack, not a queue.
https://www.cs.cmu.edu/~adamchik/15-121/lectures/Stacks%20and%20Queues/Stacks%20and%20Queues.html

Update array.pony docstring: stack v queue

---

Makefile-ponyc

Change `make docs` to only generate docs for public classes

---

.circleci/config.yml
.cirrus.yml

They run a good bit faster there than CircleCI.

Move x86 GNU Linux PR acceptance tests to CirrusCI

---

.circleci/config.yml
.cirrus.yml

Move alpine lib/llvm CI to CirrusCI

---

.github/workflows/changelog-bot.yml

Because we've missed him! Now, back to life as a GitHub action.

Bring the changelog bot back to life

---

.cirrus.yml

I got it wrong last time, this time, I actually tested from a fork.
Shockingly good idea.
Dur.

Fix building using Cirrus custom clone + forks

---

.dockerfiles/latest/x86-64-unknown-linux-gnu/Dockerfile
.dockerfiles/latest/x86-64-unknown-linux-musl/Dockerfile
.dockerfiles/release/x86-64-unknown-linux-gnu/Dockerfile
.dockerfiles/release/x86-64-unknown-linux-musl/Dockerfile

It changed as of version 0.3.0

Update ponyup PATH in docker images

---

packages/cli/_test.pony
packages/cli/command_parser.pony

fix cli issue when providing --help=false.

---

README.md

Add link to "Getting help" section of the website

---

INSTALL.md

Switch macOS install directions from brew to ponyup

---

LICENSE
README.md

* Found dead link in README.md
* Updated year in LICENSE
Best regards,

Fix dead link in README.md and Update LICENSE for date

---

.cirrus.yml

It was already auto upgrading us to Catalina.

Upgrade Cirrus macOS image

---

src/libponyc/platform/vcvars.c

Added support for Visual Studio Preview.

Added support for VS Preview

---

.github/workflows/handle-external-events.yml

Use correct PowerShell syntax for environment variables.

Fix typo in Windows docker build scripts

---

.dockerfiles/latest/x86-64-pc-windows-msvc/Dockerfile
.dockerfiles/latest/x86-64-pc-windows-msvc/git.ini
.dockerfiles/release/x86-64-pc-windows-msvc/Dockerfile
.dockerfiles/release/x86-64-pc-windows-msvc/git.ini
.github/workflows/pr.yml

This will be useful for testing corral et al

Add git to Windows ponyc docker images

---

examples/ring/main.pony

cc @SeanTAllen please review. Also let me know if the ring ascii art is too ugly and I will remove it.
#3491

examples: Add comments for ring example

---

Makefile

Fixes an install bug found by Panagiotis Mamatsis.

Create all 'lib' directories needed to do an install

---

.ci-scripts/release.bash

It was needed for circle-ci and appveyor workflows, but we no longer use
them so, let's switch to a pure "release from master" as our normal workflow.
The automated usage of a release branch often broken due to odd merge
conflicts on the release branch. That was moderately ok, because they could
be manually fixed and pushed and if you knew the release process well, you
could restart it from the correct point.
However, those problems have pretty much always been caused by the release
branch existing and the merges, so... not so good.
Closes #3533

Stop using a magic release branch

---

.cirrus.yml

PR -> Nightly -> Release makes more sense in terms of the usual flow
that something would go through.

Reorganize .cirrus.yml

---

packages/collections/persistent/_map_node.pony

This PR cleans up some unnecessary uses of the trn capability from the persistent map data structure. These were unnecessarily blocking #3591 from correcting a soundness hole in the type system.

Remove uses of trn from persistent map node

---

packages/itertools/_test.pony
packages/itertools/iter.pony

Implement RFC 66: Iter maybe

---

README.md

Add Vis to list of supported editors

---

packages/builtin_test/_test_valtrace.pony

It sometimes times out on Windows in debug. This is a test to see if
upping the timeout fixes the issue.

Increase valtrace timeout

---

.dockerfiles/latest/x86-64-unknown-linux-gnu/Dockerfile
.dockerfiles/release/x86-64-unknown-linux-gnu/Dockerfile
.github/workflows/handle-external-events.yml
.github/workflows/pr.yml

Previously it was based on glibc which might not be the same
as the base image that we are using.
Closes #3633

Switch GNU Linux dockerfiles to using Ubuntu 20.04 ponyc

---

packages/format/format.pony

https://stdlib.ponylang.io/format-Format/

Fix Format formatting so that fill, align, and width appear as bullet points

---

BUILD.md

Suggest parallelizing "make libs" step on build instructions

---

Makefile
src/libponyc/CMakeLists.txt

Previously, when Theo and I set up the install for libponyc, we
couldn't figure out cmake so we kind of hacked our way around it.
While doing other work, I figured out how to do correctly.

Correctly install libponyc

---

.cirrus.yml

I have reason to believe our cache might be incorrect for nightlies.
As it is different than PRs, I'm changing in case the different form
is causing some sort of issue.

Change fingerprint script

---

packages/builtin/string.pony

Fix example on String docstring [skip ci]

---

INSTALL.md

Kept it brief with setting default PLATFORM then using ponyup to update ponyc. Fixes #3645

FreeBSD install via ponyup (#3645)

---

src/libponyc/codegen/genexe.c

Debug code that was kept during testing of #3745

Remove extra debug print [skip ci]

---

src/libponyc/CMakeLists.txt

I ran into this during local development and was wondering if there was a reason this wasn't mainlined, so I'm creating a PR to get the builders to run against it

Mainline cmake patch from nixpkgs to improve compatibility

---

INSTALL.md

We have official releases for it, now available via ponyup.

Add Rocky 8 information to INSTALL.md

---

.cirrus.yml

With the recent work on Arm support, both now pass.

Turn arm and armhf CI tests back on

---

.release-notes/3879.md
BUILD.md

Add build instructions for 32-bit Raspbian

---

.release-notes/3887.md
Makefile

Fix incorrect version in nightly ponyc builds

---

BUILD.md

Folks seem to occasionally try to do from a bare source tree.

Note that building from source requires the repository

---

INSTALL.md

Add note to INSTALL that we only offer AMD64 builds

---

packages/collections/list.pony
packages/collections/list_node.pony

Continues work started in #3673 within a ponylang owned branch.
Only ~1/2 done with the docstrings so not ready to merge, but has been rebased on main and work by palash25 has been preserved.

collections: Add examples for each function

---

.release-notes/3994.md
lib/CMakeLists.txt

This change updates our LLVM submodule to `llvmorg-13.0.1`

Update LLVM to 13.0.1

---

INSTALL.md

Also update prerequisites to reflect updated VS version and terminology.

Update `INSTALL.md` to mention ponyup for Windows.

---

.dockerfiles/latest/x86-64-pc-windows-msvc/Dockerfile
.dockerfiles/release/x86-64-pc-windows-msvc/Dockerfile

This PR adds the corral windows executable to the Windows ponyc docker images.
Closes #3562

Add corral to Windows docker images

---

.release-notes/rfc-72.md
examples/echo/echo.pony
examples/files/files.pony
examples/mandelbrot/mandelbrot.pony
examples/net/listener.pony
examples/net/net.pony
examples/net/pong.pony
examples/under_pressure/main.pony
packages/backpressure/backpressure.pony
packages/files/_test.pony
packages/files/file_path.pony
packages/files/files.pony
packages/ini/ini.pony
packages/net/_test.pony
packages/net/dns.pony
packages/net/net_address.pony
packages/net/proxy.pony
packages/net/tcp_connection.pony
packages/net/tcp_listener.pony
packages/net/udp_socket.pony
packages/ponytest/ponytest.pony
packages/process/_test.pony
packages/process/process.pony
packages/process/process_monitor.pony
packages/runtime_info/auth.pony
packages/runtime_info/scheduler.pony
test/libponyc-run/runner/_find_executable.pony
test/libponyc-run/runner/_test_definitions.pony
test/libponyc-run/runner/_tester.pony
test/libponyc-run/runner/main.pony

See [RFC #72](https://github.com/ponylang/rfcs/blob/main/text/0072-change-stdlib-object-capabilities-pattern.md) for complete details.
Closes #4028

Change the standard library pattern for object capabilities

---

test/libponyc-run/regression-2408/main.pony

Add regression test for issue 2408.

---

BUILD.md

- adds build instructions for Asahi Linux
- tested with `make test`

Add Asahi Linux build instructions

---

examples/ffi-callbacks/README.md
examples/ffi-struct/README.md

- adds Linux/Windows build instructions

Add platform specific build documentation for FFI examples

---

.cirrus.yml

Run glibc Linux CI against Ubuntu 22.04

---

.ci-scripts/arm64-nightly.bash
.cirrus.yml

There's no release notes for this. Those will be added when we add release as well as nightly once the nightlies have been tested and any kinks are worked out.

Add MacOS Apple Silicon nightly builds

---

.cirrus.yml

We should close #4008 after this is merged.

Add debug build testing for Windows PRs

---

src/libponyrt/actor/actor.c

We currently make multiple calls to `has_sync_flag` in order to check
if an actor has some flags set or not. Compilers generally do not
optimize `atomic` operations very aggressively and it is very likely
that subsequent calls to `has_sync_flag` all end up executing one
after another instead of being coalesced into a single atomic operation.
This commit combines multiple calls to `has_sync_flag` into a
single call to `has_sync_flag_any` in order to only do a single
atomic read instead of multiple atomic reads. The 
`has_sync_flag_any` function was added for clarity.
The `is_muted` function is removed as part of this for consistency and to
minimize confusion because in some cases a direct call to `has_sync_flag`
had to be made to be able to combine atomic operations and it didn't
seem like …

Combine multiple `has_sync_flag` calls to minimize atomic operations

---

packages/net/_test.pony

I believe I found and fixed a source of instability.

Turn Windows network tests back on

---

src/libponyrt/sched/scheduler.c

One of the commits originally in #4331

Fix typo 'potentially'

---

src/libponyrt/sched/scheduler.c

One of the commits originally in #4331

Directly initialize immediately assigned variable

---

src/libponyrt/ds/stack.h

this matches lists and hashmaps.
One of the commits originally in #4331

Add an actual member to stacks

---

packages/builtin_test/_test.pony
src/libponyrt/gc/gc.c
src/libponyrt/gc/objectmap.c
src/libponyrt/mem/heap.c
src/libponyrt/mem/heap.h
src/libponyrt/mem/pagemap.c
src/libponyrt/mem/pagemap.h
test/libponyrt/mem/heap.cc
test/libponyrt/mem/pagemap.cc

Reverts ponylang/ponyc#4368
I didn't notice the "do not merge" label here.

Revert "Move heap ownership info from chunk to pagemap"

---

test/rt-stress/string-message-ubench/main.pony

This update does two things:
- Exits on fatal errors
Previously fatal errors could be missed in the logs (we never look) or would only be seen in `debug` mode. Both fatal errors will now exit the program immediately with a non-zero exit code which will result in noticeable failure.
- Make messages a bit more stressful
Previously every message was the string "42". We are now sending larger messages that grow more and in the process allocate more memory (in a not particularly efficient fashion) to stress the runtime "just a bit" more than previously.

Improve string-message-unbench stress tester

---

src/common/dtrace_probes.d

"Typos" basically.
Fixes #4445

Fix incorrect dtrace_probe setup

---

EDITORS.md

The language support was recently updated to the current latest main https://github.com/mawww/kakoune/pull/5079

EDITORS.md: add Kakoune text editor

---

packages/random/random.pony

Fix typo in docstring

---

src/libponyrt/sched/scheduler.c

Destroy mutemap on scheduler shutdown

Destroy mutemap on scheduler shutdown

---

.github/workflows/add-discuss-during-sync.yml
.github/workflows/changelog-bot.yml
.github/workflows/lint-action-workflows.yml
.github/workflows/pr.yml
.github/workflows/release-notes-reminder.yml
.github/workflows/release-notes.yml

Limiting our permissions to the base minimum.

Limit some workflow permissions 

---

.github/workflows/pr.yml
CMakeLists.txt
src/libponyc/codegen/genfun.c
src/libponyrt/gc/cycle.c
src/libponyrt/mem/heap.c
src/libponyrt/mem/pool.c
src/libponyrt/mem/pool.h
test/libponyrt/mem/pool.cc

So the address sanitizer can better detect issues
Including adding an address and undefined behavior sanitizer CI build and a couple of minor fixes identified by the address sanitizer

Manual poisoning for pool/heap when using address sanitizer

---

.github/workflows/stress-test-runtime.yml
Makefile
make.ps1
test/rt-stress/tcp-open-close/README.md
test/rt-stress/tcp-open-close/tcp-open-close.pony

The new test open and closes TCP connections. This stresses the ASIO system and actor creation/destruction.

Add new runtime stress test

---

.ci-dockerfiles/cross-arm/Dockerfile
.ci-dockerfiles/cross-armhf/Dockerfile
.github/workflows/pr.yml

We are getting some weird failures in our cross CI so this is an easy thing to attempt to fix before we call it a day and give up on the 32-bit testing.

Update the QEMU used in our cross runner

---

.release-notes/fix-4613.md
src/libponyc/type/lookup.c
test/full-program-tests/regression-4613/main.pony
test/full-program-tests/regression-4613/pkg/trait.pony

Don't duplicate visibility tests for inherited trait bodies

---

src/libponyrt/lang/time.c

Address edge case in ponyint_formattime

---

.release-notes/4661.md
src/libponyrt/sched/scheduler.c
src/libponyrt/tracing/tracing.c
src/libponyrt/tracing/tracing.h

this allows for correlating specific message send trace events with specific message receive trace events

Enhance scheduler message tracing with message ids

---

.release-notes/gold.md
src/libponyc/codegen/genexe.c

Don't set gold as the default ponyc linker on Linux

---

.ci-dockerfiles/arm64-unknown-linux-ubuntu24.04-builder/Dockerfile
.ci-dockerfiles/cross-arm/Dockerfile
.ci-dockerfiles/cross-armhf/Dockerfile
.ci-dockerfiles/cross-riscv64/Dockerfile
.ci-dockerfiles/stdlib-builder/Dockerfile
.ci-dockerfiles/x86-64-unknown-linux-fedora41-builder/Dockerfile
.ci-dockerfiles/x86-64-unknown-linux-ubuntu22.04-builder/Dockerfile
.ci-dockerfiles/x86-64-unknown-linux-ubuntu24.04-builder/Dockerfile

They automatically associated the image in GHCR with this repository.

Add image labels to CI Dockerfiles
