ponylang/ponyc

- .circleci/config.yml
- Makefile
- README.md
- src/libponyc/options/options.c
Changing default_openssl to default_ssl is slightly less verbose and
in the future will allow the possibility of different libraries to be
specified, such as libressl.
Also, change PONY_DEFAULT_OPENSSL to PONY_DEFAULT_SSL.
> Change default_openssl to default_ssl

- examples/message-ubench/main.pony
This allows message-ubench to cleanly stop executing, without this it
had to be forcibly stopped with Ctrl-C or kill.
> Add report-count parameter to message-ubench

- packages/net/http/common_log.pony
- packages/time/_test.pony
- packages/time/date.pony
https://github.com/ponylang/ponyc/issues/1902
* Date -> PosixDate.
* If any of the creation arguments is negative set them to zero.
* Tests for PosixDate.
> Rename Date to PosixDate

- Makefile
- examples/README.md
- examples/main.pony
- examples/overload/main.pony
- examples/under_pressure/main.pony
The `examples/main.pony` source, which is used for the
`make test-examples` test, didn't include the relatively
new `examples/under_pressure` and `examples/overload` apps.
This PR fixes:
1. The omission of `under_pressure` and `overload` from the
`make test-examples` check.  (Plus a few comments in `examples/main.c`.)
2. Add `examples/README.md` in hopes that documentation can help
avoid repeating the omission problem.
3. Add `make test-examples` to the list of stuff done by the
`make test-ci` target.
4. Fix the compilation errors in `under_pressure` and `overload`.
> Fix `make test-examples` errors if missing example apps were included

- packages/bureaucracy/custodian.pony
This is a pet peeve of mine, and you have a great open contribution model, so I figured I'd contribute a fix. :)
I grepped the project for other instances of "you're" that should be "your" and vice versa, and I could not find any.
> [documentation] Fix grammatical error: you're => your

- src/libponyc/codegen/codegen.c
- src/libponyc/codegen/gendesc.c
- src/libponyc/codegen/genexe.c
- src/libponyc/reach/reach.c
- src/libponyc/reach/reach.h
- src/libponyrt/gc/serialise.c
- src/libponyrt/gc/serialise.h
- src/libponyrt/pony.h
- src/libponyrt/sched/start.c
- test/libponyc/util.cc
Individual features can now be initialised separately and the user can specify a type descriptor array to be used for serialisation. The latter change allows us to remove the usage of `dlsym` to find the type descriptor array.
> Give more user control on language features initialisation in pony_start

- Makefile
- src/common/ponyassert.h
- src/libponyc/ast/ast.c
- src/libponyc/ast/token.c
- src/libponyc/ast/treecheck.c
- src/libponyc/codegen/gencall.c
- src/libponyc/codegen/genexe.c
- src/libponyc/reach/reach.c
- src/libponyrt/actor/actor.c
- src/libponyrt/actor/messageq.c
- src/libponyrt/gc/cycle.c
- src/libponyrt/sched/mpmcq.c
- wscript
Previously, `pony_assert` was forwarding to `assert` when used in libponyrt due to the way the `PONY_NO_ASSERT` macro was being used.
This change removes the `PONY_NO_ASSERT` macro and adds two new macros: `PONY_ALWAYS_ASSERT` and `PONY_NDEBUG`.
- `PONY_ALWAYS_ASSERT` is the opposite of the `PONY_NO_ASSERT` macro. It is defined by the build system for libponyc.
- `PONY_NDEBUG` is defined when `NDEBUG` is defined and `PONY_ALWAYS_ASSERT` isn't defined. When `PONY_NDEBUG` is defined, `pony_assert` becomes a noop.
This change results in the following behaviour:
- In libponyrt debug, `pony_assert`s are checked.
- In libponyrt release, `pony_assert`s aren't checked.
- In libponyc, `pony_assert`s are always checked.
> Correctly use pony_assert in the runtime

- packages/serialise/serialise.pony
- src/libponyc/pkg/package.c
- src/libponyrt/gc/serialise.c
- src/libponyrt/gc/serialise.h
- src/libponyrt/sched/scheduler.h
- test/libponyc/compiler_serialisation.cc
- test/libponyrt/ds/hash.cc
This change removes the possibility to define custom exception functions when serialising object graphs. The previous behaviour, which is to always raise Pony errors, has been re-implemented.
Now that we have the `pony_try` function and that we know that a C++ catch-all clause can catch Pony errors, we don't need exception parameterisation.
> Remove exception parameterisation from serialisation

- src/libponyc/expr/call.c
- src/libponyc/pass/expr.c
- test/libponyc/literal_inference.cc
Errors for default arguments could leave the AST in an illegal state,
which was causing assertions when evaluating default args during TK_CALL evaluation in the expr pass.
This PR makes those errors stop compilation immediately, so they are properly reported.
This fixes #2496 
I did not handle `TK_LITERAL` in `uifset` as it seemed to be more of an unwanted state of the AST in general, if such an AST node reaches this function and thus tried to avoid getting into this branch in the first place.
> Properly report default argument inference errors

- .appveyor.yml
- Dockerfile
- Makefile
We forgot to remove some lines dealing with extra files that have been required in order to build the docs.
They got deleted but not all build files have been updated.
This is hereby done.
fixes #2537
> cleanup build files after doc generation merge

- packages/process/process_monitor.pony
In 1104a6ccc182d94e3ec25afa4a2d028d6c642cc4 an extra BackpressureAuth
parameter was added to ProcessMonitor::create(), but the sample code
was not updated.
[skip ci]
> Update sample code in ProcessMonitor documentation

- packages/net/tcp_connection.pony
Addresses the first part of the problem described in #2526.
> Add warning about _pending's use in tcp_connection.pony

- README.md
Build instructions for Ubuntu Xenial didn't work for me and needed an extra parameter. Added a section to the README.
> Add Ubuntu Artful section to build instructions

- src/libponyc/codegen/codegen.c
- src/libponyc/codegen/codegen.h
- src/libponyc/codegen/gencall.c
- src/libponyc/codegen/gencontrol.c
- src/libponyc/codegen/gendesc.c
- src/libponyc/codegen/genexe.c
- src/libponyc/codegen/genfun.c
- src/libponyc/codegen/genident.c
- src/libponyc/codegen/genmatch.c
- src/libponyc/codegen/genoperator.c
- src/libponyc/codegen/genprim.c
- src/libponyc/codegen/genreference.c
- src/libponyc/codegen/genserialise.c
- src/libponyc/codegen/gentype.c
This change is a followup to abdcf2e and 884c62d. Instead of fully reifying each function before generating it, the code generator now reifies part of the function as needed.
This further reduces the amount of AST duplication during compilation and will simplify the upcoming work on type-erased generics, which will in turn be used in the separate compilation work.
> Use deferred reification during code generation

- packages/cli/command_spec.pony
In package cli at command_spec.pony:
- Original add_help() function always adds a help option with an empty description
- I add a parameter that allows to modify the standard help option's description while using add_help
> Allow user defined help string at CommandSpec.add_help()

- src/libponyc/ast/ast.c
the print routine in ast.c already prints a crlf so the one printed
in ast_fprint is unnecessary, this change removes the extra crlf.
To test I added some consecutive ast_print statements to
suggest_alt_name:
```
if(case_ast != NULL)
{
+    AST_GET_CHILDREN(case_ast, first, second);
+    printf("suggest_alt_name:    ast "); ast_print(ast, 200);
+    printf("suggest_alt_name:  first "); ast_print(first, 200);
+    printf("suggest_alt_name: second "); ast_print(second, 200);
+
+    return NULL;
+
```
Before this change the output would be:
```
$ ./build/debug/ponyc ../issue-2508/
Building builtin -> /home/wink/prgs/pony/ponyc/packages/builtin
Building ../issue-2508/ -> /home/wink/prgs/pony/issue-2508
suggest_alt_name:    ast (reference (id doit))
suggest_alt_name:  first box …
```
> Remove extra crlf from ast_fprint

- pony.g
- src/libponyc/ast/parser.c
- src/libponyc/ast/treecheckdef.h
- src/libponyc/expr/lambda.c
- src/libponyc/pass/docgen.c
- test/libponyc/parse_entity.cc
This PR implements the first part of RFC 50: https://github.com/ponylang/rfcs/blob/master/text/0050-class-actor-fields-docstrings.md (The second part is docgen documentation in the tutorial).
It does roughly the following
* adapting the parser to accept optional docstrings below actor and class fields
* adapt the docgen pass to also display field docstrings if available
The ponylang mkdocs theme has been updated for field docstrings. Example:
fixes #2502
> [RFC 50] add member docstrings

- src/common/platform.h
- src/libponyc/ast/ast.c
- src/libponyc/ast/ast.h
- src/libponyc/codegen/genexe.c
- src/libponyc/codegen/genlib.c
- src/libponyc/options/options.c
- src/libponyc/pass/pass.c
- src/libponyc/pass/pass.h
- src/libponyc/pkg/package.c
- src/libponyc/pkg/package.h
- src/libponyc/plugin/plugin.c
- src/libponyc/plugin/plugin.h
- src/libponyc/reach/reach.h
- src/ponyc/main.c
This change adds a framework for compiler plugins. Plugins are specified through the new `--plugin` command line option and can observe the compiler data structures at various stages of the compilation process. Only read-only plugins are supported.
An example of this functionality is a plugin that reports detailed metrics about the compilation process.
> Add basic compiler plugins

- packages/files/file.pony
Use @ponyint_o_rdonly rather than _rdwr in the calls to @open and
@_open.
> Make the File.open constructor use read-only mode (Issue #2567)

- src/libponyc/pass/refer.c
- test/libponyc/suggest_alt_name.cc
The pony_assert(ast_id(id == TK_ID) assumes that ast_id(id)) is
always a TK_ID, but that is not the true if the first child of case_ast
is a function or behavior.
This fix checks for a TK_ID for both first and second children of
case_ast and gives up if neither is a TK_ID instead of asserting.
> Fix compiler crash in alternate name suggestion logic (issue #2508).

- packages/serialise/serialise.pony
- src/libponyc/reach/paint.c
- src/libponyc/reach/reach.c
- test/libponyc/reach.cc
This change ensures that for every compilation of the same code with the same compiler version, type and method IDs will not change. This is done by ensuring a deterministic iteration order of the reachability map (which is done by hashing object contents rather than object addresses.)
> Ensure type and method IDs determinism between recompilations

- packages/process/process_monitor.pony
This is a 99% fix for #2529; instead of the test program in the issue failing almost immediately with 10 subprocesses, it fails after somewhere in the region of 3k to 50k iterations, depending on whether ponyc is a debug build, has extra debugging printfs inserted, etc. When some extra code is inserted into the epoll asio backend to check the return value of epoll_ctl(..., EPOLL_CTL_DEL,...), call is always failing as the fd is already closed. I don't quite understand why the test program eventually hangs; it almost seems like some events are not being posted to the receiving actor. This needs further testing, so please leave #2529 open.
> Always unsubscribe process_monitor fds before closing them (#2529)

- src/libponyc/expr/call.c
- src/libponyc/expr/ffi.c
- src/libponyc/expr/lambda.c
Add type info for arguments and parameters in the "argument not a subtype of parameter" error.
Fix for issue #2530.
> Add arg and param type to "not a subtype" error (issue #2530)

- lib/gbenchmark/src/commandlineflags.cc
- wscript
This seems cleaner than using #undef's that where used when change
9c0053990ba7d4748274f9c7ddce85756488eb0a added them to commandlineflags.cc.
@kulibali, could you review this please.
> Use NOMINMAX to get gbenchmark to compile on windows

- lib/gbenchmark/src/internal_macros.h
- lib/gbenchmark/src/sysinfo.cc
- lib/gbenchmark/src/timers.cc
These changes serve no real purpose in gbenchmark where there are no
differences between FREE BSD and DragonFly BSD.
I didn't realize that when I created PR #2573 "Update gbenchmark" and
merged in the gbenchmark changes from PR #2183. This reverts back to
just using BENCHMARK_OS_FREEBSD in lib/gbenchmark and thus a few less
differences between lib/gbenchmark and google/benchmark.
> Revert gbenchmark DragonFly BSD 4.8 Support in gbenchmark

- packages/builtin/array.pony
- packages/builtin/pointer.pony
- packages/builtin/string.pony
- src/libponyc/codegen/genprim.c
`_consume_from` was implemented as a workaround for `Array.compact`, which needed to copy elements from a pointer to another without aliasing, and thus couldn't use `Pointer._copy_to`. The API of
`_consume_from` didn't reflect the function name, as the receiver wasn't necessarily consumed. Even though the function could only be used from the builtin package, the discrepancy was somewhat confusing and could have lead to subtle bugs within builtin.
The new `_convert` function does a raw (potentially unsafe) cast between pointer types and is used in `Array.compact` to construct an aliased pointer type. This is still an unsafe hack around the type system's safety, but it is now a clear and straightforward hack, similar to `Pointer._unsafe`.
No changelog entry since this is a change to a …
> Add Pointer._convert and remove Pointer._consume_from

- src/libponyrt/mem/pool.c
This reverts commit 5494d9b3ea54d33617894bd7e3b0c4b6b10e7078.
The above commit was intended to leave a smaller memory footprint
that stabilized at a quicker rate. However, testing using Wallaroo's
Market Spread application showed explosive memory growth when dealing
with a high workload. After speaking to @dipinhora about the issue, he
suggested reverting the commit as this was not the effect intended
by his change. He suspects the issue might be due to how the
`pool_pull` function behaves but has not had the time to investigate
to confirm. For additional information on the suspected cause of the
bug, contact @dipinhora.
**Notes:**
The memory of the Wallaroo Market Spread application processing 3m messages per second grew to roughly 850mb within 5 minutes with this commit. With the …
> Revert "Make scheduler threads share memory more quickly"

- src/libponyc/pass/sugar.c
- test/libponyc/sugar.cc
from classes or actors with initialized fields
by executing `sugar_docstring` on the constructors before adding the initializers. This will actually execute `sugar_docstring` twice on such constructors, but as it is idempotent, there is no danger here.
The docstrings have been inlined into the constructor body before.
Now they will show up correctly in the generated docs.
Fixes #2582
> Fix extracting docstring from constructors

- src/libponyc/codegen/codegen.c
- src/libponyc/codegen/codegen.h
- src/libponyc/codegen/gentype.c
- src/libponyc/codegen/host.cc
The LLVM optimiser in its current state treats infinite loops as provoking undefined behaviour, which can lead to very undesirable effects in Pony programs (for example, an incorrect behaviour being called on a message receive.)
This change should completely fix the example described above, and fix some other less catastrophic manifestations of this bug.
There are ongoing efforts to fix these bugs on LLVM's side. Once they are completely fixed, this workaround can be removed.
> Partially mitigate LLVM's infinite loops bug

- src/libponyc/codegen/genfun.c
- src/libponyc/codegen/gentrace.c
- src/libponyc/codegen/gentype.c
- test/libponyc/codegen_trace.cc
Now that tuples can be subtypes of some interfaces, they must be properly traced in those cases. Tuples now have a trace function which is called when traced from behind an interface.
> Fix tracing of boxed tuples through interfaces

- src/libponyc/pass/flatten.c
- test/libponyc/flatten.cc
Specifying an incorrect capability on a type parameter should result in a compiler error. The previous implementation of the associated check was incorrect and never resulted in an error (but the correct capability was being set.)
> Properly report type parameter capability errors

- src/libponyc/pass/expr.c
- src/libponyc/pass/flatten.c
- src/libponyc/type/subtype.c
Previously, union folding (the process of removing members from the union if they have a redundant subtyping relationship) was done during the flatten pass. This was problematic, as the `is_subtype` function needed for folding can return false negatives for structural subtyping if the AST processing hasn't reached the traits pass.
Union folding now happens during the expr pass, which runs after the traits pass. The flatten pass now only flattens union members in a single AST node. This doesn't fix any type checking issue as getting a false negative in that situation only meant that a redundant union member would be present. However, it does allow us to prevent other potential bugs since we can now add an assertion checking the pass status in the structural subtyping code.
> Delay union folding until the expr pass

- src/libponyc/type/alias.c
- test/libponyc/recover.cc
It is now allowed to recover one mutable element in the tuple, as long as all other elements are already safe.
In addition, the compiler now reports an error when attempting to recover unsafe tuples instead of silently accepting without actually lifting the capabilities.
> Allow recovering at most one element of a tuple to mutable capability.

- src/libponyrt/actor/actor.c
- src/libponyrt/pony.h
- src/libponyrt/sched/scheduler.c
This commit adds a C function that, given a scheduler context, returns
the index of the scheduler. This can be useful in applications that
interact with C libraries and need to do things on a per-thread basis.
> Add support for getting the index of a scheduler

- src/libponyrt/lang/socket.c
As of OSX Mountain Lion, there are new options for keepalive
socket options that allow the same amount of control as on
Linux and BSD. See the following two links reference the
new options and their behavior:
https://lists.apple.com/archives/macnetworkprog/2012/Jul/msg00005.html
https://github.com/dotnet/corefx/issues/14237#issue-193825607
This commit updates the pony_os_keepalive function to take
advantage of this functionality.
> Update pony_os_keepalive for OSX

- src/libponyrt/lang/socket.c
According to man pages for write/read/send/etc, POSIX allows
for operations on nonblocking sockets to fail with either
EWOULDBLOCK or EAGAIN.
This commit updates the code in socket.c to handle EAGAIN
the same as EWOULDBLOCK for increased portability.
> Handle EAGAIN errors on socket operations

- src/libponyrt/asio/asio.c
- src/libponyrt/asio/asio.h
- src/libponyrt/sched/scheduler.c
- src/libponyrt/sched/scheduler.h
Prior to this commit, it was possible for the ASIO thread to
be stopped in anticipation of runtime termination when runtime
termination didn't actually occur. This would leave the runtime
in an invalid state where a new ASIO thread would need to be
restarted.
This commit changes the behavior to ensure that the ASIO thread
is only stopped when the runtime is about to be terminated to
ensure the runtime cannot be in an invalid state where the ASIO
thread isn't running.
> Ensure ASIO thread cannot be stopped prematurely

- src/libponyrt/asio/epoll.c
- src/libponyrt/asio/iocp.c
- src/libponyrt/asio/kqueue.c
Also added asserts to pony_asio_event_resubscribe_(read|write); only for epoll & kqueue because iocp doesn’t have those two functions.
This is based on a request @mfelsche made in #2580.
While I have your attention, I'll just note that pony_event_resubscribe_(read|write) are not declared in event.h, despite being marked with `PONY_API`. However, as they are not defined at all for Windows it's not clear if they are actually part of the api, or just some internals that can be used in pony code, so the only place they are used in ponyc is in tcp_connection.c.
> Make asserts consistent across asio implementations

- src/libponyc/expr/array.c
- test/libponyc/badpony.cc
that can possibly return null.
fixes #2602 
would you want a test for that?
> Fix compiler crash related to array inference.

- packages/builtin/env.pony
- packages/builtin/stdin.pony
- packages/files/directory.pony
- packages/files/file.pony
- packages/files/file_info.pony
- packages/files/file_mode.pony
- packages/files/file_path.pony
- packages/json/json_doc.pony
- packages/json/json_type.pony
- packages/net/http/_client_connection.pony
- packages/net/http/_http_parser.pony
- packages/net/http/client.pony
- packages/net/http/payload.pony
- packages/net/http/status.pony
- packages/net/http/url.pony
- packages/net/net_address.pony
- packages/options/options.pony
- packages/ponybench/benchmark.pony
- packages/ponytest/test_helper.pony
where it is possible and makes sense.
With the merge of #2543 this is now syntactically valid.
Please feel free to give better suggestions for any docstring you think is wrong, inappropriate or incomplete.
> Add field docstrings to public fields of stdlib entities

- packages/builtin/string.pony
that could surface if the newly allocated cstring buffer is not set to 0 .
Fixes #2613
> Fix off-by-one error in String.cstring

- src/libponyrt/mem/heap.c
- src/libponyrt/pony.h
This change forbids the reallocation of foreign memory in pony_realloc. This is because the function can only know the size of the old allocation (and thus the amount to copy) if the memory was pony_alloc'ed.
> Do not realloc non-pony_alloc'ed memory in pony_realloc

- CHANGELOG.md
- examples/commandline/main.pony
- examples/gups_basic/main.pony
- examples/gups_opt/main.pony
- examples/httpget/httpget.pony
- examples/mandelbrot/mandelbrot.pony
- examples/message-ubench/main.pony
- examples/printargs/printargs.pony
- examples/yield/main.pony
- packages/buffered/reader.pony
- packages/builtin/env.pony
- packages/builtin/stdin.pony
It is now allowed to supply a custom input stream and a custom exit code handler to the user-exposed constructor of Env, allowing full customisation of the artificial environment.
Manual changelog entry included.
> Allow more customisation of artificial environments

- README.md
When trying to install via DEB package on bintray, according to the README instructions, I hit issues with this command:
```
sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys "D401AB61 DBE1D0A2"
```
```
gpg: "D401AB61 DBE1D0A2" not a key ID: skipping
```
After reading [this ticket](https://github.com/ponylang/ponyc/issues/1825) and seeing a different key there, I changed it to the following, and everything worked:
```
apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys "379CE192D401AB61"
```
Did the old command ever work?
Am I missing something?
> Fix GPG key for bintray in README.

- src/libponyc/ast/ast.c
- src/libponyc/ast/ast.h
- src/libponyc/codegen/genmatch.c
- src/libponyc/codegen/gentrace.c
- src/libponyc/expr/match.c
- src/libponyc/expr/operator.c
- src/libponyc/type/matchtype.c
- src/libponyc/type/matchtype.h
- test/libponyc/matchtype.cc
Detailed information is now reported by each `is_x_match_x` function, similar to how subtyping errors are reported.
> Improve pattern matching error reporting

- packages/files/file_path.pony
Hi, this PR fixes 2 issues mentioned in #2158:
- directory is disposed in the end of the loop, otherwise it can result in too many open files error.
- files are omitted from recursive descend, so `Directory(this)?` should work without throwing so many errors.
> Fix FilePath.walk performance issues (issue #2158).

- src/libponyrt/actor/actor.c
I'd found this bug while working on an app that uses `Backpressure.apply()` and `Backpressure.release()`.  This patch fixes a bug in actor.c's `ponyint_actor_run()` that could mute an actor that had `FLAG_UNDER_PRESSURE` status.
> Do not mute sender if sender is under pressure

- .appveyor.yml
- .ci-dockerfiles/llvm-6.0.0/Dockerfile
- .ci-dockerfiles/llvm-6.0.0/README.md
- .circleci/config.yml
- .travis_script.bash
- Makefile
- src/libponyc/codegen/codegen.c
- src/libponyc/codegen/gendebug.cc
- src/libponyc/codegen/gendebug.h
- src/libponyc/codegen/genopt.cc
- src/libponyc/codegen/gentype.c
- src/libponyc/codegen/host.cc
- wscript
This PR includes build system and code changes to support LLVM 6.0.0.
> Update with experimental support for LLVM 6.0.0

- src/libponyc/codegen/gencontrol.c
- src/libponyc/codegen/gencontrol.h
- src/libponyc/codegen/genexpr.c
- src/libponyc/codegen/genfun.c
- src/libponyc/reach/reach.c
- test/libponyc/codegen.cc
This fixes a bug where code generation would fail when trying to convert a tuple from a recover block to an abstract type. This was occurring because the `gen_assign_cast` function was expecting the tuple to have the LLVM type corresponding to the Pony type outside of the recover block, but it was encountering the type from inside of the recover block. This was failing because we use different LLVM types for tuples with differing capabilities.
Objects from recover blocks are now casted to the correct expected type before being handled to their user.
Closes #2639.
> Fix code generation failure with tuples in recover blocks

- CHANGELOG.md
- packages/builtin/float.pony
- packages/builtin/pointer.pony
- packages/builtin/real.pony
- packages/builtin/signed.pony
- packages/builtin/string.pony
- packages/builtin/unsigned.pony
- packages/collections/hashable.pony
- packages/net/http/_host_service.pony
- src/libponyc/ast/stringtab.c
- src/libponyc/codegen/genreference.c
- src/libponyc/expr/reference.c
- src/libponyrt/ds/fun.c
- src/libponyrt/ds/fun.h
- test/libponyc/codegen_identity.cc
- test/libponyc/util.cc
Having hash values being 64-bit wide on both 32 and 64-bit platforms was a bit odd. With USize, that width will match the machine word width on every platform.
> Make digestof and hash() return USize instead of U64 and add hash64()

- src/libponyc/codegen/codegen.c
- src/libponyc/codegen/genexe.c
- src/libponyc/codegen/genident.c
- src/libponyc/codegen/genlib.c
- src/libponyc/reach/reach.c
- src/libponyc/reach/reach.h
- src/libponyc/reach/subtype.c
- src/libponyc/reach/subtype.h
The previous algorithm for identity of objects was based on closed-world assumptions. That is, code was generated based on the reachable types in the program and the resulting algorithm wasn't generic. The current code generation process used in the compiler being purely closed-world, that genericity wasn't needed and the algorithm worked fine.
With the upcoming work on separate compilation, there will be cases where the code generation process is open-world, i.e. where the compiler doesn't know every existing type in the program when generating code. In those cases, the previous algorithm won't be usable anymore.
In addition, the previous algorithm worked by enumerating every possible type and generating specific code for each one, which could result in a lot of code being generated. A …
> Refactor identity code generation to avoid closed-world assumptions

- Makefile
It seems the apt.llvm.org packages already ship 6.0.1 although the official release is only scheduled for june, see http://lists.llvm.org/pipermail/llvm-dev/2018-March/121757.html. 
My `llvm-config-6.0 --version` installed from: `deb http://apt.llvm.org/xenial/ llvm-toolchain-xenial-6.0 main` shows `6.0.1`.
So i adapted the Makefile to support it.
The stdlib tests and the examples compile and run just fine on my machine.
There are no ci tests using the apt.llvm.org packages. Should we add them?
> Allow llvm-6.0.1 in the Makefile

- src/libponyc/codegen/genexe.c
- src/libponyc/options/options.c
- src/libponyc/pass/pass.h
I'm experimenting with compiling static binaries for easier distribution of compiled Pony programs.
I'm not sure yet everything that will be required, but this PR is a first step. Using this flag, I was able to compile a static binary within an alpine docker container, and run it on my host.
At some point after merging this, I want to formalize this process and write up some instructions for it. Then we can remove the "experimental" warning from this flag.
> Add experimental flag to compile a static binary.

- src/libponyc/type/matchtype.c
- test/libponyc/matchtype.cc
When pattern-matching tuples that have the same number of elements,
ponyc was treating the entire match as violating capabilities when
only one of the elements was violating. In truth we should be able
to recognize that tuples are distinct from the other elements.
This patch fixes `is_tuple_match_tuple` to return MATCHTYPE_REJECT
as soon as any pairwise element comparison returns MATCHTYPE_REJECT.
The fix was pinpointed by @Praetonus when I discussed this issue with
him.
> Fix tuple pattern matching issue where only some elements would violate caps.

- src/libponyc/ast/ast.c
- src/libponyc/pass/syntax.c
- test/libponyc/annotations.cc
- test/libponyc/codegen.cc
The compiler now checks for known annotation locations, and errors when that location is incorrect, for example a `packed` annotation on something else than a struct definition. This doesn't affect annotations that aren't recognised by the compiler.
> Issue a compiler error on a known annotation in an invalid location

- CHANGELOG.md
- packages/builtin/source_loc.pony
- src/libponyc/pass/sugar.c
- test/libponyc/sugar_expr.cc
SourceLoc already shows the method name of the __loc object,
but not the type name. Adding the type name is a logical next step,
since it is available.
EDIT:
Also renames `method` as `method_name`.
> Add SourceLoc.type_name method, showing the name of the containing type.

- Makefile
- src/libponyc/codegen/codegen.c
- src/libponyc/codegen/host.cc
Hi, this PR is trying to fix minor compilation issues I've found building and using ponyc on arm (32bit only at the moment), I hope I haven't done anything completely wrong.
Currently `-avx512f` is added explicitly to the list of cpu features in `libponyc/codegen/host.cc` and `libponyc/codegen/codegen.c` for all platforms when llvm < 5.0.0, though it is only supported by `x86`. As a result ponyc is generating at least one warning `'-avx512f' is not a recognized feature for this target (ignoring feature)` at multiple stages. 
Plus there's a minor bug in line 789 of `src/libponyc/codegen/codegen.c` 
```
size_t temp_len = strlen(opt->features) + 9; // should be 10 instead
char* temp_str = (char*)ponyint_pool_alloc_size(temp_len);
snprintf(temp_str, temp_len, "%s,-avx512f", opt->features); …
```
> Disable avx512f for x86 targets only

- src/libponyc/pass/docgen.c
This commit replaces the current MkDocs theme for generated standard library documentation with a version based on Material design with custom modifications (https://github.com/ponylang/mkdocs-theme). It also changes parts of the docgen pass to fit this new theme (thanks, @mfelsche), and changes the package for CI.
The generated documentation can be found in https://epiceric.github.io/
> Use Material theme for stdlib documentation

- src/libponyrt/mem/pool.c
Hi, this small patch fixes `pool_global_t.central` field intializer in `pool_global` for arm platforms (issue #2654).
> Fix atomic initializer in libponyrt pool_global for arm (#2654) 

- Makefile
The current `install` target is basically unusable for distributions. For example ponyc package in Arch Linux contains the [following comment](https://git.archlinux.org/svntogit/community.git/tree/trunk/PKGBUILD?h=packages/ponyc&id=6955fe6884dbe3481cd90f3b1e7bf8d9e87e8c5f#n46:):
> The makefile is very strange and requires almost as much post-correction as to simply do the installation myself. Even with patches to the makefile to stop it attempting to symlink locations it has no business touching.
I prefer to fix issues in upstream instead of making workarounds in each distribution, so I’ve fixed the Makefile to use `DESTDIR` and adhere to widely adopted [GNU conventions for install variables](https://www.gnu.org/prep/standards/html_node/Directory-Variables.html).
> Fix `make install` to use DESTDIR and follow common conventions

- packages/signals/signal_handler.pony
This allows programs that are waiting on a signal to proceed to
work. Sometimes, there are programs that are waiting for an alarm,
or similar prior to performing I/O.
This was impossible, because signal handlers were never registered
as noisy actors in asio. This allows for an optional named parameter
to be passed with that context.
A simple example of a program that was not supposed to terminate until it received a signal:
```pony
use "signals"
use "bureaucracy"
actor Main
// Create a TERM handler
let custodian = Custodian
let signal = SignalHandler(TermHandler(env, custodian), Sig.int())
custodian(signal)
class TermHandler is SignalNotify
let _env: Env
let _custodian : Custodian
new iso create(env: Env, custodian : Custodian) =>
_env = env
_custodian = custodian …
```
> Add mechanism to register (noisy) signal handler

- .ci-dockerfiles/alpine-llvm-3.9.1/Dockerfile
- .ci-dockerfiles/alpine-llvm-3.9.1/README.md
- .ci-dockerfiles/llvm-3.9.1/Dockerfile
- .ci-dockerfiles/llvm-3.9.1/README.md
- .ci-dockerfiles/llvm-4.0.1/Dockerfile
- .ci-dockerfiles/llvm-4.0.1/README.md
- .ci-dockerfiles/llvm-5.0.1/Dockerfile
- .ci-dockerfiles/llvm-5.0.1/README.md
- .ci-dockerfiles/llvm-6.0.0/Dockerfile
- .ci-dockerfiles/llvm-6.0.0/README.md
- .ci-dockerfiles/openssl-1.1.0/Dockerfile
- .ci-dockerfiles/openssl-1.1.0/README.md
- .ci-dockerfiles/shellcheck/README.md
- .circleci/config.yml
- packages/files/_test.pony
- packages/files/file.pony
mostly by writing tests for these cases. 
TL;DR the behavior is as expected in error cases.
fixes #2570
> Fix File.valid() and clarify File behavior in error cases

- src/common/platform.h
- src/libponyrt/lang/posix_except.c
Fix of issue #1719.
ARM64 systems do not use ARM Exception Handling ABI (EHABI), but rather the DWARF exception handling standard.
The fix turns off special ARM handling of exceptions when the target platform is ARM64.
This enables builds of the codebase on ARM64 systems with standard implementation of libunwind as shipped with gcc 5+.
* Tested on [ODROID-C2](http://www.hardkernel.com/main/products/prdt_info.php?g_code=G145457216438)
* Built arm64v8 Docker image with ponyc binary and passing tests: [vassilvk/arm64v8-ponyc](https://hub.docker.com/r/vassilvk/arm64v8-ponyc/)
* [Dockerfile](https://gist.github.com/vassilvk/7a0c119049723b3c2ea76758984bcf4c) for above image
> Fix failing aarch64 (ARM64) build (issue #1719)

- benchmark/libponyrt/ds/hash.cc
- benchmark/libponyrt/mem/heap.cc
- benchmark/libponyrt/mem/pool.cc
Hi, this PR fixes #2679, so that all benchmarks compile without warnings on 32 bit systems.
> Fix libponyrt benchmarks for 32bit platforms

- src/libponyc/codegen/genreference.c
I encountered this while porting pony to illumos.  On LLVM 3.9.1 when building the compiler/libs/etc as 32-bit, running the libponyrt tests would trip an LLVM assert (as described in the bug), and several other tests would segfault.  After applying this fix, the LLVM assert was not triggered and the segfaulting tests now completed successfully.  In addition another user has stated that applying the fix to 32-bit ARM also fixes problems encountered there.
> Fix __digestof phi expression returns the wrong type (#2683)

- packages/builtin/real.pony
- packages/builtin/signed.pony
- packages/builtin/unsigned.pony
- packages/builtin_test/_test.pony
These methods are pretty slow on non `native128` machines as we need to manually check for overflow.
fixes #2409
> Add addc, subc and mulc functions to I128 and U128

- src/libponyc/type/typeparam.c
- src/libponyc/type/viewpoint.c
- test/libponyc/type_check_subtype.cc
This PR fixes a case I ran into where typechecking was broken for `box->A`, when `A` was a type parameter that gets reified with a different type parameter at the outer level.
The case is demonstrated in the example from the new new unit test.
> Avoid flattening arrow to type param, fixing typechecking when reified with another type param.

- packages/files/_test.pony
- packages/files/directory.pony
On non-Linux and non-BSD platforms the direction.open_file() logic
defaults to a named path base open, rather than using `openat` calls.
However, this was using the `File.create(...)` call which opens files
for read/write, rather than just readonly. This in turn fails since
the `FileWrite` capability is explicitly dropped.
This commit simply switches to using `File.open(...)` which opens the
file in a readonly mode.
This fixes: https://github.com/ponylang/ponyc/issues/2695
> Change directory.open_file() to use readonly open

- packages/builtin/signed.pony
as it might not be available on some 32 bit systems (verified for an illumos system by @jasonbking ).
The required runtime function `__mulodi4` is not available from the gcc runtime library on these systems, it seems.
This change should not have any performance impact, as already verified in #2645 .
See also:
* https://bugs.llvm.org/show_bug.cgi?id=14469
* https://bugs.llvm.org/show_bug.cgi?id=16404
> Do not use llvm.smul.with.overflow.i64 anymore

- packages/files/_test.pony
- packages/files/file.pony
`File._descriptor(...)` was computing the `writeable` flag by checking
if the `FileRead` capability was set, rather than the `FileWrite`
capability.
> Compute File.writeable based on FileWrite instead of FileRead.

- src/libponyrt/lang/stdfd.c
This enables support for ANSI escape sequences in Windows console output for `stdout` and `stderr` for all Pony programs.
Fixes #2700.
Note that this will only work on Windows 10 builds later than 10586.
> Enable virtual terminal color output on Windows.

- packages/files/_test.pony
- packages/files/file.pony
Currently, `File.flush` returns `false` when the number of bytes pending to write is zero, even though the docstring says that:
```
Returns false if the file wasn't opened with write permission.
Raises an error if not all the bytes were written.
Returns true if it sent all pending data.
```
This situation should fall under the `true` condition - all pending data was successfully written - it's just that the number of bytes was zero. It definitely doesn't fall under the `false` condition because it has nothing to do with write permissions.
This PR fixes that bug and adds a test.
> Fix File.flush return value for case of zero bytes to flush.

- packages/files/_test.pony
The test `files/File.create-exists-not-writeable` creates a temporary file which is then supposed to be deleted.  This PR successfully deletes the file on Windows.
> Fix temporary file from test not getting deleted on Windows

- packages/builtin/string.pony
- packages/builtin_test/_test.pony
This PR addresses #2705, namely the over-aggressive truncation of trailing characters in String.rstrip().
> Incorrect rstrip handling of multibyte characters

- examples/under_pressure/main.pony
- packages/net/tcp_connection.pony
The examples given for how to use manually applied backpressure could lead
to deadlocking as it would be possible to dispose of the TCPConnection
or close it while backpressure had been applied and then not release it.
[skip ci]
> Update Backpressure.apply/release examples

- packages/process/_test.pony
- packages/process/process_monitor.pony
This is part one of addressing issue #2714. We avoid breaking compatibility with the API in this change.
We should rely on the system to do these checks properly. Since we don't currently have a clean way to signal failure of execv, we'll assert that the path is a proper file first.
> Relax ProcessMonitor checks for execute bits

- packages/builtin/string.pony
- packages/builtin_test/_test.pony
The loop pushing values from iter didn't increment n, resulting in finite iterators getting concated completely.
Also infinite iterators such as `Iter.repeat_value` would result in the function never returning and eating up memory.
This behavior contradicts the docstring.
> Fix String.concat ignoring the len parameter

- Makefile
- src/libponyc/codegen/genexe.c
The -mcx16 option for GCC is only valid on the x86 compiler and
it only applies to 64 bit code. See the following url for x86
options for GCC:
https://gcc.gnu.org/onlinedocs/gcc/x86-Options.html
This commit changes it to only be enabled for x86_64 targets.
> Only enable mcx16 for gcc for x86_64 targets

- .packaging/rpm/ponyc.spec
- Makefile
- README.md
- RELEASE_PROCESS.md
This commit
* updates install instructions to rely on Fedora COPR
packages and Ubuntu Launchpad PPA packages where applicable.
* adds additional compile from source instructions for
recent Fedora and OpenSuSE distributions.
* updates release instructions to account for the new COPR/PPA
packages that need to be confirmed to be successfully built.
* Cleans up recent Fedora/CentOS/RHEL build from source command
with a small enhancement to the `Makefile`.
> Update install, release instructions for COPR/PPA

- packages/cli/_test.pony
- packages/cli/cli.pony
- packages/cli/command_parser.pony
- packages/cli/command_spec.pony
- packages/stdlib/_test.pony
And Actually run the cli tests (that weren't passing).
To fix the case of a `CommandSpec.leaf` without args and with help i added a `_type` fields and getters for properly determining if a `CommandSpec` is a parent or a leaf. I would be more comfortable with having two different classes here that share a common trait, but i tried going that route and it entails some breaking API changes that need to go through the RFC process. I decided to ease the pain for now with this fix, but will most likely do a separate RFC soon.
> Fix CommandSpec without args and help

- src/libponyrt/sched/cpu.c
Specifically when numa is enabled and the count of available cpus isn't
greater than the number of numa cores.
Previously, when
```
if(avail_cpu_count > numa_count)
avail_cpu_size = numa_count;
```
was executed, then at that point avail_cpu_size was 0. this means if
`avail_cpu_count` is not greater than `numa_count` then `avail_cpu_size`
will remain 0 and:
```
ponyint_pool_alloc_size(avail_cpu_size * sizeof(uint32_t));
```
will allocate no memory and bad segfaulting things will happen.
This commit patches the bug to set `avail_cpu_size` to the CPU_COUNT
when we enter `ponyint_cpu_init`.
`  avail_cpu_size = avail_cpu_count = CPU_COUNT(&all_cpus);`
Fixes #2559
Fixes #2689
> Fix memory overflow when allocating CPUs when numa is enabled

- src/libponyrt/asio/epoll.c
Neither ASIO_DISPOSABLE or ASIO_DESTROYED events should cause a
read/write resubscription. However, we were allowing this.
Fixes #2684
> Fix incorrect disposable/destroyed epoll resubscribe handling

- src/libponyrt/sched/scheduler.c
As part of performance testing Wallaroo using multiple workers,
@JONBRWN discovered a regression in both throughput and latency.
He tracked the issue down the commit that re-enabled dynamic
scheduler scaling (fc80968ba54dedc2d486c74a7c39114081465497).
NOTE: This performance issue did not exist for singler worker
runs of Wallaroo.
Some head scratching and testing led to the current commit to
resolve the multi-worker performance issue. My best guess is that
before this change the `steal` loop was dependent on a memory
access to determine if dynamic scheduler scaling needed to
suspend a thread or not as its initial check. This would lead to
somewhat erratic behavior where some times the `steal` loop would
take long while other times it wouldn't depending on how long the
memory load took. …
> Fix performance related to dynamic scheduler scaling

- examples/gups_basic/main.pony
- examples/gups_opt/main.pony
- examples/mandelbrot/mandelbrot.pony
- examples/yield/main.pony
Although the commands specified in the examples don't have subcommands they used CommandSpec.parent,
which is meant for commands having at least 1 subcommand. Using CommandSpec.leaf fixes this issue,
as leaf is meant for single commands without subcommands. A parent CommandSpec adds a help subcommand
when calling add_help() on it and this rendered the commands unusable as a subcommand was expected.
Fixes #2314
> Fix cli usage in examples

- packages/serialise/serialise.pony
- src/libponyc/pkg/package.c
- src/libponyrt/gc/serialise.c
- src/libponyrt/gc/serialise.h
- src/libponyrt/sched/scheduler.h
- test/libponyc/compiler_serialisation.cc
- test/libponyrt/ds/hash.cc
This reverts commit d34dce667accf0797f0afcc5e04fd0605d1ad82e.
While performance testing the Pony version of Wallaroo's Market Spread
application in a multi worker scenario, it was discovered that the above
commit introduced a performance regression in both throughput and latency.
This regression is not present in a single worker run where serialisation
is not used. It should be noted that this regression only occurs when
consuming messages at a maximum rate and is not present if the sending
worker is not performing at maximum capacity. With this commit reverted,
sending in messages at the same rate resulted in higher throughput
and lower latencies.
If an example application is needed to recreate this behavior we can
provide instructions to run the Wallaroo application or attempt to
create …
> Revert "Remove exception parameterisation from serialisation (#2524)"

- packages/collections/persistent/_test.pony
- packages/collections/persistent/list.pony
This change fixes `Lists.from()`, which returned a reversed list, and the associated test, which didn't actually call it.
The change also changes `apply()` to use `from()` so as to have a single implementation of making a list from a sequence.
> Fix `collections/persistent/Lists.from()` to return elements in the correct order

- src/libponyc/codegen/genreference.c
- test/libponyc/codegen.cc
Insight for fix came from Sylvan.
Closes #2735
> Fix compiler segfault caused by dead code removal of tupled variables

- packages/buffered/reader.pony
- packages/net/http/_http_parser.pony
- packages/net/http/_test.pony
- packages/term/readline.pony
This implements [RFC 56](https://github.com/ponylang/rfcs/blob/master/text/0056-buffered-reader-line-iso.md) and fixes #2755 
This is a breaking change for code bases that do not use explicit types when assigning the returned `String iso^` to a variable:
```pony
let line = reader.line()?
```
These code bases need to either add an explicit type to their variable (`let line: String val = reader.line()?`) or need to `consume` the line upon aliasing or giving away to another function/behaviour.
> RFC 56: Make buffered.reader.line return String iso^

- Makefile
I ran into a problem linking lib/llvm failed because the system installed
llvm was installed in /usr/local/lib. When I tried to link the version
in <ponyc>lib/llvm it failed because the llvm in /usr/local/lib was linked
instead.
> Search for /usr/local/lib last

- packages/builtin/real.pony
- packages/builtin/signed.pony
- packages/builtin/unsigned.pony
I had a need for bit reverse semantics, noticed that `Integer` has `bswap` which exposes the `llvm.bswap` intrinsic, but the `llvm.bitreverse` intrinsic was missing.
So this PR adds the exposure of that missing intrinsic.
> Add Integer.bit_reverse, exposing the llvm.bitreverse intrinsic.

- src/libponyc/codegen/genreference.c
I recently added code to gen_tuple to fix a bug. That fix while
technically correct, added a bit of code duplication. I don't mind code
duplication, but unneeded duplication around freeing resources does tend
to bother me. It's usually an easy way to eventually end up not freeing
something.
This commit changes the code I added to gen_tuple to remove the
duplication.
> Refactor gen_tuple

- packages/promises/_test.pony
- packages/promises/promise.pony
Also, add a new unit test for this scenario.
> Fix Promise bug where join() element's reject doesn't reject the entire join

- src/libponyc/codegen/genreference.c
- test/libponyc/codegen.cc
I don't know the compiler well and I went off what I knew and believe I
found the root cause for our tuple bugs that started with 9222f08. Which
was in turn fixing https://github.com/ponylang/ponyc/issues/2735.
However, a number of bugs came from that fix because, it didn't fix the
root issue. Which was `gen_localdecl` returning GEN_NOVALUE where
GEN_NOTNEEDED was needed. This is why, prior to 9222f08, `gen_tuple` was
returning GEN_NOTNEEDED when the value it has was GEN_NOVALUE.
Fixes #2760
> Fix incorrect tuple handling

- packages/files/_test.pony
- packages/files/file.pony
Currently, when the `_pending_writes` IO vector inside `File`exceeds `IOV_MAX`, we enter a loop of iterating over chunks of the IO vector of size less than or equal to `IOV_MAX` in count. This loop was invalid, causing out-of-bounds array accesses that bubbled up an `error`.
This PR fixes the loop logic, and updates the tests to catch such issues.
It also cleans up some of the code and comment formatting issues in `File._write_to_disk`.
> Fix File.writev and File.flush in cases where the IO vector exceeds IOV_MAX.

- packages/ponytest/test_helper.pony
ℹ️ This was missing a `t` in `AmbienAuth`.
> ponytest/test_helper: fix link, line width

- packages/files/file.pony
Prior to this commit, there was a garbage-collection safety issue
with the way that the `_pending_writev` array worked in the `File`
class. The pending writev data was being stored in a flat array
with element type of `USize`, with the byte pointers being converted
to type `USize` in order to be stored alongside the buffer length
numbers in the same array.
Storing these pointers as numbers meant that they are no longer
traced by the garbage as being pointers, meaning that the garbage
collector would try to free the underlying memory due to no longer
being pointed to by any valid pointer.
This PR fixes the issue by using an `Array[(Pointer[U8], USize)]`
instead of an `Array[USize]`. This also eliminates some complexity
in the code that was related to accessing the array data in blocks
of 2 …
> Fix GC-safety issue with writev pointers in File.

- src/libponyrt/asio/epoll.c
Correctly this time as I messed up the boolean logic in
8b21f0a519fafdefef4ebdc7ed86cb629c572c2e.
Closes #2684
See for initial incorrect PR
https://github.com/ponylang/ponyc/pull/2744
>  Fix incorrect disposable/destroyed epoll resubscribe handling

- src/libponyc/pass/refer.c
Commit 9eb1687e introduced a bug in the symbol status forward
propagation where breaks are missing between the different
switch cases, causing the TRY case to fall through into the
REPEAT case.
> Fix missing break in refer_seq

- packages/json/json.pony
- packages/json/json_doc.pony
- packages/json/json_type.pony
JsonType has not been sendable anyways as JsonObject and JsonArray have been of refcap ref in JsonType,
so this only changes JsonDoc to be non-sendable, which should only have very little effect.
My first iteration was to make JsonDoc, JsonObject and JsonArray iso but this turned out to be cumbersome to use (especially when traversing into nested structures).
The other possibility would be to make all elements of JsonType val but this also turns out to be a little limiting when constructing a JSON structure, so i went with
the least invasive way for now.
Also added some package docs.
> Change refcap of JsonDoc to ref for better usability

- packages/json/json.pony
The """ ... """ cases the following error:
> Error:
> /home/stewart/opt/pony/bleed/packages/json/json.pony:60:22: syntax
> error: expected type, interface, trait, primitive, class, actor, member
> or method after # JSON Package
> Escape quotes " in JSON package documentation.

- packages/files/_test.pony
- packages/files/file.pony
While investigating a potential bug in my implementation of #2707 I found this one:
When requesting more bytes than available from a File the _errno was set to
although reading less than available bytes (> 0) is no error condition.
If anything then FileEOF should be set in this case to signal that we reached the end of file.
Nonetheless i kept it as it is right now, as i think it is more reliable to detect FileEOF when reading 0 bytes.
> Do not set File._errno when reading less than requested bytes.

- packages/builtin/array.pony
Fix #2759 
I added a few lines to the docstring for `Array.contains`, and provided an alternative predicate function object for matching by structural identity.
> Document Array.contains's default predicate

- src/libponyrt/lang/directory.c
By default Windows will translate `\n` to `\r\n` when writing to files, and vice versa when reading.  This interacts poorly with seeking in the file first (#2707).  This change makes opening files via the `files` package always use "binary" mode, which will not do any translation.
> Always use "binary" mode when opening files on Windows.

- src/libponyrt/gc/cycle.c
- src/libponyrt/sched/scheduler.c
In PR #2709, @sylvanc pointed out a concern regarding the cycle
detector creating a message storm due to how it would ask all
actors whether they are blocked or not on every interval.
This commit changes the logic so that the cycle detector only
asks set number of actors whether they are blocked or not. If
it is not able to ask all actors, it will resume iterating actors
on the next iteration.
This commit also addresses @SeanTAllen's concern regarding the
conditional check order using `ponyint_actor_getnoblock`.
> Make cycle detector block checking incremental

- .bintray_deb.bash
- .ci-dockerfiles/deb-builder/Dockerfile
- .ci-dockerfiles/deb-builder/Dockerfile.jessie
- .ci-dockerfiles/deb-builder/README.md
- .packaging/deb/rules
- .travis.yml
- .travis_commands.bash
- .travis_script.bash
With the introduction of deb packaging/distribution via Ubuntu
Launchpad PPA, we lost the ability for folks to be able to install
old versions of ponyc via their package manager. See:
https://github.com/ansible/ansible/issues/23143 for more info.
This commit switches back from Launchpad to Bintray for
hosting/distribution of deb packages. This necessitated that we
build the deb packages ourselves.
This PR includes changes to the travis ci config to now run two
additional jobs for every release build. One to build all the
debian version packages. The other to build all the ubuntu version
packages. The changes also include uploading the packages to a new
bintray debian repo.
Unfortunately, I ran into some issues with using `sbuild` on trusty
so I had to fall back to using docker containers …
> Deb packaging for bintray to allow for old version installation

- packages/net/_test.pony
Fix  #1942.
This method will log a message explaining why the test might fail and give instructions on how to re-run the test suite with that test excluded.
I did my best to stick to the plan set out by @SeanTAllen [here](https://github.com/ponylang/ponyc/issues/1942#issuecomment-316504382), but I did not fulfill point 2, as the test already has a label. Instead, the log message explains how to use `--exclude` to run the rest of the test suite.
> Add _TestBroadcast.timed_out()

- Makefile
- src/common/llvm_config_begin.h
- src/common/llvm_config_end.h
- src/libponyc/codegen/genopt.cc
- wscript
This change uses llvm-config to get the build-mode for llvm. This is then
used to set NDEBUG appropriately so the llvm headers included in
llvm_config_begin.h have NDEBUG defined if the build was Release or
RelWithDebInof and undefined if Debug.
See ponylang issue #2776 for more details.
> Fix symbol clash that arises from LLVM debug/release mismatch #2776

- .appveyor.yml
- wscript
`llvmBuildMode` needs to be defined even for `make clean`.
> Fix Python error in Windows when "make clean" is run

- Makefile
- src/libponyc/codegen/genexe.c
While investigating #2823 for OpenBSD support and also #2825, I also tried twiddling a bit with FreeBSD and discovered that it isn't possible to compile with `config=debug` successfully.  Running `gmake config=debug test verbose=true` on ponyc's tag `0.24.0` on both FreeBSD 11 + LLVM 3.9.1 and DragonflyBSD 4.8.1 + LLVM 3.9.1:
```
[...]
c++ -MMD -MP -march=native -mtune=generic -Werror -Wconversion -Wno-sign-conversion -Wextra -Wall -g -DDEBUG -std=gnu++11 -fno-rtti   -c -o build/debug/obj/tests/libponyrt/util.o test/libponyrt/util.cc  -I src/common/ -I src/libponyrt/ -isystem lib/gtest/
Linking libponyrt.tests
c++ -o build/debug/libponyrt.tests build/debug/obj/tests/libponyrt/ds/fun.o build/debug/obj/tests/libponyrt/ds/hash.o build/debug/obj/tests/libponyrt/ds/list.o …
```
> Add libexecinfo to debug builds for BSD

- .travis_script.bash
- CHANGELOG.md
I missed one minor detail in the bintray deb packaging PR as I was
cleaning things up for the PR and that caused the bintray debs
travis jobs to fail when they tried to install LLVM as part of the
normal release steps.
This commit fixes that to ensure the normal release steps don't
run during the bintray deb building jobs.
> Ensure bintray deb travis jobs don't try and run PPA/COPR/etc

- .travis_script.bash
NOTE: This will require the cron job functionality to be enabled through the Travis UI (https://docs.travis-ci.com/user/cron-jobs/).
-------------------------------
Currently only for Travis and only builds debian packages and
installs ponyc HEAD using brew.
Currenly doesn't save any packages built but will be useful to catch
any packaging related issues.
> Initial version of nightly packaging builds

- packages/builtin/array.pony
- packages/builtin/string.pony
- packages/builtin_test/_test.pony
Prior to this commit, if `Array.trim_in_place` and `String.trim_in place`
trimmed all of the memory allocated for the array or string (i.e.
`trim_point == space()`) then trim_in_place would still use _ptr._offset
to set the pointer to be the byte after the last byte allocated by the
array or string. This was bad for many reasons but sometimes especially
bad if that next byte happened to be in a different pagemap that had not
yet been allocated. This would result in a segfault the next time `reserve`
was called because the runtime would think this pointer was not allocated
by pony and complain that it cannot realloc memory not allocated by pony.
This commit fixes the logic in trim_in_place to allocate a new Pointer
if _alloc == 0 (i.e. all of the memory allocated for the array or string …
> Fix array and string trim_in_place allocation bounds check

- .bintray.bash
- .travis.yml
- .travis_commands.bash
- .travis_script.bash
NOTE: The bintray upload will fail until a generic repo with the name `ponyc-appimage` is created in the pony-language bintray account.
----------------------------------
See https://appimage.org/ for more info about the AppImage format.
The AppImage packages are built in a CentOS 7 docker image and
should theoretically be compatible with all glibc based x86_64
distros with the same or a newer glibc version.
This commit also fixes an issue with the nighly build of debian
packages.
> Initial version of AppImage packaging for ponyc

- src/libponyrt/platform/threads.c
While investigating some strange memory-clobbering looking behavior in #2850, I discovered that macOS uses a different default Pthreads stack size than Linux does.  This PR uses the `RLIMIT_STACK`'s current limit if it is sane, i.e., if it meets the minimum size and isn't infinity.
Note that the libuv developers discovered this and have a patch that I borrowed from: https://github.com/libuv/libuv/issues/669
I'm not Pthreads-savvy enough to know if it is safe to set both actual stack memory & stack size in the same `attr`, in the case of the Pony runtime's checking for NUMA use on Linux.  I am being conservative and assuming that they should not be combined. This patch could save a few lines if it were OK to do combine them.
>  Use RLIMIT_STACK's current limit for Pthreads stack size if it is sane

- .travis.yml
- .travis_commands.bash
- .travis_script.bash
- README.md
- RELEASE_PROCESS.md
This commit removes the recently added Launchpad PPA generation now
that the new Bintray DEB packages are successfully building during
releases. The README is updated to direct users to use the new
Bintray DEB packages instead of the Launchpad PPA packages. This
was done mainly because Launchpad PPA does not allow installing of
older versions once a new version is released.
This commit also includes the details regarding how to use the
AppImage package that is now cre0ated and uploaded to Bintray.
> Remove Launchpad PPA in favor of new Bintray DEB packages

- src/libponyc/ast/ast.c
- src/libponyc/codegen/gencontrol.c
- test/libponyc/codegen.cc
`then` clauses could be skipped if the containing `try` expression was within a loop and the body or else clause contained a `continue` or `break` statements. Also if the `try` was somehow nested into another `try` and the body or else clause contained a `return` the `then` clause was skipped.
This has been solved by going up the AST and searching for all `then` clauses to generate.
fixes #2843
> Fix skipped try-then clauses on return, break and continue statements

- packages/promises/promise.pony
The current promise examples don't compile with pony `0.24.3` and after mentioning it on IRC, I've fixed these to examples so they work now.
> Fix promise examples so that they compile

- packages/files/_test.pony
- packages/files/path.pony
Fixes #2861, and adds several cases to the `files/Path.clean` test.
> Fix `files/Path.clean()` not correctly handling multiple `..`

- src/libponyc/expr/lambda.c
- src/libponyc/pass/flatten.c
- src/libponyc/pass/syntax.c
- test/libponyc/badpony.cc
- test/libponyc/object.cc
Previously using a type alias pointing to a UNION type in the provides list of an object literal made the compiler assert.
fixes #2829 
There is still a missing case where one would in general expect a compiler error, but nothing is thrown: Having a union of subtypes behind a type-alias:
```pony
interface I1
interface I2
type T1 is (I1 | I2)
actor Main
new env(e: Env) =>
object is T1 end
```
By the time the object AST is resolved the union folding already kicked in, so `T1` only resolves to `I1`, not a union anymore. I am unsure what to do about this. Is this really a case that we should care about?
> Fix validation of provides lists of object literals.

- Makefile
- README.md
- lib/gbenchmark/src/internal_macros.h
- lib/gbenchmark/src/sysinfo.cc
- lib/gbenchmark/src/timers.cc
- packages/builtin/platform.pony
- src/common/paths.h
- src/common/platform.h
- src/libponyc/codegen/genexe.c
- src/libponyc/codegen/genopt.cc
- src/libponyc/codegen/genopt.h
- src/libponyc/codegen/genprim.c
- src/libponyc/pass/pass.h
- src/libponyc/pkg/buildflagset.c
- src/libponyc/pkg/package.c
- src/libponyc/pkg/platformfuns.c
- src/libponyc/pkg/platformfuns.h
- src/libponyc/platform/paths.c
- src/libponyrt/lang/socket.c
- src/libponyrt/mem/alloc.c
- src/libponyrt/platform/ponyassert.c
- src/libponyrt/sched/cpu.c
- src/ponyc/main.c
Hi --
As asked, here is a PR that adds OpenBSD support.
Must be built with default_pic=true.
Have not really done any runtime testing, but it passes the build test so that's a strong start.
> Added OpenBSD support.

- packages/builtin/_partial_arithmetic.pony
- packages/builtin/real.pony
- packages/builtin/signed.pony
- packages/builtin/unsigned.pony
- packages/builtin_test/_test.pony
- src/libponyc/ast/bnfprint.c
- src/libponyc/ast/lexer.c
- src/libponyc/pass/sugar.c
- test/libponyc/lexer.cc
- test/libponyc/verify.cc
This PR adds partial arithmetic functions and operators to all integer types.
Normal classes can also provide partial arithmetic operators, like `+?`, `-?`, `*?`, etc. by implementing `add_partial`, `sub_partial`, `mul_partial` etc. the same way the normal operators work on classes.
I limited this PR to `+?`, `-?`, `*?`, `/?` and `%?`.
Two question arised during implementation:
* Should we extend these methods to all numeric types, especially to floating point operations, erroring whenever `NaN` or `Inf` or `-Inf` would be returned?
* Should we add `shl_partial`, `shr_partial` and `neg_partial` too? As part of this PR?
Closes #2814
> [RFC 58] Add partial arithmetic for integer types

- packages/builtin/stdin.pony
The current implementation fills the full underlying array based on the
"space" available.
However, the space may be larger than the chunk size since space is
allocated in powers of two. However, when the data buffer is passed back
via the InputNotify handle it is first appropriately truncated to the
actual `len` read by @pony_os_stdin_read. But, the implementation of
truncate sets the size to max(len, size) and does not take into account
the underlying allocated space.
The net result is that reading of stdin looses data unless the chunk
size provided is actually a power of two — in which case
`_size == _alloc`.
This change simply limits the read to `data.size()` rather than
`data.space()`.
Please see: https://github.com/ponylang/ponyc/issues/2871.
> Fix losing data when reading from STDIN.

- CHANGELOG.md
- examples/files/files.pony
- packages/buffered/reader.pony
- packages/files/_test.pony
- packages/files/file.pony
- packages/files/file_lines.pony
- packages/ponytest/_test_runner.pony
- packages/ponytest/pony_test.pony
- packages/ponytest/unit_test.pony
* remove `File.line`
* add `ponytest.UnitTest.set_up` method for initializing test state that needs a `TestHelper` (i.e. for getting an `Env`)
Fixes #2185
> Reimplement files.FileLines

- wscript
This change modifies the `wscript` file to handle spaces in the directory ponyc is built in.  Fixes #2878
> Fix building on Windows in a directory with spaces in its name

- src/libponyc/codegen/gendebug.cc
Existing code results in a warning, and since warnings are treated as errors, the compilation fails.
> Fix compilation warning on windows.

- README.md
This change adds a mention of the "Desktop Development for C++" workload for Visual Studio 2017, and updates the link to the Visual C++ Build Tools (#2885).
> Update Windows requirements in README [skip ci]

- packages/builtin/_partial_arithmetic.pony
- packages/builtin/real.pony
- packages/builtin/signed.pony
- packages/builtin/unsigned.pony
- packages/builtin_test/_test.pony
This is added in order to provide all basic operators as unsafe, normal, partial and checked version.
`modc` is following.
> Add divc method to integer types

- src/libponyrt/lang/stdfd.c
Standard input on Windows was hanging when a modifier key (CTRL, ALT or SHIFT) was pressed.  This change correctly handles the console keydown event where there is no actual character value.
Fixes #2891
> Correctly handle modifier keys for TTY stdin on Windows

- CHANGELOG.md
- packages/collections/persistent/_bits.pony
- packages/collections/persistent/_map_node.pony
- packages/collections/persistent/_test.pony
- packages/collections/persistent/benchmarks/main.pony
- packages/collections/persistent/map.pony
This PR includes modifications to the persistent hash map which have also resulted in a fix for #2866. The improvements include removing the `U8` level field from all nodes and applying full CHAMP compression to the entries at each node.
> Improved CHAMP map

- src/libponyrt/mem/pool.c
Thanks to @malte for identifying the root cause of #2013.
This PR fixes things so that if there's a request for a `size_t`
sized allocation, it actually tries to allocate it instead of
pretending that it allocated it while not actually allocating
anything which results in memory clobbering and segfaults.
resolves #2013
> Fix invalid allocation bug in runtime that allows for segfaults

- src/libponyrt/asio/epoll.c
- src/libponyrt/asio/event.h
Prior to this commit, the way the ASIO notifications worked on
linux epoll included an edge case/race condition that allowed
for a loss of ASIO events.
As part of testing wallaroo scalability, we encountered an issue
(WallarooLabs/wallaroo#2547) where some of our TCP actors would
stop reading from the socket for no reason even though there
was data waiting on the socket. After much fighting, @SeanTAllen
inferred that the ASIO subsystem was losing notifications and
the TCP actor was never notified about the data waiting on the
socket.
This commit changes things so that going forward:
* ASIO one shot subscriptions do *not* use edge triggered mode, but
instead use level triggered mode
* Always tries to resubscribe to both read and write depending on
the state of the `ev->readable` and …
> Fix ASIO one shot lost notifications problem

- .travis_commands.bash
- .travis_script.bash
mkdocs and our theme can be rather fragile. It's broken before. We are
going to need to touch it soon. So, this adds a daily check to make sure
its working correctly and won't blow up during a release.
> Add test that our documentation building works

- packages/buffered/benchmarks/main.pony
- packages/ponybench/_runner.pony
- packages/ponybench/benchmark.pony
This commit adds `before_iteration` and `after_iteration` to ponybench
benchmarks. It also changes the syncbenchmark `before` and `after`
to allow them to throw errors.
This commit also updates the `buffered` package benchmarks to use the
new `before_iteration` and `after_iteration` hooks.
----------------------------------
NOTE: These changes might need to go through the RFC process. They seem like "principle of least surprise" to me but others may not agree.
----------------------------------------
old benchmark results:
```
vagrant@ubuntu-xenial:~/dhp/packages/buffered/benchmarks$ ./benchmarks.after --ponythreads=1 --ponyminthreads=1
Benchmark results will have their mean and median adjusted for overhead.
You may disable this with --noadjust.
Benchmark …
```
> Add before/after iteration hooks to ponybench

- README.md
A friendly user on the #ponylang IRC channel noticed that the top level README's link to the AppImage package download area isn't correct.  Let's edit README.md to correct the link.
> Correct README.md link to AppImage packaging location

- src/libponyc/pkg/package.c
basically only relevant for docgen purposes - so the dir given as arg to ponyc wont be used as is as package name, but its basename will be.
> [docgen] use basename as program package name

- Makefile-ponyc
Later in the makefile, it's looking at `$(wildcard $(lib)/libdtrace_probes.a)` to copy it.
> Install libdtrace_probes.a into the right directory on FreeBSD

- packages/builtin/stdin.pony
- packages/json/json.pony
- packages/ponytest/pony_test.pony
- packages/ponytest/test_helper.pony
- src/libponyc/pass/docgen.c
as this is required for new mkdocs 1.0.4 the ponylang theme is now based on ( the pages section is now deprecated).
[skip ci]
> Adapt to new mkdocs version in pony theme

- src/libponyc/codegen/host.cc
LLVM does not yet support getting CPU features on FreeBSD/aarch64 (or armv6/7), the situation is probably similar on other non-Linux OSes.
In the case it fails, let's just assume NEON (it's mandatory on aarch64 and very likely present on armv7).
> Allow getHostCPUFeatures to fail on ARM platforms

- src/libponyc/codegen/genexe.c
#2826 restricted -lexecinfo to debug compilers (not even to building something in debug mode).
This doesn't make much sense. I'm not sure why ordinary builds can succeed without -lexecinfo, but bitcode-runtime builds can't. Either way, if it's always included on non-glibc-Linux, it should always be included on BSD.
> Link to libexecinfo on BSD always, not just in a debug compiler

- packages/collections/map.pony
- packages/itertools/iter.pony
- src/libponyc/expr/lambda.c
- src/libponyc/type/alias.c
- src/libponyc/type/cap.c
- src/libponyc/type/matchtype.c
- src/libponyc/type/subtype.c
- test/libponyc/cap.cc
This fixes a bug in the capability subtyping implementation where capabilities were being treated as subtypes of themselves, and adds exhaustive tests for capability subtyping.
Closes #2601.
> Fix unsafe cases in capability subtyping implementation

- packages/builtin/_partial_arithmetic.pony
- packages/builtin/real.pony
- packages/builtin/signed.pony
- packages/builtin/unsigned.pony
in order to enable use of shl/shr and other methods specialized for signed and unsigned integers in a generic context (e.g. for code handling all kinds of signed ints).
This fixes #2390
> Make _SignedInteger and _UnsignedInteger public

- packages/cli/_test.pony
- packages/cli/command_spec.pony
before:
```
usage: stable [<options>] <command> [<args> ...]
...
Commands:
...         
add <type><source>    Adds a new dependency to the local `bundle.json`.
...
```
after:
```
usage: stable [<options>] <command> [<args> ...]
...
Commands:
...         
add <type> <source>    Adds a new dependency to the local `bundle.json`.
...
```
> Add whitespace between multiple args on cli help output

- README.md
There is not enough information on this in the readme. It's necessary to select the "Visual Studio C++ core features" individual component in the Visual C++ Build Tools 2017 installer to get an installation that works for pony.
As fair as I can tell it adds the "SxS" key in the "VisualStudio" key in the registry. Without this ponyc will complain that "Microsoft link.exe" cannot be located.
> Add information what to install from Visual C++ Build Tools 2017

- packages/collections/_test.pony
- packages/collections/heap.pony
This PR adds binary heaps to the standard collections package. This includes both minimum and maximum priority heaps through the `MinHeap` and `MaxHeap` classes.
closes #2948
> [RFC 60] Add binary heaps

- src/libponyc/ast/parserapi.c
- test/libponyc/sugar.cc
In case we already have an error state, only count errors arising from
this parser pass.
> Ignore parser errors when other errors have already been noticed.

- packages/builtin/string.pony
Hopefully partial arithmetic will be able to make use of carry/overflow registers to make this faster than the custom overflow check that was used previously.
> Use partial arithmetic in read_int instead of custom overflow check

- packages/collections/_test.pony
- packages/collections/map.pony
Be a bit more specific with the documentation for Map.upsert in response
to #2965. In addition, to make the expected behavior even more clear,
add a couple more tests where we use subtraction rather than addition
which should make the behavior more clear.
Closes #2965
> Clarify Map.upsert documentation

- packages/ponytest/pony_test.pony
- packages/time/_test.pony
- packages/time/posix_date.pony
- src/common/ponyassert.h
- src/libponyrt/lang/time.c
- src/libponyrt/platform/ponyassert.c
This is a pull request to address issue #2729 . It sets the `PosixDate.format()` function as a partial function, and catches the structured exception thrown by Windows, throwing a Pony error instead.
> Fix silent crash with incorrect time formats in Windows

- src/libponyc/pkg/package.c
- src/libponyc/pkg/package.h
- src/libponyc/pkg/program.c
- test/libponyc/program.cc
This is for #2936.
The use of `pony_realpath` (which calls the POSIX `realpath` underneath)
is convenient, but brings a change in behaviour: before, we have passed
just about anything into `prog->libpaths`, regardless of the directory's
existence. With `realpath`, nonexistent directories will make the call
return an error.
To remediate the impact a bit, I've added an `errorf()` statement.
However, to make this round, I think we might have to either check for
existence in both cases~, or don't do that in either one.~
*Update*: I've rearrange stuff so that both absolute and relative paths are check (by being passed through `pony_realpath`. This is a potentially a backwards-incompatible change; I'd think it might be one we can accept, though? Let's discuss this 😃
> libponyc: resolve relative paths in use "path:..." statements

- Makefile-ponyc
- src/libponyc/codegen/genexe.c
Updating minimum OSX version from 10.8 to the current minimum version of 10.12 supported by Apple.  The minimum supported OSX version is not officially advertised but can be worked out by looking at the Apple updates web page here https://support.apple.com/en-us/HT201222.  See also the discussion on this issue https://github.com/ponylang/ponyc/issues/2920.
> Fix linker library version error on MacOS when installed via Homebrew

- packages/ponytest/test_helper.pony
Following discussion from [this Slack thread](https://ponylang.slack.com/archives/CFFPDRCDT/p1549153332153100).
[ci skip]
> Document type parameters of TestHelper ReadSeq methods

- src/libponyc/pass/flatten.c
- test/libponyc/badpony.cc
- test/libponyc/util.cc
Hi there folks 👋 
After reading this tweet https://twitter.com/ponylang/status/1095373775288393729 I took the liberty to take over this PR: #2648.
> This should indeed result in a compiler error. In `pass_flatten` in `pass/flatten.c`, instead of accepting all embedded structs, we should check whether the struct is `Pointer` or `MaybePointer` and reject accordingly. Checking the name of the type is sufficient, as user packages cannot contain types with names identical to builtin types.
After some changes, the example code below should now reproduce two assertion errors with the message: "embedded fields must be classes or structs":
```pony
struct Ok
class Whoops
embed ok: Ok = Ok
embed not_ok: Pointer[None] = Pointer[None]
embed also_not_ok: MaybePointer[Ok] = MaybePointer[Ok](Ok)
actor …
```
> Reject Pointer and MaybePointer from being embedded

- wscript
Like a moron I had made the Windows build system only run debug-mode `stdlib` tests, which masked the fact that there is some kind of memory corruption going on for both 6.0.1 and 7.0.1 builds in release mode.
3.9.1 will need to be the default until that can be figured out.
> Revert to LLVM 3.9.1 as the default for Windows builds.

- src/libponyc/codegen/genopt.cc
- src/libponyc/options/options.c
- src/libponyrt/sched/start.c
- wscript
Until LLVM 7 the heap-to-stack workaround was not necessary on Windows.  However, it seems we need it for LLVM 7.
This change also correctly runs the stdlib tests in release mode for Windows CI.
Fixes #3011
> Use heap-to-stack workaround for Windows

- src/libponyc/pass/docgen.c
This was broken when the shape of the ast was change in PR #2242
Closes #3015
> Fix default arguments not being displayed correctly in generated docs

- lib/llvm/Makefile
In lib/llvm/Makefile a distclean causes an error:
wink@wink-desktop:~/prgs/ponylang/ponyc-wink0/lib/llvm (fix-distclean)
$ make distclean
Makefile:36: "lib/llvm/Makefile MAKECMDGOALS=distclean"
Makefile:109: "lib/llvm/Makefile: LLVM_PROJECT_LIST="
Makefile:117: "lib/llvm/Makefile: PROJECT_LIST="
rm -f built-* installed-*
rm -rf /home/wink/prgs/ponylang/ponyc-wink0/lib/llvm/build /home/wink/prgs/ponylang/ponyc-wink0/lib/llvm/dist
rm -rf /home/wink/prgs/ponylang/ponyc-wink0/lib/llvm/src/* /home/wink/prgs/ponylang/ponyc-wink0/lib/llvm/src/.*
rm: refusing to remove '.' or '..' directory: skipping '/home/wink/prgs/ponylang/ponyc-wink0/lib/llvm/src/.'
rm: refusing to remove '.' or '..' directory: skipping '/home/wink/prgs/ponylang/ponyc-wink0/lib/llvm/src/..'
make: *** [Makefile:199: distclean] …
> Fix distclean error

- Makefile-ponyc
This fixes #3016 by adding lines back introduced in PR #824. This code conditionally added llvm include directory only if it wasn't already included. These lines were a small part of PR #2976 which adds LLVM 7.0.1 compatibility.
> Fix fatal error: math.h no such file or directory

- src/libponyc/options/options.c
- src/libponyrt/sched/start.c
Prior to this commit, if a random user happened to be running
multiple pony applications that are CPU intensive, they would run
into unnecessary CPU contention due to CPU pinning (at least on
Linux) due to the first few cores being the ones used by all the
applications even if the system may have more cores available. This
was particularly troublesome because users may not even be aware
that the application they're running is a pony application.
This commit changes the default to not pin scheduler threads to CPU
cores. It also removes the `--ponynopin` CLI argument and replaces
it with the `--ponypin` CLI argument to leave the control for
pinning as an option for advanced users without requiring all users
of pony applications to understand pinning and how to disable it.
Resolves #3023
> Change default to disable pinning of scheduler threads to CPU cores

- .appveyor.yml
- wscript
This should be merged after #3030
> Make LLVM 7.0.1 the default for Windows builds and releases.

- .appveyor.yml
In order to simplify our CI, we will only build with LLVM 7.0.1 for Windows.
> Only build LLVM 7.0.1 for Windows CI.

- Makefile-ponyc
This is our current list of LLVM versions that have testing.
[skip ci]
> Update to latest supported LLVM versions

- .appveyor.yml
Changes to that Makefile have no impact on the Windows build and
shouldn't trigger a build.
[skip  ci]
> Add Makefile-ponyc to the Appveyor ignore list

- Makefile-ponyc
- Use [:space:] instead of \s or \S for space characters
- Add support for -I or -isystem when getting include dirs
Also add some disabled $(warning ..) statements
> Fix llvm handling for FreeBSD

- packages/builtin/string.pony
- packages/builtin_test/_test.pony
- packages/cli/command_spec.pony
- packages/options/options.pony
- src/libponyrt/lang/directory.c
and fail if the string at the given offset contains an invalid F32/F64
which includes the empty string and trailing characters.
previously they were returning `0` in their respective return-type. So it was impossible to find out if parsing failed.
fixes #3026
> make String.f32() and String.f64() partial

- packages/net/tcp_connection.pony
When `TCPConnection` is closed the remote and local addresses are _empty_ - they are no longer valid as the addresses have been reset/lost.  This PR documents this case in the associated doc strings.
> Update TCPConnection docs around local and remote addresses

- Makefile-ponyc
MacPorts installed LLVM works fine with building ponyc. However, the
makefile currently only looks for llvm-config versions using the
Homebrew naming scheme.
This commit adds support for finding llvm-config with its standard
MacPorts naming scheme:
llvm-config-mp-VERSION
[skip ci]
> Make building with MacPorts LLVM easy

- Makefile-ponyc
We don't support 3 or 4 anymore so, there's no point detecting them to
tell people that we don't support them anymore. I'm running this through
CI to verify that none of our jobs rely on these.
> Remove unsupported LLVM versions from detection

- .cirrus.yml
In all likelihood if one fails, both will fail. We have a maximum of 2 slots
for running FreeBSD jobs on Cirrus. With this change, they will be run in
sequence. First the release build tests, then the debug build tests.
This will allow for more than 1 PR to be doing FreeBSD tests at the same time.
Yes, it makes the total FreeBSD testing time longer for a given PR, however,
CircleCI and its many jobs that get run is the limiting factor for how long
it takes to fully test a PR, not Cirrus. In the end, the extra time of running
sequentially gets washed out for each individual PR.
> Run FreeBSD CI jobs in sequence

- CONTRIBUTING.md
- README.md
- RELEASE_PROCESS.md
- SUPPORT.md
We've decided to deprecate it. Everyone seems to want a Slack channel
rather than IRC so we are shutting down the IRC channel.
[skip ci]
> Remove references to the #ponylang IRC channel

- Makefile-ponyc
Does a few small things:
1- orders our search in terms of preference where we prefer newer LLVMs
to
older ones. Generic llvm-config is considered the least desirable.
2- only search in the users PATH. don't go poking into "magic"
directories
where some tool might have installed a version looking for llvm-config.
If we do that, then it makes it impossible for a user with more than 1
LLVM installation to pick the version to use based solely on their PATH.
> Clean up llvm-config options

- .travis.yml
> Update Travis release config job from LLVM 3.9.1 to 7.0.1

- .packaging/deb/control
Previously it was hardcoded to LLVM-3.9.1. Note this impacts Ubuntu as
well here because "Debian" here refers to the packaging format shared by
Ubuntu.
> Update Debian packages to use "available system LLVM"

- .circleci/config.yml
- .gitmodules
- README.md
- lib/llvm/Makefile
.circle/config.yml:
Cap CPUs to a maximum of 4 if using $(nproc) in .circle/config.yml
.gitmodule and lib/llvm/src:
Remove branch and and Changed lib/llvm/src tag llvmorg-7.0.1
README.md:
updated with instructions for changing default target
lib/llvm/Makefile:
- Don't use --depth=1 as I found it was more trouble then it's worth.
It makes switching to other commits difficult and looks like it takes
longer to transfer with circle CI.
- Change get-nothing target to not be a .PHONY target as prior to this target:
`$(LLVM_BUILD_DIR)/generated-llvm-makefile-$(LLVM_TARGET): $(GET_LLVM_SRC_TARGET)`
would always need updating.
- Use $(MAKE) instead of make directly except in buildit and installit
where its conditional as we need to use ninja or $(MAKE) as
appropriate.
> Change lib/llvm default target to be tag llvmorg-7.0.1

- .ci-dockerfiles/llvm-3.9.1/Dockerfile
- .ci-dockerfiles/llvm-3.9.1/README.md
- .circleci/config.yml
- .packaging/deb/control
This reverse previous deprecation of 3.9.1. We are going to keep 3.9.1
for as long as it is the default system LLVM for distro versions we
support. This may change if we determine that shipping packages using a
vendored LLVM works.
> Build Debian release packages using LLVM 3.9.1

- .bintray_deb.bash
- .ci-dockerfiles/deb-builder/Dockerfile
- .ci-dockerfiles/deb-builder/README.md
- .packaging/deb/rules
- .travis_commands.bash
- README.md
It's end of life is in April. We don't have any releases before then,
time to say goodbye to our trusty old Trusty.
Closes #3060
> Stop supporting Ubuntu Trusty

- .cirrus.yml
- Makefile-ponyc
Clever is bad. Eventually it bites you in the ass. Ask The Narrator, he
knows.
Prior to this commit, we were trying to be clever and helpful and would
bend over backwards to try and find the user's LLVM installation
whereever their package manager of choice might put it. This was, in the
end, a losing battle. We were constantly adding more and more
variations.
To make it worse, we tried to have a hierarchy where we would look for
LLVM 7 first then 6 etc. We did this by looking something like:
llvm-config-7
llvm-config-6
The problem with this approach was that some installations, wouldn't use
the `-7` notation. For example, if you download a release directly from
releases.llvm.org, then your llvm-config will simply be `llvm-config`.
I discovered this when, after installing LLVM 7 from …
> Stop trying to be clever when finding user's LLVM installation

- Dockerfile
Part of our general move off of LLVM 3.9.1.
> Upgrade Docker image to use LLVM 7.0.1

- .cirrus.yml
Some of our CI jobs for FreeBSD are timing out trying to install
packages using pkg.
There are two values we can change to control this:
FETCH_TIMEOUT and FETCH_RETRY. They default to 30 (for seconds) and 3
(for times). Each is set in /usr/local/etc/pkg.conf.
This commit doubles the number of retries from the default of 3 and
should hopefully cut down on our failures encountered while trying to
install dependencies.
> Increase number of times we try fetching from FreeBSD repos

- src/libponyc/platform/vcvars.c
Fixed issue with ponyc not being able to find Visual Studio Build Tools in non-standard locations, as per https://github.com/ponylang/ponyc/issues/3067
> Fixed issue with ponyc not being able to find Visual Studio Build Tools in non-standard locations.

- Makefile-ponyc
This is not as big a change as it looks, it moves all of the llvm specific code in Makefile-ponyc into one place and then uses a single `ifneq ($(MAKECMDGOALS),clean)` to **not** execute the llvm specific code if the target is clean.
> Do not require LLVM_CONFIG with clean

- .packaging/rpm/ponyc.spec
These would be broken by not being able to find llvm-config after our
Makefile cleanup
[skip ci]
> Fix COPR releases

- src/libponyc/reach/reach.c
- test/libponyc/reach.cc
Prior to this PR, the fact of whether methods of a union member were marked
as reachable when called via a union (or intersection) reference was
accidentally depending on the order in which things were marked
reachable in the compiler execution. When a type was marked
as a subtype of the union before the method call was reached,
everything was okay, but when that order was reversed
(possible through indirection of a trait), things were not okay -
the methods seen as reachable through the union weren't copied
into being reachable on the subtype of the union as they were
supposed to.
The result was the possibility of runtime segfaults when the
expected vtable entries were not present, as observed in #3096.
This PR fixes that by ensuring this copy happens. Prior to this PR,
the copy was only …
> Ensure methods reached through a union are detected as reachable.

- packages/backpressure/backpressure.pony
Fixes a few grammatical issues in the docs and some minor rewording.
> Fix minor grammar issues in backpressure docs

- .cirrus.yml
Because Homebrew doesn't have LLVM-7 available anymore and this sort of
thing is fairly regular with them.
> Install LLVM via MacPorts for CI jobs

- CONTRIBUTING.md
- README.md
- RELEASE_PROCESS.md
- SUPPORT.md
We are going to be deprecating the mailing lists there soon as they get
very little usage.
[skip ci]
> Remove references to groups.io

- .cirrus.yml
We were installing llvm 7 via MacPorts (not available via Homebrew) and
libressl and pcre2 via Homebrew. This switches us to a 100% MacPorts
installation.
Ideally, as our advised method of installation is via Homebrew (and most
people use Homebrew) we'd do everything via Homebrew. However, their
LLVM story is really poor (you can't easily select a version, sometimes,
a version isn't available at all - like LLVM 7 at this moment), so I
switched us to the far less problematic MacPorts.
> Install all MacOS CI dependencies via MacPorts

- Makefile-lib-llvm
Passing MAKEFLAGS is not necessary because "most" flags are propagated
already see:
https://www.gnu.org/software/make/manual/html_node/Options_002fRecursion.html#Options_002fRecursion .
This doesn't cause a problem when Makefile-lib-llvm is invoked directly
from the command line because MAKELEVEL=0 and  MAKEFLAGS did not have a
"w" in it. But when Makefile-lib-llvm is invoked from .package/deb/rules
it is not the root, MAKELEVEL > 0, so MAKEFLAGS has a "w". Thus, when
passing $(MAKEFLAGS) on the command line to Makefile-ponyc the "w" ends up
to be a Goal and Makefile-ponyc fails.
> Do NOT pass MAKEFLAGS to sub-makes

- src/libponyc/pass/flatten.c
- test/libponyc/flatten.cc
Sendable lambdas/object literals can only capture sendable variables. They are converted into fields on the anonymous type
and constructor parameters. The error reporting was using the type of the parameter to determine the source location of the parameter, which for inferred types was referring to the location of the expr whose type was used when when inferring the type.
This change uses the actual parameter location for error reporting.
Fixes #3123 
The new output for the example in #3123 :
```
Error:
/home/mwahl/dev/pony/scratch/main.pony:9:36: this parameter must be sendable (iso, val or tag)
p.next[None]({(x: None) => d.min})
^
```
> Fix error reporting for non-sendable lambda captures.

- src/libponyrt/lang/stdfd.c
This affected a program of mine which implemented a server waiting for input on stdin. The actor `Stdin` was spawned with `_use_events=false` and thus using a busy loop to read from stdin. 
The current logic is only to use events for `Stdin` if stdin is connected to a tty. When the pony server is forked and stdin is connected to the parent process it is currently doing a busy loop.
This busy loop, constantly polling for data to read, is suitable when stdin is a redirected file like in './pony_program < inputfile.txt', but does not make sense when listening for spare input. 1 CPU was at 100% all the time while the program did nothing and received nothing.
The proposed solution is to only **not** use asio events to wait for data to be available when stdin can be detected to be a file. This …
> Avoid busy loop when waiting for input on stdin.

- packages/json/json.pony
Hi,
The parsing examples in Pony docs contain redundant backslashes which provoke compilation errors. 
One example, taken from [here](https://stdlib.ponylang.io/json--index/#parsing-json): 
```pony
doc.parse(\"\"\"{"key":"value", "property: true, "array":[1, 2.5, false]}\"\"\")?
```
The idea for the commit is from @srenatus who helped me find the error in the first place. 
All potential errors in this commit are mine. 
Cheers,
> removed backslashes from parsing examples

- packages/builtin/std_stream.pony
- packages/files/file_stream.pony
- packages/logger/_test.pony
- src/libponyrt/lang/stdfd.c
This was missing for stdout and stderr and was mostly causing issues on windows.
Fixes #3095
> Add behaviour OutStream.flush for explicitly flushing streams. 

- src/libponyrt/gc/actormap.c
- src/libponyrt/gc/actormap.h
- src/libponyrt/gc/gc.c
Prior to this commit, the delta map would be updated even if the
cycle detector was disabled.
This commit changes things so that the delta map is only updated
if the cycle detector is enabled because the cycle detector is
the only thing that uses the delta map.`
> Only update deltamap if cycle detector is enabled

- packages/net/tcp_connection.pony
Fixes #3109 
The text for [RFC 62](https://github.com/ponylang/rfcs/blob/master/text/0062-tcpconnection-hard-close.md) mentions the alternative of having a function for immediately muting a connection so that it can be closed right after, but this seemed like the easiest thing to do.
> Expose TCPConnection.hard_close()

- Makefile-ponyc
- README.md
OpenBSD 6.5 has /usr/bin/llvm-config as part of the base install, but
base doesn't include /usr/bin/llc, so the llvm port is still required.
The port installs /usr/local/bin/llvm-config, so the Makefile can end
up using the wrong llvm-config which means it can't find llc.
Pointing LLVM_CONFIG at the port's path fixed the build for me.  I
think this gives the right behavior for anyone on OpenBSD.
> Update build for OpenBSD 6.5

- packages/builtin/array.pony
- packages/builtin/string.pony
- packages/builtin_test/_test.pony
This commit adds the following:
* Update `chop` in string and array to allow `is` to work correctly
after an `unchop`
* `unchop` to both array and string to allow the un-chopping of a
chopped string or array
* `repeat_str` and `mul` to string to allow easy repeating of
strings
> Add unchop to array and unchop, repeat_str and mul to string

- src/libponyrt/gc/cycle.c
- test/libponyc/codegen.cc
As part of PR #2800, I broke the cycle detector due to incorrect
incremental logic for querying actors for if they're blocked. I
relied on the hashmap internal array/bucket index value instead
of keeping tracking of # of actors queried for if they're blocked
during the current function call.
This commit resolves the logic issue described above by keeping
a running count of actors queried during the current function
call.
This commit also implements @plprofetes suggestion to make the
threshold for # of actors to query for if they're blocked into
a dynamic value. Specifically, the threshold is now the larger
of the `CD_MAX_CHECK_BLOCKED` constant (which is 1000) or 10%
of the total number of actors currently known to exist by the
cycle detector.
Resolves #2975.
> Fix cycle detector issue with checking for blocked actors

- src/libponyrt/sched/scheduler.c
Prior to this commit, suspended scheduler threads would not be woken
up even if there was more than one actor to be run in parallel.
This commit changes things so that if a scheduler thread has more
than one actor that has work to be done, it will wake up a suspended
scheduler thread to run the additional actor in parallel.
Resolves #3151.
> Wake up suspended scheduler threads if there is work for another one

- packages/collections/list_node.pony
As per Issue #3132.
After discussion with @SeanTAllen on Zulip[1], notes were added to flag that some functions are only intended to be called by Collections.List
[1] https://ponylang.zulipchat.com/#narrow/stream/189985-beginner-help/topic/Prepending.20.2F.20appending.20to.20ListNodes
> Update Collections docs - Add ListNode examples

- src/libponyrt/mem/heap.c
The undefined behavior sanitizer identified the left shifting of
the constant 1 by 31 to be undefined behavior due to the type
being `int` by default. This commit avoids the undefined behavior
by explicitly casting the constant 1 to uint32_t.
> Fix undefined behavior for bit shifts in heap logic

- src/libponyc/pkg/package.c
The address sanitizer identified a stack-use-after-scope error in
a function used for tests. This commit fixes this error by ensuring
the path passed to the package_add_magic_path function is properly
copied.
> Fix stack-use-after-scope in compiler test

- Makefile-ponyc
- src/libponyc/codegen/genexe.c
This PR includes: 
* Add ability to build with sanitizers and rework Makefile use processing
This commit changes the Makefile logic for when `use=` arguments
are provided to list out which `use=` options are being enabled
and also to throw an error if an unknown `use=` option is specified.
.
This commit also adds the ability to build with some common google
sanitizers for detecting potential issues with the runtime and
compiler.
* Fix race condition for last_cd_tsc initialization
The thread sanitizer identified the initialization of last_cd_tsc
to 0 as a race condition because every thread would set the value
to 0 on start. This commit changes things so the initialization is
done once as variable declaration time to avoid this race.
* Fix undefined behavior for bit shifts in heap logic …
> Add ability to build with sanitizers and rework Makefile use processing

- src/libponyrt/sched/scheduler.c
The thread sanitizer identified the initialization of last_cd_tsc
to 0 as a race condition because every thread would set the value
to 0 on start. This commit changes things so the initialization is
done once as variable declaration time to avoid this race.
> Fix race condition for last_cd_tsc initialization

- packages/net/ssl/_ssl_init.pony
- src/libponyc/codegen/genopt.cc
The address sanitizer identified a couple of minor memory leaks,
one in the compiler optimise function in genopt and another in
the ssl initialization code in the stdlib. This commit resolves
both memory leaks.
> Fix memory leaks identified by address sanitizer

- packages/json/_test.pony
- packages/json/json_doc.pony
Fixes #3097
I am very new to pony, so entirely possible I've done something obviously wrong here, or mucked up some style stuff.
Played around with a couple different implementations, including passing a flag to `_parse_decimal` to indicate whether it should check for leading zeros (*not* in the case of exp/frac), but this approach seemed clearer.
> Do not permit leading zeros in JSON numbers

- .circleci/config.yml
- .cirrus.yml
- .packaging/deb/rules
- .packaging/rpm/ponyc.spec
- Makefile-lib-llvm
- Makefile-ponyc
- README.md
- packages/crypto/digest.pony
- packages/net/ssl/_ssl_init.pony
- packages/net/ssl/ssl.pony
- packages/net/ssl/ssl_context.pony
- packages/net/ssl/x509.pony
- src/libponyc/options/options.c
This introduces an array of valid versions, and only errors out if the
passed default_ssl version is not among them.
Unfortunately, the list of valid default_ssl version in the help output
does not use that variable.
Also switches the default_ssl debug output to "info" (was "error").
Fixes #3150, I hope.
> Allow use of OpenSSL 1.1.1 when building Pony

- Makefile-ponyc
- src/libponyc/pkg/buildflagset.c
- src/libponyc/pkg/buildflagset.h
- src/libponyrt/gc/serialise.c
- test/libponyc/buildflagset.cc
- wscript
As indicated in the google test advanced documentation
(https://github.com/google/googletest/blob/master/googletest/docs/advanced.md#shuffling-the-tests),
shuffling tests can help identify bad dependencies between tests.
> Enable shuffling of tests that use the gtest framework

- .github/FUNDING.yml
For Open Collective, as described in [this article](https://help.github.com/en/articles/displaying-a-sponsor-button-in-your-repository).
> Add "Sponsor" button in GitHub

- packages/net/tcp_connection.pony
- src/libponyrt/lang/socket.c
Prior to this commit, the usage of ASIO_ONESHOT was coded into every
outgoing connection created by the runtime. This is a little odd when we
consider that incoming connection can pick their asio flags to use in
_accept.
With the change, selecting asio flags for read/write/one shot is mostly
in the control of the Pony level tcp library. Listeners still start as
non-one shot and read only. It would be reasonable to allow listeners to
select one shot or not, however, at this time, there isn't a need.
Whereas, there is a need for allowing this change. Currently, my Lori
library doesn't work because it doesn't yet support one shot. It worked
with many Pony versions until we fixed a bug where one shot was being
turned off in the runtime after the first event.
Exposing this bug in Lori lead me …
> Allow use of runtime TCP connect without ASIO one shot

- CHANGELOG.md
- packages/net/tcp_connection.pony
Port over bc6f78bcaad55156393753c540befe9f581065bc from wallaroo.
There's a nasty possible bug in TCPConnection before
applying this change.
Because `_mute` and `_unmute` are synchronous methods on
TCPConnection and because they can be called inside
`_pending_reads` via code executing in `notify.received`, its
possible to mute and unmute a source while executing
`_pending_reads`.
Prior to this change, if you were to unmute from inside a pending
reads via the above scenario, `_unmute` would synchronously call
`_pending_reads` to re-enter that function and start processing
data out of order. Further, we could end up in an infinite loop
so long as enough data existed.
> Make reading via TCPConnection re-entrant safe

- CHANGELOG.md
- packages/net/tcp_connection.pony
Port over of the following PR from wallaroo:
https://github.com/WallarooLabs/wallaroo/pull/2565
This commit adds a `_write_again` to the `TCPConnection` actor
and modifies the `_pending_writes` function to yield by calling
`_write_again` after having sent at least `_max_size` bytes.
This will allow other actors and GC to run when a large amount
of data has been queued up to be sent.
> Make TCPConnection yield on writes to not hog cpu

- CHANGELOG.md
- packages/builtin/pointer.pony
- packages/net/tcp_connection.pony
Prior to this commit, the TCPConnection `pending_writev` buffer had to
have a secondary buffer called `_pending` to ensure that the data
wouldn't get GC'd too early by the runtime.
This commit removes that hack and replaces it with a slightly different
hack based on the strategy used in `File` in PR #2775. The hacky part
is that now we have two buffers for `writev` data. One for windows
(`_pending_windows`) and one for non-windows (`_pending_posix`) to
account for the difference in order of the struct between windows
and posix. This, however, seems less bad than the previous hack of
having the secondary buffer to ensure GC safety.
resolves #2782
resolves #2779
> Cleanup TCPConnection GC-safety mechanism for writev buffers

- CHANGELOG.md
- packages/net/tcp_connection.pony
Port over of the "faster tcp" logic from wallaroo PRs:
WallarooLabs/wallaroo#2203
WallarooLabs/wallaroo#2563
That provides a significant performance improvement to the
throughputs and latencies for the wallaro performance test.
Also fix performance issue with buffer handling for non-expect case
> Change how TCP connection reads data to improve performance

- src/libponyrt/actor/actor.c
- src/libponyrt/actor/actor.h
- src/libponyrt/sched/scheduler.c
* Change actor->muted to be size_t
* Reorganize some muting/overload related checks/actions into
functions (`maybe_mute` and `batch_limit_reached`)
* Use the new functions for both normal message processing
and continuations (these checks were missing prior to this commit)
* Change `ponyint_actor_run` signature to have a boolean if it is
being run in polling mode or not and remove batch size. Batch size
is now set from a constant at the top of the function.
* Change logic related to how overload is set to ensure it is not
set when polling to avoid overload/mute getting set unnecessarily
due to polling using `batch size == 1` (previously; now, batch
size is always the default).
TODO/OPEN ITEM: `pony_poll` can currently result in a muted actor
getting run via `ponyint_actor_run` when it …
> Minor muting/overload related cleanups and bug fixes

- CHANGELOG.md
- packages/net/_test.pony
- packages/net/ssl/ssl.pony
- packages/net/ssl/ssl_connection.pony
- packages/net/tcp_connection.pony
- packages/stdlib/_test.pony
This commit adds SSL tests for expect, writev, mute, unmute, and
throttle. As part of adding these tests, some bugs were encountered
and fixed to get the tests to pass.
> Add SSL tests and fix some SSL related bugs

- lib/llvm/Makefile
- lib/llvm/llvm-base.rules
lib/llvm/Makefile: OSX does not support LLVM_USE_LINKER so do not specify
a LLVM_LINKER and instead use the default system linker.
- Default LLVM_LINKER to empty value
- Only set LLVM_USE_LINKER if LLVM_LINKER is not empty
lib/llvm/llvm-base.rules: OSX does not support the -T parameter so just
use the position parameters. The first parameter is the target
and the second parameter is the name of the symlink, so removing
the -T fixes this incompatibility.
> Fix lib/llvm to support MacOS

- packages/net/tcp_connection.pony
Fixes #3182
When _expect != 0, then we know how many bytes to expect from
the socket, so only call _read_buf.undefined() when we know
that the buffer is too small to accomodate _expect bytes.
> tcp_connection.pony: fix _read_buf_size() realloc bug

- CHANGELOG.md
- packages/net/tcp_connection.pony
- packages/net/tcp_listener.pony
Prior to this commit, the buffering in TCPConnection was overly
complicated. This was a carry over from the old style of buffer
handling. However, after Dipin Hora's commits to bring over the "faster
tcp" changes from Wallaroo, the buffer handling no longer makes sense.
Prior to this commit, a TCPConnection would be provided two variables to
control read buffering: init_size, max_size. The read buffer would start
at init_size and would grow to max_size.
Before "faster tcp", the buffer would only grow in size if we read the
entire buffer's worth of data in one recv call. After the data was read,
the buffer would be truncated and then handed off to the
TCPConnectionNotify. This was very wasteful. If you had a buffer of 128
allocated bytes and only read 4, then the 124 allocated bytes would …
> Simplify buffering in TCPConnection

- packages/net/tcp_connection.pony
- packages/net/tcp_listener.pony
Prior to this change, _read_buffer_size was used for 3 different
purposes:
- Sizing the read buffer
- Controlling how many bytes to read before yielding the CPU
- Controlling how many bytes to write before yielding the CPU
This commit provides 3 different variables, one for each of the 3
possible usages.
Closes #3186
> Break TCPConnection's _read_buffer_size into 3 different variables

- packages/net/tcp_listener.pony
_read_buffer_size never changes value so it can be a let rather than a
var.
> Change var to let in TCPListener

- CHANGELOG.md
- src/common/dtrace_probes.d
- src/libponyrt/actor/actor.c
@SeanTAllen reminded me that I was going to add these probes in a separate PR soon after the original DTrace probes were added.  I'd forgotten until now, silly me.
> Add DTrace/SystemTap probes for muted & unmuted events

- packages/net/tcp_connection.pony
We were calling it in a number of places that don't matter. Ends up
being extra function calls that serve no purpose. Also, removes a
duplicate guard around doing a resize. In that one case, we'd check the
resize condition twice in a row.
> Cleanup Unixen TCPConnection read buffer resizing

- CHANGELOG.md
- packages/net/_test.pony
- packages/net/tcp_connection.pony
Prior to this commit, `expect` could be used to create a denial of
service on a Pony application. If you used expect to handle a framed
protocol, then, you'd by default accept any sized `except` value which
could result in huge amounts of memory being allocated. Memory that
could vastly outstrip the max buffer size set for controlling memory
usage.
After this commit, `expect` is partial and will result in an error if
attempting to set an expect value that is greater than our max read
buffer size.
I intended to commit this prior to another PR, but forgot and thought
that I had. As it is, this PR works in conjunction with #3185 to prevent
expect from being passed that is greater than the max buffer size
thereby deadlocking the logic post #3185.
> Close Denial of Service issue with TCPConnection.expect

- CHANGELOG.md
- packages/builtin/asio_event.pony
I need this functionality in my Lori library to support both 1-shot and
edge triggered ASIO functionality in a single actor. I could put a
method to examine in my library but including for testing on AsioEvent
seems like the best course of action.
> Add method to AsioEvent to see if an event is a oneshot

- CHANGELOG.md
- src/libponyc/expr/reference.c
- test/libponyc/badpony.cc
This PR fixes return type checking to allow aliasing for non-ephemeral return types.
I discovered this type system issue after a discussion with @rkallos in which we discussed how to fix `Map.insert` (and others) to not have an unreachable error case.
Looking into it further, I discovered that the type system had a simple bug that wasn't obvious due to the inconsistency in how Pony handles return type checking (the fact that using the ephemeral modifier is required to describe a unique return type, whereas on all other type specifications, the ephemeral modifier is useless).
This PR doesn't address that inconsistency, because it would be a major breaking change for the language, but this does fix the small bug that went unnoticed because of it.
The bug can be reproduced with the following …
> Fix return type checking to allow aliasing for non-ephemeral return types.

- README.md
In current version of SpaceVim, ~/.SpaceVim.d/init.toml is default configuration file.
to load lang#pony layer:
```
[[layers]]
name = 'lang#pony'
```
> Update readme for editor support

- src/libponyc/ast/ast.c
- src/libponyc/ast/ast.h
- src/libponyc/ast/symtab.c
- src/libponyc/ast/symtab.h
- src/libponyc/pass/refer.c
- src/libponyc/pass/verify.c
- src/libponyc/verify/control.c
- test/libponyc/refer.cc
- test/libponyc/util.cc
- test/libponyc/verify.cc
Prior to this commit, a `consume`d variable could not be
reassigned in a `try` block. This commit changes things to allow
a `consume`d variable to be reassigned within a `try` block only
if it is reassigned in the same expression where it is consumed
(i.e. `z = do_stuff(consume z)`) and only if that expression does
not include any partial calls.
Also, add tests for various `consume` related scenarios.
> Allow reassignment of `consume`d variable in try (sometimes)

- Makefile-lib-llvm
I was building ponyc with a vendored LLVM in a WSL2 environment and
had it fail because `sh` couldn't make heads or tails of some of the
characters in my PATH entry. In particular, because of spaces in
some of the path names.
> Don't error out when building vendored LLVM when PATH is "odd"

- src/libponyc/options/options.c
Everything was in place for this to work except that it would reject the
openssl_1.1.x flag as it wasn't in the allowed list.
> Fix "broken" SSL 1.1.x support

- .circleci/config.yml
It was possible for it not to get run if arm builds failed
and people might merge something broken given that arm
builds fail sometimes.
A more general clean up of circleci ordering is needed but this
is good for now. That more general clean up will be coming
when the release process is changed.
> Run docker image validation earlier

- src/libponyc/options/options.c
As part of f26953fd8b09194a34fec859be093f72471d4003, I removed all
of the defaults rather than only the printing of the removed openssl
version.
This commit readds it.
> Readd printing of defaults with `--version`

- CHANGELOG.md
- Makefile-ponyc
Fix a GNU Make macro bug that prevents `make use=dtrace` to work
correctly on FreeBSD and Linux+SystemTap platforms.  I don't
understand exactly why, but using `$(shell which dtrace 2> /dev/null)`
inside of the `USE_CHECK` macro definition always results in the
empty string.
When moved outside of the macro definition, plus using `+=` to
update the value of `$(DTRACE)`, works correctly on both
FreeBSD's GNU Make 4.2.1 and Ubuntu Xenial/16.04's GNU Make 4.1.
> Fix `which dtrace` path check

- .appveyor.yml
Temporary til we figure out why they are failing constantly.
Closes #3237
> Turn off Windows debug builds

- packages/cli/command_parser.pony
- packages/collections/_test.pony
- packages/collections/map.pony
- packages/ini/ini_map.pony
Thanks to https://github.com/ponylang/ponyc/pull/3201, it's now possible to make Map.insert & friends total functions. Not only that, but Map.insert should be slightly faster in the case where the insertion causes the underlying array to grow, as it is no longer necessary to do the lookup for the final value.
I suspect this would constitute a pretty large breaking change, as I'm sure code like `try map.insert(k, v)? end` is pretty common, and after this change it would be a compile-time error.
This PR is incomplete. There are some more partial-not-partial functions that can be fixed, like Map.insert_if_absent.
> Make Map insertion functions total

- .ci-dockerfiles/x86-64-unknown-linux-gnu-nightly/Dockerfile
- .ci-dockerfiles/x86-64-unknown-linux-gnu-nightly/README.md
- .ci-scripts/x86-64-unknown-linux-gnu-nightly.bash
- .circleci/config.yml
- This has the API Key hardcoded and public.
It will be invalidated before this is merged and I will set up using
an encrypted value.
- It's not putting nightlies into the "real" remote repository for them.
Currently, its using `main-pony/ponyc-nightlies` which is a test area.
This will also need to be updated once I know it's working.
> Dry run of running a small segment of "nightlies" on CircleCI

- .ci-dockerfiles/alpine-llvm-5/Dockerfile
- .ci-dockerfiles/alpine/Dockerfile
- .ci-dockerfiles/cross-llvm-7.0.1-aarch64/Dockerfile
- .ci-dockerfiles/cross-llvm-7.0.1-arm/Dockerfile
- .ci-dockerfiles/cross-llvm-7.0.1-armhf/Dockerfile
- .ci-dockerfiles/cross-llvm-7.0.1-i686/Dockerfile
- .ci-dockerfiles/ubuntu-16.04-base/Dockerfile
- .ci-dockerfiles/ubuntu-18.04-base/Dockerfile
- .ci-dockerfiles/ubuntu/Dockerfile
- .dockerhub/alpine/Dockerfile
- Dockerfile
We no longer have a dependency on SSL for building or testing Ponyc.
Closes #3240
> Remove SSL from Docker images

- .ci-dockerfiles/alpine-llvm-5/Dockerfile
- .ci-dockerfiles/alpine/Dockerfile
- .ci-dockerfiles/centos7-llvm-3.9.1/Dockerfile
- .ci-dockerfiles/ubuntu-16.04-base/Dockerfile
- .ci-dockerfiles/ubuntu-18.04-base/Dockerfile
- .ci-dockerfiles/ubuntu/Dockerfile
- .ci-dockerfiles/x86-64-unknown-linux-gnu-nightly/Dockerfile
- .dockerhub/alpine/Dockerfile
- Dockerfile
I'm working on adding support for sending notifications from CircleCI
to the Pony Zulip. bash and curl are required for it work.
This commit updates our Dockerfiles to assure that bash and curl are
installed.
> Prepare Docker images for sending CircleCI notifications to Zulip

- .ci-scripts/x86-64-unknown-linux-gnu-nightly.bash
- Makefile-ponyc
Nightly builds aren't particularly meaningful with a version like
0.29.0-a334234vv. The version we are telling people is in the form,
nightly-YYYYMMDD. This commit changes our setup to allow the overriding
of the version/tag that is used to identify this build and package
version. It also updates the nightly builds to take advantage of that.
We should as part of the new release process we are moving towards,
revisit the naming we use for all package builds as well as the
displayed version information. This is, however, an excellent start and
should allow us to fairly easily identify nightly releases if folks
report errors and then go get that particular version for testing.
I'm open to the idea that the displayed version should include a SHA like:
nightly-YYYYMMDD-SHA
> Allow overriding of ponyc version

- CHANGELOG.md
- src/libponyrt/gc/cycle.c
Prior to this fix, the Cycle Detector could end up in a situation
where it would have an inconsistent viewref which would result
in a segfault with the cycle detector trying to send a message
to an actor that was already destroyed.
This commit fixes the bug by making the cycle detector apply
deltamap updates from actor block messages immediately.
resolves #2977
> Fix segfault due to Cycle Detector viewref inconsistency

- CHANGELOG.md
- src/libponyc/codegen/genexe.c
- src/libponyc/options/options.c
- src/libponyc/pass/pass.h
* Ensure that `-latomic` comes after `-static` to fix static linking
* Allow overriding `-fuse-ld` command for linking
> Fix static linking issue encountered during stable build

- .ci-dockerfiles/alpine-llvm-7/Dockerfile
- .ci-dockerfiles/alpine-llvm-7/README.md
- .circleci/config.yml
- Makefile-ponyc
* Use `llvm-config`'s `--system-libs` option
* Add option to statically link ponyc
* Add an alpine static link build
Note: This supersedes https://github.com/ponylang/ponyc/pull/3260 as it changes the hardcoded system libs for llvm to be dynamic based on whatever `llvm-config` outputs. This effectively removes the `ncurses` dependency on linux while leaving it for mac. I haven't updated the docs/dockerfiles in this PR though.
Note the second: the alpine static build for circleci is a temporary hack that needs to be fixed.
> Add ability to static build ponyc

- CHANGELOG.md
- src/libponyrt/lang/socket.c
- src/libponyrt/platform/ponyassert.c
Prior to this commit building with a toolchain based on `musl`
in a `glibc` distribution (like ubuntu) would result in an error.
For these environments `execinfo.h` is not available because
`musl` doesn't include it and these distributions don't package
`libexecinfo` resulting in an error.
This commit changes things to allow the builds to succeed by
ensuring that the `socket.c` includes are only used if the
`__GLIBC__` macro is defined. It also updates `ponyassert.c` to
work around the lack of `execinfo.h` by `ifdef`'ing out the
call to `backtrace` resulting in a binary that compiles but is
not able to print a stacktrace on an assertion.
> Make builds with `musl` on `glibc` systems possible

- packages/builtin/string.pony
- packages/builtin_test/_test.pony
This commit improves the documentation of the two methods to better
differentiate them from one another, and creates more `String.split` tests.
Closes #3266.
> Clarify `String` methods `split` and `split_by`

- RELEASE_PROCESS.md
- release.bash
This shouldn't be merged until @Theodus reviews to make sure I got the changes in flags for changelog-tool correct and until changelog-tool 0.3.0 is released.
> Update changelog-tool usage to match version 0.3.0 changes

- src/libponyrt/platform/threads.c
NetBSD doesn't provide this header.
> restrict pthread_np.h to openbsd,freebsd,dragonflybsd.

- CHANGELOG.md
- packages/net/_test.pony
- packages/net/proxy.pony
- packages/net/tcp_connection.pony
- packages/net/tcp_connection_notify.pony
Added proxy_via to the tcp_connection_notify with a default implementation; used it in the tcp_connection constructors.
Allows for proxies to be implemented by decorating a TCPConnectionNotify with another.
> Add the ability to change the hostname&service from a TCPConnectionNotify before connecting

- CHANGELOG.md
- packages/collections/_test.pony
- packages/collections/map.pony
`Map.sub` accepts a `value` argument that it never uses.
> Remove unnecessary argument to Map.sub

- src/libponyrt/actor/actor.c
- src/libponyrt/sched/scheduler.c
This commit changes some of the muting/unmuting logic to improve
performance. It combines some atomic load/store pairs with single
add/sub atomic operations. It also removes an unecessary stack when
unmuting actors that may have been muted due to sending messages
to an overload or muted actor.
-------------------------------------------------------------------------
The following are some microbenchmarks to measure impact of this change. Please keep in mind that they were run on a linux virtualbox vm on windows 10 system without cpu isolation and thermal cpu scaling/throttling was enabled.
Output of running master for `message-ubench`:
```
./message-ubench.master --report-count 25
```
```
time,run-ns,rate
1566723387.255238972,999563862,14461124
1566723388.255102083,999067631,16710694 …
```
> Improve performance of muting/unmuting logic

- src/libponyrt/sched/scheduler.c
This commit switches from test-and-set to test-and-test-and-set
approach for the scheduler_count_changing atomic bool when
relying on signals for dynamic scheduler scaling because
test-and-test-and-set reduces cache line invalidations and scales
better. See the following link for more details:
https://geidav.wordpress.com/2016/03/23/test-and-set-spinlocks/
> Use test-and-test-and-set for scheduler scaling logic

- packages/builtin/array.pony
Fix the empty Array example to include type information.
I also swapped periods for semicolons to make it clearer that the text preceding the code examples is directly related to the examples. It didn't seem like there is a consistent style one way or another.
> Update Array example in documentation

- .cirrus.yml
The high sierra images are no longer available. We were auto upgraded to
Mojave. The version of MacPorts we used doesn't install on Mojave.
This PR should get everything working again.
> Update CirrusCI MacOS setup

- .circleci/config.yml
As part of this commit, we need to turn them off being built on DockerHub.
Why don't we want to build on DockerHub?
It's very slow to do there. When releases are done, it takes several hours
to do the various images we need built. Additionally, we doubt that DockerHub
has the ability to build Docker images that use the vendored LLVM that we
are moving to as it takes a long time to complete.
This commit ONLY switches to building "latest" and "alpine" tags on CircleCI.
Release related tags are still done on DockerHub. Before that change can happen,
other changes will need to be made.
> Build "latest" Docker images on CircleCI

- .circleci/config.yml
Almost all our CircleCI jobs are PR acceptance tests that don't need
to be run when we merge to master. It should have already been handled
when we tested the PR.
> Don't run PR acceptance tests on master or release

- .cirrus.yml
Those are special branches that we consider "not PR related" and
all the current CirrusCI tasks are for PRs only.
> Only run CirrusCI against branches other than master and release

- .ci-scripts/build-alpine-docker-images-on-release.bash
- .ci-scripts/build-docker-images-on-release.bash
- .circleci/config.yml
- RELEASE_PROCESS.md
Prior to this commit, we built our Docker images for each release
using DockerHub's infrastructure. This was slow and would take many
ours because:
- Builds would run sequentially
- The build server is slow and underpowered
With this commit, we will now be building on CircleCI. This allows us
a quicker process to get images built. It will also allow us to
switch to using vendored LLVM in for our Docker images.
Using vendored LLVM wasn't possible when images were built on DockerHub's
infrastructure as the build times would have been excessive (and might
have ended up timing out).
> Build Docker release images on CircleCI

- CHANGELOG.md
- src/libponyrt/sched/start.c
Follow up to #3303 
Also, I think I should add a commit to handle the formatting around `{` on the same line as their matching… `if` statements? All statements? What is the formatting preference? Should I bring consistency to the entire file? See https://github.com/ponylang/ponyc/pull/3303#discussion_r329204642
Finally, I think c429d54 probably warrants a CHANGELOG entry, wdyt?
```
$ ./helloworld --ponythreads=0
--ponythreads can't be less than 1
$ echo $?
255
```
> Avoid silently overflowing (signed) ints to unsigned int values in args

- .ci-scripts/x86-64-unknown-nightly-musl-nightly.bash
- .circleci/config.yml
At this moment, the script to run the build and upload is an almost
complete copy of the GNU version. I'm leaving the duplication for now
as we are going to have additional variations coming soon and I don't
want to "DRY" up the scripts too soon.
> Add building a musl libc version of Pony nightly

- CHANGELOG.md
- src/libponyrt/options/options.h
- src/libponyrt/sched/start.c
I think fixes #3318 
But this also means specifying `--ponythreads` would be silently ignored: 
```
./helloworld --ponythreads=1              
Hello, world.
$ ./helloworld --ponythreads=0   
Hello, world.
$ ./helloworld --ponymaxthreads=1
Hello, world.
$ ./helloworld --ponymaxthreads=0
--ponymaxthreads can't be less than 1
```
Should we alias the two? Forbid `--ponythreads` as an option? Maybe make sure the `--pony*` "namespace" only contains "known" options? … thinking out loud
> Renamed --ponythreads to ponymaxthreads, fixes #3318

- src/libponyrt/sched/start.c
Follow up to #3317:
Writing [these release notes](https://github.com/ponylang/ponyc/issues/3314#issuecomment-539591621), I realized I had missed the `--ponygcfactor` 🤦‍♂ 
So here's the behavior: 
```
$ ./helloworld --ponygcfactor=0.3 
--ponygcfactor can't be less than 1.0
$ ./helloworld --ponygcfactor=-1.3
--ponygcfactor can't be less than 1.0
$ ./helloworld --ponygcfactor=1.3 
Hello, world.
$ ./helloworld --ponygcfactor=1.0
Hello, world.
```
Given this [guard clause](https://github.com/ponylang/ponyc/blob/master/src/libponyrt/mem/heap.c#L301-L302) here, I think `1.0` makes sense…
> Added gcfactor min check

- src/libponyc/codegen/codegen.c
- src/libponyc/options/options.c
- src/libponyc/pass/pass.h
Implementations of RFC 64.
Now developers can use `--llvm-args` with a comma-separated string to pass LLVM-specific arguments to debug build of ponyc.
> LLVM command line options integrations (issue #3327)

- CHANGELOG.md
- packages/builtin/runtime_options.pony
- src/libponyc/codegen/genexe.c
- src/libponyc/pass/sugar.c
- src/libponyc/type/subtype.c
- src/libponyc/type/subtype.h
- src/libponyc/verify/fun.c
- src/libponyrt/options/options.h
- src/libponyrt/sched/cpu.c
- src/libponyrt/sched/scheduler.c
- src/libponyrt/sched/start.c
- test/libponyc/util.cc
- test/libponyc/util.h
- test/libponyrt/util.cc
- test/libponyrt/util.h
Prior to this commit, the only way to override the default pony
runtime options was via the command line.
This commit allows for programmatic override of the default pony
runtime options via a specific bare function created on the Main
actor:
`fun @runtime_override_defaults(rto: RuntimeOptions) => None`
In order to override the values, a programmer would replace the
`None` with logic to directly set the various options on the `rto`
variable. This bare function is limited in what is allowed and
is only allowed to call functions on `primitive`s to ensure no
memory allocation occurs as it is called before the runtime is
fully initialized.
This commit also renames the internal variable in `options_t` from
`nopin` to `pin` to better align with how it is set from the
command line so it is …
> Allow programmatic override of the default runtime options

- CHANGELOG.md
- src/libponyc/pass/refer.c
- src/libponyc/pass/verify.c
- src/libponyc/pkg/package.c
Starting with GCC 8, they added a new warning `stringops-truncation`. It
is well intentioned but, seems prone to a lot of false positives.
It found several false positives in the Pony codebase and because we treat
all warnings as errors, you can't build ponyc with GCC 8+.
This commit switches from using strncpy to memcpy. They are in the end, the
same operation except a difference in return type. However, with the new
gcc option, memcpy will not complain about not copying the null terminator.
Fixes #3313
> Fix building with GCC 8+

- Makefile-ponyc
It makes for a more portable Linux binary. This is safe to do if
we statically link LLVM, otherwise, it is very bad.
> Statically link libgcc and libstdc++ when we can

- .circleci/config.yml
We are moving away from supporting system installed LLVM on Linux x86.
This takes us one step closer.
> Only run Linux x86 CI with "vendored LLVM"

- .circleci/config.yml
- .cirrus.yml
Prior to this commit we were running the following for CI:
release build of pony that:
- built examples
- ran stdlib tests with -d
- ran stdlib tests
- ran the core tests
- validated the grammar
and for the same commit we were doing:
debug build of pony that:
- built examples
- ran stdlib tests with -d
- ran stdlib tests
- ran the core tests
- validated grammar
We decided we weren't getting much out of doing both release and debug build tests of ponyc.
This commit drops the debug ponyc builds. Note, we are still testing the standard library
with the pony specific `--debug` mode. It's only the runtime that we aren't doing debug for.
> Stop using debug ponyc builds for CI

- .ci-dockerfiles/stdlib-builder/Dockerfile
- .ci-dockerfiles/stdlib-builder/build-and-push.bash
- .ci-scripts/build-and-push-stdlib-documentation.bash
- .github/workflows/publish-stdlib-documentation.yml
- Makefile-ponyc
Previously, we built the standard library documentation on release
as part of our TravisCI setup. We've since deprecated TravisCI usage.
This commit adds
- building documentation via GitHub Action on each release
- Dockerfile for image that is used for doing the building
- GitHub Action to update the stdlib-builder image daily
This commit remove
- `online-docs` Makefile rule
Although this is set to run on each release, it could be run locally
if we needed to update the documentation. I ran used the image and
script that does the building to update our documentation after the
0.33.0 release failed to build documentation due to an error on the
TravisCI side.
Closes #3362
> Build documentation on release

- .cirrus.yml
The custom clone script for building with Vendored LLVM was hard
coded to using the ponylang/ponyc repo. That fails when the PR
is coming from a fork.
> Allow CirrusCI to run for PRs from forked repos

- .github/workflows/changelog-bot.yml
Now version 0.0.2 instead of 0.0.1. Will now correctly work with
forked repositories.
> Turn changelog-bot back on

- Makefile-ponyc
So Ubuntu and some other Linux distros use the "alternatives" system
to switch common system tools like cc and c++. When a distro uses this
approach, then cc and c++ are symlinks to a program that returns a
value for what compilers to actually use.
So if I want to use clang and clang++ then I can use alternatives to set
cc and c++ accordingly.
Unfortunately, GNU make sets default values for the CC and CXX macros that
do not play well with the alternatives approach.  It sets CC to cc which
plays well with alternatives, but CXX is set to g++ which doesn't.
So on ubuntu, you will get a compilation error if you use alternatives
and try to build ponyc with clang as it will end up using clang and g++.
This commit addresses the situation by checking to see if CC and CXX are
returning conflicting …
> Fix building ponyc with clang on Ubuntu

- .dockerfiles/x86-64-unknown-linux-gnu/Dockerfile
- .dockerfiles/x86-64-unknown-linux-gnu/build-and-push.bash
- .dockerfiles/x86-64-unknown-linux-musl/Dockerfile
- .dockerfiles/x86-64-unknown-linux-musl/build-and-push.bash
- .github/workflows/latest-docker-images.yml
- .github/workflows/pr.yml
As part of our move to using a vendored LLVM that we build for our
ponyc releases, we decided that our Docker images should also use
the vendored LLVM.
However, building the vendored LLVM requires a lot of resources to do
in a timely fashion. None of the available Docker builder environments
are particularly effective at building.
We came together and decided that really, once a day was enough to
update the "latest" images and that using ponyup to install the most
recently nightly builds of ponyc, stable, et al seemed like a very good
approach.
This commit adds a new directory for storing our Dockerfiles that are
used for building these end user prebuilt ponyc images. I am leaving
the old files in place as they are used by both the release and latest
builds and this commit only updates …
> Build latest docker images once a day

- .dockerfiles/x86-64-unknown-linux-gnu/Dockerfile
- .dockerfiles/x86-64-unknown-linux-musl/Dockerfile
As part of adding the ability to install release channel applications
using ponyup, the cli changed.
This commit updates for those changes.
See https://github.com/ponylang/ponyup/pull/22 for more information.
[skip ci]
> Update for recent ponyup breaking changes

- README.md
`llvm@3.9` can't be found on Brew anymore and it is obsoleted in MacPorts.
> Update README.md to recommend LLVM 7

- .github/workflows/changelog-bot.yml
Given our workflow, we never use it for anything other than PRs
that merge into master. Given that, running on pushes to other
branches is wasteful.
This commit turns off for anything that isn't master.
> Only run the CHANGELOG bot against master

- .dockerfiles/x86-64-unknown-linux-gnu/Dockerfile
Was missing dependencies needed to build and link programs in the image.
Closes #3388
> Allow gnu latest images to be used with the Pony playground

- .dockerfiles/x86-64-unknown-linux-musl/Dockerfile
You can't compile programs in the existing images due to missing
dependencies.
Closes #3389
> Make musl latest images usable on Pony playground

- src/libponyc/pass/refer.c
- test/libponyc/badpony.cc
PR #3304 introduced a bug that caused segfaults with nested tuple
access.
This commit resolves the issue and adds a test to prevent another
regression.
resolves #3354.
> Fix nested tuple access regression introduced by #3304

- .ci-dockerfiles/cross-llvm-7.0.1-aarch64/README.md
- .ci-dockerfiles/cross-llvm-7.0.1-arm/README.md
- .ci-dockerfiles/llvm-7.0.1/README.md
- .ci-dockerfiles/stdlib-builder/build-and-push.bash
- .ci-dockerfiles/ubuntu-16.04-base/README.md
- .ci-dockerfiles/x86-64-unknown-linux-gnu-builder/build-and-push.bash
- .ci-dockerfiles/x86-64-unknown-linux-musl-builder/build-and-push.bash
- .ci-scripts/build-alpine-docker-images-on-release.bash
- .ci-scripts/build-docker-images-on-release.bash
- .dockerfiles/x86-64-unknown-linux-gnu/build-and-push.bash
- .dockerfiles/x86-64-unknown-linux-musl/build-and-push.bash
- .github/workflows/pr.yml
Add `--pull` to all our `docker build` commands to make sure that
we aren't using a cached local version of base images if a more
recent version is available.
> Always use most up to date base image

- .cirrus.yml
We were being auto-upgraded. This commit makes the change known
and explicit.
> Update the macOS image on Cirrus

- .github/workflows/handle-external-events.yml
Prior to this commit, we were building our daily "latest" Docker images
at a fixed time of day. This should usually be fine as that days nightly
build should be done and uploaded by then.
However, there is no guarantee that this will be the case. It's possible
the daily build could fail or it could be delayed.
This commit changes how latest docker image builds are triggered. Instead
of daily at the same time, we trigger in response to a webhook from the
Cloudsmith "nightlies" repo on package synchronisation.
> Trigger latest docker image builds via Cloudsmith upload

- .ci-scripts/build-alpine-docker-images-on-release.bash
- .ci-scripts/build-docker-images-on-release.bash
- .circleci/config.yml
- .github/workflows/handle-external-events.yml
We don't need it to be trigger based as we aren't building via Ponyup
yet, but we plan to be before the next release. If we aren't using
Ponyup to populate the images before the next release, this is still
fine and doesn't do any harm.
> Move release image building to being trigger based

- .ci-scripts/trigger-nightly-builds.bash
- .github/workflows/start-a-release.yml
- .github/workflows/trigger-nightly.yml
Prior to this commit, if the curl request was sent to CirrusCI but
it didn't succeed, the build would show as green.
As of this commit, we capture the output from CirrusCI and verify
that it contains a build id. If it doesn't, we failed. On failure:
- print error
- print captured curl output
- fail the build
> Report errors if nightly build doesn't trigger

- .dockerfiles/latest/x86-64-unknown-linux-gnu/Dockerfile
- .dockerfiles/latest/x86-64-unknown-linux-musl/Dockerfile
- .dockerfiles/release/x86-64-unknown-linux-gnu/Dockerfile
- .dockerfiles/release/x86-64-unknown-linux-musl/Dockerfile
This should resolve https://github.com/ponylang/ponyc/issues/3411.
I was not sure if the proper fix is to update the readme to use a different docker command, or to update the Dockerfiles to use `/src/main` as workdir.
This PR sets the workdir for the Dockerfile to `/src/main`
> set workdir in Dockerfile

- .ci-scripts/x86-64-unknown-linux-gnu-release.bash
- .ci-scripts/x86-64-unknown-linux-musl-release.bash
- .circleci/config.yml
- .cirrus.yml
This is almost the last job to move off of CircleCI for ponyc.
We still have library jobs, but as part of the consolidation
of new release and testing process, we are working our way down
to only using CirrusCI for the heavy lifting jobs and GitHub actions
for everything else.
This is another step in that direction.
> Move release building from CircleCI to CirrusCI

- .cirrus.yml
The previous command would run for tagged commits as the tag rather
than branch name would end up in the CIRRUS_BRANCH environment variable.
Fedor from Cirrus pointed me to this change as the correct solution.
> Only run PR tasks on PR

- src/libponyc/pass/verify.c
This fixes the `cmake` branch on Windows.
> Fix the verify pass storing pointers to local variables in a hash map

- benchmark/libponyc/common/common.cc
- benchmark/libponyrt/common/common.cc
- benchmark/libponyrt/ds/hash.cc
- benchmark/libponyrt/mem/heap.cc
- benchmark/libponyrt/mem/pool.cc
- src/common/platform.h
- src/libponyc/codegen/genjit.cc
- src/libponyrt/ds/list.c
- test/libponyc/codegen.cc
- test/libponyrt/ds/list.cc
Enabling `-Wsign-conversion`, makes the compiler report many sign conversions in `libponyrt` (not a suprise). Most of them are inoffensive, but some conversions of negative integer to unsigned integers could potentially lead to infinite loops or attempts to allocate
an `(unsigned)-1` amount of memory.
Enabling `-Wsign-conversion` can prevent these things from becoming bigger issues and hint at possible refactorings of the code (e.g. use a signed integer as the return type when a function can return negative integers).
> Small steps towards enabling -Wsign-conversion for some submodules

- .dockerfiles/latest/x86-64-unknown-linux-gnu/Dockerfile
- .dockerfiles/latest/x86-64-unknown-linux-musl/Dockerfile
- .dockerfiles/release/x86-64-unknown-linux-gnu/Dockerfile
- .dockerfiles/release/x86-64-unknown-linux-musl/Dockerfile
`stable` and `corral` are effectively useless without git in the
environment. Seems like a reasonable edition.
Previously, our images included git. I removed when updated the
images because I thought "bah, we don't really need". I didn't
think through the "every image based off this will need to add
git if it wants to use stable" angle.
> Add git to Dockerfiles

- .appveyor.yml
- Makefile-ponyc
- src/libponyc/codegen/codegen.c
- src/libponyc/codegen/gendebug.cc
- src/libponyc/codegen/gendebug.h
- src/libponyc/codegen/genjit.cc
- src/libponyc/codegen/genopt.cc
- src/libponyc/codegen/genprim.c
- src/libponyc/codegen/gentype.c
- test/libponyc/codegen.cc
- wscript
This PR is for compiling with LLVM 9.0.0.
> LLVM 9.0.x support

- BUILD.md
- INSTALL.md
Closes #3414 by adding Windows PATH instructions to both prebuilt binary download (INSTALL.md) and building from source (BUILD.md) installation.
> Add Windows PATH instructions

- packages/builtin/array.pony
Update docs of builtin.Array.insert to reflect its behavior when inserting beyond the last index. In this case insert will append the value and behave like a badly performing.
Fixes #3418 
[skip ci]
> Update docs of builtin.Array.insert [skip ci] 

- src/libponyc/options/options.c
- src/libponyrt/options/options.c
- src/libponyrt/options/options.h
- src/libponyrt/sched/start.c
Stop printing the "BUG: unprocessed option id -2" message when user
passes wrong arguments.
Before this change:
$ ./build/release/ponyc -V
./build/release/ponyc: '-V' option requires an argument!
BUG: unprocessed option id -2
$ echo $?
255
After this change:
$ ./build/release/ponyc -V
./build/release/ponyc: '-V' option requires an argument!
$ echo $?
255
> Handle command line option errors more gracefully

- STYLE_GUIDE.md
Answers #3441 by modifying the 4th example to reflect the end of the rule:
> Multiple function calls should generally be aligned so that each call is placed on a separate line **indented below the initial object**.
> Updating 4th example of the STYLE_GUIDE's multi-function-call section

- src/libponyc/expr/call.c
This addresses issue #2986 by:
- giving a local equivalent to the `this->x` viewpoint adaptation (which is what is printed on the last line of the "Infos" section)
- giving a hint when the `this->x` viewpoint adaptation turns into a `box/val/iso` in the current context while also trying to access a `ref` method
As an example, this is what the error from the code included in the original issue looks like on 0.33.1:
```
Error:
/_/main.pony:19:8: receiver type is not a subtype of target type
fox()
^
Info:
/_/main.pony:19:5: receiver type: this->Fox ref
fox()
^
/_/main.pony:28:3: target type: Fox ref
fun ref apply() =>
^
/_/main.pony:10:12: Fox box is not a subtype of Fox ref: box is not a subcap of ref
let fox: Fox ref
```
And this is what the error looks like with this patch:
```
Error: …
```
> Better error message for check_receiver_cap

- packages/files/_test.pony
- packages/files/file_path.pony
When working on Windows builds for ponyup, I found that it wouldn't
link due to an error with the FFI call in `symlink`. This commit
adds a test to verify that `symlink` works.
This PR contains a test that I verified fails on Windows and then adds a change to FilePath.symlink that then allows the failing test to pass.
> Fix linker error when creating symlinks on Windows

- STYLE_GUIDE.md
- pony.g
- src/libponyc/ast/parser.c
- test/libponyc/sugar.cc
This pull request fixes issue #2988, where `not if`, `not for` and `not while` resulted in a parse error, even though these should technically be valid.
Tests have been included to prevent this issue from happening again in the future.
> Fix "not match" and "not if" causing a syntax error

- packages/collections/sort.pony
This should fix the misformatting, but I did change the indentation to using the greater than symbol and adjusted indentation throughout the example so unsure if it breaks something else now instead.
> Fix misformatting of Sort example program

- src/libponyc/pass/refer.c
- test/libponyc/refer.cc
This addresses #2828
Declaring a variable at the end of a function which expects a return value or having generally a variable declaration where the compiler expects to use the return value caused in most cases an error stating that the variable is undefined but its value is used:
```
actor Main
new create(env:Env) =>
confusing_error_msg()
fun confusing_error_msg(): String =>
var s = "A string."
```
This bit of code triggers the following error on 0.33.1:
```
Error:
main.pony:26:9: the left side is undefined but its value is used
var s = "A string."
^
Error:
main.pony:26:11: left side must be something that can be assigned to
var s = "A string."
^
```
The presence of the second error was also considered to be erroneous.
This patch discriminates in the `is_lvalue` function from …
> Improved error for undefined but used left side of declarations

- INSTALL.md
There's a single command for glibc and musl distros. The language
in the install still referenced glibc spefically. That's left over
from when it had glibc and musl specific instructions.
> Clean up Linux ponyup installation instructions

- .ci-scripts/x86-64-apple-darwin-nightly.bash
- .ci-scripts/x86-64-apple-darwin-release.bash
- .ci-scripts/x86-64-unknown-linux-gnu-nightly.bash
- .ci-scripts/x86-64-unknown-linux-gnu-release.bash
- .ci-scripts/x86-64-unknown-linux-musl-nightly.bash
- .ci-scripts/x86-64-unknown-linux-musl-release.bash
Was changed during cmake switch over but DESTDIR change from using prefix
and symlink=no had additional unintended ramifications on the creation of
the `version` directory that was expected.
This commit reverts to the prior usage that was specifically crafted for
Cloudsmith packaging.
> Fix broken cloudsmith packaging

- Makefile
The new Makefile was omitting the the `libponyc.a` and `libponyrt.a` files in the install target.
> Install libponyc and libponyrt

- .cirrus.yml
Match up with what we do for nightlies and releases. This was
part of the old cirrus setup but got lost during the cmake
transition.
> Build PRs with arch x86-64

- Makefile
This should fix the cloudsmith packaging by placing libponyrt and libponyrt-pic into the same directory as ponyc. However, the compiler should be able to find these libraries without them being in the same directory.
> Install libponyrt to install dir

- .dockerfiles/latest/x86-64-unknown-linux-gnu/Dockerfile
- .dockerfiles/release/x86-64-unknown-linux-gnu/Dockerfile
It's there in the musl ones, but not glibc ones.
> Add make to gnu based Dockerfiles

- Makefile
On some platforms, it won't exist.
> Only copy libponyrt-pic.a on install if it exists

- CMakeLists.txt
These are from https://github.com/ponylang/ponyc/blob/5858df3b2c5c2117c986844d948c1caebea71a55/Makefile-ponyc#L310
> Add back OSX build flags that were missed in CMake

- CMakeLists.txt
- Makefile
This fixes #3481. CMake was using its own value for the build architecture (`CMAKE_SYSTEM_PROCESSOR`) instead of the one the Makefile was using.  This change passes the value for `arch` that the Makefile is using to CMake to set `PONY_ARCH`.
Thus when `ponyc` is looking for a `../lib/$PONY_ARCH` directory to find `libponyrt.a` in, it'll find the same one that the Makefile created.
> Correctly pass PONY_ARCH to CMake

- .cirrus.yml
- INSTALL.md
- make.ps1
This conforms to the other OS package names.
> Make windows zip file name `x86-64` instead of `x86_64`.

- .dockerfiles/latest/x86-64-pc-windows-msvc/Dockerfile
- .dockerfiles/latest/x86-64-pc-windows-msvc/build-and-push.ps1
- .dockerfiles/release/x86-64-pc-windows-msvc/Dockerfile
- .dockerfiles/release/x86-64-pc-windows-msvc/build-and-push.ps1
- .github/workflows/handle-external-events.yml
- .github/workflows/pr.yml
This change adds Dockerfiles and associated GitHub actions to build Windows Docker images for nightlies and releases.
> Build Docker images for windows builds

- .cirrus.yml
FreeBSD 12.0 is no longer supported.
See https://www.freebsd.org/security/unsupported.html.
> Update  supported FreeBSD version to 12.1

- .ci-dockerfiles/windowsservercore/Dockerfile
- .ci-dockerfiles/windowsservercore/README.md
- .ci-dockerfiles/x86-64-pc-windows-msvc-builder/Dockerfile
- .ci-dockerfiles/x86-64-pc-windows-msvc-builder/README.md
- .ci-dockerfiles/x86-64-pc-windows-msvc-builder/build-and-push.ps1
- .cirrus.yml
This makes it work the same way as the Unix builds.
> Update Windows build docker image to use an image on DockerHub.

- CMakeLists.txt
- Makefile
- src/libponyrt/CMakeLists.txt
- src/libponyrt/mem/pool.c
The previous Unix Makefile had support for various compile options via a `use=` flag.  This PR re-implementes these in the new CMake build system.
Fixes #3496
> Re-implement the `use` handling in the new CMake build system

- .ci-dockerfiles/cross-aarch64/Dockerfile
- .ci-dockerfiles/cross-arm/Dockerfile
- .ci-dockerfiles/cross-armhf/Dockerfile
- .ci-dockerfiles/x86-64-unknown-linux-gnu-builder/Dockerfile
- .ci-dockerfiles/x86-64-unknown-linux-musl-builder/Dockerfile
- .cirrus.yml
In prep to switching to using clang as our supported compiler. Currently,
we have no specific compiler we are defaulting to. It's been decided that
we will settle on clang not gcc.
> Add clang to CI builder images

- BUILD.md
- INSTALL.md
- Makefile
If `CC` is not defined when running make, or is equal to `cc`, and `clang` is in the PATH, this sets `CC=clang` and `CXX=clang++`.
> Make clang our default compiler on Linux, macOS, and FreeBSD

- src/libponyrt/actor/actor.c
- src/libponyrt/gc/cycle.c
- src/libponyrt/gc/cycle.h
- src/libponyrt/sched/scheduler.c
- src/libponyrt/sched/scheduler.h
This addresses #3501.
PR #2709 introduced the cycle detector being lazily scheduled once a certain amount of cpu ticks (`--ponycdinterval`) has passed. Scheduler thread 0 would then 'wake up' the the cycle detector by sending it a `CHECK_BLOCKED` message. The cycle detector would then be appended to back of scheduler-0's queue. The cycle detector would then only be scheduled if either
1. Scheduler 0 is available (i.e. its queue was empty in the previous loop iteration)
2. Another scheduler thread is available and steals the cycle detector from scheduler 0's queue. However, this would only happen when the cycle detector has 'travelled' to the head of said queue.
This could create pathological behavior where cycle detection is actually deferred to a point in time where the program would be …
> schedule the cycle detector with higher priority using the inject queue

- Makefile
`make install symlink=yes` on Linux will now create symlinks to pony
libs in `/usr/local` rather than `/usr/local/$(arch)`. The uninstall
target in the Makefile has also been updated to remove these libs
and `/usr/local/lib/pony`. Thanks to @pmamatsis for reporting this
issue.
Closes #3513
> Symlink pony libs without arch directory

- packages/net/ossockopt.pony
- src/libponyrt/lang/socket.c
Add SO_RCVTIMEO_OLD, SO_RCVTIMEO_NEW, SO_SNDTIMEO_OLD, & SO_SNDTIMEO_NEW, which were added to the Linux kernel 5.1, see #3498.
Fixes #3498 
Using this test program:
```Pony
use "net"
actor Main
@printf[I32]("so_rcvtimeo = %d\n".cstring(), OSSockOpt.so_rcvtimeo())
@printf[I32]("so_rcvtimeo_old = %d\n".cstring(), OSSockOpt.so_rcvtimeo_old())
@printf[I32]("so_rcvtimeo_new = %d\n".cstring(), OSSockOpt.so_rcvtimeo_new())
@printf[I32]("so_sndtimeo = %d\n".cstring(), OSSockOpt.so_sndtimeo())
@printf[I32]("so_sndtimeo_old = %d\n".cstring(), OSSockOpt.so_sndtimeo_old())
@printf[I32]("so_sndtimeo_new = %d\n".cstring(), OSSockOpt.so_sndtimeo_new())
```
... I get the following output on an Ubuntu 19.10 x86-64 VM with a Linux 5.3.0-46-generic kernel.
```
so_rcvtimeo = 20 …
```
> Add OSSockOpt constants added by Linux 5.1 kernel

- .dockerfiles/latest/x86-64-unknown-linux-gnu/Dockerfile
- .dockerfiles/latest/x86-64-unknown-linux-musl/Dockerfile
- .dockerfiles/release/x86-64-unknown-linux-gnu/Dockerfile
- .dockerfiles/release/x86-64-unknown-linux-musl/Dockerfile
We recently switched to using clang as our default compiler. This
means that if $CC isn't set when compiling a ponyc program it will
look for clang to do linking.
Currently, clang isn't installed in the docker containers nor is $CC
set.
This wasn't an issue previously because gcc was installed so $CC not
being set didn't cause problems.
> Add clang to nightly and release Docker containers

- packages/process/_process.pony
- packages/process/_test.pony
- packages/process/_test.sh
- packages/process/process_monitor.pony
- packages/stdlib/_test.pony
- src/libponyrt/lang/process.c
- src/libponyrt/lang/process.h
I have taken the liberty of rebasing #2981 (and fixing a couple of Windows issues) because I am too impatient to wait for @mfelsche to have time to look at it.
Quoth @rkallos:
Fixes #2821.
This PR adds a pipe for errors that take place after fork() and exec(), which might also solve #2719. Data sent across this pipe winds up calling ProcessNotify.stderr. This is disingenuous, since the data was actually sent along a separate pipe. However, it seems intuitive enough, as I imagine that is where error dispatch and handling would take place. I also did not want to inflict a large change on ProcessNotify without the blessing of the Pony core team. All in all, this seemed like the path of least resistance for fixing the issue. I would be happy to change the behavior to something else.
> Let processmonitor chdir before exec

- packages/process/_process.pony
- packages/process/_test.pony
- packages/process/process_error.pony
- packages/process/process_monitor.pony
- src/libponyrt/lang/process.c
- src/libponyrt/lang/process.h
This is a breaking change, as the `ProcessError` types are now classes, not primitives, and have a `.string()` method to return their error messages.
In addition, there is no more `Unsupported` error type.
> Update ProcessMonitor errors to contain error messages

- packages/cli/_test.pony
- packages/cli/command_parser.pony
Previously, the command parser would swallow all "--" after the first
one. For me, this manifested itself in not allowing corral to be used
with lldb "corral exec -- lldb ponyc -- $(ponyc) -V=0 -o ./build/
./utility" since the second "--" is required to be passed to lldb.
This change is dependency for a PR being submitted to corral to allow
use of corral with lldb (for debugging ponyc itself).
> Fix CommandParser incorrectly handling multiple end-of-option delimiters

- CHANGELOG.md
- packages/process/_process.pony
- packages/process/_test.pony
- packages/process/_test.sh
- packages/process/process_monitor.pony
- packages/process/process_notify.pony
- src/libponyrt/CMakeLists.txt
- src/libponyrt/lang/directory.c
- src/libponyrt/lang/errno.c
- src/libponyrt/lang/errno.h
- src/libponyrt/lang/process.c
- src/libponyrt/lang/process.h
Waiting or a process to finish was potentially blocking both on windows and posix systems. It was only ever called when the child process was killed beforehand or has closed both stdout and stderr, so the actual risk to block was low, but still. Now it calls `waitpid` (and the windows equivalent) with `WNOHANG` (on windows with timeout of 0) to ensure it does not block. If the process is still running at that point, a timer is scheduled to poll the process using the non-blocking `waitpid`.
During testing I discovered that processes terminated by signals were usually reported as exited with exit-code 0, which is wrong. I changed the `ProcessNotify.dispose` signature to receive a `Signaled` or `Exited` class containing signal number or exit code. 
This works pretty well, the only case this …
> Ensure non-blocking process wait and correctly report process exit status

- .ci-dockerfiles/x86-64-unknown-linux-ubuntu18.04-builder/Dockerfile
- .ci-dockerfiles/x86-64-unknown-linux-ubuntu18.04-builder/build-and-push.bash
- .cirrus.yml
We switched our generic glibc builds to Ubuntu 20.04 and now the nightly
and release builds do not work on Ubuntu 18.04. This adds support for those
builds so that users still on Ubuntu 18.04 (like me!) can use ponyup to
install a working ponyc.
> Add Ubuntu18.04 builds

- .ci-scripts/x86-64-unknown-linux-ubuntu18.04-nightly.bash
- .ci-scripts/x86-64-unknown-linux-ubuntu18.04-release.bash
- .cirrus.yml
Prior to this change, the Ubuntu 18.04 builds would use an incorrect
triple for building and uploading. They would end up overwriting (if they
came second), the normal gnu/glibc build.
While this change will fix the issue, it shows that it is time to start
making the scripts more compact and starting to DRY them up some. We've
previously discussed during sync calls switching from using bash to python
to make same-ness easier to do. I'm not sure we need to switch to python at
this point, however, it is time to remove some duplication. That will come
in another PR.
> Upload Ubuntu 18.04 builds under the correct name

- .ci-scripts/x86-64-apple-darwin-nightly.bash
- .ci-scripts/x86-64-apple-darwin-release.bash
- .ci-scripts/x86-64-unknown-freebsd12.1-nightly.bash
- .ci-scripts/x86-64-unknown-freebsd12.1-release.bash
- .cirrus.yml
This PR brings ponyc in line without scripts we have for building
to take the cloudsmith api key from the environment rather than via
the command line
> Release builders: normalize cloudsmith api key usage

- src/libponyrt/actor/actor.c
- src/libponyrt/sched/scheduler.c
After a review of the memory ordering with atomics related to backpressure
and actor muting, Sylvan's statement was "this is broken on ARM".
Here's the fixes.
> Fix atomics usage related to actor muting for ARM

- src/libponyrt/actor/actor.h
While doing a separate review together, Sylvan noticed that while not
currently wasteful, that the layout of pony_actor_t could end up in
resulting in excess alignment packing in the future.
> Potentially save on space for an actor in the future

- .ci-scripts/x86-64-unknown-freebsd-12.1-nightly.bash
- .ci-scripts/x86-64-unknown-freebsd-12.1-release.bash
- .cirrus.yml
- INSTALL.md
- RELEASE_PROCESS.md
It's highly problematic for ponyup to name artifacts with freebsd12.1 rather
than freebsd-12.1 as it goes against the expected naming scheme for ponyup
managed resources.
> Rename FreeBSD artifacts

- .cirrus.yml
As we are going to be adding more Linux distros that we support based
on community request, using a matrix of the few differences between
each should make it easier for us to support adding new ones.
We could eventually incorporate the macOS and FreeBSD builds as well,
but this seems like a good first step.
> Switch Linux nightly and release config to matrix

- src/libponyrt/lang/process.c
I think there are a couple of problems with recent changes to `ponyint_win_process_wait`.  I should have caught them in review.
Changing the timeout value to 0 means that `WaitForSingleObject` won't block, so we can't close the handle in that case.  Also 0x80 is the return code `WAIT_ABANDONED` which doesn't apply to processes.  We should be checking for `WAIT_TIMEOUT` (0x102) which means the process hasn't exited yet.  Also we need to make sure that retval is not 0 or 1 in an error case where `GetLastError()` returns 0 for some reason.
> Fix incorrect Windows process waiting

- CMakeLists.txt
- Makefile
- src/libponyrt/actor/actor.c
- src/libponyrt/actor/actor.h
- src/libponyrt/pony.h
Pony doesn't use continutations and never has. The code
was added when the runtime was shared with other projects.
> Remove unused actor continutations code

- INSTALL.md
This adds a note to the ponyc install documentation
to inform users that clang will be used as default
compiler, and gives them instructions on how to
override with their compiler of choice.
Fixes #3520 
Signed-off-by: hasheddan <georgedanielmangum@gmail.com>
> Add note for setting CC and CXX for prebuilt pony installs

- RELEASE_PROCESS.md
These tools have been replaced with CirrusCI, Cloudsmith, and GitHub Actions. This removes them from the release process documentation.
[skip ci]
Signed-off-by: hasheddan <georgedanielmangum@gmail.com>
> Remove travis, appveyor, and homebrew references in release process

- src/libponyrt/mem/pool.c
Adds an explicit constructor to `pool_block_t` . Without the explicit constructor, the compiler says "attempting to reference a deleted function", referring to the auto-created constructor.
> Compile fix for the latest MSVC compiler (MSVC 19.26.28806.0, from Visual Studio 16.6.2)

- src/libponyc/ast/parserapi.h
Fixes minor typo in parser description to read recursive descent instead
of recursive decent. I do in fact believe the parser is also pretty
decent.
Signed-off-by: hasheddan <georgedanielmangum@gmail.com>
> Update parser comment to read recursive descent

- make.ps1
#3544 
This PR allows to build ponyc project using vs2019 preview.
Without my changed，It will prompt "No Visual Studio 2017+ was found in the system."
> Added vs2019 preview support for building ponyc

- src/libponyc/pass/sugar.c
- test/libponyc/sugar.cc
A with expression like the following caused the compiler to abort:
```pony
with (a, b) = some_tuple do
error
end
```
This PR fixes those cases and adds some test coverage for desugaring with expressions in general.
Fixes #3581
> Fix with expressions using tuple destructuring.

- src/libponyc/type/typeparam.c
Fixes https://github.com/ponylang/ponyc/issues/3570
> Fix typeparam check endless recursion

- packages/files/_test.pony
- packages/files/file_path.pony
On Windows, `_unlink()` cannot remove a file if it is read-only. This change calls `_chmod(..., _S_IWrite)` on files that are about to be removed so as to make sure they are removable.
This fixes an issue with temp directories being left around from tests in Corral, as Git often makes some of its files read-only.
> Force removing read-only files on Windows with `FilePath.remove()`

- src/libponyc/type/cap.c
- test/libponyc/cap.cc
Currently, this causes some compile errors in collections/persistent/_map_node
And they really don't seem trivial to fix; it's relying pretty heavily on the ability to mutate some trn views of trns. It can't be changed to ref either since ref also goes to box.
So I'm not sure we can make this change without going forward with extracting/non-extracting
Fixes https://github.com/ponylang/ponyc/issues/3572
> Change trn->trn to box to fix a soundness hole

- packages/logger/_test.pony
- packages/logger/logger.pony
[RFC text](https://github.com/ponylang/rfcs/blob/master/text/0067-add-log-level-argument-to-logformatter.md)
Closes #3594
> Add LogLevel as argument to LogFormatter

- packages/builtin/string.pony
String is really a collection of bytes and several methods assume
that characters are a single-byte.
> Update String documentation to be more correct

- .gitignore
- BUILD.md
- Makefile
and introduce a way to generate compile_commands.json file using CMAKE_FLAGS.
This might help developers leverage LSP clients for C development like clangd and also might enable better control over cmake if desired.
I shortly thought about generating the `compile_commands.json` file in every case, but it might be too much e.g. for CI systems building ponyc. After all it is only interesting when building from source and developing.
> Add CMAKE_FLAGS variable for specifying special CMAKE variables

- .ci-scripts/build-and-push-stdlib-documentation.bash
Prior to this change, we haven't built the standard lib docs due to
an error since February yet, the build has been green. This
should fix that issue. I hope.
> Have stdlib documentation building fail build if it fails

- .ci-dockerfiles/stdlib-builder/Dockerfile
- .ci-dockerfiles/stdlib-builder/build-and-push.bash
- .github/workflows/handle-external-events.yml
The image that was based on Ubuntu wasn't correctly installing
the ponylang theme and then doc building would fail.
This PR
- Switches to alpine for the base of the doc building image because it works
- Adds building the doc builder image both after a release and after each nightly
- Switches to having 2 tags for the image
- release
- latest
By building a latest on each nightly, we can catch any errors building the image
before we get to a release (hopefully).
> Fix broken standard library documentation builder

- packages/logger/_test.pony
- packages/logger/logger.pony
This reverts commit 4d4cb9223bf7a790e9eb64e45661b3e6119f2322.
The original intent behind RFC0067 was to make it easy to add a prefix with the
log level for any given log message. However, there is a logic bug in the
implementation; the log level prefix added to messages in LogFormatter would
always be the log level specified in Logger.create(), not the log level desired
at specific call sites. This would lead to misleading log messages where the log
level prefix doesn't match the severity of the log message, such as "FINE:
Critical error. Shutting down".
It would be better if these changes were reverted so a more thought-out solution
could be implemented in the future.
> Revert "Implement RFC0067"

- src/libponyc/expr/reference.c
- test/libponyc/recover.cc
I should have opened this ages ago, but this change always allows simple assignments with variables defined locally:
`x.y = e`, `x.y.z.q = e`
Soundness can be seen because this functionality is possible today using methods, it is just very cumbersome.
This also includes a change to enable field-writes to non-local variables when the destination is sendable (this is slightly less than the most general: which would include writing a sendable expression to any field; but that requires adding more check logic). The current checks had very strange logic, and don't seem to be necessary: We only need to maintain isolation of the recover region, so it's perfectly fine to move sendable items in or out without restriction, since they cannot violate the guarantees. See …
> Always allow field access for objects defined inside a recover block

- .dockerfiles/latest/x86-64-pc-windows-msvc/Dockerfile
- .dockerfiles/latest/x86-64-unknown-linux-gnu/Dockerfile
- .dockerfiles/latest/x86-64-unknown-linux-musl/Dockerfile
- .dockerfiles/release/x86-64-pc-windows-msvc/Dockerfile
- .dockerfiles/release/x86-64-unknown-linux-gnu/Dockerfile
- .dockerfiles/release/x86-64-unknown-linux-musl/Dockerfile
The following are fixes from the Hadolint docker linter. We
can't turn it on as part of the linting process as we can't turn
it off for our Windows Dockerfiles and it does not know how to
handle the Windows-ism in it.
> Minor Docker linting fixes

- .ci-dockerfiles/x86-64-unknown-linux-centos8-builder/Dockerfile
- .ci-dockerfiles/x86-64-unknown-linux-centos8-builder/build-and-push.bash
- .cirrus.yml
- .release-notes/3629.md
- BUILD.md
At the request of Damon Kwok, we are adding prebuilt CentOS 8 versions
of ponyc. Both nightly and release builds.
> Add prebuilt ponyc binaries for CentOS 8

- .github/workflows/handle-external-events.yml
The release process for ponyc was broken. Prior to this commit,
the final step of the release process, announcing the release, was never
triggered.
This happened because the trigger-release-announcement step of the process
didn't work correctly. The previous versions of release-bot-action would
only work if trigger-release-announcement was started by a tag being pushed.
For all other ponylang repos, this was the case. ponylang/ponyc is different.
With ponyc, assets are built on CirrusCI rather than GitHub. This means that
we can't include the triggering of the announcement in release.yml (which is
started by a tag being pushed). Instead trigger-release-announcement is
triggered from handle-external-event.yml.
handle-external-event.yml is started when HTTP POST calls are made from …
> Fix broken release process

- EDITORS.md
- README.md
Not sure you want this, but i thought i clean up the README.md somewhat, by moving the editor support list to a separate file and link to it from README.md.
> Move editor support from README.md to EDITORS.md

- .release-notes/3635.md
- lib/CMakeLists.txt
- lib/llvm/patches/2020-09-01-is-trivially-copyable.diff
Visual Studio 16.7 introduced a change in C++20 compatibility that breaks building LLVM on Windows (#3634).  This change adds a patch for LLVM that fixes the issue.  Fixes #3634.
The change also introduces a check in CMake of the hashes of the patch files. Since the build caches in CI depend on the contents of `libs/CMakeLists.txt`, and that file contains the desired hash, changing the patches (and thus the desired hash) will force a rebuild of the libs build caches (in the same way as changing the Git checkout for LLVM will force a rebuild).
> Fix building libs with Visual Studio 16.7

- README.md
Reorganization based on the conversation raised during the move to EDITORS.md -- only change from my example in the EDITORS.md PR is I had to place the Resources section (which I had left out of the example).
> Reorganize README based on #3624 conversation

- .release-notes/3637.md
- Makefile
When implementing the CMake build system, I missed copying a couple of lines from the old Makefile that meant that you could only specify one `use=` option when doing `make configure` on Posix.  This change restores those lines, so you can specify multiple options for `use`, e.g. `make configure use=memtrack_messages,address_sanitizer`.
> Fix missing Makefile lines to re-enable multiple `use=` options

- .release-notes/3639.md
- packages/collections/range.pony
It was agreed when discussing #2969 that Range.next should be partial
and return an error when you reach the end rather than returning the
end index over and over again.
This is a breaking change.
Closes #2969
> Make Range.next() partial

- packages/builtin_test/_test_valtrace.pony
Comment says "test all 4 actors". It is testing 3 because it is
testing the same one twice and skipping one.
> Fix bug in Valtrace builtin test

- INSTALL.md
@Theodus can you help me complete writing this, possibly adding needed ponyup issues and features as we go?
>  Update "how to install on Linux" instructions

- .release-notes/3467.md
- src/libponyc/pass/refer.c
- test/libponyc/refer.cc
Function calls in `consume` are deemed invalid by the syntax checker.
However, they seep in via field accessors on the function call
expressions. This change fixes #3453.
> Consistent handling of  function calls in consume expressions

- .github/linters/.yaml-lint.yml
A large number of our yml files for CI jobs won't pass with it on and we don't want to mess around with them to get them to pass.
> Don't do line-length yaml linting

- make.ps1
This matches what we do with Linux and makes sure that tests that
have competing needs for resources can't accidentally clash.
> Run windows standard library tests sequentially

- .release-notes/dipin-cd-patch.md
- src/libponyrt/actor/actor.c
- src/libponyrt/gc/cycle.c
This commit speeds up reaping of some actors by the cycle-detector.
When an actor is done running, we do a check similar to the check
we do for when --ponynoblock is on:
- Check to see if the actor's message queue is empty
- Check to see if it has a reference count of 0
If both are true, then the actor can be deleted. When --ponynoblock
is used, this is done immediately. It can't be done immediately when
the cycle detector is in use because, it might have references to
the actor in question.
In order to safely cleanup and reap actors, the cycle detector must
be the one to do the reaping. This would eventually be done without
this change. However, it is possible to write programs where the
speed at which the cycle detectors protocol will operate is unable
to keep up with the speed at which …
> Speed up cycle detector reaping some actors

- .release-notes/3650.md
- src/libponyc/pass/refer.c
- src/libponyc/pass/syntax.c
- test/libponyc/refer.cc
* `consume (consume variable).field` must result in similar compilation error as  `consume (consume variable)`.
* `consume f().field` must result in similar compilation error as `consume f()`
* `(consume c).field` must not result in a crash.
Fixes #3463, #3567 (and #3453)
> Prevent compiler crashes on certain `consume` expressions

- .release-notes/3657.md
- packages/builtin/array.pony
While the memory of the two array pieces was disjoint, a non-sendable element type could allow aliases between the two array portions that would violate isolation.
Fixes https://github.com/ponylang/ponyc/issues/3652
> Fix soundness problem with Array.chop

- .github/workflows/pr.yml
It was turned off because we merged a PR that broke it for
release images until such time as the next release was done.
> Turn back on checking release image as part of PR

- .release-notes/cd-double-free.md
- src/libponyrt/actor/actor.c
This fixes a bug introduced with the recent short-lived actor garbage
collection improvements.
Here's the race:
- Cycle detector is on
- Cycle detector is aware of an actor
1. Actor finishes a scheduler run
2. Actor marks queue as empty
3. Actor has rc of 0 so it sends a BLOCK message to the cycle detector
Between 2 and 3, the cycle detector sends an IS_BLOCKED message to
the actor. The actor is rescheduled on the same scheduler thread as the
cycle detector.
Because in 3, we sent a BLOCK message and the rc is 0 (and can't change),
the cycle detector is going to delete the actor when it processes the
BLOCK message.
However, the actor exists on another schedulers queue. Either of the following
could happen:
- Actor runs again before deletion, sends another BLOCK message to the cycle …
> Fix race condition in cycle detector block sent handling

- test/libponyc/matchtype.cc
The bug that 2737 was meant to fix is no longer an issue however
we don't have a regression test for it. This PR takes the regression
test from @jemc's original PR and adds it on its own.
> Add regression test from #2737

- .release-notes/3667.md
- src/libponyrt/actor/actor.c
- src/libponyrt/actor/messageq.c
- src/libponyrt/actor/messageq.h
- src/libponyrt/gc/cycle.c
- src/libponyrt/sched/scheduler.c
Prior to this commit, there could be race conditions with a actor
running concurrently on two different threads due to work being
done after an actors queue was marked empty.
This commit reworks the logic to ensure that the actors queue being
marked empty is the last thing that occurs in `ponyint_actor_run`
to prevent these race conditions.
This commit also adds logic in the cycle detector to not send any
messages to actors that are marked as pending destroy to ensure
that the cycle detector cannot create a race condition by sending
messages to a zombie actor (with `rc == 0`) that is about to be
reaped in the near future.
> Fix race conditions that can lead to a segfault

- packages/cli/env_vars.pony
Currently the doc generator doesn't escape html-like tags, and merely inserts them as-is in the final document. This should be fixed, but for now we can avoid that by enclosing tag-like in code/pre tags ourselves.
> Prevent html escaping in documentation

- .release-notes/issue-3669.md
- src/libponyc/codegen/genoperator.c
- test/libponyc/codegen.cc
This fixes a compiler crash that used to occur when certain kinds of assignment expressions that have no logical result value were used as the last expression in an `if` block, and possibly other control flow constructs as well. Now the compiler makes sure that the code generation for those cases always bears a value, even though the type system guarantees that the value will never be used in such a case. This prevents generating invalid LLVM IR blocks that have no proper terminator instruction.
> Fix compiler crash when an if block ends with an assignment that has no result value.

- .ci-dockerfiles/x86-64-pc-windows-msvc-builder/Dockerfile
- .cirrus.yml
- .dockerfiles/latest/x86-64-pc-windows-msvc/Dockerfile
- .dockerfiles/release/x86-64-pc-windows-msvc/Dockerfile
The error in the recent Windows CI builds seems to indicate a problem with the Windows system in the container that Cirrus is using. This PR updates the dockerfile and Cirrus config to use an updated image.
> Update windows build dockerfile

- .release-notes/3686.md
- src/libponyc/codegen/genexe.c
With the change from Catalina to Big Sur, Apple moved the location of
libraries. On Big Sur, it is required to pass the location of the System
library. The `-lSystem` option is still required for macOS 10.15.7 and
lower.
We don't currently distinguish between different macOS versions, so we
should keep both options. As long as the absolute path of the System
library is present, the `-lSystem` option won't pose any problems on Big
Sur.
This should fix #3684.
> Fix link errors on macOS Big Sur

- .release-notes/3687.md
- src/libponyrt/lang/socket.c
`os_socket_listen`, `os_socket_connect` and `os_connect` incorrectly
assumed that the return value from `os_addrinfo_intern` would never be
NULL, and therefore would call freeadrinfo with a null pointer, causing
a segmentation fault.
This should fix #3685.
> Fix unhandled null pointer returning from os_addrinfo_intern

- packages/net/udp_socket.pony
As in the tutorial, there needs to be a blank line before a list, or the items will be included in the previous paragraph.
> Fix UDPSocket docs

- INSTALL.md
Ponyup doesn't work because of a change in library locations. Building from source currently has issues as well.
> Include note about lack of macOS M1 support in INSTALL

- .github/workflows/handle-cloudsmith-events.yml
The handle external events workflow was overly broad. It was only
used for cloudsmith related events. Mixing in other events into
the same workflow would be problematic.
This PR scopes the workflow correctly which will allow the use
of respository_dispatch with other workflows in the future.
> Scope "handle external events" to cloudsmith events only

- .github/workflows/cloudsmith-package-sychronised.yml
With a previous PR, I tried to correct the scope of the workflow but
got the event type we sent from cloudsmith incorrect because I wasn't
looking at the correct place in the Cloudsmith UI.
> Fix cloudsmith package synchronised event handling

- .github/workflows/cloudsmith-package-sychronised.yml
Adds sending a GitHub repository dispatch event to ponylang/shared-docker
when all 3 nightly docker images are done building.
This will allow us to trigger nightly shared-docker image rebuilds when
the new images are available rather than hoping that the times line up.
Additional triggered jobs will be added once I know this is working.
For example, triggering testing against the latest ponyc master images
in our various repos.
Additional repos to send to can be added to the `repos` section of the
job's matrix.
At this time, we don't send any payload data with the event as I'm not
aware of what we might need to include.
> Add sending events when nightly releases are finished

- .github/workflows/cloudsmith-package-sychronised.yml
We don't want the github action disappearing out from under us,
so we forked it into ponylang-main where we can use it from.
> Switch to using ponylang-main version of ssh-action

- .github/workflows/cloudsmith-package-sychronised.yml
Sends a repository_dispatch event of type `ponyc-musl-release` when
all Linux musl release artifacts have been built. Event is only sent
to repositories that have been "registered to receive" by adding to
the repo matrix in the "send-release-event" job.
Sending a repository_dispatch event allows other ponylang repos to
kick off workflows in response to some part of a release being done.
> Add sending a repository_dispatch event when a release is done

- .release-notes/3675.md
- packages/builtin/array.pony
- packages/builtin_test/_test.pony
Fixes #3668. String already checked for a potential null pointer before constructing, so it was safe. Also added a test case to check this.
> Fix memory safety problem with Array.from_cpointer

- .release-notes/3700.md
- src/libponyc/pkg/package.c
Fixes incorrect qualified path name building for relative package imports,
Instead of doing the relative path in relation to the package we were in,
it did it based on the base of the program.
So for example instead of getting
"semver/version"
or an equiv
"semver/test/version/../../version"
You'd end up with
"semver/../../version"
> Fix bad package names in generated documentation

- packages/builtin_test/_test.pony
- packages/stdlib/_test.pony
At the moment, there's a race condition that can cause a segfault when
garbage collecting an actor if the cycle detector is on. I haven't had
the solid block of time to fix the problem.
In the meantime, there have been distracting CI failures.
This commit turns off the cycle detector for standard library tests. This
will give us more confidence in those tests. If there is a segfault, we
know it isn't from the known issue.
The changes in this commit will be removed along with the fix for the
race condition.
> Run standard library tests without the cycle detector

- .release-notes/3707.md
- src/libponyrt/sched/cpu.c
* On both FreeBSD and DragonFly, `sysctl hw.ncpu` returns the number of
logical CPUs, NOT the number of physical CPU cores.
* FreeBSD has sysctl `kern.smp.cores`.
* DragonFly has sysctl's `hw.cpu_topology_core_ids` and
`hw.cpu_topology_phys_ids`. Both multiplied together results in the
number of cores.
* If `kern.smp.cores` (FreeBSD) or `hw.cpu_topology_*` (DragonFly) is
not available, use `hw.ncpu` instead.
* For example on FreeBSD 12.2p3 running a i7-8565U:
sysctl hw.ncpu # => 8
sysctl kern.smp.cores # => 4
* For example on DragonFly 5.9-DEVELOPMENT with Xeon E5-1620:
sysctl hw.ncpu # => 8
sysctl hw.cpu_topology_phys_ids # => 1
sysctl hw.cpu_topology_core_ids # => 4
sysctl hw.cpu_topology_ht_ids   # => 2
* I found this by running a HTTP benchmark on a FreeBSD system
(i7-8565U, 4 cores / …
> Fix calculation of # CPU cores (FreeBSD/DragonFly)

- .release-notes/3713.md
- src/libponyc/codegen/gencall.c
Previously, the compiler would ignore any `?` annotations on FFI
declarations, which could result in the generated code lacking any
guards for errors, causing the final program to abort at runtime.
h/t to @jemc for noticing what needed to be fixed.
> Fix partial FFI declarations ignoring partial annotation

- .release-notes/3716.md
- Makefile
- src/libponyc/CMakeLists.txt
It's possible to use libponyc from projects other than ponyc. Using the
library gives you access to all the various compiler functionality. However,
it is hard to use the library because, you need to link in the correct libstdc++,
libblake, and LLVM. Figuring out what is the correct version of each is very
difficult.
With this change, a new library `libponyc-standalone.a` will be created as
part of the build process.
Applications like the "in pony documentation generator" that I am on will
be able to link to libponyc-standalone and pick up all it's required dependencies.
Windows, BSD, and macOS libraries are not created at this time but can be added
as needed in the future.
> Create a standalone libponyc on Linux

- .release-notes/3719.md
- src/libponyc/pass/traits.c
- test/libponyc/traits.cc
`ast_replace` (potentially) copies the input AST, hence it's important
to do the symbol table patching on the output AST. Otherwise the
patching will happen on the wrong nodes, which leads to methods with
a wrong symbol table.
Fixes #3305
> Fix symbol table patching for overriding default methods

- .cirrus.yml
It will take longer to verify a PR but it means that we shouldn't
have nightlies failing on us from changes.
> Run PRs on all nightly and release Linux targets

- .release-notes/3723.md
- src/libponyc/codegen/genfun.c
- test/libponyc/codegen.cc
It's possible that the method body returns a subtype of the return type.
For example, a return value with type `((U32, U32) | (U32, None))` is
legal for a method with return type `(U32, (U32 | None))`, but it
requires a cast.
071db1051b01b02a1224867c5bdbae3983634231 changed that methods returning a tuple always use a cast as if the method body's value already has the return type. Unfortunately, it doesn't go into detail why. This already caused an issue in #849 and an exception was added if return type and body type are both tuples. I think that assumption doesn't hold: for the above mentioned case, the return type is a tuple, but the body type is an union, and yet the current code continues as if the body produces a tuple.
Fixes #2609, #2808
> Fix tuple related compiler segfaults

- .release-notes/fix-param-type-reference-crash.md
- src/libponyc/pass/traits.c
- test/libponyc/traits.cc
This fixes a bug in rescoping. Rescoping happens after a method was
copied from a trait/interface to another type. It starts with a fresh
scope, visits all of the method's AST nodes and adds the visited symbols
to the method's symbol table. This includes type parameters. If a type
parameter reference is visited, the referenced type parameter is looked
up and added as data to the node.
As rescoping starts with a fresh scope, adding the type parameter to the
reference fails if the type parameter itself is not defined yet. This is
fixed by eagerly adding type parameters to the scope before visiting
type parameter references.
Fixes #3285
> Fix compiler crash related to type parameter references

- .release-notes/3674.md
- packages/process/_pipe.pony
This commit fixes a fun bug that results from multiple bits coming together.
First, the ProcessMonitor when running on Windows doesn't using ASIO. Instead
of having events pushed to it, we poll periodically to see if there's anything
to read or if we can write any pending writes.
Because of the polling, it is possible that we will attempt to read when there's
no data in the pipe. When using non-blocking IO with pipes, a read that would return
0 bytes returns an error and sets the error code to a no data error code.
We were interpreting the no data code as it should be when using blocking io. When
using non-blocking io, there error communicates "no data right now, try again later"
which wasn't what we were doing.
The same incorrect handling of the "no data" error code was present in the …
> Fix early pipe shutdown with Windows ProcessMonitor

- .release-notes/3729.md
- src/libponyc/expr/literal.c
- test/libponyc/literal_inference.cc
Before this change, code such as `1~add(2)` would hit an assertion error
when the compiler tried to infer the type of the literal 2. The compiler
tries to find the type of the receiver of the function, in this case
`1`, but it lacked the ability to do so when using partial functions. In
those cases, the compiler would try to look at the type of the `~`
token, which is not a valid value literal, and as such it would fail.
Fixes #3531
> Fix literal inference through partial function

- examples/fan-in/main.pony
- examples/message-ubench/main.pony
- examples/under_pressure/main.pony
- packages/assert/assert.pony
- packages/builtin/_to_string.pony
- packages/capsicum/cap_rights.pony
- packages/debug/debug.pony
- packages/files/directory.pony
- packages/files/file.pony
- packages/format/_format_float.pony
- packages/process/_pipe.pony
- packages/term/ansi_term.pony
- test/libponyc/badpony.cc
- test/libponyc/codegen.cc
In preparation of support of Apple silicon, add a declaration for all variadic FFI functions. This needs to be in place before the changes in #3731 can be applied.
> Annotate variadic FFI functions

- .cirrus.yml
The addition of a value allows us to bust the cache for other reasons
we might need like:
- cache is corrupted
- builder image changed
- we are feeling frisky
> Add a cache buster value to Windows LLVM lib fingerprint

- packages/net/ossockopt.pony
The example mentions the `@pony_os_setsockopt` function, which was
originally added in PR #2513, but eventually removed before the PR got
merged.
> Fix setsockopt example in OSSockOpt docs

- .release-notes/3643.md
- packages/collections/map.pony
- src/libponyc/codegen/genmatch.c
- src/libponyc/expr/array.c
- src/libponyc/expr/call.c
- src/libponyc/expr/control.c
- src/libponyc/expr/lambda.c
- src/libponyc/expr/match.c
- src/libponyc/expr/operator.c
- src/libponyc/expr/reference.c
- src/libponyc/pass/expr.c
- src/libponyc/type/alias.c
- src/libponyc/type/cap.c
- src/libponyc/type/cap.h
- src/libponyc/type/matchtype.c
- src/libponyc/type/subtype.c
- test/libponyc/array.cc
- test/libponyc/badpony.cc
- test/libponyc/cap.cc
- test/libponyc/type_check_subtype.cc
- test/libponyc/util.cc
Most individual commits have a long comment describing what they do.
Notably, had to weaken the type of two map methods as they were incorrect for the implementation that they had (and it should be reasonably obvious I hope).
We will also need to ensure that documentation correctly disambiguates between `iso` and `iso^` when talking about subtyping, as otherwise the error messages may be quite confusing (`iso` is not a subcap of `ref`). This is painfully unintuitive  with current docs/cap-naming, but that unintuitiveness was exactly what got us into this unsound subtyping mess.
Fixes #1964 
Updated subtyping table:
> Change to Steed's model of subtyping

- .release-notes/3746.md
- src/libponyc/expr/match.c
- src/libponyc/expr/operator.c
- src/libponyc/type/matchtype.c
- src/libponyc/type/matchtype.h
- test/libponyc/matchtype.cc
Since a struct doesn't have a type descriptor, it's impossible to match
against it, unless it's exactly the same struct type. Before, the
return type of matchtype.c:is_matchtype didn't convey enough information
to the caller about the reason why two types couldn't match. In most
cases, this is due to reference capabilities, so that's what the error
message shows.
By distinguishing the specific case of a match failure due to lack of
type descriptor, the compiler can give a friendlier error message to the
user.
---
This fixes #2000 and fixes #3565, and mostly follows the approach described by @jemc on the second issue.
> Improve error message for match on structs

- .release-notes/3752.md
- examples/circle/main.pony
- packages/builtin/string.pony
- packages/encode/base64/_test.pony
Fixes #3750 by implementing RFC 69.
---
I've marked this as "do not merge" until other ponylang libraries are updated to deal with this change in a backwards-compatible way (where possible).
> Change return type of String.add to String iso^

- .release-notes/realloc-fix.md
- packages/builtin_test/_test.pony
- src/libponyrt/mem/heap.c
Both Array.chop and String.chop violate an expectation that the memory
allocator had.
The memory allocator was written before the standard library and assumed
it would be responsible for doing "smart things" with realloc. That is,
when you ask for a realloc, perhaps you don't really need it. Perhaps
you already have enough.
This worked without issue in the standard library until `chop` came along.
Chop turns a single previous object allocation into 2 and that confused
the memory allocator and could lead to it not reallocating (malloc and copy)
when safety required it. Instead it would return the same pointer it was given.
Based on how the Pony standard library ended up, with String and Array understanding
how much they allocated, we do not need that realloc behavior.
This commit removes …
> Fix memory corruption with Array.chop and String.chop

- .release-notes/3758.md
- src/libponyc/pass/expr.c
- test/libponyc/ffi.cc
We're only interested in ignoring the "guard" part of a use command, but
we still want to go through the arguments to check for any possible
errors during the expr pass. In particular, we're interested in the
NullablePointer constraint check.
----
043dbb1ede410ab6432ef6d16edc73c7cebcaf82 added the original code that ignored `use` statements during the `expr` pass.
I don't know the specific rationale, but it seems we can do this check in a more fine-grained manner so that the rest of a `use` statement goes through the expr pass.
Fixes #3757 
Edit: I made this a draft PR since I'm sure there could be a better way of doing this if I understood the reason for ignoring `use` statements.
> Fix NullablePointer type constraint check being omitted in FFI declarations

- packages/cli/_test.pony
- packages/collections/list.pony
- packages/collections/list_node.pony
- packages/collections/sort.pony
- packages/math/_test.pony
- packages/net/_test.pony
- packages/net/net_address.pony
- packages/net/tcp_connection.pony
- packages/ponytest/test_helper.pony
This small change removes whitespace-only lines from files in the standard library. All I did was run this with GNU Sed:
```sh
sed -i -sE 's|^\s+$||' packages/**/*.pony
```
You might want to [review this with whitespace changes disabled](https://github.com/ponylang/ponyc/pull/3761/files?w=1).
I don't think this merits a changelog update.
There may be some long-term improvements to make here, like an update to the style guide or adding some sort of autoformatter, but this is my first contribution!
> Remove whitespace-only lines from stdlib

- .release-notes/3763.md
- src/libponyc/pass/scope.c
- test/libponyc/iftype.cc
Fixes #3762, but paging @jemc just in case he thinks if this should be fixed somewhere else in the compiler
> Fix "iftype" expressions not being usable in lambdas or object literals

- packages/capsicum/cap_rights.pony
The definitions of these functions appear to have a mixture of fixed and
optional parameters, but looking at [upstream definitions](https://github.com/freebsd/freebsd-src/blob/de1aa3dab23c06fec962a14da3e7b4755c5880cf/sys/sys/capsicum.h#L326-L340)
suggests that some of these functions should have different function
signatures.
For example, while the function __cap_rights_set is defined as taking a
fixed argument, the cap_rights_set calls it with __VA_ARGS__, which
means that all arguments are optional. In case of doubt, we should go
with what the macros do, to avoid any future failures during the verify
step of LLVM. In any case, upstream should probably fix these definitions.
---
This was causing a CI error for #3768, but it should probably go into its own PR for better visibility, so it …
> Fix FFI definitions for vararg capsicum functions

- .release-notes/3777.md
- packages/collections/_test.pony
- packages/collections/flag.pony
Note - I've written a test-suite to cover 90% of this module but it's dependent on a second PR that I'm about to open.
Test coverage is in there.
> Fix bug where Flags.remove could set flags in addition to unsetting them

- .release-notes/3778.md
- packages/collections/_test.pony
- packages/collections/flag.pony
Extending Flags.create to (optionally) allow initialization of a
Flags object with the numeric representation populated. This value
defaults to 0 (no flags set).
> Allow Flags instances to be created with a set bit encoding

- .release-notes/3779-fix.md
- src/libponyc/pkg/package.c
Prior to this change, a library could contain a package called `builtin`
that would override to standard library version. This could be an attack
vector. You can still override the standard library location by using the
ponyc `--paths` option.
Any code which relied on the PONYPATH items being before the standard
library in the package search path will need to switch to using `--paths`
on the ponyc command line.
Closes #3779
> Don't allow PONYPATH to override standard library

- lib/CMakeLists.txt
The previous version we were using doesn't build with gcc 11
> Update google benchmark version

- .ci-dockerfiles/x86-64-unknown-linux-rocky8-builder/Dockerfile
- .ci-dockerfiles/x86-64-unknown-linux-rocky8-builder/build-and-push.bash
- .cirrus.yml
- .release-notes/rocky.md
- BUILD.md
With CentOS 8 no longer being supported as of the end of 2021, many of
the former CentOS users are migrating to Rocky Linux which offers the
same model that CentOS previously offered.
By adding nightly and release version now, we'll be ready when CentOS 8
is discontinued to provide a path for any CentOS pony users.
Another PR will come once we have a release version of pony out and we
have added support in ponyup to add installation instructions for Rocky
Linux.
> Add support for prebuilt Rocky Linux versions

- src/libponyrt/CMakeLists.txt
This commit changes `src/libponyrt/CMakeLists.txt`
to prefer `${CMAKE_CURRENT_SOURCE_DIR}` (which refers to `src/libponyrt`)
over `${CMAKE_SOURCE_DIR}/src/libponyrt` (which is a more roundabout way
of referring to the same directory, but breaks if you try to use `src/libponyrt`
as the root source directory for CMake).
This change makes it possible to build `libponyrt.bc` by itself,
without building anything else in the repo, with a sequence of commands like this:
```
mkdir src/libponyrt/build
env CC=clang CXX=clang++ cmake -S src/libponyrt -B src/libponyrt/build -DPONY_RUNTIME_BITCODE=true
env cmake --build src/libponyrt/build --target libponyrt_bc
```
This doesn't require building LLVM (i.e. `make libs`) or anything else in the repo,
so the whole build process completes within a few …
> Fix libponyrt CMakeLists.txt for standalone build.

- .cirrus.yml
py37-pip package is coming back as no longer available. Let's move
up to the next version.
> Change Python version in FreeBSD CI

- .release-notes/fix-3789.md
- src/libponyrt/mem/alloc.c
Usage of VM_FLAGS_SUPERPAGE_SIZE_ANY when doing allocations causes
ponyc to OOM if it is built with xcode 12.5.
Fixes #3789
> Fix OOM on MacOS when using xcode 12.5

- .release-notes/fix-3792.md
- src/libponyc/codegen/genexe.c
We only support the last 3 versions.
Closes #3792
> Change minimum supported MacOS API version to 10.14

- .cirrus.yml
Apparently, we never set for FreeBSD and MacOS builds. I noticed today
when I needed to bust the MacOS LLVM cache while testing.
> Add missing LLVM CI cache buster values

- .release-notes/3789.md
- .release-notes/next-release.md
- CHANGELOG.md
- CMakeLists.txt
- src/libponyc/codegen/genexe.c
It turns out, from our testing, that `macosx-version-min` isn't needed.
We tested building ponyc and a pony program without macosx-version-min
on Catalina and were then able to use both without issue on an earlier
version of MacOS- Mojave.
After this is merged, we'll do additional testing with nightly versions
of ponyc and corral built on Big Sur by running them on earlier MacOS
releases.
> Fix MacOS version mismatch warnings when linking Pony programs

- src/libponyrt/sched/cpu.c
While looking at M1 stuff, I noticed that this function was using the wrong
implementation for modern Apple ARM - the tick unit for `mach_absolute_time`
is no longer expected to always be nanoseconds, and `clock_gettime_nsec_np`
with a clock type of `CLOCK_UPTIME_RAW` is the recommended replacement.
See:
- https://eclecticlight.co/2020/09/08/changing-the-clock-in-apple-silicon-macs/
- https://developer.apple.com/documentation/kernel/1462446-mach_absolute_time
I don't think a release note is needed, because as far as I know,
this ifdef section for Apple ARM only applies to M1 and iOS/WatchOS/AppleTVOS,
none of which are currently officially supported by Pony.
But M1 hopefully will be soon.
> Fix ponyint_cpu_tick for Apple ARM.

- .release-notes/3765.md
- src/libponyc/verify/fun.c
- test/libponyc/codegen_trace.cc
- test/libponyc/verify.cc
When an immutable object is sent across actors, the garbage collector
traces its associated object graph, using the type descriptor of the
root object. Structs don't have a type descriptor, so the GC can't trace
them.
An option is to track additional information for objects without type
descriptors, but this incurs in severe overhead for the normal case.
Another option, what this commit does, is to disallow non-opaque objects
without type descriptors to be the root of an object graph when used as
parameters to behaviours. Essentially, this means that one has to wrap
non-tag structs inside another object with a type descriptor. This also
applies to structs inside tuples, since the GC will try to trace each
element in the tuple.
---
Fixes #3765
> Prevent non-opaque structs from being used as behaviour parameters

- .release-notes/3808.md
- Makefile
FreeBSD puts all non-base system files under /usr/local prefix, which results in `<unwind.h>` not being found (with **libunwind** being actually installed) when compiling with `runtime-bitcode=yes` option, unless proper `CPATH` and `LIBRARY_PATH` environment variables are defined. This PR addresses the issue, by providing relevant checks and adjustments in the Makefile.
> Fixed Makefile for FreeBSD

- .release-notes/mode-os.md
- packages/files/_file_des.pony
- packages/files/directory.pony
- packages/files/file.pony
- packages/files/file_mode.pony
- packages/files/file_path.pony
FileMode has always had a private method for getting an integer
representation of the file mode. However, it was private and only
available for use within the `files` package.
I discovered this when writing a pure pony tar library and needed
exactly the functionality of _os.
This commit changes `_os` from private to public as `os` and updates
its callers.
> Make FileMode._os public

- .release-notes/next-release.md
- CHANGELOG.md
- packages/files/_file_des.pony
- packages/files/directory.pony
- packages/files/file.pony
- packages/files/file_mode.pony
- packages/files/file_path.pony
Joe pointed out that the previous (not yet released change) that made
FileMode._os could be better. u32 is a more clear name. _os didn't
really matter as a name as it was private. With the functionality
becoming public we need the best name possible. u32() makes perfect
sense as the name as it is the filemode in a U32 representation.
> Rename FileMode.os to FileMode.u32

- .release-notes/3187.md
- packages/process/_process.pony
- packages/process/_test.pony
- packages/process/process_monitor.pony
- src/libponyrt/lang/process.c
In Windows we are closing the process handle when the process successfully exits. However, the wait timer in `ProcessMonitor` repeatedly calls wait on the child, even after it's exited.
This change makes `ProcessMonitor` and `_ProcessWindows` cache final values for the process exit status, so repeated calls to wait on the child will not be referencing an invalid handle.
This also fixes a combinatorial explosion of timers in `ProcessMonitor._wait_for_child()`.
> Clean up child process exits on Windows

- .cirrus.yml
- .release-notes/3816.md
- packages/net/_test.pony
- packages/net/ossocket.pony
- packages/net/tcp_connection.pony
- packages/net/tcp_listener.pony
- packages/process/_test.pony
- src/libponyrt/lang/socket.c
- src/libponyrt/platform/ponyassert.c
- src/libponyrt/sched/cpu.c
On Windows the `TCPConnection` code was not immediately unsubscribing to ASIO events when trying to shut down a connection. It was also not ever checking to see if all the relevant IOCP operations were complete, so in certain cases it would wait forever on the ASIO event and hang the program.  This change makes `TCPConnection` immediately unsubscribe. There may be some pending IOCP events left over but since we're shutting down we don't care about them reaching client code.
On Windows the recommended way to check the status of a connection is to use `SO_CONNECT_TIME` rather than `SO_ERROR`. Certain failing IOCP operations will not set `SO_ERROR`, so this changes `TCPClient._is_sock_connected()` to use `SO_CONNECT_TIME` on Windows.
Fixes a case in `TCPConnection._event_notify` where …
> Cleanup and fixes for Windows sockets

- .release-notes/3784.md
- src/libponyc/codegen/genopt.cc
Ticket #3784 tracked an issue related the MergeMessageSend optimization pass, which does Pony-specific optimizations within the LLVM optimizer pipeline.
It turned out that this pass was not written to handle the case of being run on a code block that contained sections of code that had already been optimized by this pass, and in such a case it failed an assertion error, crashing the compiler on such a program.
The fix was to disable running the pass on blocks in which we could detect signs of the optimization of that pass already being present.
Programs that were previously compiling okay should not see any difference in behavior or performance - the only programs that could potentially benefit from the skipped optimization were crashing, so there is no regression in their behavior. …
> Fix a compile-time crash related to Pony-specific optimizations.

- Makefile
uname -o isn't supported on MacOS, however, -s and works on all
platforms that we support via ponyup.
Closes #3832
> Fix make error on MacOS

- packages/process/_test.pony
This test was added on PR #3817, which was missed by PR #3819
since it wasn't rebased.
> Fix process test after RFC 70

- packages/collections/flag.pony
This was probably meant to be "underlying" and not "unlying".
> Fix typo in comments.

- src/ponyc/main.c
The strncat call is perfectly safe. It wasn't previously giving a warning
but as of gcc-11, that is no longer the case.
Closes #3806
> Silence gcc false positive

- .cirrus.yml
Makes debugging when there's no cache easier as if you get a failure
later, you'll have your newly build LLVM in the cache for the next run.
> Upload "libs" cache as soon as it is done populating

- Makefile
When debugging issues that happen on occassion, if you build the
tests via a command line like `make test-stdlib-debug` and it passes
the first time, you have to go through an entire rebuild and run again
waiting for a failure to have a binary that isn't removed. It can get
very annoying.
I am always removing these lines when testing. I don't think they are
necessary as they are placing items in the build/ directory which can
be tidied up with `make clean`.
> Don't remove test "binaries" after running tests

- .release-notes/3854.md
- src/libponyrt/gc/cycle.c
- src/libponyrt/sched/cpu.c
- src/libponyrt/sched/cpu.h
- src/libponyrt/sched/scheduler.c
This commit reworks tick usage to be safe with tick values that wrap around.
Most of our tick value sources will provide a monotonically increasing
value. However, our fallbacks, currently used on non Apple Arm CPUs
do not maintain the invariants.
They are implemented using clock_gettime and as such, wrap around fairly
regularly. They shouldn't wrap around quick enough that they are likely
to go around more than once.
This PR adds a "difference" function that will get the amount of ticks
between compared ticks. Within the runtime ticks are used to set
an amount of time to pause when there's no work to do and are used to
determine when to run the cycle detector.
Prior to this patch, on some Arm hardware, the cycle detector would end up running
very infrequently.
> Fix erratic cycle detector triggering on some Arm systems

- .release-notes/3860.md
- src/libponyc/codegen/genopt.cc
The code removed in this commit dates to the very first Arm 32 support
that Sylvan added. It appears during the elapsed years, that the bug
that was being worked around was fixed. The workaround is now itself
a source of odd behavior and crashes for me as I try to get `main`
working on a Raspberry Pi 4 running a 32-bit version of Raspbian.
With the code as it stands before this patch is applied, I get
crashes when running the standard library tests in debug mode. I
can reliably reproduce using the `serialise` tests but it was
also happening "randomly" with other tests as well.
After removing Sylvan's workaround, I have seen a total lack of the
issue.
Closes #3851
> Fix non-release build crashes on Arm

- src/libponyrt/actor/actor.c
The PR #3284  introduced a mechanism to track runtime memory use for
debugging purposes. However, when configured with the options provided there in, build now fails.
This commit fixes the minor  signature mismatch.
This is to fix #3862.
> Build failure fix when configured with `PONY_USE_MEMTRACK`

- packages/cli/_test.pony
The `ponycli/unknown_command` test is already before this one
> Rename repeated CLI test

- .release-notes/3871.md
- src/libponyrt/mem/pool.c
- src/libponyrt/sched/mpmcq.c
- src/libponyrt/sched/mpmcq.h
Within our pool and mpmcq implementations, we have code for handling
the ABA problem. The code is split into an X86 version and a "not X86"
version which at this time means "Arm".
The X86 version is heavily tested and works quite well. It has a theoretical
problem that needs to be addressed by deeper changes, but overall, it
is very solid.
The Arm code, on the other hand, isn't working properly. What exactly is wrong
isn't something that I've determined. What I can say is that when in use,
I am seeing issues with asserts being triggered related to scheduler muting
and memory pool usage. These asserts should only trigger if something is
very wrong.
The assert related problems felt like "an atomics issue" and really, like
a problem around the ABA code. I tested the changes in this PR on …
> Fix major source of runtime instability on non-x86 based platforms

- .release-notes/3875.md
- src/libponyc/codegen/host.cc
While getting pony working on 64-bit Arm, we found a bug where the
`test-stdlib-debug` tests would segfault. Everything worked fine with `release`
builds, but `debug` builds would crash.
After investigation, we've found that in `codegen_machine` in `host.cc` if the
`opt_level` is get to either `CodeGenOpt::Default` or `CodeGenOpt::Aggressive`
instead of `CodeGenOpt::None` the problem goes away.
It seems likely that this is an LLVM bug, but that hasn't been established.
We've committed a fix in `host.cc` that when the target is `arm` (which is
64-bit arm) that we use `CodeGenOpt::Default`. This is far from ideal, but gets
us working compilations until we can investigate further.
The end result of this should either be a patch that we upstream to LLVM or
possibly, the discovery that we are …
> Fix segfaults with debug mode code on 64-bit Arm

- .ci-dockerfiles/aarch64-unknown-linux-ubuntu20.04-builder/Dockerfile
- .ci-dockerfiles/aarch64-unknown-linux-ubuntu20.04-builder/build-and-push.bash
- .cirrus.yml
- .release-notes/3876.md
We have CI for 64-bit Arm via Graviton. We know that at least
on the 64-bit Raspberry Pi that there are still issues.
> Add 64-bit Arm (Graviton) as a supported platform

- .cirrus.yml
- Makefile
Runs message-ubench on 3 platforms making sure we don't get any
crashes. This can help verify that we don't have bugs that
have snuck past the shorter PR tests.
We run both release and debug versions of ubench to check for any
issues with either optimization level.
A debug version of the ponyc runtime is used so that we will trigger
any asserts if they are violated.
Currently the stress test is set to run for 30 minutes for each version.
> Add a nightly stress test CI job

- .release-notes/m1.md
- BUILD.md
- INSTALL.md
- test/libponyc/codegen.cc
Pony is now supported on Apple Silicon (M1 processors). Our support is "best effort" for now, since we currently lack continuous integration for Apple Silicon. Users on this platform will need to install Pony from source for the time being.
> Add Apple Silicon as a supported platform

- .cirrus.yml
We haven't found any value from testing the various different Linux
distributions. It might protect a breakage on a given distro before
it ends up as a failure of a nightly build, but in practice that
hasn't happened.
We now have good alerting on our nightly tasks failing so if it were
to happen, we should be alerted fairly quickly.
Areas where we have seen issues are now covered by these PR tests.
- glibs vs musl
- debug and release runtimes
As part of this PR, we are lowering the memory requested by each
PR task has history has shown that we don't ever use more than 5 gigs.
The 24 gigs we were requesting ended up being overkill.
> Reduce the number of x86 Linux PR tasks

- lib/CMakeLists.txt
This commit leaves FreeBSD at 1.10.00 because 1.11.0 isn't working
on FreeBSD.
> Update build time googletest dependency to 1.11.0

- .cirrus.yml
We don't need as much as we had set. This lower amount might help
us get machines more quickly as we need fewer resources.
> Lower stress test memory usage

- .cirrus.yml
Once we have a VM, let's not give it up after running release
and then wait for another to run debug. Based on how the
build system works, we don't need to segregate them by VM as the
build system already does that.
> Combine x86 Linux PR CI jobs from 4 to 2

- .cirrus.yml
Until this is proven working, the nightlies and releases will stay
on Big Sur. Given there is a ponyc release coming very soon, I
want to delay the nightlies and releases updates until after that release
is done.
> Switch macOS PRs to run against Monterey

- .cirrus.yml
Checking the history of our usage, we never use more than a little
over 3 gigs of memory. By setting our requested amount at 4, we
might be able to get additional concurrent VMs and complete the
release processes quicker.
> Lower requested RAM for Linux nightly and release builds

- .cirrus.yml
We haven't come very close to the 60 minute default, but it would
really suck to have a nightly or release fail because we ended up
with a long LLVM build.
> Set release CirrusCI tasks to have a 2 hour timeout

- lib/CMakeLists.txt
1.5.4 is unable to build with clang 13. Upgrading to 1.5.6 should
address that issue.
We still can't update FreeBSD as 1.5.3 continues to be the last
version that builds on it.
> Update Google benchmark dependency

- .cirrus.yml
Everything has been fine for a couple days with building the nightlies
on Monterey, so I feel good about making this change.
> Build macOS releases on Monterey

- packages/files/files.pony
The `FilePath.create` constructor is no longer partial
> Update files package documentation after RFC 70

- .release-notes/clock_uptime_raw.md
- packages/time/time.pony
Previously, we were using `mach_absolute_time` on macOS to get the number of ticks since boot, with the assumption that ticks increment at nanosecond intervals. However, as noted by [Apple](https://developer.apple.com/documentation/apple-silicon/addressing-architectural-differences-in-your-macos-code#Apply-Timebase-Information-to-Mach-Absolute-Time-Values), this assumption is flawed on Apple Silicon, and will also affect any binaries that were built on Intel, as the Rosetta 2 translator will not apply any time conversion.
The recommended replacement to `mach_absolute_time` is to use `clock_gettime_nsec_np` with a clock of type `CLOCK_UPTIME_RAW`.
Joe already applied this fix to `cpu.c` on 197b952d3d753a15a088d9a1bb9043295d588280, but we missed the call to `mach_absolute_time` on …
> Fix underlying time source for Time.nanos() on macOS

- .release-notes/fix_cli.md
- packages/cli/_test.pony
- packages/cli/command_parser.pony
The current command parser in the `cli` package cuts option arguments of `String` type at the first equal sign. This release fixes the problem for long options (`--option=foo=bar`) and for short options such as `-O=foo=bar`. Short options such as `-Ofoo=bar` will continue to raise an "ambiguous args" error.
The code below shows the bug, with the option argument being cut short at the first equal sign. The code below prints "foo" instead of the complete value, "foo=bar". The same is true when uses the short version of the option, like `-t=foo=bar`.
```pony
use "cli"
actor Main
try
let cs =
CommandSpec.leaf("simple", "", [
OptionSpec.string("test" where short' = 't')
])?
let args: Array[String] = [
"ignored"; "--test=foo=bar"
]
let cmdErr = …
```
> Fix `cli` package from mangling option arguments with equal signs

- .release-notes/3933.md
- src/libponyc/expr/call.c
- src/libponyc/expr/ffi.c
- src/libponyc/expr/lambda.c
- src/libponyc/type/subtype.c
- test/libponyc/badpony.cc
- test/libponyc/recover.cc
A few subtyping errors were technically incorrect, or unnecessarily obtuse. This improves the wording to better clarify the meaning of these.
Fixes #3929 and #3928
> Clarify wording for some subtyping errors

- src/libponyc/type/subtype.c
A multi-line string in #3933 was missing a space that would have to be inserted between two sentences
> Fix a small typo with PR #3933

- .release-notes/3949.md
- CMakeLists.txt
- Makefile
- lib/CMakeLists.txt
- Adds a Makefile variable `pic_flag` that you can set to either `-fpic` or `-fPIC` for both `make libs` and `make configure`
- ~~On `aarch64`, the variable will default to `-fPIC` for `make libs` and `make configure` (see #3870); on other Unix architectures it will be set to `-fpic`~~.
- Fixes #3870
> Fix inability to fully build pony on Raspberry PI 4's with 64-bit Raspbian

- .release-notes/3880.md
- BUILD.md
> Add build instructions for 64-bit Raspbian

- .release-notes/hide_actor_pad_size.md
- src/libponyc/codegen/codegen.c
- src/libponyrt/actor/actor.h
- src/libponyrt/pony.h
Previously, in the `pony.h` header that exposes the "public API" of the Pony runtime, information about the size of an actor struct was published as public information.
This change removes that from the public header into a private header, to hide
implementation details that may be subject to change in future versions of the Pony runtime.
This change does not impact Pony programs - only C programs using the `pony.h` header to use the Pony runtime in some other way than inside of a Pony program, or to create custom actors written in C.
---
This commit moves the `PONY_ACTOR_PAD_SIZE` preprocessor value and `pony_actor_pad_t` struct into `actor.h`.
> Hide C header implementation details related to actor pad size.

- .release-notes/bye-simplebuiltin.md
- src/libponyc/options/options.c
- src/libponyc/pass/pass.h
- src/libponyc/pkg/package.c
The ponyc option `simplebuiltin` was never useful to users but had been exposed
for testing purposes for Pony developers. We've removed the need for the
"simplebuiltin" package for testing and have remove both it and the compiler
option.
Technically, this is a breaking change, but no end-users should be impacted.
> Remove simplebuiltin compiler option

- src/libponyc/codegen/genprim.c
in order to get all the possible information out of the cpuid instructions.
Previously it has only been used in time.pony for performance measurements to
avoid reordering of instructions together with RDTSCP. Now it can be used to detect CPU features.
Example of the current behaviour prior to this PR:
```pony
use @"internal.x86.cpuid"[(I32, I32, I32, I32)](eax: I32)
actor Main
(let a1, let b1, let c1, let d1) = @"internal.x86.cpuid"(I32(0))
(let a2, let b2, let c2, let d2) = @"internal.x86.cpuid"(I32(1))
env.out.print("a1 == a2 -> " + (a1 == a2).string())
env.out.print("b1 == b2 -> " + (b1 == b2).string())
env.out.print("c1 == c2 -> " + (c1 == c2).string())
env.out.print("d1 == d2 -> " + (d1 == d2).string())
```
According to https://en.wikipedia.org/wiki/CPUID …
> Actually pass arg to internal.x86.cpuid

- src/libponyrt/platform/threads.c
Tested in pop! OS 21.10 with kernel 5.15. The `rlim_t` type has been changed to `unsigned long int`, it seems.
Let's see if CI with an older kernel reports breakage.
> Fix compilation issue with clang 13 / gcc 11 on linux 5.15

- .release-notes/3973.md
- CHANGELOG.md
- packages/builtin/asio_event.pony
- packages/builtin/stdin.pony
- packages/net/tcp_connection.pony
- packages/net/tcp_listener.pony
- packages/net/udp_socket.pony
- packages/process/process_monitor.pony
- packages/signals/signal_handler.pony
- packages/time/timers.pony
- src/libponyc/pass/verify.c
- src/libponyc/verify/type.c
- src/libponyc/verify/type.h
- test/libponyc/badpony.cc
When Pony allowed interfaces to have private methods, it was possible to use an interface to break encapsulation for objects and access private methods from outside their enclosing package.
The following code used to be legal Pony code but will now fail with a compiler error:
```pony
actor Main
let x: String ref = "sailor".string()
let y: Foo = x
y._set(0, 'f')
env.out.print("Hello, " + x)
interface Foo
fun ref _set(i: USize, value: U8): U8
```
`AsioEventNotify` in the standard library had to be changed from an interface with a single private method to a trait in order to conform with this change.
Fixes #2772
> Don't allow interfaces to have private methods

- packages/net/_test.pony
They aren't providing any value at the moment as we assume all
failures are the flakiness. We can turn them back on when we
figure out why they fail in CI (and fix).
So far, we can't find a reason and we can't get it to happen locally.
> Turn off flakey Windows network tests

- .release-notes/3823.md
- src/libponyc/expr/operator.c
- test/libponyc/badpony.cc
Builds upon @mateus-md work on #3894, fixes #3823.
When this is squashed and merged, the commit message should be "Fix compiler assertion failure when assigning error to a variable"
> Fix compiler assertion failure when assigning error to a variable

- .release-notes/nodoc.md
- CHANGELOG.md
- packages/buffered/_test.pony
- packages/builtin_test/_test.pony
- packages/builtin_test/_test_valtrace.pony
- packages/bureaucracy/_test.pony
- packages/cli/_test.pony
- packages/collections/_test.pony
- packages/collections/persistent/_test.pony
- packages/encode/base64/_test.pony
- packages/files/_test.pony
- packages/format/_test.pony
- packages/ini/_test.pony
- packages/itertools/_test.pony
- packages/json/_test.pony
- packages/logger/_test.pony
- packages/math/_test.pony
- packages/net/_test.pony
- packages/process/_test.pony
- packages/promises/_test.pony
- packages/random/_test.pony
- packages/serialise/_test.pony
- packages/signals/_test.pony
- packages/stdlib/_test.pony
- packages/strings/_test.pony
- packages/time/_test.pony
- src/libponyc/pass/docgen.c
- src/libponyc/pass/syntax.c
The can be used to control the pony compilers documentation generation,
any structure that can have a docstring (except packages) can be
annotated with \nodoc\ to prevent documentation from being generated.
This replaces a hack I put in years ago to filter out items that
were "for testing" by looking for Test and _Test at the beginning of
the name as well as providing UnitTest or TestList.
All standard library test items have been annotated with \nodoc\ to
keep them continuing to not have documentation generated by our
standard process of creating the standard library documentation site.
ponylang org libraries will need to be updated as well.
Note that the "should we include this package" hack to filter out
packages called "test" and "builtin_test" still exists for the time
being until we …
> Add "nodoc" annotation

- .release-notes/3984.md
- packages/runtime_info/auth.pony
- packages/runtime_info/runtime_info.pony
- packages/runtime_info/scheduler.pony
- src/libponyrt/sched/scheduler.c
- src/libponyrt/sched/scheduler.h
Previously, when users wanted to optimize the parallelizing work based on the maximum number of actors that can be run at a single time, we were pointing them to using the private runtime method `@ponyint_sched_cores()`.
This was problematic for two reasons:
1. We were pointing users at an internal implementation method that we hadn't promised not to change.
2. We were requiring users to muck about with FFI for something that has become somewhat common for users wanting to maximize performance want to know.
We've now exposed some information about scheduler threads via a new package `runtime_info` thereby resolving both of the problems mentioned above.
Pony users should expect to see additional information added to the `runtime_info` package moving forward.
Anyone who was using the …
> Add a pony primitive that exposes scheduler information

- src/libponyrt/sched/cpu.c
- src/libponyrt/sched/cpu.h
- src/libponyrt/sched/scheduler.c
We were doing extra work in `ponyint_cpu_core_pause` that wasn't used
when we weren't going to yield.
This commit switches to only call `ponyint_cpu_core_pause` if use_yield
is true thereby simplifying `ponyint_cpu_core_pause` and not doing
extra work like calling `ponyint_cpu_tick_diff`.
Closes #3986
> Refactor how ponyint_cpu_core_pause is called

- packages/files/files.pony
The example program in the "files" package would not compile because
there was an unnecessary `try` block. This is fixed so that users will
have a working example of how to use the package.
> Fix package-level example in "files"

- src/libponyrt/gc/gc.c
I was storing the type for the wrong object into the object map
in acquire_object. This led to ponyup going boom.
Other programs would as well, but ponyup exhibited.
I'm going to spend some time thinking about how to test this, but
at the moment I don't know the specific combo of Pony code that
got us here.
> Fix bug in #3993

- .release-notes/simplify_stdin_read.md
- packages/builtin/stdin.pony
- src/libponyrt/lang/stdfd.c
The signature of the `pony_os_stdin_read` function has been simplified to remove the `bool* out_again` parameter.
```diff
-PONY_API size_t pony_os_stdin_read(char* buffer, size_t space, bool* out_again)
+PONY_API size_t pony_os_stdin_read(char* buffer, size_t space)
```
It is permitted to call the `pony_os_stdin_read` function again in a loop if the return value is greater than zero, and the platform is not windows. Given that those two conditions are enough information to make a decision, the `out_again` parameter is not needed, and can be removed.
Technically this is a breaking change, because the function is prefixed with `pony_` and is thus a public API. But it is unlikely that any code out there is directly using the `pony_os_stdin_read` function, apart from the `Stdin` actor in the …
> Remove out parameter from `pony_os_stdin_read`

- .release-notes/3988.md
- packages/runtime_info/scheduler.pony
- src/libponyrt/sched/scheduler.c
Adds three additional functions to `SchedulerInfo`. Based on the current state of information available from the runtime, this is pretty much all we would want to expose about the scheduler system at this time.
> Expose additional scheduler info via the runtime_info package

- make.ps1
- Use `HEAD` for development version hashes instead of `HEAD^`
- Make `build` the default build action for `make.ps1`
> Windows build script tweaks

- .cirrus.yml
They are failing fairly regularly and we need to look into why some on the runner tests hang. 
Gordon think that it might be related to other Windows failures we've seen lately (which I think are corral related).
Gordon suspects that all the issues might be tied together by an unknown issue in the Windows Process Monitor code.
> Turn off running debug build Windows tests

- .release-notes/3953.md
- packages/builtin/array.pony
- src/libponyc/expr/array.c
- src/libponyc/expr/call.c
- src/libponyc/expr/control.c
- src/libponyc/expr/lambda.c
- src/libponyc/expr/operator.c
- src/libponyc/expr/reference.c
- src/libponyc/pass/flatten.c
- src/libponyc/pass/verify.c
- src/libponyc/type/alias.c
- src/libponyc/type/cap.c
- src/libponyc/type/cap.h
- src/libponyc/type/viewpoint.c
- src/libponyc/verify/fun.c
- test/libponyc/CMakeLists.txt
- test/libponyc/cap.cc
- test/libponyc/stable_type.cc
This PR introduces checks around variables and other unaliasing points, to reject programs which attempt to create variables whose capabilities are inherently unsound. The checks about comptability of intersections have been moved to this check after investigation of the origin, as it is not needed for soundness, but this can be reinstated in the original location if helpful for engineering purposes.
Fixes #3931
Some generic code may still produce unsoundness after instantiating, but this change is hopefully a step-forwarding to introducing the necessary constraints.
> Ban variables whose capability is unsound to alias

- .release-notes/3991.md
- packages/promises/promise.pony
- test/libponyc-run/promise-flatten-next-regression-3856/main.pony
This fixes #3856 with only a workaround and explicitly without actually solving the underlying issue, but hey, it's something.
Somehow the replaced lambda, or to be exact, the hygienic type created for it, wasn't properly reified and remained as a generic type. The hygienic type generates was:
```
promises_$2$7_String_val_String_val
```
which seems correct, but this is the type that failed the reachability, namely the part where the methods from the interface `Fulfill` have been applied to the type:
```
type: {(A): Promise[B #share] tag}[String val, String val] ref
```
> Add workaround for compiler assertion failure in Promise.flatten_next

- .release-notes/issue-3616.md
- src/libponyc/CMakeLists.txt
- src/libponyc/pass/completeness.c
- src/libponyc/pass/completeness.h
- src/libponyc/pass/pass.c
- src/libponyc/pass/pass.h
- src/libponyc/pass/refer.c
- src/libponyc/verify/fun.c
- src/libponyc/verify/fun.h
- test/libponyc-run/regression-3615/main.pony
Previously, exhaustive matches were handled after we verified that an object's fields
were initialized. This lead to the code such as the following not passing compiler
checks:
```pony
primitive Foo
fun apply() : (U32 | None) => 1
type Bar is (U32 | None)
actor Main
let bar : Bar
new create(env : Env) =>
match Foo()
| let result : U32 =>
bar = result
| None =>
bar = 0
end
```
This commit moves field initialization checking to the verify pass so that it
comes after the expression pass when exhaustiveness checking is done. This also
moves code to patchup matches from the refer pass to a new completeness pass
that comes after the expression pass. The new `completeness_match` code is
identical to `refer_match` code except that an else clause with a value of
`TK_NONE` no longer means a clause …
> Take exhaustive match into account when checking for field initialization

- .release-notes/fix-3655.md
- src/libponyc/pass/flatten.c
- test/libponyc/flatten.cc
Tuple types aren't legal constraints on generics in Pony and we have a check in
the syntax pass to detect and report that error. However, it was previously
possible to sneak a tuple type as a generic constraint past the syntax check by
smuggling it in a type alias.
Type aliases aren't flattened into their various components until the flatten
pass which follows the syntax pass. This means that the following code would
cause a compiler assertion:
```ponyc
type Blocksize is (U8, U32)
class Block[T: Blocksize]
```
This commit adds an additional check in the flatten pass to report an error on
smuggled tuple types as generic constraints.
Fixes #3655
> Fix compiler crash related to using tuples as a generic constraint

- .release-notes/lcm.md
- packages/math/_test.pony
- packages/math/greatest_common_divisor.pony
- packages/math/least_common_multiple.pony
Adds code for determining least common multiple and greatest common divisor to the standard library math package.
> Add LeastCommonMultiple and GreatestCommonDivisor to math package

- .release-notes/while-else-initialize.md
- src/libponyc/pass/refer.c
- test/libponyc-run/while-else-can-initialize-fields/main.pony
- test/libponyc/refer.cc
Previously, due to a bug in the compile's while/else handling code, the
following code would be rejected as not initializing all object fields:
```pony
actor Main
var _s: (String | None)
var i: USize = 0
while i < 5 do
_s = i.string()
i = i + 1
else
_s = ""
end
```
This commit fixes while/else handling in `refer_while` so that it matches the
correct logic as seen in `refer_if`.
Partially addresses a series of related bugs in #3283.
> Fix incorrect "field not initialized" error with while/else

- .release-notes/tuples-in-unions-constraint.md
- src/libponyc/pass/flatten.c
- test/libponyc/flatten.cc
Tuple types aren't legal constraints on generics in Pony and we have a check in
an early compiler pass to detect and report that error. However, it was
previously possible to "sneak" a tuple type as a generic constraint past the
earlier check in the compiler by "smuggling" it in a type union in a type
alias.
The type aliases aren't flattened into their various components until after the
code that disallows tuples as generic constraints which would result in the
following code causing ponyc to assert:
```ponyc
type Blocksize is (U64 | (U8, U32))
class Block[T: Blocksize]
```
We've added an additional check to the compiler in a later pass to report an
error on the "smuggled" tuple type as a constraint.
Fixes #4016
> Fix compiler crash related to using tuples in a union as a generic constraint

- .release-notes/4022.md
- packages/term/ansi.pony
The `erase` function states that it erases to the left of the cursor, but the escape code it returns uses the value for erasing to the right of the cursor.
```pony
fun erase(): String =>
"""
Erases everything to the left of the cursor on the line the cursor is on.
"""
"\x1B[0K"
```
Fixes #4021
> Fix incorrect code returned by ANSI.erase

- .release-notes/4026.md
- packages/itertools/iter.pony
This fixes a small stdlib issue discovered during: https://github.com/ponylang/ponyc/pull/4018
The signatures for map and map_stateful in itertools were overly strict, requiring `B^` instead of just `B`, but only returned `Iter[B]`. Thus it had to be instantiated with `iso^` in some cases, exercising a bug with double ephemerals.
This is not a breaking change.
> Fix the signature of Iter's map_stateful/map to not require ephemerals

- .release-notes/fix_llvm_call_receiver_type_cast.md
- src/libponyc/codegen/gencall.c
> Fix LLVM IR verification error found via PonyCheck

- packages/process/_test.pony
There's no need to call `complete` on timeout. See PonyTest docs
on long tests for more information.
> Remove unneeded `timeout` methods from ProcessMonitor tests

- .release-notes/pm-init-error.md
- packages/process/_process.pony
- packages/process/process_monitor.pony
- packages/process/process_notify.pony
Previously, when a process failed to start up, it was possible to get a report
that the process had started up and exited with the error code 0 which
normally signals success.
The problem comes from some rather poor state handling in the `process` package.
This commit doesn't fix the larger issue of all kinds of weirdness around state
handling but it does address the specific bug that was most likely to be
triggered in our unit tests.
The flow in its most extreme form was:
- ProcessMonitor is created in test runner
- Long test is setup
- Dispose when done is setup to send dispose to ProcessMonitor
- ProcessMonitor never successfully starts a Process so its child is _ProcessNone
- notify gets called with `failed`
- `dispose` is sent to the ProcessMonitor
- ProcessMonitor extracts exit code …
> Fix failed initialization bug in Process Monitor

- .dockerfiles/latest/x86-64-pc-windows-msvc/Dockerfile
- .dockerfiles/release/x86-64-pc-windows-msvc/Dockerfile
- .release-notes/windows-images.md
GitHub has updated from 2019 to 2022, so we are doing the same
as you can't have differing versions.
> Update Windows version used as the base for Windows images

- .release-notes/3953.md
- packages/builtin/array.pony
- src/libponyc/expr/array.c
- src/libponyc/expr/call.c
- src/libponyc/expr/control.c
- src/libponyc/expr/lambda.c
- src/libponyc/expr/operator.c
- src/libponyc/expr/reference.c
- src/libponyc/pass/flatten.c
- src/libponyc/pass/verify.c
- src/libponyc/type/alias.c
- src/libponyc/type/alias.h
- src/libponyc/type/cap.c
- src/libponyc/type/cap.h
- src/libponyc/type/reify.c
- src/libponyc/type/subtype.c
- src/libponyc/type/viewpoint.c
- src/libponyc/verify/fun.c
- test/libponyc/CMakeLists.txt
- test/libponyc/cap.cc
- test/libponyc/matchtype.cc
- test/libponyc/stable_type.cc
- test/libponyc/type_check_subtype.cc
This PR introduces checks around variables and other unaliasing points, to reject programs which attempt to create variables whose capabilities are inherently unsound. The checks about compatibility of intersections have been moved to this check after investigation of the origin, as it is not needed for soundness, but this can be reinstated in the original location if helpful for engineering purposes.
Fixes https://github.com/ponylang/ponyc/issues/3931
Some generic code may still produce unsoundness after instantiating, but this change is hopefully a step-forwarding to introducing the necessary constraints.
> Ban unstable variables

- .release-notes/3447.md
- src/libponyc/codegen/genmatch.c
- test/libponyc-run/regression-3447/main.pony
We previously had a compiler crash caused by trying to jump to a
next block in a match that might not exist because it had been
removed from the particular reification of a generic.
Fixes #3447
> Fix crash with exhaustive match and generics

- .github/workflows/cloudsmith-package-sychronised.yml
- .github/workflows/pr.yml
Sadly, Windows containers need to use the same environment as the
host OS. This means that we want to control which Windows version
is being used in our actions so we can control the upgrade.
> Use a fixed Windows version for GitHub actions

- .release-notes/4054.md
- src/libponyc/pass/sugar.c
- test/libponyc/sugar.cc
In 2018, when we [removed case functions](https://github.com/ponylang/ponyc/pull/2542) from Pony, we also removed the checking to make sure that parameters names were valid.
We've added checking of parameter names to make sure they match the naming rules for parameters in Pony.
Fixes #4054
> Fix parameter names not being checked

- packages/itertools/iter.pony
This PR changes the heading types for all Examples in the `itertools/iter.pony` file to be `<h4>` instead of `<h2>`
Previously, `## Example` got translated to `<h2>Example</h2>`, which was problematic for two reasons:
1. The method itself has a lesser heading (`<h3>`)
2. `<h2>` is visible in the Table of Contents
`<h4>` still has an anchor link, and is no longer visible in the ToC, see screenshot of local mkdocs instance after making the change:
Thanks!
> Example heading in itertools package should be h4

- .release-notes/4059.md
- src/libponyc/codegen/genopt.cc
- test/libponyc-run/regression-4059/main.pony
This is a good one. One the March 22, 2022 development sync,
we collectively debugged issue #4059. We finally arrived at
the conclusion that our call graph usage was incorrect.
Originally during the call, Joe realized that while we were
using, we weren't doing it correctly. The initial assumption
was that the incorrect usage was innocous, however, it was
determined shortly thereafter that something about the incorrect
usage was in fact causing issue 4059.
This commit removes the offending code.
Gordon reported during the call that when the call graph code
was added as part the (now years ago) addition of LLVM 4 support
that the code was cribbed from the Dlang compiler and he posited,
probably not correctly.
Fixes #4059
> Fix compiler crash in HeapToStack optimization pass

- src/libponyc/codegen/gentype.c
- src/libponyc/codegen/host.cc
Several years ago, Benoit added code to work around LLVM's lack
of support for properly functioning infinite loops.
LLVM added support for infinite loops.
With this commit, we are removing Benoit's temporary fix.
> Remove infinite loop workaround

- .release-notes/fix_3997.md
- packages/files/_test.pony
- src/libponyc/pass/syntax.c
- test/libponyc/badpony.cc
Fixes #3997, but not sure if this should have the "changed" or "fixed" label.
> Don't allow FFI calls in default methods or behaviors

- src/libponyrt/actor/actor.c
This reverts commit bc927a619a139cd1270a723613652b4506005ae1.
When I identified the edge case, I forgot that when an actor gets
muted, it returns without marking its queue as empty and therefore,
won't be seen as being empty if another actor sends a message to it
even if there aren't actually messages in queue.
The error that causes the assertion failure that led me to doing the
original commit is probably the same that is causing #4069 and when
that is fixed, the assertion for a muted actor being run will also
be fixed.
Closes #4076
> Revert "Fix issue that could lead to a muted actor being run (#3974)"

- .cirrus.yml
- Makefile
This commit adds nightly stress tests that run with the cycle
detector active.
> Add to nightly stress tests

- src/libponyc/pass/syntax.c
- test/libponyc-run/ffi-call-in-initializer/additional.c
- test/libponyc-run/ffi-call-in-initializer/main.pony
Fixes #4086, forgot to check the case where the call happens outside of a method
> Fix compiler assertion on FFI call

- Makefile
- make.ps1
- test/libponyc-run/runner/_coordinator.pony
Not all bugs are seen in release mode. Some require debug mode to
be observed. There are regression tests for example that only happen
in one mode or the other.
> Add running our full pony program tests in debug mode

- packages/backpressure/backpressure.pony
- packages/net/tcp_connection.pony
* Rewriting so they don't pass AmbientAuth, but instead the
appropriate type.
* Some examples passed the OutStream interface instead of the
concrete type StdStream which breaks the example.  Just uses
concrete type StdStream right the way through now.
> Corrected a few of the examples in the documentation.

- packages/debug/debug.pony
- packages/net/tcp_listener.pony
- packages/net/udp_socket.pony
* debug/debug.pony: Missing "use \"debug\"" in the example.
* net/tcp_listener.pony and net/udp_socket.pony: try…end blocks
are no longer required.
(Note - no corrections were needed for debug in the end as the example wasn't designed to compile)
> Corrections to examples in documentaton for debug and net

- packages/collections/list_node.pony
- packages/pony_bench/pony_bench.pony
- packages/pony_check/property_unit_test.pony
- packages/process/process.pony
* collections/list_node.pony - Incorrect single quotes to complete an
example.
* pony_bench/pony_bench.pony - Added use "pony_bench" to the example.
* pony_check/property_unit_test.pony - Corrected typo in call to
Generators primitive in the example.
* process/process.pony - Added missing use "backpressure" to example.
> Corrections to examples in documentation:

- .release-notes/fix_windows_iocp_memtrack.md
- src/libponyrt/asio/event.c
When the runtime is compiled with `-DUSE_MEMTRACK_MESSAGES` on
Windows, the code path for asynchronous I/O events wasn't
initializing the pony context prior to its first use,
which would likely cause a runtime crash or other undesirable
behavior.
The `-DUSE_MEMTRACK_MESSAGES` feature is rarely used, and has
perhaps never been used on Windows, so that explains why
we haven't had a crash reported for this code path.
Now that path has been fixed by rearranging the order of the code.
---
See [this Zulip thread](https://ponylang.zulipchat.com/#narrow/stream/190365-runtime/topic/pony_register_thread.20in.20windows.20ASIO/near/278501067) for additional discussion.
> Fix a runtime fault for Windows IOCP w/ memtrack messages.

- .ci-dockerfiles/x86-64-unknown-linux-ubuntu22.04-builder/Dockerfile
- .ci-dockerfiles/x86-64-unknown-linux-ubuntu22.04-builder/build-and-push.bash
- .cirrus.yml
- .release-notes/4062.md
- INSTALL.md
- RELEASE_PROCESS.md
> Add prebuilt ponyc releases for Ubuntu 22.04

- packages/buffered/reader.pony
- packages/builtin/array.pony
- packages/builtin/string.pony
- packages/cli/command.pony
- packages/cli/command_help.pony
- packages/cli/command_parser.pony
- packages/pony_bench/benchmark.pony
Pretty much all of the standard library leaves the optional `box`
out. These few didn't and have been changed to match the normal
pattern in the standard library.
> Remove unneeded extra `box` in `fun box` definitions

- .dockerfiles/latest/x86-64-unknown-linux-gnu/Dockerfile
- .dockerfiles/release/x86-64-unknown-linux-gnu/Dockerfile
- .github/workflows/cloudsmith-package-sychronised.yml
- .release-notes/4098.md
> Update base image for glibc Linux docker images

- src/common/pony/detail/atomics.h
- src/libponyrt/platform/ponyassert.c
While working on cross-compiling the runtime from Linux to Windows,
I ran into this issue which was causing clang to fail with:
```
src/libponyrt/platform/ponyassert.c:19:26: error: copying variable of type 'std::atomic<bool>' invokes deleted constructor
static PONY_ATOMIC(bool) assert_guard = false;
^              ~~~~~
/tmp/xwin/crt/include/atomic:2276:5: note: 'atomic' has been explicitly marked deleted here
atomic(const atomic&) = delete;
^
```
Apparently the correct way to initialize a `std::atomic` is with
an initializer list, as described in this blog post:
https://onetwobytes.wordpress.com/2021/02/24/std-atomic-defaults/
However, we don't actually use `std::atomic` on all platforms,
and the platforms that don't use it need to keep using the `=` syntax.
So the initializer needs to …
> Fix initialization of an atomic variable in `ponyassert.c`.

- src/libponyrt/CMakeLists.txt
This change contains some small fixes that make it possible to
further tweak the way the runtime bitcode is compiled, making
it possible to do things relating to cross-compilation.
- We remove the `-std=gnu11` flag, which is not actually necessary
on native Linux and breaks when trying to cross-compile to Windows.
- We respect whatever `CFLAGS` are set by adding `CMAKE_C_FLAGS`
into the clang invocation (which we must convert to a list first).
---
Note that after this change, it is possible to cross-compile
the runtime bitcode for a Windows target from a Linux host,
provided that the Linux host has obtained a copy of the Windows headers,
which can be done conveniently on non-Windows platforms using
[`xwin`](https://github.com/Jake-Shadle/xwin).
The commands for doing so (assuming the …
> Small fixes to CMake code for cross-compiling runtime bitcode.

- src/libponyc/platform/vcvars.c
Gordon originally added this gating. He stated that he believed that
it fixed a link error. However, the link error possibility is addressed
via CMake and $<$<CONFIG:Debug>:/MD> as a compilation option.
> Remove unneeded debug gating in find_kernel32

- src/libponyc/ast/ast.c
- src/libponyc/ast/token.c
`frozen` is only available on ast and token if PONY_NDEBUG isn't defined.
However, it was used in two functions regardless of the value of PONY_NDEBUG.
This isn't caught in CI as we currently use PONY_ALWAYS_ASSERT which means that
PONY_NDEBUG isn't on for any of our CI (or any other builds).
> Fix compilation error with PONY_NDEBUG

- Makefile
- make.ps1
The maximum number of tests running at once are capped to the number of physical processors.
> Make the full-program tests run in parallel

- .release-notes/fix_runtime_program_termination_assert.md
- src/libponyrt/actor/actor.c
- src/libponyrt/actor/messageq.c
- src/libponyrt/actor/messageq.h
- src/libponyrt/asio/epoll.c
- src/libponyrt/asio/iocp.c
- src/libponyrt/asio/kqueue.c
- src/libponyrt/sched/scheduler.c
When shutting down the ASIO thread and destroying its message queue,
it is possible that there may be some message(s) in flight to it,
meaning that even though we drained the queue before destroying,
the queue may be non-empty by the time we get to destroying it.
Hence, we cannot reliably assert that the queue is non-empty.
However, for actors, we can proved definitively that an actor
is done receiving messages before we destroy its message queue,
so we want to retain the runtime assert for the actor case.
This change updates the assert to be conditional based on
a boolean parameter to the `ponyint_messageq_destroy` function.
For more context, see [this Zulip thread](https://ponylang.zulipchat.com/#narrow/stream/190365-runtime/topic/ponyint_messageq_destroy.20assert.20fail).
> Disable incorrect runtime assert for ASIO thread shutdown.

- packages/builtin/array.pony
Over on [Zulip](https://ponylang.zulipchat.com/#narrow/stream/316480-standard-library/topic/Array.20from_cpointer.20vs.20reserve.20.26.20other.20methods.20that.20reserve), Adrian raised a potential issue when using `Array.from_cpointer` that is not covered in the documentation.
When creating an array from a pointer to non-managed memory, we create a situation where any operations on the array that might trigger a reallocation are unsafe. This is because the runtime assumes that a Pony array is always pointing to memory that was previously allocated by calling `pony_alloc`. Although a debug runtime will abort when reallocating, performing a realocation on a release runtime will most probably lead to a segfault at runtime.
The note about calling `from_cpointer` from non-managed memory is …
> Update Array.from_cpointer documentation

- .cirrus.yml
- Makefile
This doesn't hit us on CI since we install the `coreutils` package, which
installs `nproc` for us. If that isn't installed, however, this line will fail.
The appropriate substitute is the same as for FreeBSD.
> Use hw.ncpu on macOS instead of nproc

- .release-notes/4132.md
- packages/builtin/string.pony
- packages/builtin_test/_test.pony
These methods rely on strof/strod, which require null-terminated strings. We
were passing our pointer to C without first checking if our string was
null-terminated, which means that C would be able to read past our memory
allocation.
This fixes #1445
> Fix String.f32 and String.f64 errors with non null terminated strings

- src/libponyrt/actor/actor.c
- src/libponyrt/actor/actor.h
- src/libponyrt/sched/scheduler.c
`actor->muted` is only ever referenced from a single scheduler thread.
Either while a scheduler is running an actor or if an actor is muted
and in the scheduler's mutemap.
This commit changes `actor->muted` from being an atomic size_t to being a
regular old size_t.
> Change `actor->muted` to no longer be atomic

- .release-notes/4127.md
- packages/collections/_test.pony
- packages/collections/range.pony
The `has_next()` function in `Range` relies entirely on the variable `_forward` to decide whether or not another iteration exists. However, `_forward` is too narrowly defined to properly cover some or some `_infinite == true` cases. Currently some cases of `step` being 0 or NaN depending on `min > or < max` were broken (ie. not infinite)
> Fix for infinite Ranges

- .ci-dockerfiles/x86-64-unknown-linux-musl-builder/Dockerfile
- .cirrus.yml
We were using 3.12 which reached end of life on May 1st of this year.
This gets up to using the newest alpine release that will be supported
until May of 2024.
If this all passes CI and stress tests run as usual, I'll open a
PR to update the user facing Alpine based images.
> Upgrade Alpine version used for CI to 3.16

- src/libponyrt/actor/actor.c
- src/libponyrt/actor/actor.h
`actor->is_muted` is a `uint8_t` but it is always treated as a `boolean`.
It is also always only modified from a single scheduler thread (either to mute
or unmute the actor) but read from other scheduler threads.
This PR removes `actor->is_muted`, splits `actor->flags` into `actor->sync_flags`
and `actor->internal_flags` and adds a new sync flag called `FLAG_MUTED`.
The logic in `ponyint_is_muted`, `ponyint_mute_actor` and `ponyint_unmute_actor`
has been updated to use this new flag. Additionally, the sync flag read/modify
logic has been updated to use acquire/release semantics instead of relaxed
semantics so that it will work correctly on weakly ordered architectures (i.e. arm).
This preserves the existing behavior and makes sure all flags that are used from
multiple scheduler threads …
> Remove `actor->is_muted` and replace with a flag

- src/libponyrt/actor/actor.c
- src/libponyrt/actor/actor.h
The `actor` module currently exports a number of backpressure related
functions that are not actually used outside of `actor.c`. It also
exposes the `FLAG_*`/`SYNC_FLAG_*` enums that are not longer used
anywhere but `actor.c`.
This commit removes the unused exported functions from `actor.h` and
changes their definitions (and names) in `actor.c` to make them into
`static` functions. It also moves the two flag enums from `actor.h`
to `actor.c`.
Full list of changes:
* made `has_internal_flag` into a `static` function in `actor.c`
* renamed function `maybe_mute` to `maybe_should_mute` in `actor.c`
* removed the following declarations from `actor.h` because they are
not used by anything except `actor.c`:
* `ponyint_actor_setoverloaded`
* `ponyint_actor_unsetoverloaded`
* `ponyint_maybe_mute` …
> Hide backpressure related functions in `actor` module

- .release-notes/4143.md
- src/libponyrt/mem/heap.c
- src/libponyrt/mem/heap.h
Prior to this commit, at the start of GC, the heap clears all
`chunks` by setting them all to `empty` in `ponyint_heap_startgc`.
This is an expensive operation as it requires visiting all
`chunks` and updating their `chunk->slots` and `chunk->shallow`
values regardless of whether they are still in use or not.
`chunk->shallow` is only ever used as part of the GC process.
The old logic for heap GC was:
* mark all slots in all chunks as empty so they can all be freed by GC (`clear chunks`)
* recursively trace all roots and mark any slots still in use as not empty so they don't get freed by GC
* sweep all chunks freeing (and running finalisers) any slots that are empty
This commit uses the `chunk->shallow` with a `sentinel`
value to avoid clearing chunks for every sizeclass except
for …
> Avoid clearing chunks at start of GC

- benchmark/libponyrt/mem/heap.cc
- src/libponyrt/actor/actor.c
- src/libponyrt/mem/heap.c
- src/libponyrt/mem/heap.h
- test/libponyrt/mem/heap.cc
Prior to this commit, there were a number of heap allocation
functions for finalisers where the only difference from the
normal heap allocation functions was that the finaliser
functions kept track of which finalisers needed to be run
in the `chunk->finalisers` bitmap.
This commit combines the finaliser heap allocation functions
with their counterpart normal heap allocations functions.
It accomplishes this by adding in an extra argument called
`track_finalisers_mask` that can only be `0xFFFFFFFF` to
signify that finalisers should be tracked or `0` to signify
that finalisers shouldn't be tracked via a branchless bitwise
AND operation. This lowers the maintenance burden as now a
change to heap allocation logic will not need to be made
in two places at the same time and might even result in …
> Remove `ponyint_heap_alloc*_final` functions

- .ci-scripts/x86-64-release.bash
- .release-notes/4124.md
- src/libponyc/expr/call.c
- src/libponyc/expr/call.h
- src/libponyc/expr/operator.c
- src/libponyc/type/cap.c
- test/libponyc-run/ctor-autorecover/main.pony
- test/libponyc/recover.cc
This PR adds checks when assigning a constructor expression or passing one as a parameter to see if it can be auto-recovered, and if so, does not output a subtyping error.  E.g. for the following code:
```
actor Main
Bar.take_foo(Foo(88))
let bar: Foo iso = Foo(88)
class Foo
new create(v: U8) =>
None
primitive Bar
fun take_foo(foo: Foo iso) =>
None
```
We'd previously get errors on both lines in `Main.create()`; whereas with this PR they are now accepted.
Fixes #702
> Auto-recover constructor expressions

- .cirrus.yml
It was error prone so there's a slightly less error prone way
that we moved to as represented here.
To really make this not error prone, we'd need to move the the
system as seen in:
https://github.com/ponylang/ponyc/pull/3825
> Remove last vestiges of old manual CACHE_BUSTER

- .ci-dockerfiles/cross-riscv64/Dockerfile
- .ci-dockerfiles/cross-riscv64/build-and-push.bash
- .cirrus.yml
- .release-notes/3435.md
- CMakeLists.txt
- Makefile
- README.md
- make.ps1
- packages/builtin/platform.pony
- src/common/platform.h
- src/common/pony/detail/atomics.h
- src/libponyc/codegen/codegen.c
- src/libponyc/codegen/genopt.cc
- src/libponyc/codegen/genopt.h
- src/libponyc/codegen/host.cc
- src/libponyc/options/options.c
- src/libponyc/pass/pass.h
- src/libponyrt/sched/cpu.c
Support for riscv. All tests pass for the 64 bit target.
-------------------------------------------
Instructions for testing (validated on ubuntu 20.04):
```
sudo apt-get install -y gdb-multiarch qemu-user gcc-10-riscv64-linux-gnu g++-10-riscv64-linux-gnu
ln -s /usr/riscv64-linux-gnu/lib/* /lib
make distclean
make libs llvm_archs='X86;RISCV' build_flags='-j8'
make config=debug configure llvm_archs='X86;RISCV' build_flags='-j8'
make config=debug build llvm_archs='X86;RISCV' build_flags='-j8'
make config=debug test llvm_archs='X86;RISCV' build_flags='-j8'
make config=debug cross-libponyrt CC=riscv64-linux-gnu-gcc-10 CXX=riscv64-linux-gnu-g++-10 arch=rv64gc cross_cflags="-march=rv64gc -mtune=rocket" cross_lflags="-march=riscv64"
make config=debug test-cross-ci PONYPATH=../rv64gc/debug …
```
> Support for riscv

- .release-notes/4167.md
- src/libponyc/type/lookup.c
- src/libponyc/verify/call.c
- test/libponyc-run/private-type-as-default-argument-in-public-function/lib/lib.pony
- test/libponyc-run/private-type-as-default-argument-in-public-function/main.pony
This attempts to fix the compiler crash reported in #4130
The crash happens upon attempting to call a methods from a different package that uses a package-private type as default parameter. Since it has been decided to treat this as a bug instead of a missing error, this PR implements the fix suggested by @ergl (https://github.com/ponylang/ponyc/issues/4130#issuecomment-1147300659) , namely using `lookup_try()` instead of lookup() in call.c's `check_partial_function_call()` since the former can be configured to permit private types.
With this PR, the two examples below that crashed the compiler now both compile:
Original example:
```pony
// inside the "useful" package
primitive _PrivateDefault
actor Useful[A: Any val]
fun tag config(value: (A | _PrivateDefault) = _PrivateDefault): …
```
> Fix for crash when methods with default private type params in remote packages are called 

- .release-notes/4159.md
- src/common/pony/detail/atomics.h
- src/libponyrt/mem/pool.c
- src/libponyrt/sched/mpmcq.c
I was looking at https://github.com/ponylang/ponyc/pull/1206 and noticed
that when Benoit did the porting, that in a few places, he changed the
atomics usage unintentionally from what it was previously.
This commit reverts those (almost assuredly) inadvertent changes.
I can't guarantee that there are no other bits that were incorrect
in that commit, but I know these bits where.
I believe from a cursory glance that these could do "very bad things"
on weakly ordered memory platforms like Arm.
> Fix incorrect atomics usage

- src/libponyrt/actor/actor.c
Prior to this commit, if an actor blocked, it did not run GC to free
any memory it no longer needed. This would result in blocked actors
holding on to (potentially lots of) memory unnecessarily.
This commit causes GC to be triggered when the cycle detector asks
an actor if it is blocked and the actor responds telling the cycle
detector that it is blocked. This should result in memory being
held by blocked actors to be freed more quickly even if the cycle
detector doesn't end up detecting a cycle and reaping the actors.
This will force a GC for an actor based on the following three things:
* The actor processed at least one message since it's last GC (i.e. it did some work [GC acquire/release message or app message)
* The actor's heap is greater than 0 (i.e. it has memory that could …
> Trigger GC for actors when they tell the cycle detector they're blocked

- src/libponyrt/sched/cpu.c
Prior to this change, scheduler threads that been waiting for work
for 10000000 or more cycles would always call SleepEx/nanosleep
regardless of the value of `yield`.
When the number of cycles was at least 10000000 and no more than
10000000000, this would have sleep called with a zero value. On
both Windows and Posix, calling with a 0 value causes the thread
to yield.
We were yielding regardless of `yield` value. Yield was only
controlling if we would yield for more than our timeslice. It
wasn't preventing the scheduler thread from giving up its current
timeslice and being rescheduled at the kernel's leisure.
The code has been updated to only call sleep when yields are
requested.
> Don't call "sleep" for schedulers that shouldn't yield

- .release-notes/4180.md
- src/libponyrt/lang/stdfd.c
When printing via `StdStream.print` strings containing the null
terminator, we were just printing the string until the null terminator
and replacing the unprinted characters by padding the printed string
with space characters.
This behavior made `String.size()` inconsistent with what `fprintf` was
really printing.
This behavior has been introduced in #1768, which ensure we respected
the buffer size.
Closes #4171
> Fix bug in `StdStream.print`

- src/libponyrt/pony.h
Renamed took place in commit: d3e69a47e9193fbbe1fcffe789d126daa833c9fe
> Reflect renaming `pony_become` to `ponyint_become` also in comments

- lib/CMakeLists.txt
This is gets FreeBSD back onto the same version as our other supported operating systems.
> Update to GoogleTest 1.12.1

- .release-notes/4182.md
- src/libponyc/pass/refer.c
- src/libponyc/pass/verify.c
- test/libponyc/badpony.cc
While identity comparison with new objects was correctly catched by the
compiler as always false when using sugared syntax, it wasn't using
desugared one.
This patch makes the compiler in the latter case.
This example is now failing:
```pony
class C
actor Main
env.out.print(if C.create() is C.create() then
"C is C" else "C is NOT C" end)
```
Closes #4162
> Fix identity comparison check with desugared creations

- src/libponyrt/asio/event.h
Reduces `sizeof(struct asio_event_t)` from 48 bytes to 40 bytes on 64-bit x86 Linux/FreeBSD. The `noisy` field was talking up 3 bytes due to aligment of the following 64-bit value `nsecs` at a word boundary (offset 32).  The two other flags `readable` and `writable` fit in the alignment hole and no longer waste 8 bytes to align the whole struct at word boundaries again.
Note that the offset of `nsecs` is not changed. It still lives at offset 32.
> Reorder fields to reduce `sizeof(asio_event_t)` to 40 bytes

- .release-notes/ansi-erase.md
- packages/term/ansi.pony
With the release of 0.49.0, we changed `Ansi.erase` to be erasing left rather than right. This made sense based on the comment on the `Ansi.erase` method. However, the actual usage in the standard library of `Ansi.erase` was expecting it to erase to the right. Because of this change, since 0.49.0, the readline support in the `term` package has been broken.
This commit switches erase back to erasing to the right and in the process fixes the readline package. The commment on `erase` has been updated to reflect what it actually does.
Supporting erasing to both the left and the right seems valuable but, I'm not addressing that here and instead am leaving that to an RFC.
> Fix broken readline package

- .cirrus.yml
Compute credits are detailed here: https://cirrus-ci.org/pricing/#compute-credits
Using compute credits will allow us to prevent release tasks for ponyc from getting pre-empted. Currently, if pre-empted at "just the wrong" time, can create issues that are hard for the average Pony releasers to sort out.
Pretty much anyone but me might get flummoxed. For what we believe will be a small yearly cost, we can avoid the problem by using compute credits for releases.
To make sure I set this up correctly, I have added the use of compute credits on a single nightly release task, Once I've determined that works correctly and feel good about the regular release setup, I'll remove the use of compute credits for the nightly job.
This change as discussed at the October 25, 2022 sync and we got a quorom …
> Use cirrus compute credits when doing releases

- src/libponyrt/sched/cpu.c
Currently, the windows "lowest CPU yield time" is set to 1 millisecond which is 10x longer than on other platforms. Windows, particularly when running tests, is also noticeably slower than other platforms. I think this regular 10x longer pause can, over time, roll up into things taking much much longer on windows.
I believe it is better to yield "too little" rather than "too much".
> Speed up runtime on Windows

- src/libponyrt/asio/iocp.c
In PR #4083, I reversed some relaxing of atomic orderings that were introduced in 2016 in #1209. When I was doing that change, I missed an additional strengthing that should have been done in the IOCP subsystem.
If you note the original commit, I made a corresponding change in the EPoll subsystem, but missed doing it in the IOCP system.
> Strength the order for an atomic operation in the IOCP subsystem

- Makefile
We currently run them for 20 minutes. This change will increase it to 40 minutes. This shouldn't result in suddenly seeing errors, but the additional time won't hurt us.
> Double time we run the nightly stress tests

- BUILD.md
Python 3 is required to build LLVM.
Closes #4224
> Update build instructions

- .release-notes/nanos-overflow.md
- packages/time/time.pony
For millis, micros, and nanos support on Windows, we use the QueryPerformanceCounter as a monotonically increasing "source of time". Given the counter is 64-bits, for an imaginary 2ghz processor that probably gives us about 290ish years of ticks before we would wrap around and our monotonic nature would be broken. All this means, its an excellent "source of time".
To turn the result from the QueryPerformanceCounter into seconds, you divide its value by the QueryPerformanceFrequency. One my computer, the qpf value is 10_000_000.
The previous code for determining nanos on Windows was unfortunately, far more prone to wrapping around than the QueryPerformanceCounter. Previously, we did the following for nanos:
(qpc * 1_000_000_000) / qpf
Because we were multiplying the qpc (a 64 bit integer) …
> Avoid fairly easy to trigger overflow in Windows Time.nanos code

- .release-notes/4228.md
- src/libponyc/pass/docgen.c
Previously they have been unordered, which makes finding them hard, especially for packages with many types (like builtin). This change explicitly does not sort the fields, constructors, methods and behaviours inside a types documentation. Although I would argue that this would also help finding those elements inside a type (e.g. the documentation for chop in Array).
> Sort package types in documentation

- .release-notes/src-search-exclude.md
- src/libponyc/pass/docgen.c
This feature is currently "sponsors only" so it won't work for regular users. However, we can switch our Pony projects over to using the insiders theme and take advantage of this change.
This will improve the search experience by not including our src files in the search index.
Any users that use mkdocs-material-insiders will also be able to take advantage of this change.
> Update docgen to generate source files that are ignored

- .ci-dockerfiles/stdlib-builder/Dockerfile
- .ci-dockerfiles/stdlib-builder/build-and-push.bash
- .github/workflows/cloudsmith-package-sychronised.yml
- .github/workflows/generate-documentation.yml
- .github/workflows/rebuild-stdlib-builder.yml
In theory, this is a simple thing to do. However, there's at least a couple additional moving parts here because, we do not want to expost squidfunk's "private insiders code" in a public image on docker hub.
The commit changes our standard library builder image to live in the GitHub container registry where we have marked it as private so only we can access it. By having the builder as private, we can safely install the insiders theme in it and use it for building our standard library docs.
To install in the image, we need to supply the correct access token as part of the build process. The token has been stored in a Ponylang org secret which is supplied at the time we build on GitHub. Because this makes building locally from the command line more complicated, we have also added a …
> Install mkdocs-material-insiders in standard library builder image

- .release-notes/docgen-search-home-file.md
- src/libponyc/pass/docgen.c
The "home file" is only a list of the packages on the site. It ends up being extra noise in search results where it provides no value.
This commit adds front matter to the home file that will remove it from the search index when the mkdocs-material-insiders theme is removed.
> Don't include "home file" in documentation search

- .release-notes/rfc75.md
- packages/term/ansi.pony
Implements RFC #75.
Closes #4245
> Add support for erase left and erase line in term.ANSI

- .release-notes/4081.md
- packages/net/tcp_connection.pony
- src/libponyrt/lang/socket.c
Our prior setting of backpressure for TCP writes on Windows was naive. It was based purely on the number of buffers currently outstanding on an IOCP socket. The amount of data didn't matter at all. Whether more data could be accepted or not, also wasn't taken into consideration. This commit greatly improves the situation by only applying backpressure when Windows tells us that it is applying backpressure.
No more guessing.
Two runtime API methods have been updated on Windows.
The Windows version of `pony_os_writev` will now return the number of buffers accepted or zero if backpressure is encountered. All other errors still cause an error that must be handled on the Pony side of the API via a `try` block.
The Windows version of `pony_os_send` will now return the number of bytes accepted or …
> Improve TCP backpressure handling on Windows

- .release-notes/cycle-races.md
- src/libponyrt/actor/actor.c
- src/libponyrt/actor/actor.h
- src/libponyrt/gc/cycle.c
The Pony runtime includes an optional cycle detector that is on by default. The
cycle detector runs and looks for groups of blocked actors that will have
reference counts above 0 but are unable to do any more work as all members are 
blocked and don't have additional work to do.
Over time, we have made a number of changes to the cycle detector to improve 
it's performance and mitigate it's impact on running Pony programs. In the
process of improving the cycle detectors performance, it has become more and 
more complicated. That complication led to several race conditions that existed 
in the interaction between actors and the cycle detector. Each of these race 
conditions could lead to an actor getting freed more than once, causing an 
application crash or an attempt to access an actor …
> Fix multiple races within actor/cycle detector interactions

- .ci-scripts/x86-64-unknown-freebsd-13.1-nightly.bash
- .ci-scripts/x86-64-unknown-freebsd-13.1-release.bash
- .cirrus.yml
- .release-notes/4185.md
- RELEASE_PROCESS.md
- benchmark/libponyrt/ds/hash.cc
- benchmark/libponyrt/mem/heap.cc
- lib/CMakeLists.txt
Updates our supported FreeBSD to 13.1. 
All other changes herein were required to get everything passing. Google benchmark was particularly problematic as only the 1.7 series works on FreeBSD 13.1 but benchmark 1.7.0 didn't work on Windows.
> Update supported FreeBSD to 13.1

- .ci-dockerfiles/x86-64-unknown-linux-rocky8-builder/Dockerfile
- .ci-dockerfiles/x86-64-unknown-linux-ubuntu18.04-builder/Dockerfile
- .cirrus.yml
Both need newer a newer cmake version to be able to build the googlebench version that we are now using.
> Update rocky8 and ubuntu18 builders

- Makefile
- make.ps1
Recently, I increased the stress test duration from 20 to 40 minutes thinking "more is better" and in general, that is true. However, now that we are running longer, it is becoming a regular occurrence that stress test VMs in Cirrus are being pre-empted.
This commit puts us back to the previous 20 minute run times. At 20 minutes, we rarely got pre-empted.
> Reduce stress test duration

- .cirrus.yml
- Makefile
- make.ps1
- test/rt-stress/string-message-ubench/main.pony
We've been using examples/message-ubench for stress tests. This commit switches to having a dedicated stress test folder for the runtime `rt-stress`.
We can add additional tests and modify the stress tests therein without worrying about if the programs are used elsewhere as well.
> Add dedicated stress test program

- .cirrus.yml
- .github/workflows/cloudsmith-package-sychronised.yml
- .release-notes/bye-intel-macos.md
- INSTALL.md
- README.md
- RELEASE_PROCESS.md
CirrusCI will be removing Intel MacOS runners at the end of 2022. It isn't worth our time to try to support another CI provider for building ponyc.
> Remove macOS on Intel as a supported platform

- .release-notes/fix-4243.md
- src/libponyc/pass/docgen.c
I messed up implenting Don't include "home file" in documentation search. The front matter wasn't the first thing in the file where I added it.
> Fix incorrectly implemented PR #4243

- .release-notes/4278.md
- src/libponyc/expr/call.c
The following code crashes the compiler, because `{(ISize)} iso^` is an invalid type, and when we check its arg for autorecovery, there is no type to check:
```
class val Info
let fn: {(ISize)} iso
new val create(fn': {(ISize)} iso^) =>
fn = fn'
fun call(n: ISize) =>
fn(n)
actor Main
let info = Info({(n: ISize) => env.out.print("n = " + n.string()) })
info.call(123)
```
This PR adds a null check so we won't assert on the invalid parameter type.
> Fix an assert in `call.c` when checking an invalid argument for autorecover

- .release-notes/4274.md
- src/libponyc/type/subtype.c
- test/libponyc-run/regression-3658/main.pony
- test/libponyc/type_check_subtype.cc
Some recursive constraints in type signatures could result in infinite loops while typechecking in cases where the typechecking should have succeeded.
This fixes those cases.
Fixes https://github.com/ponylang/ponyc/issues/3658
The fix works by making these cases more coinductive: pushing the assumption before typechecking equality of expressions.
> Fix an issue with infinite loops while typechecking some expressions

- .release-notes/4283.md
- src/libponyc/expr/operator.c
- src/libponyc/type/cap.c
- src/libponyc/type/cap.h
- src/libponyc/type/safeto.c
- src/libponyc/type/safeto.h
- test/libponyc/CMakeLists.txt
- test/libponyc/cap_safety.cc
This fixes #4282
and adds a set of simple "obviously-correct" tests of soundness / some completeness.
The bug was introduced because the change to safe_to_move in https://github.com/ponylang/ponyc/pull/4124/commits/c5113e74cd96bf0fb528a301b9e45534c3a63494 was correct from an isolation standpoint, but not from the standpoint of checking mutability, which is what the operator code was using it for. I.e. the change was valid only for the case of auto-recovering a constructor, and not mutating an existing object.
Now, mutability is checked before checking safety. This allows a better error message for the user in addition to fixing the bug.
> Fix soundness bug introduced in Pony 0.51.2

- .release-notes/4287.md
- src/libponyc/type/safeto.c
- test/libponyc/cap_safety.cc
Fixes a missed case in #4283 (arrow types). Instead of displaying an error message, the user who was attempting to do an unsafe mutation of a val was greeted by a compiler crash.
Fixes #4287
> Fix compiler crash introduced in #4283

- src/libponyrt/lang/socket.c
The 6.1 Linux kernel removed DECnet support: https://lwn.net/Articles/910312/
> Remove DECnet header

- .release-notes/4291-hang.md
- src/libponyc/codegen/gencall.c
The following program used to cause an infinite loop in the compiler:
```pony
type Message is (String, String, None)
interface tag Manager
be handle_message(msg: Message val)
actor Main
Foo(env, recover tag this end)
be handle_message(msg: Message val) =>
None
actor Foo
var manager: Manager
new create(env: Env, manager': Manager) =>
manager = manager'
let notifier = InputNotifier(this)
env.input(consume notifier)
be handle_data(data: String) =>
manager.handle_message(("","",None))
class InputNotifier is InputNotify
let parent: Foo
new iso create(parent': Foo) =>
parent = parent'
fun ref apply(data': Array[U8 val] iso) =>
parent.handle_data("")
```
Fixes #4291
> Fix infinite loop in compiler

- .release-notes/4291-segfault.md
- src/libponyc/codegen/gencall.c
Fixes segfaulting caused by the following program:
```pony
type Message is ((I64 | String), String, None)
interface tag Manager
be handle_message(msg: Message val)
actor Main
Foo(env, recover tag this end)
be handle_message(msg: Message val) =>
None
actor Foo
var manager: Manager
new create(env: Env, manager': Manager) =>
manager = manager'
let notifier = InputNotifier(this)
env.input(consume notifier)
be handle_data(data: String) =>
manager.handle_message(("","",None))
class InputNotifier is InputNotify
let parent: Foo
new iso create(parent': Foo) =>
parent = parent'
fun ref apply(data': Array[U8 val] iso) =>
parent.handle_data("")
```
> Fix compiler segfault caused by infinite recursion

- .release-notes/fix-4284.md
- src/libponyrt/gc/gc.c
- test/libponyc-run/regression-4284/main.pony
When I implemented turning off the unsafe "don't trace immutable objects" optimization in PR #4256, I incorrectly caused opaque objects to be traced in a couple of scenarios.
Tracing opaque objects will result in a segfault like the one discovered by Gordon.
Fixes #4284
> Fix runtime segfault

- .ci-dockerfiles/aarch64-unknown-linux-ubuntu20.04-builder/Dockerfile
- .ci-dockerfiles/x86-64-unknown-linux-ubuntu20.04-builder/Dockerfile
I added them ages ago when I was getting errors when building the files, turns out that my clock was set a couple days in the past thanks to a WSL bug. After that was fixed, I forgot to update the Dockerfiles to remove the entries.
> Remove unneeded Max-FutureTime from Dockerfiles

- .release-notes/4303.md
- src/libponyc/CMakeLists.txt
It will not link libstdc++ statically, as this is not available on MacOS. When linking against libponyc-standalone one also needs to link against libc++, but at least we have all the LLVM symbols in there.
An example pony program linking against it would need to look like this:
```pony
use "lib:ponyc-standalone" if posix or osx
use "lib:c++" if osx
```
While i think this is acceptable, as those libs are always available on MacOS, i would be happy about any hint on how to include those in `libponyc-standalone`.
I was not able to test this on an M1 mac.
> Create libponyc-standalone on MacOS

- .release-notes/4299.md
- src/libponyc/expr/operator.c
- test/libponyc/badpony.cc
Fixes #4290 
With this change, the error becomes:
```
Error:
/Users/jairocaro-accinoviciana/issues-pony-4290/demo.pony:10:11: not safe to write right side to left side
x.foo = foo
^
Info:
/Users/jairocaro-accinoviciana/issues-pony-4290/demo.pony:9:14: right side type: Foo ref
let foo: Foo ref = Foo
^
/Users/jairocaro-accinoviciana/issues-pony-4290/demo.pony:10:5: left side type: X iso
x.foo = foo
^
```
(First time contributing to ponyc + first time contributing in C) triple check the change please 😅
> Remove ambiguity from "not safe to write" compiler error message

- src/libponyc/pass/pass.h
Always include the field `llvm_args` in the `pass_opt_t` struct, otherwise, when linking against libponyc from pony we cannot reliably use the fields coming after that, as their offset is moved by a pointers width in debug mode. And thus in ffi we don't know if the field is present or not. And we cannot conditionally exclude or include a field in a struct in pony.
When libponyc/ponyc is compiled in release mode, this field will never be used and will remain a NULL pointer.
> Always include llvm_args in the pass_opt_t struct

- INSTALL.md
The short string we previously had works for now, but if we ever start to support things like Ubuntu 22.04 on Arm then it would no longer work. Using the full platform string will continue to work forever.
> Display full platform value in Linux install instructions

- .dockerfiles/latest/x86-64-unknown-linux-gnu/Dockerfile
- .dockerfiles/latest/x86-64-unknown-linux-musl/Dockerfile
- .dockerfiles/release/x86-64-unknown-linux-gnu/Dockerfile
- .dockerfiles/release/x86-64-unknown-linux-musl/Dockerfile
Previously, before the latest version of ponyup, when running on Glibc versions of Linux, we could end up installing the wrong ponyc. To correct for this, our Dockerfiles were supplying an explicit platform to use that matched the distribution that formed the image base. This was required for our "gnu" aka "glibc" image but not for musl. We only did it for musl to provide symmetry.
The new version of ponyup will use lsb_release to correctly identify the Glibc distribution and install the correct ponyc.
> Remove explicit --platform from end user ponyc Dockerfiles

- lib/CMakeLists.txt
We have been excluding a lot lately, but this one slipped through.
> Don't include libxml2 when building llvm libs.

- .release-notes/4307.md
- src/libponyc/CMakeLists.txt
- src/libponyc/ast/ast.h
- src/libponyc/ast/token.h
Build ponyc-standalone.lib for windows as a standalone variant of libponyc. It contains blake2, LLVM libs and libponyc.
It does not (to my knowledge) contain any static system libraries yet, but pony programs linked against it, work fine as is.
Linking to it from a pony program is done in the exact same way as for the other supported platforms:
```pony
use "lib:ponyc-standalone" if linux or osx or windows
use "lib:c++" if osx
actor Main
None
```
> Build ponyc-standalone.lib for windows

- src/libponyc/pass/pass.c
- src/ponyc/main.c
Valgrind reported the allocated bytes in `pass_opt_t->all_args` as leaking, as they were allocated but never freed. So I am doing this attempt at freeing them. Valgrind seems to be happy now.
> Fix small memory leak in ponyc.

- .release-notes/4325.md
- src/libponyrt/lang/ssl.c
- src/libponyrt/platform/threads.c
Prior to this commit we were using a mechanism on Windows called `WaitForSingleObject` when we wanted to put a thread to sleep until we activated a signal to wake it up later.
Now we use `WaitForSingleObjectEx` instead, so we can be sure that the thread is kept in an "alertable" state if there is an APC (Async Procedure Call) that needs to be run during the wait period.
We use APCs for socket I/O completion callbacks, and they can only arrive on the thread that initiated them, so it's important to allow such callbacks to run even if the scheduler thread is suspended.
Note that the callbacks we use for sockets will not run any Pony code - they will only dispatch a message via the ASIO subsystem, so running those APCs is safe even if the actor has been work-stealed to another thread and is …
> Fix waiting on Windows to be sure I/O events can still come in.

- src/libponyrt/ds/hash.h
with the other HASHMAP functions by taking a name_t, not a general hashmap_t
One of the commits originally in #4331
> Make HASHMAP's fill_ratio function consistent

- .release-notes/4341.md
- src/libponyc/codegen/genopt.cc
- test/libponyc-run/regression-4340/main.pony
Fix bug in HeapToStack optimization
Our HeapToStack optimization pass was occassionally generating incorrect IR.
The following is the "annotated by Pony developers" IR after a HeapToStack 
optimization pass run for the code from Issue #4340:
```llvm
define private fastcc ptr @_TestUnivals_ref_apply_oo(ptr nocapture readnone %this, ptr nocapture readonly dereferenceable(24) %h) unnamed_addr !dbg !7533 !pony.abi !4 {
entry:
%_leaf_right = alloca i8, i64 32, align 8
%_leaf_left = alloca i8, i64 32, align 8
store ptr @Leaf_Desc, ptr %_leaf_left, align 8
%_leaf_left_value = getelementptr inbounds %Leaf, ptr %_leaf_left, i64 0, i32 1, !dbg !7539
store i64 0, ptr %_leaf_left_value, align 8, !dbg !7539
store ptr @Leaf_Desc, ptr %_leaf_right, align 8
%_leaf_right_value = getelementptr inbounds …
```
> Fix bug in HeapToStack optimization pass

- .release-notes/4345.md
- src/libponyc/pass/sugar.c
Previously, `with` blocks would allow the usage of `_` as a variable in the `with` parameters.
A `_` variable isn't usable within the block itself and `dispose` wasn't called on the variable as it isn't valid to call any methods on the special `_` variable.
The lack of `dispose` call on objects that might control resources could result in a resource leak.
We've addressed the issue by disallowing `_` as a variable name in `with` parameters.
This is a breaking change, albeit one we don't expect to have any "real-world" impact.
Fixes #4345
> Fix a possible resource leak with `with` blocks

- .dockerfiles/latest/x86-64-unknown-linux-gnu/Dockerfile
- .dockerfiles/latest/x86-64-unknown-linux-musl/Dockerfile
- .dockerfiles/release/x86-64-unknown-linux-gnu/Dockerfile
- .dockerfiles/release/x86-64-unknown-linux-musl/Dockerfile
- .release-notes/stable.md
It has been deprecated for ages and ages.
> Stop putting `stable` in ponyc Docker images

- src/libponyrt/actor/actor.c
Prior to this commit the `ponyint_release_cycle_detector_critical` function wrote 0 to the `actor->cycle_detector_critical` field without using atomic instructions even though the `ponyint_acquire_cycle_detector_critical` function uses an atomic compare exchange on the same field.
This commit updates the `ponyint_release_cycle_detector_critical` function to use an atomic instruction with `memory_order_release` memory order to store 0 into the `actor->cycle_detector_critical` field.
> Use atomic store in `ponyint_release_cycle_detector_critical` function

- src/libponyc/ast/lexer.c
This was flagged by either the memory sanitizer or the undefined behavior sanitizer as an issue.
This commit changes the datatype of `i` to be `ssize_t` so that `lexer->buflen - 1` becomes less than 0 when `lexer->buflen` == 0.
> fix `normalise_string` to prevent issues when `lexer->buflen` == 0

- .cirrus.yml
CirrusCI moved the Arm infrastructure from AWS to Google's cloud. In the process, the security setup for Docker containers changed and we no longer have the permissions required to "debug C++ code" in containers on Arm.
Cirrus is unable "for security reasons" to change the configuration of the GKE to accomodate our needs.
The error in question happens when you try to run a program started up in the debugger. We get:
"'A' packet returned an error: 8"
According to a posting on StackOverflow, this can be addressed by adding "--cap-add=SYS_PTRACE --security-opt seccomp=unconfined" to the "docker run" command.
According to CirrusCI they added NET_RAW and SYS_PTRACE capabilities in an attempt to address the problem. However, that didn't work as we continued to get errors. Cirrus says they would …
> Don't run test in debugger on Arm

- src/libponyc/pass/names.c
This was flagged by either the memory sanitizer or the undefined behavior sanitizer.
Prior to this commit, the AST node is replaced and then the call to `ast_get` tries to access the old node that has already been freed.
This commit ensures that the call to `ast_get` will correctly access the newly AST node.
> fix `names_typeparam` to prevent access to an AST node that was just replaced

- test/libponyc-run/runner/CMakeLists.txt
Prior to this commit, a call to `make build` would not rebuild the test `runner` whenever `ponyc` would get rebuilt. This could cause some confusion, especially if `libponyrt` changed, as one would expect `make build` to ensure the `runner` is built using the latest version of the runtime and compiler.
This commit ensures that the runner will get rebuilt whenever `ponyc` gets rebuilt by adding `ponyc` as an explicit dependency to the `runner` build command.
> Make sure the test runner gets rebuilt whenever ponyc gets rebuilt

- src/libponyc/CMakeLists.txt
- src/libponyrt/CMakeLists.txt
- test/libponyc-run/CMakeLists.txt
Prior to this commit, build with `use` flags enabled would have some build files saved to the wrong directory (i.e. `build/debug` instead of `build/debug-runtimestats`).
This commit updates the various `CMakeLists.txt` files to ensure all copy commands use the directories with `PONY_OUTPUT_SUFFIX` appended so that all build files are appropriately in the relevant output directory for the `use` flag enabled build.
> Ensure all build files go into correct output dir when `use` flags are enabled

- Makefile
Prior to this commit, running `make test` after running `make configure use=use_flag` would fail because the `Makefile` would look for the test binaries in the wrong directory (i.e. in `build/debug` instead of `build/debug-runtimestats`).
This commit updates the `Makefile` to try and determine the `use` output directory from the CMake configure generated `cmake_install.cmake` file so that tests can be run successfully. It will fall back to the current behavior and use the default build directory if it the file doesn't exist or it is unable to extract the directory path.
> Fix for running tests with `use=` flags enabled

- src/libponyrt/mem/heap.c
As part of https://github.com/ponylang/ponyc/pull/4143, the logic was changed to avoid clearing chunks at the start of GC (except for sizeclass 0) by using a sentinel value in the `chunk->shallow` field.
This commit, changes the implementation to rely on pointer tagging of the `chunk->m` field using the lowest bit to track whether a chunk needs to be cleared or not. The sentinel in the `chunk->shallow` is no longer needed/used allowing for this optimization to work for all sizeclasses (including the previously excluded sizeclass 0). All accesses to the `chunk->m` field now go through the utility function `get_m` to clear out the tagged bit first.
> Use pointer tagging to avoid clearing chunks at start of GC

- src/libponyrt/mem/heap.c
- src/libponyrt/mem/heap.h
Prior to this commit, the heap `chunk_t` was generic for both small and large chunks taking up more space than required for either one.
This commit specializes the small and large chunk structures by using pointer tagging on the `chunk->m` field to keep track of the chunk type and large chunk slot/shallow/finaliser and the small chunk sizeclass. This should in theory improve performance as now the `large_chunk_t` is 32 bytes and `small_chunk_t` is 36 bytes on 64 bit platforms (while `chunk_t` was previously 44 bytes.
There are no logic changes other than whatever was required to support the specialization.
> Specialize heap small and large chunk implementations

- src/libponyc/ast/bnfprint.c
This allows the compiler to put them in read only memory without additional analysis to find out that they are not written to. To do this the related parameters of the `bnf_token_set` and `bnf_rule_set` functions are marked const, to declare that they won’t modify these arguments, as they don’t.
> Make some static bnf token & rule arrays const

- CMakeLists.txt
- Makefile
- src/libponyrt/CMakeLists.txt
- src/libponyrt/mem/pool.c
- src/libponyrt/mem/pool.h
- src/libponyrt/mem/pool_memalign.c
- test/libponyrt/mem/pool.cc
This commit add an option to build pony with the pool implementation based on posix_memalign instead of the default pool implementation. This, combined with address/undefined behavior/etc sanitizers, allows for easier debugging of memory issues within the compiler and runtime.
> Add option to use pool implementation which relies on memalign

- .github/workflows/update-lib-cache.yml
We cache `lib` in order to speed up our builds as building all of LLVM takes a long long time. Once an update to any of the files that would invalidate the cached libs is done, until a new cached version is done on "main", it won't apply to new PRs.
This workflow allows us to update (if needed) the lib cache for any given branch. In general, this would usually only be used on `main`.
> Add workflow to manually update the lib cache

- .github/workflows/cirrus-failures.yml
- .github/workflows/cloudsmith-package-sychronised.yml
- .github/workflows/nightlies.yml
- .github/workflows/stress-test-runtime.yml
The previous version we were on was tied to node12 which is deprecated on runners. The new verison is node16 based and will continue to work going forward.
> Update version of github-actions-zulip

- .github/workflows/announce-a-release.yml
- .github/workflows/cloudsmith-package-sychronised.yml
- .github/workflows/pr.yml
- .github/workflows/prepare-for-a-release.yml
- .github/workflows/rebuild-stdlib-builder.yml
Eventually v2 will be deprecated. Let's update before that happens. This also gets us using v3 for all checkout actions in the ponyc repo.
> Update to actions/checkout v3

- .release-notes/4368.md
- packages/builtin_test/_test.pony
- src/libponyrt/gc/gc.c
- src/libponyrt/gc/objectmap.c
- src/libponyrt/mem/heap.c
- src/libponyrt/mem/heap.h
- src/libponyrt/mem/pagemap.c
- src/libponyrt/mem/pagemap.h
- test/libponyrt/mem/heap.cc
- test/libponyrt/mem/pagemap.cc
This is a reopening of a PR from @dipinhora - PR #4368.
It was merged too soon (I didn't see the "do not merge" label).
> Move heap ownership info from chunk to pagemap

- .github/workflows/update-lib-cache.yml
Usually this will quickly exit, however, if anything is out of date 3 hours before nightlies, it will probably be out of date at the time that nightlies happen. Running ahead of time will make the release more efficient. That efficiency is nice because if we hit a problem elsewhere with the release, it will happen "sooner in the evening" with more time for someone to look into it.
> Run "rebuild libs cache" every day 3 hours before nightlies run

- .github/workflows/pr.yml
- .github/workflows/stress-test-runtime.yml
Configure takes no time at all and we don't get anything out of them being different steps. It is fine for the level of detail we need to have them as a single "build" step.
> Merge the "configure" and "build" pony build steps together

- src/libponyc/options/options.c
- src/libponyrt/lang/time.c
The latest version of Visual Studio 2022 (17.7.0) makes some header changes that require including `<stdlib.h>` in a couple of places.
> Add includes necessary for Visual Studio 2022 v17.7.0

- Makefile
Sometimes while working on a compiler bug, it's annoying to rebuild lots of tests/runners/etc when just trying to make a new version of the compiler to do some manual testing with it.
This PR adds `make ponyc` which only uses the `ponyc` CMake target, rather than the `all` target. Everything else in the invocation is the same as it is for `make build`.
> Add `make ponyc` for building just ponyc.

- .github/workflows/pr.yml
Having it just be the ref can accidentally conflict with other workflows that set the same and run on the same events and have them operate serially (unintentionally).
> Make the concurrency group for PR workflow more scoped

- test/libponyc-run/runner/_find_executable.pony
- test/libponyc-run/runner/_tester.pony
We discovered this bug while working on moving Windows CI from CirrusCI to GitHub Actions when we tried using an LLDB that was installed at a location that had a space in the file path.
This change is extracted from PR #4383.
> Add test runner support for spaces in debugger path name

- .cirrus.yml
- .release-notes/no-arm-macos.md
- INSTALL.md
- README.md
- RELEASE_PROCESS.md
With our move off of CirrusCI, we don't have a Apple Silicon CI environment. Hopefully, we'll get one soon as GitHub is saying that they should have one sometime in Q4 of 2023.
> Drop macOS on Apple Silicon as a fully supported platform

- .github/workflows/cloudsmith-package-sychronised.yml
This commit adds a steps that runs after each update for the tagged standard library builder images. The update will delete all untagged builders.
Based on how we use the builder (build, push, use) we shouldn't ever need any of the untagged builders. They are noise for us in the UI of things that will never be used and waste storage for GitHub.
> Delete untagged stdlib builder images

- packages/runtime_info/actor_stats.pony
- packages/runtime_info/scheduler_stats.pony
Prior to this change, it wasn't clear without looking at the code that you need a runtime compiled to support runtime statistics otherwise all actor and scheduler stats will be 0.
> Update documentation for Actor and Scheduler statistics

- make.ps1
The full command wasn't being outout as `--debug=` was missing. It made for reading the actual output as seen for the command look very odd.
> Fix small output error in make.ps1

- test/libponyc-run/runner/_tester.pony
LLDB 14 and 15 (perhaps 16, we didn't test) has some issues.
It doesn't run "on crash" scripts if the crash occurred in any thread but "the main thread". Additionally, it doesn't give us the back up exit status message we would search for.
The result? CI tests run in LLDB 14 or 15 would fail but the runner would report them as having passed.
This patch is from Gordon Tisher.
> Fix failing CI tests that were run in LLDB 14 not reporting failures

- .github/workflows/stress-test-runtime.yml
When we turn off CircusCI, we'll lose macOS stress tests. This commit adds stress tests for macOS on x86.
> Add macOS Stress Tests

- .ci-dockerfiles/x86-64-unknown-linux-musl-builder/Dockerfile
- .dockerfiles/latest/x86-64-unknown-linux-musl/Dockerfile
- .dockerfiles/release/x86-64-unknown-linux-musl/Dockerfile
- .github/workflows/nightlies.yml
- .github/workflows/pr.yml
- .github/workflows/release.yml
- .github/workflows/stress-test-runtime.yml
- .github/workflows/update-lib-cache.yml
- .release-notes/next-release.md
- BUILD.md
- CHANGELOG.md
- INSTALL.md
- src/libponyc/codegen/genexe.c
With Alpine 3.17, Alpine stopped supporting libexecinfo. In the process,
the backtrace functionality was moved into musl directly. This makes it
very hard to support both pre and post 3.17 Alpine with the compiler.
We decided to not support 3.16 and earlier as it is a decent amount of
work to support both and 3.16 is EOL in about 9 months.
As part of the change, we are updating our public docker images to be
compatiable with the change. Our public Alpine images are now based off
of Alpine 3.18.
> Update supported Alpine version to 3.17 and later

- .ci-dockerfiles/x86-64-unknown-linux-ubuntu22.04-builder/Dockerfile
LLDB 14 is broken and doesn't run our "usedebugger" scripts correctly. This can result in failing tests not being reported correctly as failing.
False passing is a bad bad thing.
> Install LLDB 19 in Ubuntu 22 builder image

- .release-notes/4405.md
- packages/pony_check/property_helper.pony
- packages/pony_check/property_runner.pony
This should fix issue #4391 for very slow execution environments.
[update]
After first assuming it was a timeout issue, i.e. that a slow execution environment did not finish within the default 60 secs timeout.
It turned out to be a logical flaw in how the `_PropertyRunner` handles expecting and completing actions. It was possible to have stray actors from old property runs call into the `_PropertyRunner` instance that was already dealing with another run, thus disturbing the current run. The async Property handling with `complete` and `fail` already had such a safeguard, the `expect_action` and `complete_action`/`fail_action` calls did not yet have this.
[/update]
After investigating #4391 i was not able to find a logical flaw in the `PropertyRunner` or in the way the `UnitTest` timeout …
> Avoid hangs in async pony_check properties when using actions

- src/libponyc/CMakeLists.txt
- test/libponyc-run/ffi-libponyc-standalone/main.pony
* vanilla FreeBSD does not provide a `libstdc++`, but a `libc++`. This is the only real difference to the fallback solution in the else branch. Those should be consolidated at one point.
* `${CMAKE_AR}` resolves to `llvm-ar` which supports mri scripts
* This has been additionally tested by testing and compiling https://github.com/mfelsche/pony-ast
> Add support for building libponyc-standalone.a on FreeBSD

- .dockerfiles/latest/x86-64-pc-windows-msvc/build-and-push.ps1
- .dockerfiles/latest/x86-64-unknown-linux-gnu/build-and-push.bash
- .dockerfiles/latest/x86-64-unknown-linux-musl/build-and-push.bash
- .dockerfiles/release/x86-64-pc-windows-msvc/build-and-push.ps1
- .dockerfiles/release/x86-64-unknown-linux-gnu/build-and-push.bash
- .dockerfiles/release/x86-64-unknown-linux-musl/build-and-push.bash
- .github/workflows/cloudsmith-package-sychronised.yml
- RELEASE_PROCESS.md
We are transitioning from DockerHub to GitHub Container Registry and while we are migrating, we will push images to both registries.
> Push images to GitHub Container Registry in addition to DockerHub

- test/full-program-runner/CMakeLists.txt
When I moved and renamed the test runner, I neglected to update the cmake target executable name.  This means the runner does in fact get built the first time you run `make`, but it won't get incrementally updated if sources change.
This PR updates the name of the executable so cmake can correctly track it.
> Fix cmake dependency for moved test runner

- src/libponyc/codegen/host.cc
After extensive investigation of the weirdness that is #4369, Joe and I believe the issue is most likely an LLVM bug. However, we don't have time to pursue further.
During the investigation, I came to believe that the change to use CodeGenOpt::Default instead of CodeGenOpt::None for target optimizations would be prudent.
It prevents the known instances of bugs like #4369 which is nice but not key to this change. Changes things because they make symptoms go away isn't a good strategy if you don't understand why. We do not "fully" understand the impact of this change on bugs like #4369. However, it appears that CodeGenOpt::None is a code path that sees little use or testing and is more prone to bugs/regression.
Given that we have seen more than 1 bug that "smells like" #4369, we felt it was …
> Address issue 4369 "as best we can"

- .release-notes/4437.md
- packages/net/tcp_connection.pony
When fixing a number of "smaller" Windows TCP networking issues a couple years 
back, in addition to fixing those issues, we introduced a new bug. That bug 
lingered for two years. It lingered in large part because it would only become
apparent in a low resource environment.
When we recently switched our Windows CI from CirrusCI to GitHub Actions, we
went from a high-resource environment to a low-resource environment and started
getting a ton of "random" Windows TCP test failures.
The problem that was fairly easy to recreate in a test environment would be
fairly unlikely in most applications but existed nontheless. The scenario in
our test environment was like this:
- Test 1 runs and completes but hasn't done test teardown yet
- Test 2 starts up
- Test 1 runs the "buggy" line of code and …
> Fix "double socket close" issue with Windows version of TCPConnection

- CONTRIBUTING.md
It had gotten a bit long in the tooth over the years.
> Updating the pull request section of CONTRIBUTING.md

- packages/time/posix_date.pony
Note the "not at all obvious" caveat where we normalize %p and %P handling. Some locales will return an empty string for those format strings which if they are the only thing in the format string makes it impossible to know if there was success or failure from the format so we short-circuit those and make all locales return empty string if either formatting option is the only one in the format string.
> Update PosixDate.format doc string

- src/libponyc/pkg/platformfuns.h
From ages ago, this comment was added. Doxygen was run by someone and it flagged the comment as having params that weren't in the function signature.
I took a look a decided that:
- We don't use this comment format so it should be changed
- The commment provides no value so it should be removed
> Remove non-standard format comment

- .ci-dockerfiles/x86-64-unknown-linux-ubuntu22.04-builder/Dockerfile
- .github/workflows/nightlies.yml
- .github/workflows/pr.yml
- .github/workflows/release.yml
- .github/workflows/stress-test-runtime.yml
- .github/workflows/update-lib-cache.yml
- .release-notes/dtrace.md
- BUILD.md
- src/libponyrt/CMakeLists.txt
Dtrace functionality was missed when converting the build system to cmake.
This PR generates and links dtrace probes into `libponyrt` if the
`use=dtrace` option.
Fixes https://github.com/ponylang/ponyc/issues/4449
> Fix broken DTrace support

- .github/workflows/pr.yml
- .release-notes/fix-4431.md
- src/libponyrt/mem/pool_memalign.c
> Fix compilation error when building with pool_memalign in release mode

- .release-notes/issue-4244.md
- src/libponyc/type/alias.c
- test/libponyc/recover.cc
Last November, Gordon identified that the compiler was allowing code to recover a `val` from a `box` field. This is unsafe and very "doh".
After investigation, it was determined that this bug has existed since Sylvan introduced viewpoint adaptation to the compiler almost a decade ago.
I came up with a fix, but after talking with Sylvan, we changed to this fix as it is the "proper pure theory fix".
Fixes #4244
> Fix compiler bug that allows an unsafe data access pattern

- .ci-dockerfiles/x86-64-unknown-linux-musl-builder/Dockerfile
- .github/workflows/nightlies.yml
- .github/workflows/pr.yml
- .github/workflows/release.yml
- .github/workflows/stress-test-runtime.yml
- .github/workflows/update-lib-cache.yml
We updated our alpine version so I decided to see if we could use LLDB
instead of GDB for our debugger. And yes, we can now without a hanging.
I'm leaving GDB in the image for now in case we need to switch back.
Closes #4176
> Run musl CI tests using LLDB

- CMakeLists.txt
- src/libponyc/CMakeLists.txt
- src/libponyc/codegen/codegen.c
- src/libponyc/codegen/genexe.c
- src/libponyrt/CMakeLists.txt
This PR specifies the MacOS platform version (currently "13.0.0") in only one place, and uses CMake variables and C/C++ defines to set it appropriately.
Fixes #4469
> Set MacOS platform version in one place

- .ci-dockerfiles/stdlib-builder/build-and-push.bash
- .dockerfiles/latest/x86-64-pc-windows-msvc/build-and-push.ps1
- .dockerfiles/latest/x86-64-unknown-linux-gnu/build-and-push.bash
- .dockerfiles/latest/x86-64-unknown-linux-musl/build-and-push.bash
- .dockerfiles/release/x86-64-pc-windows-msvc/build-and-push.ps1
- .dockerfiles/release/x86-64-unknown-linux-gnu/build-and-push.bash
- .dockerfiles/release/x86-64-unknown-linux-musl/build-and-push.bash
- .github/workflows/cloudsmith-package-sychronised.yml
- RELEASE_PROCESS.md
We've been transitioning everything over to GitHub Container Registry.
> Stop pushing new images to DockerHub

- make.ps1
Previously the tests and benchmark executables were included, which doubled the size of the zip file.  This PR removes those files before zipping the release archive.
We do it this way because the Powershell command `Compress-Archive` cannot add a single file to a directory other than the root directory of the zip file, so we can't specify just `bin\ponyc.exe` in the list of things to add to the archive; it'll add it to the root directory.  Ponyc expects to find its lib and packages directories one directory below where it is.
Fixes #4272
> Only include `ponyc.exe` in the `bin` directory of Windows release zip files

- .release-notes/4476.md
- packages/runtime_info/_test.pony
- packages/stdlib/_test.pony
It wasn't being built as part of testing/documentation for standard library.
> Fix missing "runtime_info" package documentation

- .release-notes/4481.md
- packages/builtin/float.pony
- test/full-program-tests/regression-4480/main.pony
> Use the correct LLVM intrinsics for `powi` on *nix.

- .ci-dockerfiles/x64-64-unknown-linux-fedora39-buiilder/Dockerfile
- .ci-dockerfiles/x64-64-unknown-linux-fedora39-buiilder/build-and-push.bash
- .github/workflows/nightlies.yml
- .github/workflows/release.yml
The builder will be used to build nightly and release versions of ponyc targetting Fedora 39.
No release notes are being added at this time, nor is RELEASE_PROCESS.md being updated as until a nightly runs, we can't be sure this will fully work.
The docker image created for the builder can almost certainly be trimmed down in size, but I am not a Fedora/DNF expert. I am looking to the requester of Fedora 39 support to assist with trimming the image down.
> Add Fedora 39 builder

- src/libponyc/codegen/genopt.cc
I'm not sure what that stray `+` was doing in there.
> Fix compiler warning

- .release-notes/4479.md
- src/libponyc/codegen/genserialise.c
- test/full-program-tests/regression-4479/main.pony
A bug in the handling of serializing bare lambdas was introduced when we updated to LLVM 15. This commit contains the fix.
Joe wrote the fix during a sync call after I identified the offending function during triage of a Red reported issue.
Closes #4479
> Fix bug when serializing bare lambdas

- .release-notes/4493.md
- examples/constrained_type/.gitignore
- examples/constrained_type/README.md
- examples/constrained_type/main.pony
- packages/constrained_types/_test.pony
- packages/constrained_types/constrained.pony
- packages/constrained_types/constrained_types.pony
- packages/stdlib/_test.pony
Implements RFC 79.
https://github.com/ponylang/rfcs/blob/main/text/0079-constrained-types.md
Closes #4492
> Add constrained_types package to the standard library

- packages/constrained_types/constrained_types.pony
There is a missing backtick in the documentation which causes a formatting issue in the documentation.  This PR fixes this.
> Adding a missing backtick in the documentation.

- .release-notes/4505.md
- src/libponyc/pass/refer.c
- test/libponyc/refer.cc
Fix #4477
Before this PR this code didn't work and cause segmentation fault as reported in issue #4477:
```pony
struct FFIBytes
var ptr: Pointer[U8 val] = Pointer[U8].create()
var length: USize = 0
fun iso string(): String val =>
recover String.from_cpointer(consume FFIBytes.ptr, consume FFIBytes.length) end
actor Main
env.out.print("nothing to see here")
```
Now, with the changes in this PR, here's what the compiler generates as an error:
```
Building builtin -> /home/slacturyx/Programming/Personal/Github/ponyc/packages/builtin
Building ./app -> /home/slacturyx/Programming/Personal/Github/ponyc/app
Error:
/home/slacturyx/Programming/Personal/Github/ponyc/app/app.pony:6:46: You can't consume an expression that isn't local. More specifically, you can only consume a …
```
> Fix compiler crash

- .dockerfiles/latest/x86-64-unknown-linux-gnu/Dockerfile
- .dockerfiles/release/x86-64-unknown-linux-gnu/Dockerfile
- .github/workflows/cloudsmith-package-sychronised.yml
- .release-notes/ubuntu24-images.md
Our Docker images have had their base image updated from Ubuntu 22.04 to Ubuntu 24.04.
> Update the base image for our ponyc images

- src/libponyc/type/subtype.c
This make the error message a bit more helpful in cases like those seen in #4514.
Resolves #4514
> Improve error message for generic subtyping.

- .release-notes/4527.md
- src/libponyrt/mem/heap.c
Prior to this commit, the heap small chunk size setting logic would bitwise-or in the size into the appropriate bits of the small chunk but this is technically incorrect as it doesn't clear out the bits first.
This commit changes the logic to ensure the relevant bits are cleared first before the new size is bitwise-or'd in.
> Make heap small chunk size setting logic more precise/correct

- .github/workflows/nightlies.yml
- .github/workflows/pr.yml
- .github/workflows/release.yml
- .github/workflows/stress-test-runtime.yml
- .github/workflows/update-lib-cache.yml
Version 3 contains a deprecated version of node that will cause the actions to stop working in the not so distant future.
> Update to actions/cache version 4

- src/libponyrt/actor/actor.h
Prior to this commit, we had to manually update the actor pad size if the size of pony_actor_t changed.
This commit makes it so that the actor pad size is now automagically calculated by the compiler so it doesn't have to be manually maintained any longer.
> Make actor pad automagically calculated

- .github/workflows/pr.yml
> Add CI test that everything works when runtimestats are on

- src/libponyrt/mem/heap.c
The implementation of actor heap large chunk recycling from #4531 too naive and results in actors wasting huge amounts of time related to large chunk recycling.
This commit effectively disables the large chunk recycling but doesn't undo the code changes at the moment because the expectation is that large chunk recycling will be re-enabled in the near future with an improved implementation.
> Disable actor heap large chunk recycling

- src/libponyrt/mem/heap.c
The implementation of actor heap chunk recycling from #4531 had two bugs. First, the large heap re-use logic (which was temporarily disabled in #4534) had a bug related to how it updated the large chunk recyclable list pointer in the heap. Second, the memory clearing logic in the `ponyint_heap_endgc` function was clearing more of the heap than it should have been resulting in a memory leak for both small and large chunk recyclable chunks.
This commit re-enabled large chunk recycling (undoing #4534) and fixes both bugs so that both large chunk and small chunk recycling work as expected without memory leaks.
> Fix heap chunk recycling memory leak and another bug

- .release-notes/4537.md
- src/libponyrt/CMakeLists.txt
Use `HINTS` instead of `PATHS` in the CMake `find_path` command that tries to find our custom-build `llc`. From the documentation for `find_file` it seems that `PATHS` is searched after the system `PATH`, so if there was a system `llc` that would get picked up first.  Since `HINTS` is searched before `PATH`, our `llc` now gets picked up correctly.
> Correctly find custom-built `llc`

- src/libponyrt/sched/mpmcq.c
- src/libponyrt/sched/mpmcq.h
- src/libponyrt/sched/scheduler.c
according to address sanitizer, prior to this commit, the mpmcq node free could cause a use-after-free error from another thread that might still be reading from `tail->next`. This was technically safe in this context since the logic will end up looping due to the CAS failing in the while condition due to the aba counter being out of sync.
This commit defers freeing of the nodes and instead recycles them for future pushes onto the mpmcq from the same thread to ensure that there are no use-after-free concerns any longer.
> Fix mpmcq use-after-free bug

- src/libponyrt/actor/messageq.c
- src/libponyrt/actor/messageq.h
- src/libponyrt/asio/epoll.c
- src/libponyrt/asio/event.c
- src/libponyrt/asio/iocp.c
- src/libponyrt/asio/kqueue.c
- src/libponyrt/sched/scheduler.c
- src/libponyrt/sched/scheduler.h
this is much easier to understand and maintain instead of having to remember that `-1` is an unknown scheduler everywhere it is used
> Use a constant for unknown scheduler index

- src/libponyrt/actor/actor.c
- src/libponyrt/actor/actor.h
- src/libponyrt/asio/event.c
- src/libponyrt/gc/cycle.c
- src/libponyrt/gc/cycle.h
- src/libponyrt/sched/scheduler.c
- src/libponyrt/sched/scheduler.h
Prior to this commit, when an actor was sent a message (from another actor or from the ASIO thread), it might get scheduled on the inject queue or the sending actor's scheduler thread depending on whether the context of the sending thread was a runtime scheduler thread or not. This was required to ensure that sending from the ASIO thread would add the actor to the inject queue. The same behavior was relied on during the runtime startup to ensure actors created before the scheduler threads were started were put on the inject queue. This made it hard to ensure that the cycle detector always ended up on the inject queue instead of the sending actor's scheduler thread. it was also less efficient than necessary for the majority of scenarios when an unscheduled actor might need to be scheduled …
> Make actor scheduling when unscheduled a tiny bit more efficient

- .release-notes/4540.md
- src/libponyc/ast/error.c
Address sanitizer prefers that the length check happen first.
> Fix buffer out of bounds access issue

- src/libponyrt/sched/scheduler.c
prior to this commit, every scheduler thread tried to initiate the shutdown CNF/ACK process if it was unable to `steal` from another scheduler thread even through in practice only scheduler 0 could ever initiate shutdown since it is the only one that receives ACK/BLOCK/SUSPEND messages and has enough information.
This commit changes things so that it is explicit that only scheduler 0 initiates the shutdown CNF/ACK process.
> Only scheduler 0 can initiate shutdown

- src/libponyrt/sched/scheduler.c
Prior to this commit, `signal_suspended_threads` would signal scheduler threads already known to be awake (based on the active scheduler count check variable) unnecessarily.
This commit changes the logic to only signal schedulers that are known to be asleep by starting at the value of active scheduler count check variable instead of index 0.
> Don't signal threads that are already known to be awake

- src/libponyrt/sched/scheduler.c
Prior to this change, it was possible to not shutdown all scheduler threads. ponyint_thread_join on non-Windows systems calls pthread_join. pthread_join can fail and that failure needs to be handled. In our case here, given that ponyint_thread_join returns a boolean, the response to an error is to try again.
If we encounter a non-recoverable error, this new strategy should result in a hang rather than undefined behavior. If we have hangs that we trace to this changed functionality, we look at more robust error handling and changing the interface from ponyint_thread_join.
> Correctly shutdown all scheduler threads

- .release-notes/4550.md
- src/libponyrt/sched/scheduler.c
Prior to this commit, the logic to detect quiescence had a race condition in relation to dynamic scheduler scaling and it was possible for the runtime to incorrectly detect quiescence and termninate early if a scheduler thread suspended at just the right time.
This commit changes the quiescence logic to keep an accurate track of exactly how many scheduler threads are active at the time the quiescence detection protocol begins so it can ensure that any scheduler threads suspending or unsuspending can no longer cause an incorrect determination that might lead to early termination of the runtime.
> Fix early quiescence/termination bug

- test/libponyrt/mem/heap.cc
resolves https://github.com/ponylang/ponyc/issues/4551
> Fix use=runtimestats heap test

- .ci-dockerfiles/x86-64-unknown-linux-musl-builder/Dockerfile
because a lot of lldb functionality requires it
> Add py3-lldb to musl ci builder

- .github/workflows/pr.yml
it seems the signal passing of SIGINT from lldb doesn't behave the same on macos as it does on linux..
> Don't use lldb for macos because stdlib tests fail silently with it

- .github/workflows/nightlies.yml
- .github/workflows/pr.yml
- .github/workflows/release.yml
- .github/workflows/stress-test-runtime.yml
- .github/workflows/update-lib-cache.yml
We were using libs rather than lib as the path to look up the libs CMake file. This meant that changes to it didn't result in the cache being properly busted.
> Fix incorrect LLVM CI caching

- .release-notes/4556.md
- Makefile
- src/libponyrt/asio/epoll.c
- src/libponyrt/asio/event.c
- src/libponyrt/asio/iocp.c
- src/libponyrt/asio/kqueue.c
- src/libponyrt/sched/scheduler.c
- src/libponyrt/sched/scheduler.h
Prior to this commit, there was a very rare edge case in the termination logic that could result in early shutdown resulting in a segfault.
This commit simplifies and reworks the shutdown/termination logic in order to make it more robust with less edge cases.
The logic now:
* does not un-noisy an actor from the ASIO thread until the relevant ASIO event is destroyed instead of when it is unsubscribed. This is important because the ASIO subsystem still has a reference to the actor and can send a message to it until the ASIO event is destroyed even if it has been unsubscribed
* always runs the CNF/ACK protocol to all schedulers instead of only the active ones
* disables scheduler scaling to ensure all schedulers are active for the duration of the termination CNF/ACK protocol to avoid / …
> Fix rare termination logic failures that could result in early shutdown

- .release-notes/4575.md
- src/libponyrt/platform/ponyassert.c
I'm not sure when OpenBSD made this change, but on OpenBSD 7.6, `backtrace` returns a `size_t`. Prior to this change, building pony fails with
```sh
/home/despereaux/build/ponyc/src/libponyrt/platform/ponyassert.c:45:25: error: implicit conversion loses i
nteger precision: 'size_t' (aka 'unsigned long') to 'stack_depth_t' (aka 'int') [-Werror,-Wshorten-64-to-3
2]
stack_depth_t depth = backtrace(addrs, 256);
~~~~~   ^~~~~~~~~~~~~~~~~~~~~
1 error generated.
*** Error 1 in target 'src/libponyrt/CMakeFiles/libponyrt.dir/platform/ponyassert.c.o'
*** Error 1 in . (src/libponyrt/CMakeFiles/libponyrt.dir/build.make:612 'src/libponyrt/CMakeFiles/libponyr
t.dir/platform/ponyassert.c.o': cd...)
*** Error 2 in . (CMakeFiles/Makefile2:371 'src/libponyrt/CMakeFiles/libponyrt.dir/all')
*** Error 2 in …
```
> Change stack_depth_t to size_t on OpenBSD

- src/libponyc/type/compattype.c
The return value of the function ```viewpoint_lower()``` is always checked for NULL.
On the other hand, the check ```if(a == NULL)``` was meaningless because the pointer ```a``` was previously dereferenced in ```viewpoint_lower(a)```.
Looks like it was a typo.
> Fix possible null dereference

- src/libponyrt/mem/heap.c
- src/libponyrt/mem/heap.h
- src/libponyrt/mem/heap_chunk_sorting.h
- test/libponyrt/mem/heap.cc
So they can better fight for their rights..
Prior to this commit, small_chunk_t and large_chunk_t were distinct types. This was great for correctness but prevented a useful optimization.
This commit changes things so that small_chunk_t and large_chunk_t have been combined into chunk_t which has a union in it for the small/large chunk specific fields. There are now a lot of assertions added in the relevant functions that deal with small and large chunks to ensure that the received chunk is of the right type because the compiler can no longer help enforce correctness.
This allows for small and large chunk recycling to take advantage of the fact that the block backing a small chunk is the same size as the block backing the smallest large chunk size allowed so they both now use the same …
> Unionize actor heap large and small chunks

- .ci-dockerfiles/x86-64-unknown-linux-ubuntu24.04-builder/Dockerfile
- .github/workflows/nightlies.yml
- .github/workflows/pr.yml
- .github/workflows/release.yml
- .github/workflows/stress-test-runtime.yml
- .github/workflows/update-lib-cache.yml
Adds a dependency to support Dipin's "manual poisoning for pool/heap when using address sanitizer" work.
> Update ubuntu 24 builder

- .release-notes/4593.md
- packages/cli/_test.pony
- packages/cli/command_parser.pony
Prior to this fix, parsing a sub-command proceeded before assigning defaults to the parent's options.  This fix factors out the default processing so it can occur before parsing a sub command.
Fixes #4580
> Apply default options for a CLI parent command when a sub command is parsed

- lib/CMakeLists.txt
as it wasn't compiling with clang-18 on FreeBSD 14.2 anymore.
Let's see if CI thinks this is sufficient.
> Upgrade googletest dependency

- src/libponyc/codegen/genprim.c
- src/libponyrt/ds/hash.h
- src/libponyrt/ds/list.h
ubsan doesn't like call's through function pointers of incorrect function types. This is used in both hash/list stuff along with in genprim. This commit fixes things to make ubsan happy.
`runtime error: call to function flag_free through pointer to incorrect function type 'void (*)(void *)'`
> ubsan: fix "call to function through pointer to incorrect function type"

- src/libponyc/pkg/buildflagset.c
ubsan doesn't like that buildflagset adds offsets to null pointers. This commit fixes things to ensure that buildflagset always has a valid text buffer to work with.
`runtime error: applying non-zero offset 11 to null pointer`
> ubsan: fix buildflagset "applying non-zero offset to null pointer"

- src/libponyc/reach/reach.c
ubsan doesn't like it when a null pointer is passed to memcpy. this commit fixes things to make ubsan happy.
`runtime error: null pointer passed as argument 2, which is declared to never be null`
> Fix null pointer argument

- src/libponyc/type/lookup.c
ubsan doesn't like it when we read a member from a null pointer. this commit fixes it to make ubsan happy.
`runtime error: member access within null pointer of type 'pass_opt_t'`
> Fix member access within null pointer of type 'pass_opt_t'

- test/full-program-tests/cycle-detector/main.pony
by decreasing the size and number of rings that need to be collected
> Make cycle detector test less likely to time out

- src/libponyrt/sched/scheduler.c
- test/full-program-tests/cycle-detector/main.pony
make cycle detector run more often and make the program only use a single pony thread to reduce contention..
also, don't pause cycle detector during shutdown anymore.. instead run it without unblocking scheduler 0 so it can do what it needs to do without interrupting the CNF/ACK shutdown process..
> Make cycle detector test less likely to time out again

- src/libponyrt/ds/fun.c
ubsan doesn't like it when unaligned reads happen. this commit fixes things to make ubsan happy.
NOTE: fix uses `memcpy` which at least some compilers optimize well.
See: https://blog.quarkslab.com/unaligned-accesses-in-cc-what-why-and-solutions-to-do-it-properly.html
`runtime error: load of misaligned address 0xb2af29174143 for type 'uint64_t' (aka 'unsigned long'), which requires 8 byte alignment`
> Fix unaligned read in fun.c siphash

- src/common/ponyassert.h
- src/libponyc/CMakeLists.txt
- src/libponyc/ast/ast.c
- src/libponyc/ast/token.c
- test/libponyc/CMakeLists.txt
pony_always_assert was added at some point to help always get backtraces from assertions from ponyc (even in release builds) but it was disabled because it was including debug code in release builds unnecessarily.
this commit ensures that pony_always_assert now only impacts pony_assert (and only for libponyc not libponyrt) to make sure that debug code will not be included in release builds and also only enables pony_always_assert for libponyc and libponyc.tests (and not libponyrt).
> Resurrect pony_always_assert and decouple it from pony_ndebug

- src/libponyrt/mem/alloc.c
Before:
```
out of memory: Cannot allocate memory
```
After:
```
out of memory trying to allocate 18446744073709551615 bytes: Cannot allocate memory
/workspaces/ponyc/src/libponyrt/mem/alloc.c:53: ponyint_virt_alloc: Assertion `bytes < 0` failed.
Backtrace:
./ponyc(ponyint_assert_fail+0xb8) [0xc4de3bb213d4]
./ponyc(ponyint_virt_alloc+0xcc) [0xc4de3bb2d30c]
./ponyc(+0x20a1c) [0xc4de3bb20a1c]
./ponyc(+0x20198) [0xc4de3bb20198]
./ponyc(ponyint_pool_alloc_size+0x50) [0xc4de3bb2009c]
./ponyc(ponyint_heap_alloc_large+0x2d8) [0xc4de3bb1d1d0]
./ponyc(ponyint_heap_alloc+0xcc) [0xc4de3bb1cc00]
./ponyc(pony_alloc+0x74) [0xc4de3bb13044]
./ponyc(Pointer_U8_val_ref__alloc_Zo+0x14) [0xc4de3bb107b0]
./ponyc(String_ref_create_Zo+0x40) [0xc4de3bb0f3e4]
./ponyc(String_val_repeat_str_Zoo+0x6c) …
```
> Print more informative message and backtrace on out of memory error

- src/libponyrt/actor/actor.c
Prior to this commit, if the cycle detector was enabled all actors would run a GC cycle before sending a block message to the cycle detector. This is helpful for actors that are waiting for additional work to be able to release some memory that they don't need but wasteful for zombie actors that the cycle detector will destroy as soon as it receives the block message for them.
This commit changes the logic so that the GC cycle no longer run for zombie actors when they block because the cycle detector will destroy the actor soon anyway.
> Don't run GC for zombie actors when they are blocked

- .release-notes/4616.md
- src/libponyrt/actor/actor.c
- src/libponyrt/actor/actor.h
- src/libponyrt/gc/cycle.c
The logic in the actor run and the cycle detector work together to enable fast reaping of actors with rc == 0. This relies on atomics and protecting the relevant areas of logic with critical sections. This logic unfortunately suffered from a use-after-free bug due to a race between the cycle detector receiving the block message and destroying the actor and the actor cycle detector critical flag being release as identified in #4614 which could sometimes lead to memory corruption.
This commit changes things to remove the need to protect the logic with critical sections. It achieves this by ensuring that an actor with rc == 0 that the cycle detector knows about will never be rescheduled again even if the cycle detector happens to send it a message and the cycle detector is free to reap the …
> Fix use-after-free triggered by fast actor reaping when the cycle detector is active

- src/libponyrt/asio/epoll.c
- src/libponyrt/asio/iocp.c
- src/libponyrt/asio/kqueue.c
There's an ABA condition that can exist with how the ASIO system works in the runtime. There's guard
conditions in various functions to ditch early for scenarios where this is encountered.
A few years ago, some asserts were added to those guard clauses. Unfortunately, that defeats the purpose of the guards and will eventually result in assertions being triggered under load with a debug runtime.
Without completely rewriting how the ASIO system works to be ABA friendly, these asserts are a bad idea. I don't feel up to doing a rewrite at this time, so I am removing the asserts.
> Remove invalid asserts from ASIO system

- examples/dtrace/mbox-size-all-actor-messages.d
- examples/dtrace/telemetry.d
- examples/systemtap/telemetry.stp
- src/libponyc/codegen/codegen.c
- src/libponyc/codegen/genexe.c
- src/libponyrt/actor/actor.c
- src/libponyrt/actor/actor.h
- src/libponyrt/gc/cycle.c
- src/libponyrt/gc/cycle.h
code referring to ACTORMSG_DESTROYED, ACTORMSG_CREATED and the ctx argument to ponyint_destroy are no longer used as the logic has evolved over time and can be removed.
> Remove code related to ACTORMSG_DESTROYED and ctx for ponyint_destroy

- .github/workflows/stress-test-runtime.yml
Improve our coverage some more.
> Add aarch64 Linux stress tests with the cycle detector enabled

- .release-notes/4620.md
- src/libponyrt/actor/actor.c
- src/libponyrt/sched/scheduler.c
- src/libponyrt/sched/scheduler.h
Some scheduler and actor runtime stat printing weren't properly gated by the "should print" check and thus would always print.
Closes #4619
> Fix incorrect printing of runtime stats

- .release-notes/leak.md
- src/libponyrt/sched/mpmcq.c
- src/libponyrt/sched/mpmcq.h
- src/libponyrt/sched/scheduler.c
This reverts commit b5decbaa7def023fd893e2215515b83fad7502bc.
The fix of a theoretical use after free (which is currently not actually an issue) is causing a very real world explosion in memory usage for some programs.
> Fix memory leak

- Makefile
Newer versions of grep were giving warnings when running make using our Makefile.
"grep: warning: stray \ before /"
This commit fixes the cause of the warnings.
> Fix warning from grep when running make

- .release-notes/a.md
- packages/runtime_info/_test.pony
- src/libponyrt/actor/actor.c
- src/libponyrt/sched/scheduler.c
Note this would have been caught much earlier if we were building examples on Windows as part of CI as there is a runtime info example that would fail on Windows.
Closes #4624
> Fix being unable to compile programs that use runtime info on Windows

- Makefile
- make.ps1
- test/full-program-runner/_cli_options.pony
- test/full-program-runner/_tester.pony
All runtime options start with --pony so using --ponyc as an option for the program could result in a naming conflict later.
This renames from `--ponyc` to `--compiler`.
> Rename the --ponyc option to the full-program-runner

- .ci-scripts/macOS-configure-networking.bash
- .github/workflows/stress-test-runtime.yml
Otherwise, most connections will fail to be established because of:
https://web.archive.org/web/20180129235834/http://danielmendel.github.io/blog/2013/04/07/benchmarkers-beware-the-ephemeral-port-limit/
> Configure MacOS networking before running network related stress tests

- .ci-dockerfiles/x86-64-unknown-linux-arch-builder/Dockerfile
- .ci-dockerfiles/x86-64-unknown-linux-arch-builder/build-and-push.bash
- .github/workflows/test-with-latest-tools.yml
This commit adds a daily workflow step that builds a new Arch Linux environment with the latest tools like clang. The environment is then used to build and test a complete ponyc installation (including LLVM and other libs).
This will help us identify breakage against new versions of our supported tools as soon as possible.
> Add workflow to test with "very up-to-date" tools

- .github/workflows/pr.yml
- make.ps1
> Build examples as part of Windows CI

- .release-notes/4628.md
- src/libponyc/expr/match.c
- test/full-program-tests/regression-4612/main.pony
Due to how default method bodies are implemented, we only want to do match checks within the context of the trait, not in the context of the class that has inherited the method.
Closes #4612
> Don't duplicate match checks for inherited trait bodies

- src/libponyrt/actor/actor.c
- src/libponyrt/actor/actor.h
- src/libponyrt/asio/event.c
- src/libponyrt/gc/cycle.c
This might not live on in this fashion for a long time. This at the moment exists for the pony_asserts. However, to make the cycle detector work better, we do want to know if an actor has any live asio events. If it does, we should never mark it as blocked as it isn't. A live asio event means that the actor is capable of getting messages and should never be evaluated for being in a cycle. That change however, is for another day.
> Add live asio event tracking for debugging

- src/libponyrt/platform/ponyassert.c
Prior to this commit, when a pony_assert failed, it would print a message saying "Backtrace functionality not available" on macos.
This commit makes it so macos will now print backtraces on pony_assert failures similar to other platforms.
> Make pony assertions print backtraces on macos

- .release-notes/4647.md
- src/libponyrt/sched/scheduler.c
- src/libponyrt/sched/scheduler.h
- src/libponyrt/sched/systematic_testing.c
Prior to this commit, the systematic testing next thread logic would consider switching to the pinned actor thread even if it was suspended. This was very wasteful since the suspended pinned actor thread would not do any meaningful work and almost immediately re-suspend itself.
This commit changes things so that the next thread logic properly takes into account whether the pinned actor thread is suspended or not when selecting the next thread to activate.
> Make sure systematic testing doesn't switch to suspended thread

- make.ps1
Sometime with Windows stress tests, the process would finish fine but LLDB would return a non-zero exit code for itself thereby failing the process. This was not good.
We will now check the process under test code for success/failure rather than the debugger exit.
> Fix "not really failing" Windows stress tests

- .release-notes/asio-race.md
- src/libponyrt/asio/epoll.c
- src/libponyrt/asio/iocp.c
- src/libponyrt/asio/kqueue.c
The removed code was accessing an event that was also being modified from other threads. In particular, by the TCP Connection actor that the event belonged to (only TCPConnection currently uses one-shot events).
This could lead to all the hilarity that one can expect from things.
Closes #4639
> Fix race condition in epoll ASIO system

- src/libponyrt/options/options.c
Prior to this commit, if someone passed an unrecognized pony runtime option (due to a typo or otherwise), the pony program would silently ignore the argument and keep running without the operator knowing that the intended pony runtime option wasn't applied.
```
root@5babe01f566f:/workspaces/ponyc# ./helloworld --ponyblah
Hello, world.
root@5babe01f566f:/workspaces/ponyc#
```
This commit changes things so that pony programs will now print out an error message and exit with a non-zero exit code when an unrecognized pony runtime option is supplied:
```
root@5babe01f566f:/workspaces/ponyc# ./helloworld --ponyblah
./helloworld: Unrecognised pony runtime option: '--ponyblah'!
Run './helloworld --ponyhelp' for available pony runtime options.
root@5babe01f566f:/workspaces/ponyc#
```
> Make pony programs exit on an unrecognized pony runtime option

- src/libponyrt/actor/actor.c
- src/libponyrt/sched/scheduler.c
Prior to this commit, the actor run stop tracing events could potentially result in a use-after-free if the actor had already been destroyed (by the cycle detector or the fast actor reaping logic) by the time the actor run stop tracing event was issued.
This commit changes the logic so that the actor run start and actor run stop tracing events are now issued from within `ponyint_actor_run` and explicitly issued at a time before the actor is flaged to be destroyed to ensure that there is no possibility of a use-after-free error.
> Fix user-after-free in actor run stop tracing events

- src/libponyrt/actor/actor.c
- src/libponyrt/gc/gc.c
- src/libponyrt/gc/trace.c
- src/libponyrt/tracing/tracing.c
- src/libponyrt/tracing/tracing.h
Prior to this commit, the GC tracing mark events included objectmap sweep and actormap sweep time accidentally..
Now, the mark events no longer includes objectmap sweep and actormap sweep time and the sweep events are further broken down into objectmap sweep, actormap sweep and heap sweep..
> Enhance actor gc tracing to be more correct and precise

- .github/workflows/stress-test-tcp-open-close-macos.yml
- Makefile
This is primarily because Linux completes much faster than MacOS. As part of this change, we will run only 1/10th of the number of connections for MacOS versus Linux.
> Allow setting the number of times we run an open/close stress test

- .release-notes/4666.md
- src/libponyrt/actor/actor.c
Prior to this commit, the following program would result in huge memory usage when `--ponynnoblock` was used.
```pony
use "collections"
use "random"
use "time"
class Notify is TimerNotify
let _a: A
var _m: Main
new iso create(a: A, m: Main) =>
_a = a
_m = m
fun ref apply(timer: Timer, count: U64): Bool =>
_a.done(_m)
false
actor A
new create(m: Main, n: USize) =>
let timers = Timers
let timer = Timer(Notify(this, m), n.u64() * 1_000_000)
timers(consume timer)
be done(m: Main) =>
m.done(this)
actor Main
let n: USize = 100000
var e: USize = 0
let max_num_oustanding: USize = 13
var num_outstanding: USize = 0
let s: SetIs[A] = s.create()
let rand: Random
let t = Time.seconds()
rand = Rand(t.u64())
spawn()
be spawn() =>
if e < n then
while num_outstanding < …
```
> Prevent memory explosion when using ponynoblock in some programs

- src/libponyc/CMakeLists.txt
- src/ponyc/CMakeLists.txt
This fixes libc++ compatibility by checking what C++ implementation exists and then utilizing it. We also only link libgcc if it exists.
This is necessary for https://github.com/NixOS/nixpkgs/pull/396553.
> Fix libc++ compatibility

- .github/actionlint.yaml
- .github/workflows/nightlies.yml
- .github/workflows/pr.yml
This adds checking on PR for Windows on Arm64. I haven't been able to get LLDB working correctly for tests so that is off.
This also adds building nightlies so we can see if there are issues in that workflow.
No changelog entry yet as this is an exploratory change with others to follow if this works out.
> Add partial support for Windows on Arm64

- Makefile
We are seeing some timeouts that look like a test never gets started. By setting to 1 rather than number of real plus fake CPUs, we can see if it is OS resource starvation or something else.
> Set test runner max parallelism to 1

- .github/workflows/pr.yml
For reasons that are unknown to me, the ld.bfd installed in our 32-bit testing environments does not skip over incompatible libraries when attempting to link.
This means if bfd is used, that we can't link programs because it first finds the host environment pony runtime and fails. The ld.gold that is in the environment correctly skips over and finds the correct one.
I spent more time than I should have on trying to fix so that it doesn't ever find the host pony runtime but never got that working. This is the "make it work fix".
This fix is needed because gold has been ejected from binutils as Google has abandoned work on it and no one else has come forward to support so GNU is back to bfd as "the GNU linker".
As the lack of gold rolls out to various Linux distros, we are going to need to …
> Set explicit linker when testing 32 bit cross compiled architectures

- src/libponyc/options/options.c
We have been using the feature forever and it is supported with musl libc. It is not supported with glibc.
> Remove experimental label from `--static` compiler option

- .ci-scripts/aarch64-nightly.bash
- .github/workflows/nightlies.yml
This is an exploratory addition that will help shake out any issues we might have with doing aarch64 builds that get uploaded to Cloudsmith.
We've never done in a Linux aarch64 environment so it is possible this might expose issues that we need to address before we start to provide aarch64 builds and announce them to the world.
> Add aarch64 linux musl nightly builds

- .ci-scripts/arm64-nightly.bash
- .ci-scripts/arm64-release.bash
Our armv8 settings came because that it what was reported as working on m1 macs. However, I had Joe test and armv8-a works fine. -a will be targeted to a more specific set of arm processors including aarch64.
There are "smaller" arm64 processors that are included with armv8 that no one is likely to try to use our prebuilts on so armv8-a is a better floor for us to set.
> Use more appropriate arch when doing arm64 builds

- .github/workflows/update-lib-cache.yml
We only had ones that were used in pr.yml. This includes ones only used in nightlies.yml and release.yml.
Closes #4708
> Add additional builders to our lib update workflow

- .release-notes/4722.md
- src/libponyc/platform/vcvars.c
Turns out the latest SQL Server Management Studio uses the Visual Studio installation system, so ponyc could try to find `link.exe` under its installation instead of Visual Studio's.
This change make sure we're finding an install of Visual Studio itself.
> Make the check for Visual Studio more robust

- .ci-dockerfiles/x86-64-unknown-linux-ubuntu22.04-builder/Dockerfile
- .ci-dockerfiles/x86-64-unknown-linux-ubuntu24.04-builder/Dockerfile
- .dockerfiles/latest/x86-64-unknown-linux-gnu/Dockerfile
- .dockerfiles/latest/x86-64-unknown-linux-musl/Dockerfile
- .dockerfiles/release/x86-64-unknown-linux-gnu/Dockerfile
- .dockerfiles/release/x86-64-unknown-linux-musl/Dockerfile
The legacy format being replaced results in a warning.
> Update Dockerfiles to use new ENV format

- .github/workflows/test-registry-package-dump-event.yml
I am probably going to use for building multiarch image manifests for so I need to get a good idea of what we are getting.
> Add temporary github actions workflow to examine our registry_package events

- .github/workflows/cloudsmith-package-sychronised.yml
- .github/workflows/test-registry-package-dump-event.yml
It appears that if we push an image with the default token, that registry_package events are not sent. This is like how you can't trigger a new workflow from an action using the default github token like using that token to push to main.
This commit updates all our ponyc images that would require multiplatform builds aka all the Linux ones to use a PAT from ponylang-main to push thereby allowing registry_package events to occur.
> Cause registry_package events to get sent
