ponylang/ponyc

- packages/net/buffer.pony
- packages/net/test.pony
These methods allow peeking at the next bytes in the buffer without consuming them. This is particularly useful for parsing protocols that encode strings and other binary sequences by prepending the string length instead of relying on a null terminator or line feed.
> Feature: Add peek methods to net/Buffer.

- packages/builtin/string.pony
There are some two-argument String methods that could benefit from having the second argument be optional, as there is a sensible "default" value that applies implicitly to a wide variety of cases.
Specifically, these methods:
- `String.at` - default to use `offset = 0`
- `String.delete` - default to use `len = 1`
- `String.substring` - default to use `to = -1` (to end of string)
- `String.cut` - default to use `to = -1` (to end of string)
- `String.cut_in_place` - default to use `to = -1` (to end of string)
This PR introduces those default values to enhance the usability of the API without breaking compatibility for any existing code.
> Add default values to last argument in some String methods.

- src/libponyrt/lang/socket.c
This was causing an endless loop and system churn in the
`TCPListener._accept` function when running on systems where
errno is set to `EAGAIN` from `accept` or `accept4`.
From [the man page for `accept4`](http://linux.die.net/man/2/accept4):
> `EAGAIN` or `EWOULDBLOCK`
The socket is marked nonblocking and no connections are present to be accepted. POSIX.1-2001 allows either error to be returned for this case, and does not require these constants to have the same value, so a portable application should check for both possibilities.
> Fix os_accept to handle `ns==-1`, `errno==EAGAIN`.

- packages/files/filemode.pony
Before any_read has instead been set twice.
> FileMode.group() and FileMode.private() now set the any_exec bit

- packages/builtin/asioevent.pony
- packages/builtin/stdin.pony
- packages/net/tcpconnection.pony
- packages/net/tcplistener.pony
- packages/net/udpsocket.pony
- packages/time/timers.pony
The Event type is integral to the builtin (and not builtin) I/O types, so it makes complete sense that it's a builtin type, but I would say that you have to be very careful about naming builtin types, because they are the only names that a user can never use as a type name in their own packages.
In this case, I feel that `AsioEvent` (or perhaps, `IOEvent`) does a better job at describing how this type is used (it is not a generic "event", but is specifically related to IO and the `asio_event_` set of functions, and corresponds to the `asio_event_t` C type), and also leaves the name `Event` open for types in other packages (think `mypackage.Event`, using the namespaced variant of the `use` statements).
If you disagree with this suggestion, feel free to close this.
> Rename builtin type Event as AsioEvent.

- CHANGELOG.md
- README.md
- packages/files/directory.pony
"Mac OS X"/"OS X" should be spelled with a space before the "X". Please pull.
> Correct "OSX" to "OS X".

- Makefile
There is three fixes on this commit:
1- Allow ponyc be installed at any location chosen by the "prefix" make parameter.
2- On ubuntu 14.04 with clan-3.6.2 I was getting error messages about -std=c++11 been used on "C" files.
3- Also on ubuntu 14.04 with clang-3.6.2 I was getting link time errors related to some "rtti" elements not found.
With this changes I was able to compile and install ponyc to a user folder (without need to install anything to /usr/loca/lib/ponyc).
> Fixes to compile on linux

- packages/builtin/platform.pony
- src/common/platform.h
- src/libponyc/pkg/platformfuns.c
- src/libponyc/pkg/platformfuns.h
Hi!
Since Pony seems to target 32 and 64bits Linux, OSX, FreeBSD and Windows, I added checks for the different programming models on those platforms.
> Allow Pony to determine the platform's programming model in use conditions

- src/libponyc/pkg/package.c
If readlink returns FILENAME_MAX as the length of the copied string
then the following `path[r] = '\0'`, where r = FILENAME_MAX is a
1 byte out of bounds buffer overflow.
Fixed by allocating path to be FILENAME_MAX + 1 byte for the NULL
character.
(Bug found [using Coverity](https://scan4.coverity.com/reports.htm#v22790/p11538/fileInstanceId=4743130&defectInstanceId=1281844))
> Fix buffer overrun in add_exec_dir

- packages/debug/debug.pony
Adds Debug.out and Debug.err print facility discouraging direct usage of
@printf and @fwrite when Env is not available. Messages are only printed if
the --debug flag is provided to ponyc, dropped otherwise.
> Add debug convenience utility package

- src/libponyrt/options/options.c
If a match_type is not MATCH_LONG then the match_name
pointer points to p->short_opt which is a single char.
This is passed to strlen a few lines later. This will be
a buffer overrun if short_opt is not the null char.
The fix I'm doing here is to use strnlen and pass the
match_length, which is set to 1 for the case of
a short option.
Bug found using [coverity](https://scan.coverity.com/projects/doublec-ponyc).
> Fix possible buffer overrun in options find_match

- src/libponyrt/options/options.c
This is an alternate fix to the issue that was attempted
to be resolved in commit d1901df1. That fix had problems
with options that are substrings of other options. For
example, --antlr vs --antlrraw.
This fix explicitly checks for a SHORT option and does
not do the strlen test in that case. match_length will
always be 1 and the short option is length one so the
test will succeed.
See pull request #329 for details of the previous fix that was backed out. I'm looking out how the tests are done and I'll try adding some option tests if no one else gets to it.
> Alternate fix to possible overrun in option parsing

- packages/net/http/test.pony
- packages/net/http/url.pony
Previous `URL.build()` implementation was looking for a colon to the left starting from **@**. When password part was omitted it found a colon after the scheme
```
http://user@host
^
```
thus resulting in empty username and `//user` as password.
--
Test case verifies only relevant URL fields as I believe the test should make it clear what's being tested.
> Parse URL with omitted password

- packages/term/readline.pony
Hello.
This fixes a bug in Readline. When the same line is entered twice in a row, either from direct input or from the history, the position in the history isn't updated.
Example:
```
> A
(Press enter)
> B
(Press enter, then up)
> B
(Press enter, then up)
> A
```
> Fix history handling in Readline

- packages/regex/regex.pony
- packages/regex/test.pony
Fixes zero width matches for Regex.split() and pulls all the constant flag values to a primitive at the top.
> Fix zero width matches for Regex.split()

- src/common/platform.h
Only define snprintf if the compiler is older than version 19.0
> Only define snprintf for versions older than VS2015

- packages/ponytest/helper.pony
This matches `expect_error()` declaration. Having parameter `test` as
box allows simpler lambda expression 
``` pony
lambda() ? => error end
```
instead of
``` pony
lambda ref() ? => error end
```
> Accept box test function in TestHelper.assert_error()

- packages/regex/match.pony
- packages/regex/regex.pony
- packages/regex/test.pony
- API is similar to python's Match  https://docs.python.org/2/library/re.html#re.MatchObject.groups
- Fix the handling of group number counting
> Add support for Match.groups()

- packages/files/file.pony
Currently, `File.set_length` will always return `false`, even in success.
This PR fixes the control flow to return the correct boolean value.
> Fix File.set_length return value in success.

- packages/builtin/string.pony
- packages/stdlib/test.pony
When `String.substring()`'s `to` parameter exceeded maximum index, a
result was 1 byte longer than it should.
> Return exact length substring

- packages/builtin/string.pony
- packages/net/http/url.pony
- packages/regex/regex.pony
- packages/stdlib/test.pony
Initial inclusive range implementation was inspired by languages like R,
Julia, Lua. It turned out all these languages are one-indexed whereas
Pony indexes start from 0. After the discussion (see #359) agreement has
been made to change the range to half-open.
> String half-open range

- packages/files/directory.pony
- packages/files/filepath.pony
- packages/files/path.pony
- packages/net/http/payloadbuilder.pony
- packages/options/envvars.pony
- packages/options/options.pony
- packages/term/readline.pony
PR #417 left some uses of `String.substring` and `String.codepoints` unchanged, where they should have been changed to match the changed behavior of the second argument.
This was probably the cause of #427.
This PR fixes the remaining uses of these methods.  I did a full search for these methods on all files in the repo, and compared to the list of those changed in #417.
@andymcn [Here's one spot I wasn't sure about in the JSON package](https://github.com/CausalityLtd/ponyc/blob/873323591465b29d4de5a27d923ec02d9a078f73/packages/json/doc.pony#L423) - I don't understand how this invocation was supposed to work, since `to` will usually be less than `from` here.  I thought I would leave that for you to deal with since you wrote that snippet and I don't understand what's going on there.
> Clean up uses of String.substring and codepoints methods after #417.

- packages/builtin/string.pony
- packages/stdlib/test.pony
Negative offset is relative to string and depends on its size. This
dictates that offset has to be translated to index in the context of
corresponding string.
> Compare substrings when negative offsets given

- src/libponyc/platform/vcvars.c
Windows 10 has a longer ProductVersion size than the current code permits.
> Increase ProductVersion Length

- src/libponyc/platform/vcvars.c
Sets the kernel32 path to the Windows SDK specific path.
Fixes #437.
> Fix kernel32 path

- src/libponyc/expr/operator.c
I am just playing with the language at the moment and I was surprised by the  error message I got (until I wen to read the docs) 
I thought a better error message might help. Perhaps the message could be even more descriptive or specific?
> Better error message for missing ref

- packages/ponytest/ponytest.pony
- packages/stdlib/test.pony
Should have added this in the last commit.
I also fixed a usage message for the PonyTest command line options to match the actual --noprog name.
> Added a unit test for String.bool()

- packages/options/options.pony
- packages/options/test.pony
Fleshed out the unit tests for Options, combining a couple.
Fixed discovered broken Options parsing off-by-one errors. These may have been introduced by the changes to use half-open range for String, and missed due to lack of tests.
> Options tests and fixes

- Makefile
override macports /opt/local/bin/ar, causing all kind of assertions in config=release with lto
also let AR_FLAGS be overridden. i.e. AR=llvm-ar needs rs, not -rcs when
archiving byte-compiled code for lto
> use darwin system AR

- packages/net/ssl/sslinit.pony
- src/libponyc/codegen/genexe.c
- src/libponyc/codegen/genlib.c
and not the macports `/opt/local/bin/ld` variant
to find the 3.6 llvm libdir for the right -fLTO lib.
Fixes #467 and issues with fellow macports folks with
config=release.
See e.g. https://github.com/CausalityLtd/ponyc/issues/456#issuecomment-169082678
who had the same problem as me.
> use darwin system linker

- examples/echo/echo.pony
- examples/yield/main.pony
yield example: fix short -p option
but short options do not work at all anymore
echo example: rename service to port
> examples: various

- Makefile
add install uninstall clean stats deploy prerelease as .PHONY targets
so that an accidental file will not skip this step.
also support verbose=1 to print the commands, for verification
supercedes PR #470 (force_install)
> make: add phony targets, support verbose=1

- packages/options/options.pony
- packages/options/test.pony
we need to strip the matched part of the short option but we forgot with the last remaining "-" string to delete the argument, so that the next iterator will use the correct size
> fix short options processing

- packages/builtin/string.pony
Says it returns the length of the String,
which one would assume is the total number
of characters. However, per conversation with
Sylvan, it in fact returns the number of bytes
that make up the string.
> Correct String.size documentation.

- src/libponyc/pkg/package.c
created by the new emacs flycheck mode.
https://www.gnu.org/software/emacs/manual/html_node/emacs/Interlocking.html#Interlocking
> ignore .#*.pony emacs lock files

- packages/ponytest/ponytest.pony
calling a unit test can cause errors, thus the partial signature
> fix ponytest doc

- packages/builtin/array.pony
- packages/builtin_test/test.pony
Element can be inserted at the very beginning or between existing
array elements. To insert at the very end, however, requires `push()`
to be used. Allowing insertions at the very end makes `insert()`
consistent and `Array` easier to use.
> Allow element to be inserted at the end of array

- src/libponyc/codegen/gencontrol.c
`LLVMBuildLandingPad`'s API changed in a backwards-incompatible way for 3.7.0, but
was then restored in 3.7.1 and later. This change makes the condition for the
call to `LLVMBuildLandingPad` specific to LLVM 3.7.0; all other versions use the
original API.
Tested on LLVM 3.7.1 on 32-bit ARMv7 and 3.7.0 on x86_64, both Linux; all tests
passing.
> Tighten an #if condition: LLVM 3.7.0 has a breaking change fixed in 3.7.1+

- packages/net/http/payloadbuilder.pony
When writing a server and receiving a new request, _payload.status is 0. This
condition was being hit accidentally, preventing the body from being read.
> Parse incoming HTTP request bodies correctly in payloadbuilder

- Makefile
- src/libponyc/ast/lexint.c
- src/libponyc/codegen/codegen.c
- src/libponyc/codegen/gencall.c
- src/libponyc/codegen/genopt.cc
- src/libponyc/codegen/genopt.h
- src/libponyc/codegen/genprim.c
- src/libponyc/codegen/gentype.c
- src/libponyc/expr/ffi.c
- src/libponyc/pass/sugar.c
- src/libponyc/pass/syntax.c
- src/libponyc/pkg/ifdef.c
- src/libponyc/pkg/ifdef.h
- src/libponyc/pkg/package.c
- src/libponyc/pkg/package.h
- src/libponyc/pkg/platformfuns.c
- src/libponyc/pkg/platformfuns.h
- src/ponyc/main.c
- test/libponyc/program.cc
- test/libponyc/util.cc
This pull request adds cross compiling functionality to ponyc. It does not address cross linking and the usual gcc cross compile chain is required for linking.
See: https://github.com/dipinhora/rpxp for an example of use of the cross compiling features in a Linux X86_64 environment targeting a Linux Arm 32 bit environment.
* Update all code generation related bits (codegen, expr, ast, pass,
pkg) in libponyc to dynamically check for target machine features
(OS, architecture, etc) based on LLVM Triple.
* Adjust Makefile for building to 32 bit targets on 64 bit platforms.
* Update test/libponyc/util to call `package_init` in order to
properly intialize compiler for dynamic targets to fix some failing
tests.
* Disable some tests in test/libponyc/program.cc because they fail
when run as part …
> Add cross compiling functionality

- packages/collections/lists.pony
- packages/collections/test.pony
The primitive Lists has the following methods:
```
contains[A: (Any #read & Equatable[A])](l: List[A], a: A): Bool 
drop[A: Any #read](l: List[A], n: USize): List[A]
every[A: Any #read](l: List[A], f: {(A!): Bool} val): Bool
exists[A: Any #read](l: List[A], f: {(A!): Bool} val): Bool
filter[A: Any #read](l: List[A], f: {(A!): Bool} val): List[A]
flat_map[A: Any #read, B](l: List[A], f: {(A!): List[B]} val): List[B]
flatten[A](l: List[List[A]]): List[A]
fold[A: Any #read,B: Any #read](l: List[A], f: {(B!, A!): B^} val, acc: B): B
map[A: Any #read, B](l: List[A], f: {(A!): B^} val): List[B]
partition[A: Any #read](l: List[A], f: {(A!): Bool} val): (List[A], List[A])
reverse[A: Any #read](l: List[A]): List[A]
take[A: Any #read](l: List[A], n: USize): List[A]
take_while[A: Any #read](l: …
```
> Add a suite of helper functions for the list collection with corresponding tests

- packages/builtin/string.pony
- packages/builtin_test/test.pony
String.count would fail to count the last instance of a substring in a string if the substring appeared twice at the end of the string. For example, "atat".count("at") would return 1 instead of 2.
The problem was caused because the loop that drives the search was terminated when the loop index was greater than or equal to the difference in length of the two strings being compared. Because of the way String.count used the String.find method, this was only a problem in situations where finding the second-to-last-string resulted in the index now being equal to the difference in length of the two strings being compared, causing the loop to terminate before finding the last occurrence of the substring.
The solution was to replace `k < j` with `k <= j` in the match search loop.
I added grey-box …
> Fix issue 577 and add tests for String.count.

- src/libponyc/pass/docgen.c
All we are doing is checking to see if the first character of the name is '_'.
This is standard Pony idiom and enforced by the compiler. We can expect
that anyone seeing '_name' knows that it is private and that 'name' is public.
The removed output added little value while cluttering up the documentation.
> Remove public/private output from entity documentation

- src/libponyc/pass/docgen.c
We were displaying both the ? and "can raise an error"
which is redundant. For now, we are going with just the
'?'.
> Simplify partial function documentation formatting

- packages/builtin/maybe.pony
- packages/builtin_test/test.pony
- src/libponyc/codegen/codegen.c
- src/libponyc/expr/ffi.c
- src/libponyc/expr/reference.c
- src/libponyc/type/subtype.c
This patch is for #567: it renames Maybe[A] to MaybePointer[A] in Pony code.  The tests pass on Linux.  I didn't rename any of the internal compiler functions (e.g. `is_maybe()`) -- should I do those as well?
> rename Maybe[A] to MaybePointer[A]

- src/libponyc/pass/docgen.c
Hi, I've been lurking on the mailing lists for a few weeks, and I had some time to start looking at a couple of the easy issues.
This patch for #585 sorts behaviours and functions for classes and actors by whether or not they are public or private.  The generated documentation shows (if any exist):
- Public Behaviors
- Public Functions
- Private Behaviors
- Private Functions
The patch also fixes a bug I found where the `docgen->package_file` field was not initialized.
Tests pass on Linux.
> make doc generator sort behaviors and functions by public/private

- src/libponyc/ast/symtab.c
- src/libponyc/expr/postfix.c
- src/libponyc/expr/reference.c
- src/libponyc/pass/docgen.c
- src/libponyc/pass/import.c
- src/libponyc/pass/names.c
- src/libponyc/pass/names.h
- src/libponyc/pass/sugar.c
- src/libponyc/type/lookup.c
This is my patch for #576.
I added the functions to `pass/names.h`/`pass/names.c` and included that header where needed. Was that the right place?
I wasn't sure if, or where, to add tests for these new functions.
> Centralize checks for names being private, types, internal tests, and FFI declarations

- .travis.yml
There's numerous issues with the formatting in the readthedocs
theme. Material is far from perfect but it displays the docs
in a more readable format.
This is a short term fix on the way to a theme that works better
for the Pony standard library docs.
> Switch to material theme for docs

- src/libponyc/pass/docgen.c
Will organize into public and private for non-testing related
entities and into testing/non-testing entities.
Public Entities
Private Entities
Testing Entities
After talking to Sylvan, once this is accepted, I will
rename from 'entities' to 'types'
> Organize package entities by visibility and purpose

- src/libponyc/pass/docgen.c
As Sylvan pointed out, they are types.
AND he prefers they be referred to that way.
> Rename 'entities' to 'types' in package documentation

- packages/ponytest/ponytest.pony
Otherwise they end up getting smushed together.
Intent of original formatting is lost.
> Format list as markdown list in ponytest documentation

- README.md
This adds the `apt-get` incantations required and notes that `pcre2` needs to be installed by source. Instructions for that are included.
> Add instructions for installing prerequisites on Linux

- CHANGELOG.md
- src/libponyrt/gc/gc.c
Magically GC code exists that will attempt to
"force free" data that is not referenced in the
allocating actors working set when release messages
arrive.
It shouldn't do this for anything with a finalizer.
It would be bad. BOOM! bad if that was to happen.
> Don't "force free" memory of objects with finalizers

- CHANGELOG.md
- packages/builtin/string.pony
- packages/builtin_test/test.pony
This fixes the bug described in #638. I also added some unit tests for the function, as there was none.
> String.compare() bug and unit tests

- packages/net/test.pony
- packages/signals/test.pony
This PR fixes the names of test `timed_out` callback functions.
The name of this test case callback function was changed from `timedout` to `timed_out` in b88f6da, but that commit forgot to also change the these callback function implementations, so they were implementing functions with the wrong (old) name.
Because they were using the wrong name, when a test timed out and [the test runner called `timed_out`](https://github.com/ponylang/ponyc/blob/ff4b7d6f4c843c3eb30d8862c9445814c0465e93/packages/ponytest/runner.pony#L155) to clean up assets, it deferred to [the default implementation that does nothing](https://github.com/ponylang/ponyc/blob/ff4b7d6f4c843c3eb30d8862c9445814c0465e93/packages/ponytest/unit.pony#L27-L35).  Consequently, the assets were never cleaned up, and in the case of …
> Fix names of test `timed_out` callback functions.

- CHANGELOG.md
- src/libponyc/codegen/codegen.c
- src/libponyc/codegen/genexe.c
- src/libponyc/codegen/genobj.c
- src/libponyc/codegen/genopt.cc
- src/libponyc/pass/pass.c
- src/libponyc/pass/pass.h
- src/libponyc/pkg/package.c
- src/ponyc/main.c
This patch adds a command-line argument (per #569) `--verbose=N`, where N is from 0 to 4.  Various things are printed for verbosity >= N:
- 0: only errors are printed
- 1: compilation stages, e.g. "Generating", "Linking"
- 2: optimization and package info, e.g. "Building stdlib\regex..."
- 3: external tool command lines, e.g. for linking
- 4: currently nothing...
> add verbosity level as a command line argument

- examples/echo/echo.pony
- examples/files/files.pony
- examples/httpget/httpget.pony
- examples/httpserver/httpserver.pony
- examples/mandelbrot/mandelbrot.pony
- examples/net/listener.pony
- examples/net/net.pony
- examples/net/pong.pony
- minimal-cases/issue-629/629.pony
- packages/files/filepath.pony
- packages/files/test.pony
- packages/glob/test.pony
- packages/net/auth.pony
- packages/net/dns.pony
- packages/net/http/client.pony
- packages/net/http/clientconnection.pony
- packages/net/http/requestbuilder.pony
- packages/net/http/server.pony
- packages/net/http/serverlistener.pony
- packages/net/ipaddress.pony
- packages/net/ssl/sslcontext.pony
- packages/net/tcpconnection.pony
- packages/net/tcplistener.pony
- packages/net/test.pony
- packages/net/udpsocket.pony
This is based on @dckc 's work on capability-secure networking.
The idea is to use primitives as authorisation tokens, so that
higher level interfaces can be built that hold those primitives,
but can do additional validation. For example, an application
might want to limit the ports that can be listened on. To do so,
pass a class that can construct a TCPListener (by holding a
TCPListenerAuth token) but will only do so for a specified port
range.
> Use primitives for capabilities-secure networking

- examples/readline/main.pony
Having a fixed command set isn't particularly realistic.
Modified the readline example to record commands entered
so they can be part of command history for completion.
> Store command history in Readline example

- README.md
- src/libponyc/codegen/genexe.c
- src/libponyc/platform/vcvars.c
- test/libponyrt/mem/heap.cc
After my premature tweet yesterday I can build PonyC and run the tests on Windows.  This PR contains a couple of code fixes, and an updated description of the steps I took in the README.
Note that to get the libraries I needed, I made a small utility that gets and builds libpcre2-8.lib and gets a binary of libssl-32.dll and libcrypto-32.dll from LibreSSL.  I mention this in my changes to the README; I hope that's OK.
> add Windows build details to readme

- src/libponyc/codegen/genexe.c
- src/libponyc/codegen/genlib.c
- src/libponyc/codegen/gentype.c
- src/libponyc/pass/docgen.c
This PR updates compiler printf statements from the recent rewrite to use the new PONY_LOG macro, which checks the desired verbosity level.
> check verbosity flag for compiler messages

- src/libponyc/ast/lexer.c
This PR adds string representations for the `TK_FORMALVALUEARG` and `TK_FORMALVALUEPARAM` tokens, which were previously missing.
> Add string representations for TK_FORMALVALUE* tokens.

- examples/mailbox/main.pony
Most people come across it and aren't aware that it's a
stress test that should result in large amounts of memory
usage.
> Add explanation to Mailbox example

- CHANGELOG.md
- src/libponyc/codegen/genexe.c
- src/libponyc/pkg/program.c
- src/libponyc/pkg/program.h
- test/libponyc/program.cc
Add a new parameter, rpath_preamble, to program_lib_build_args
(libponyc/pkg/program.c). If this argument is non-null, then for
all library paths from the source code, command line, and PONYPATH
environment variable, add rpath_preamble plus the libpath to the string
used as a linker command line. For Linux and FreeBSD, modify the calls
to program_lib_build_args to use "-Wl,-rpath," as the rpath_preamble. For
Windows and Mac OS X, pass NULL as rpath_preamble.
Previously, if a dynamic library were in a non-standard location, the
library could not be found at run time.  The -rpath argument includes
the paths on the run time dynamic library search path, allowing dynamic
libraries to be found in non-standard locations.
The OS X linker appears to add the -L paths to the executable's search
path …
> Add -rpath to the link command for library paths

- packages/term/readlinenotify.pony
In version 0.2.0, the interface for `ReadlineNotify` changed from return values and exceptions to promises, but the documentation wasn't updated.
> Update ReadlineNotify documentation

- CHANGELOG.md
- Makefile
This is a fix for #648. I'm not a Makefile expert, so feel free to say if there is a better way to do it.
> Do not enable LTO if LLVMgold isn't found

- .travis.yml
Something is broken with the LLVM 3.8 package fetching in Travis' new Ubuntu Precise platform. So we disable it for now until it can be investigated and fixed later.
> Disable Linux + LLVM 3.8 build on Travis CI for now.

- src/libponyc/codegen/gendebug.cc
- src/libponyc/codegen/genopt.cc
- src/libponyc/codegen/host.cc
This PR contains a few minor fixes for building on Windows with LLVM 3.8.
The LLVM headers contain a couple of redundant "inline" modifiers, which Visual C++ warns on.  Also, Visual C++ warns on "converting a 32-bit shift to 64 bits".
> fixes for Windows compile

- CHANGELOG.md
- packages/collections/map.pony
- packages/collections/test.pony
Hashmap.contains was calling apply within a try...else...end. This change
cuts out the middleman, just calling _search.
Fixes #678
> Simplify HashMap.contains

- src/libponyc/pass/docgen.c
Previous we were only checking a types provides list
which wouldn't identify tests when they were like
trait _TopTest is UnitTest
trait _RefinedTopTest is _TopTest
_RefinedTopTest would be listed as a private type rather than
as a test type. Logger and its _StringLogger test exposed this
flaw.
> Identify additional test types as test types

- src/libponyc/pass/docgen.c
If a package doesn't have a category of types, ie
no private types or no test types, they shouldn't
be displayed.
Previously this was like
Public Types
* type
* type
Private Types
Test Types
* test type
It will now be
Public Types
* type
* type
Test Types
* test type
> Remove unused type categories from documentation

- CHANGELOG.md
- Makefile
- README.md
As discussed in #690. I also renamed the Makefile variable `LTO` to `LTO_PLUGIN` to clarify its role and to avoid confusion with `lto` in lowercase.
> Drop dynamic LTO detection in the build system

- CHANGELOG.md
- packages/builtin/array.pony
- packages/builtin_test/test.pony
The `ArrayValues.rewind()` method "rewinds" so that subsequents calls
to `next()` return items starting from the first item in the array.
This came as a result of a conversation with Sylvan. There was a
situation where it made sense to have `rewind()` as part of
`ArrayValues`, but we didn't think it made sense to make it part of
the `Iterator` interface.
> Add `ArrayValues.rewind()` method

- CHANGELOG.md
- packages/builtin/array.pony
- packages/builtin_test/test.pony
Add a parameter `predicate` to the `find` and `rfind` methods of Array
that accepts a lambda returning Bool, which replaces the `is` test in
the methods. By default, to maintain current behavior, this predicate
is passed a lambda that uses an `is` test, but it can be replaced with
a test using equality or any other binary predicate.
Add tests for find and rfind.
Fixes #659
> Paramaterize Array.find/rfind on a comparator

- src/libponyc/ast/frame.c
- src/libponyc/ast/frame.h
- src/libponyc/pass/flatten.c
- src/libponyc/type/cap.c
- src/libponyc/type/compattype.c
- src/libponyc/type/compattype.h
- src/libponyc/type/matchtype.c
- src/libponyc/type/matchtype.h
- src/libponyc/type/subtype.c
- src/libponyc/type/viewpoint.c
- src/libponyc/type/viewpoint.h
- test/libponyc/matchtype.cc
- test/libponyc/type_check_subtype.cc
An intersection type represents multiple views on to the same
object. As such, every view in an intersection type must be
locally compatible with every other view. This check is introduced
in the flatten pass (and skipped for provides lists and constraints
as they do not represent actual object view). As a result, the
subtyping check for intersection types is simplified to the natural
form, i.e.:
T1 <: T3 or T2 <: T3
---
(T1 & T2) <: T3
> Check local compatibility for intersection types

- README.md
This is to make sure no one else suffers the pain of #692.
Let me know if there's a better spot to put this. It might only apply to Linux or sufficiently new GCC versions or something, too; that's hard to debug.
> Update README with comments on running in VirtualBox

- src/libponyc/type/alias.c
Use viewpoint_lower() on arrow types when considering whether or
not they are sendable.
> Treat more arrow types as sendable

- src/libponyc/pass/docgen.c
The order that we put definitions in source files is more
meaningful than alphabetizing. With this change, we preserve
the alphabetizing ONLY for package level. This makes sense,
the programmer hasn't provided explicit ordering for the
packages that make up the program, but they have for the types
that make up the various packages and modules.
> Only sort program level documentation elements

- src/libponyc/codegen/genexe.c
- src/libponyc/reach/reach.c
When compiler verbosity is set to maximum (ie 4), print out a the
complete reachability analysis results, including vtable sizes and
vtable indices for all types and methods.
> Verbose reachability

- src/libponyc/reach/reach.c
Prevent a double-free situation by duplicating the AST node that
represents a tuple field in the reachability phase.
> Dup AST nodes for tuple fields in reachability

- src/libponyc/pass/docgen.c
Before this commit, we printed "optional" next to parameters
that came with default values. Nice, but not as useful as
knowing what that value is.
This change should had "straight forward" defaults. If the default
is a complex expression, it will probably render like shit and per
this discussion: https://pony.groups.io/g/dev/thread/724212#15,
we'll need to revisit and improve that printing. However, this commit
should work for just about everything that is currently in the
stdlib.
Closes #682
> Print default values in documentation

- src/libponyc/pass/docgen.c
But that wasn't accounted for by the previous code. It
was only displaying caps for TK_FUN (functions) not
TK_NEW as well (constructors).
> Constructors can have capabilities

- CHANGELOG.md
- packages/stdlib/test.pony
- packages/time/nanos.pony
- packages/time/test.pony
This PR adds the `time.Duration` primitive with utility functions for converting various durations of time to nanoseconds, for passing to other functions in the `time` package.
This was discussed in #547.
Note that the first set of functions takes a `U64`, which should be fast for inlining, but there is a second set of functions for the case where you want to pass a `F64`, which I also imagine might be quite common ("timeout after 1.5 seconds" somehow seems more direct than "timeout after 1500 milliseconds").  I wanted to do this with a type parameter, but it looked like there wasn't a good way to do this while preserving the efficiency of the `U64` versions of the functions (let me know if there is a clever trick for this).
> Add time.Nanos primitive with utility functions for time conversion.

- src/libponyc/pass/docgen.c
Given that constructors can be partial, it makes a lot of sense to do this.
> Display return types for constructors in docs

- test/libponyc/literal_inference.cc
- test/libponyc/util.cc
- test/libponyc/util.h
More tests for #570.
Move to finding literals directly by value rather than by crawling around from other constructs.
Add tests for inference in parameters, returning a value and using a returned value, type aliases, binary expressions, arrays, if, while, match, try and for. So, certainly not all constructs covered, but a fair proportion.
Tests for arrays and for required extending the faked up builtin types declared at the top of test/libpony/util.cc
> Strengthen numeric literal type inference tests

- src/libponyc/pkg/package.c
- src/libponyc/pkg/package.h
- src/libponyc/ponyc.c
- src/libponyc/ponyc.h
- src/ponyc/main.c
- test/libponyc/util.cc
This patch for #574 collects compiler init and shutdown functions in new functions ponyc_init() and ponyc_shutdown().
The test framework's PassTest::build_package() doesn't use them, as it seems to rely on some other things that I haven't investigated yet.
> reorganize compiler init and shutdown (#574)

- src/libponyc/pass/flatten.c
It's possible to hit the flatten pass on types that have already
been flattened, for example when generating an anonymous type for
a lambda. Instead of asserting that the child count is 2, the
flatten step can be skipped if the child count is greater thant 2.
> Don't assert on union/isect flatten

- README.md
- premake5.lua
This patch adds a character set option to the Windows premake definition file so you don't have to change your projects' character sets manually.
> tweak to Windows premake file to avoid manually setting project char sets

- CHANGELOG.md
- packages/collections/set.pony
- packages/collections/test.pony
Because often:
```pony
if my_set.contains(element) then
do_something()
else
do_something_else()
end
```
is clearer and more convenient than:
```pony
try my_set(element)
do_something
else
do_something_else()
end
```
> added contains function to HashSet[A] with relevant tests

- src/libponyc/expr/control.c
- test/libponyc/recover.cc
- test/libponyc/util.cc
- test/libponyc/util.h
This PR adds some tests for the semantics of `recover ... end` blocks.
My next PR is going to be mucking around with auto-recover for #702, so I thought it would be a good idea to get some of the semantics of `recover` under test so I can be sure I'm not breaking anything important.
These tests may not cover 100% of what it means to `recover`, but it's a start.  We can always add more as we find missing coverage and/or regressions in the future.
> Add some tests for recover semantics.

- packages/net/ssl/sslinit.pony
- src/libponyc/codegen/genexe.c
- src/libponyc/expr/reference.c
- src/libponyc/pass/flatten.c
As pointed out by @dckc, primitive _init taking an Env as an
argument gives ambient authority to any package declaring a
primitive with an _init function. Since these functions are
meant primarily for initialising FFI libraries, access to Env
isn't needed. If a use case appears where some part of Env is
needed, this can be revisited.
> Primitive _init now takes no arguments

- packages/builtin_test/test.pony
- packages/collections/test.pony
`UnitTest.apply` used to use the return value of the function body, but now these dangling `true`s are a useless remnant of a bygone era.
This PR removes them.
> Remove useless true return values in stdlib/builtin UnitTests.

- README.md
As discussed in Issue #649 I've changed the README.md file to update the LLVM install instructions for Linux using the recently updated builds in the LLVM APT repository.
I left the instructions for Debian unchanged since I haven't actually tested that, but I think they are probably exactly the same now as for Ubuntu and could be redundant.
> Updated LLVM install instructions for Linux

- src/libponyc/pass/docgen.c
Previously we printed out that a type alias
"Implements" the types it provides. Not exactly
correct. Will now say "Type Alias For".
> Clarify type alias documentation

- src/libponyc/codegen/codegen.h
- src/libponyc/codegen/genexe.c
- src/libponyc/codegen/genheader.c
- src/libponyc/codegen/genlib.c
- src/libponyc/codegen/genprim.c
- src/libponyc/codegen/gentype.c
- src/libponyc/reach/reach.c
- src/libponyc/reach/reach.h
- test/libponyc/paint.cc
Rather than pass around a supporting stack and next type id, use
an encapsulating structure. This allows more supporting reachability
data structures without affecting every method signature.
> Use an encapsulating reach_t structure

- CHANGELOG.md
- packages/builtin/stdin.pony
This PR adds a chunk_size argument to Stdin.apply, allowing the user to set a custom size for chunks reported to the notifier.
> Allow user to set custom chunk_size for Stdin notifications.

- Dockerfile
- README.md
This PR adds a Dockerfile for automated builds.
This should be an easier way for some users to try the latest revision of ponyc master, without having to actually build from source.
Think of it like a kind of nightlies, but it actually happens on every commit and it's only in docker.
> Add Dockerfile for automated builds.

- Dockerfile
implements changes described in issue #775
> use ubuntu:16.04 base image to simplify dependencies

- packages/capsicum/caprights.pony
- packages/files/filecaps.pony
- packages/process/process-monitor.pony
- packages/process/process-notify.pony
- packages/process/test.pony
- packages/stdlib/test.pony
This package gives you control over an external process. You
can spawn any process and have control over STDIN, STDOUT and
STDERR of the spawned process. All communications is done via
async IO and will not block. Any errors during operation related to
system calls are surfaced to the caller as ProcessError via the
notifier.
> Add process package that enables control of external processes [pr# 3]

- Dockerfile
implements fix as described in issue #780
> Dockerfile to build only config=release files, remove after install

- packages/collections/persistent/map.pony
- packages/collections/persistent/test.pony
This PR renames tests so that they better describe what collection they test and renames private map classes so that they don't collide with classes for future collections.
> rename tests for collections/persistent

- packages/collections/persistent/map.pony
- packages/collections/persistent/test.pony
This should have been USize considering that other collections use USize as the return type for their size methods. It was an oversight on my part.
> return usize with size method

- examples/delegates/main.pony
The old delegate example code didn't really demonstrate what a
delegate did, which was confusing for me when I initially started to
try to use delegates. It creates several objects, some of which are
used as delegates, but then calls those objects directly. To
demonstrate delegation, the delegate should be set to one of those
classes, and then the delegating object should be called to
demonstrate that it is delegating the call to the delegate. This
commit implements that behavior.
> Improve delegate example code

- CHANGELOG.md
- src/libponyc/expr/call.c
- src/libponyc/expr/ffi.c
- src/libponyc/expr/lambda.c
When building a lambda capture and not specifying a type, the
captured type should be the alias of the captured expression.
> Alias lambda capture types

- CHANGELOG.md
- packages/net/tcpconnection.pony
- packages/net/tcpnotify.pony
- packages/net/test.pony
This PR adds the `sentv` method to `TCPConnectionNotify`.
This gives the `TCPConnectionNotify` object the option to treat `writev` calls differently from `write` calls, for protocols where this affects the final encoding of the bytes.  For example, this feature will be used in the [`pony-zmq`](https://github.com/jemc/pony-zmq) redesign, where it is vital to making CURVE encryption work with no intermediate actor.
> Add sentv method to TCPConnectionNotify.

- packages/collections/persistent/list.pony
- packages/collections/persistent/test.pony
This PR makes the `collections.Persistent.List` class conform to the `ReadSeq` interface, including implementing `apply` and `values`.
> Make collections.Persistent.List conform to ReadSeq interface.

- packages/collections/persistent/map.pony
This PR just removes the option for entries to be None since the compression has made it obsolete.
> remove None entries in persistent/Map

- packages/promises/promise.pony
Added package-level documentation for the promise package. The
documentation explains how promises work and gives two examples of how
they can be used.
> Add package documentation for promises

- src/libponyc/ast/id.c
Close #755
Current version will suggest variable name start with
underscore, which is not accepted by the compiler however
> fix wrong suggestion in error message

- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- README.md
This PR reformats markdown files to avoid hard wraps in favor of soft wrapping by our text editors and doc renderers.  It also makes this policy clear in `CONTRIBUTING.md`.
See some discussion here: https://github.com/ponylang/pony-for-x/pull/1#issuecomment-217628633
> Avoid hard wraps in markdown files.

- CHANGELOG.md
- packages/net/test.pony
- packages/ponytest/helper.pony
- packages/ponytest/runner.pony
Last week when I was working on some TCP tests in the `net` package (and my own tests in other packages), I noticed that it's quite onerous to write non-trivial async tests with `ponytest`. Particularly,
* When you have actors to be disposed of (like  when the test is over (even in a timeout or early fail), it required creating a separate "manager" actor to dispose of, and calling `fail` on the manager instead of `complete` on the `TestHelper` directly.  This feature (disposing of `DisposableActor`s when the test is over) can be built directly into the `TestHelper` and `TestRunner` and remove the need for these intermediate manager actors entirely.
* When you have a complex asynchronous test, you want to be able to test that it reaches various checkpoints (that I called "actions"). When …
> Add more ponytest TestHelper convenience methods for async tests.

- CHANGELOG.md
- packages/builtin/arithmetic.pony
- packages/builtin/float.pony
This is very useful when manipulating NaNs.
> Add copysign function for floating point numbers

- CHANGELOG.md
- packages/builtin/arithmetic.pony
- packages/builtin/float.pony
- packages/builtin_test/test.pony
I think having this function could be good because using `finite` and `nan` to check infinity can add complexity to the code and is quite obscure to people unfamiliar with floating point numbers.
> Add infinite function for floating point numbers

- CHANGELOG.md
- src/libponyrt/gc/gc.c
- src/libponyrt/gc/gc.h
- src/libponyrt/gc/trace.c
- src/libponyrt/pony.h
As discussed in #675. Please do not merge yet.
This is the algorithm @sylvanc suggested. My implementation seems to work in all 4 cases (local acquire/local release, remote acquire/local release, local acquire/remote release and remote acquire/remote release) but there are some issues to resolve.
- What if the memory wasn't Pony-allocated? Should we assert or just let it crash?
- Currently, acquiring an object more than one time is possible and requires multiple releases to allow collection. Is this a problem?
- Should we have separate functions for local and remote like the other functions in `gc.c`?
- Do we need unit tests for this? Maybe as a separate PR?
- Are the function names right?
- Are the function parameters right?
> Add acquire/release GC tracing

- CHANGELOG.md
- src/libponyrt/actor/actor.c
- src/libponyrt/actor/messageq.c
- src/libponyrt/pony.h
As discussed in #796.
I also renamed some index variables misleadingly named `size` to keep things clear.
> Add pony_alloc_msg_size runtime function

- packages/collections/persistent/map.pony
- packages/collections/persistent/test.pony
The updated test previously failed since collision nodes were not counted when adding up all the entries.
> fix persistent/Map size() method

- CHANGELOG.md
- Makefile
Building on Arch Linux, using gcc 6.1.1 and LLVM 3.7.1, fails with
the error:
/usr/include/c++/6.1.1/cmath:45:23: fatal error: math.h: No such file or directory
#include_next <math.h>
Avoiding the use of -isystem if the LLVM include directory is already
on the search path should avoid the problem.
This fixes #797
> Only use -isystem for LLVM if the directory is not already on the path

- Makefile
The fix introduced in #824 added a stray slash in the build commands when
`llvm.include` was empty, which caused build failures.
> Fix build issue in Makefile

- CHANGELOG.md
- packages/net/http/payloadbuilder.pony
- packages/net/http/requestbuilder.pony
- packages/net/http/responsebuilder.pony
- packages/net/readbuffer.pony
- packages/net/test.pony
- packages/net/writebuffer.pony
The WriteBuffer provides a way to build messages using convenience
functions for common data encodings. It is complementary to the
ReadBuffer (formerly Buffer) which is used to extract information from
a message.
As part of this change I renamed Buffer to ReadBuffer to make its
purpose more clear.
> Add net/WriteBuffer

- CHANGELOG.md
- src/libponyc/ast/error.c
- src/libponyc/ast/parserapi.c
- src/libponyc/ast/treecheck.c
- src/libponyc/codegen/codegen.c
- src/libponyc/codegen/genexe.c
- src/libponyc/codegen/genlib.c
- src/libponyc/codegen/genobj.c
- src/libponyc/codegen/genopt.cc
- src/libponyc/codegen/gentype.c
- src/libponyc/pass/docgen.c
- src/libponyc/pass/pass.c
- src/libponyc/pass/pass.h
- src/libponyc/pkg/ifdef.c
- src/libponyc/pkg/package.c
- src/ponyc/main.c
Currently, all error and info and diagnostic output is logged to stdout.  This is a problem for dumping ASTs from earlier passes, which are also sent to stdout.  It seems more correct to dump AST output to stdout (as output of the program), and send all errors and info and out-of-band compiler messages to stderr.
> Print error and info messages to stderr instead of stdout.

- src/libponyc/codegen/genfun.c
Previously, this line of code always switch to the return type for
gen_assign_cast if the return type was a tuple. This is needed in
order to codegen the right LLVM return type. However, if the body
type is also a tuple, then the body type, rather than the result
type, should be passed to gen_assign_cast so that the correct
boxed type can be chosen by gen_box if necessary.
> Generating tuple return value with tuple bodies

- src/libponyc/codegen/codegen.c
- src/libponyc/codegen/codegen.h
- src/libponyc/codegen/gencall.c
- src/libponyc/codegen/gencontrol.c
- src/libponyc/codegen/genexpr.c
- src/libponyc/codegen/genident.c
- src/libponyc/codegen/genident.h
- src/libponyc/codegen/genmatch.c
- src/libponyc/codegen/genoperator.c
- src/libponyc/codegen/genopt.cc
- src/libponyc/codegen/genprim.c
- src/libponyc/codegen/gentype.c
The LLVM load-combine pass can produce invalid results when
combining i1 loads. Previously, it was believed this only
happened on OSX, so the load-combine pass was disabled on OSX.
However, a Linux test case has been found.
The performance cost of disabling load-combine is high. Switching
to representing Bool as i8 instead of i1 has no runtime cost, and
may actually improve performance depending on how LLVM was storing
sequences of i8 in structures.
The load-combine pass is now re-enabled on all platforms.
> Use LLVM i8 for Bool instead of i1

- src/libponyc/codegen/genopt.cc
The BBVectorize pass was producing incorrect results for some
floating point vectorisations. Use the SLPVectorize pass instead,
enable MergeFunctions to reduce binary size, and disable debug
info on optimised builds until the debug info produced by ponyc
no longer causes problems post-optimisation.
> Remove BBVectorize pass

- .gitattributes
Git being a non-semantic tool can't tell when changes to the same
line are additive or exclusive. This really comes to the fore for
us with the CHANGELOG.md file where multiple people will be adding
entries at the same time. The default for git it is assume they
are exclusive changes. Usually, this is the correct assumption,
however with the CHANGELOG.md, it is not.
This commit changes merges of CHANGELOG.md to use the "union"
merge strategy. It is described in the Git book as:
Instead of leaving conflicts in the file, resolve conflicts favouring
our (or their or both) side of the lines.
You can read more about git merge strategies at:
https://git-scm.com/docs/git-merge-file
> Fix annoying, constant CHANGELOG merge conflicts

- .gitattributes
Utilize git attibutes (https://git-scm.com/docs/gitattributes) to
make sure we have 2 space indent, no tabs for indent, no trailing
whitespace and lf as our line ending.
> Set basic attributes on standard source files

- CHANGELOG.md
- src/libponyrt/gc/cycle.c
- src/libponyrt/gc/gc.c
- src/libponyrt/gc/objectmap.c
- src/libponyrt/gc/objectmap.h
Previously, something resent as immutable was fully traced. This
was to protect against a premature free on release when the object
was not reachable by the owner. However, it resulted in an off-by-
one error in the RC and a memory leak.
Now, objects resent as immutable need not be fully traced, which is
a performance optimisation as well as removing the memory leak. As
a result, reachability on locally owned objects that have been sent
in messages is no longer tracked, so a release message can't result
in an immediate free (a gc cycle has to happen).
> Memory leak when iso send is resent as val

- CHANGELOG.md
- packages/collections/map.pony
Allows for code such as:
```pony
Map[String, String].concat([
("hi", "there"),
("sailor", "boy")].values())
```
> Have HashMap.concat return `this` rather than `None`

- packages/builtin/string.pony
Previously, it was copying _alloc bytes from the array, when the
array did not have _alloc bytes available. This would often succeed
due to an extra byte being read not causing a problem. However, for
a zero-length array or an array aligned right on a page boundary,
this would segfault.
Copying _size bytes always works, even for a zero-length array.
> String.from_array should copy _size bytes

- packages/process/process-monitor.pony
In the child branch of a fork(), it is normally incorrect to use
exit(), because that can lead to stdio buffers being flushed
twice, and temporary files being unexpectedly removed.
> Fix exit call to use _exit instead which is safer for a chile process

- CHANGELOG.md
- src/libponyc/pass/syntax.c
- test/libponyc/badpony.cc
> Fix compiler crash on object literal with uninitialized fields.

- packages/process/process-monitor.pony
- EAGAIN needs to return 11 on Linux and 35 on OSX and FreeBSD
- O_NONBLOCK needs to return 2048 on Linux and 4 on OSX and FreeBSD
> Add primitive to deal with EAGAIN and O_NONBLOCK values on Linux and OSX

- examples/httpserver/httpserver.pony
Makes it clear that only the cast to 'AmbientAuth' can fail
> Refactor examples/httpserver

- CHANGELOG.md
- src/libponyc/pass/docgen.c
- src/libponyc/pass/sugar.c
In generated documentation, replace the use of hygienic, generated
names for anonymous function types with a nice name based on the type
of the function. Generated names have the form of `$0$1` and are less than useful.
This change associates a nice name with function types based on the
`{(ISize):ISize}` syntax and uses that name in generated documentation.
Additionally, this change adds the reference capability for the function
to the nice name, as in `{ref(ISize):ISize} ref`.
There were actually two (and a half) problems involved in this issue: 
* `doc_type` in docgen.c was using `ast_name` for anonymous function types; `ast_name` for lambdas is generated hygienically as *$M$N*. This was trivially fixed by using `ast_nice_name`.
* (The half-problem.) `doc_type` was generating a broken …
> Use the nice name for types when generating documentation (#872)

- packages/builtin/int.pony
`ISize` is 32 bits only on ILP32.
No changelog entry since `ISize` was introduced in the 32 bits port, which isn't part of a release yet.
> Fix ISize.min/max_value on LLP64

- CHANGELOG.md
- src/libponyc/ast/lexer.c
- test/libponyc/lexer.cc
Previously the lexer accepted `7___4_9__.6_` as a numeric literal. This
change reports an error for duplicated underscore and underscores
terminating the literal.
This fixes #765
> Allow only single, internal underscores in numeric literals (#765)

- src/libponyc/codegen/codegen.c
This avoids redundant calls in generated code after inlining. `pony_ctx` always returns the same pointer from within a single behaviour so this is safe.
> Mark pony_ctx as readnone in LLVM IR

- packages/net/tcpconnection.pony
- packages/net/test.pony
TCPNotify has a method you can override to change
expect value when expect is called, however,
prior to this the notifier was never called by
TCPConnection resulting in lots of intersting issues
if you were relying on that to be called.
> Call notifier when expect is called

- src/libponyc/pass/names.c
- test/libponyc/badpony.cc
This PR fixes #901 by setting name resolution pass errors to be fatal.
This stops some more exotic forms of type alias recursion (such as
when a type aliases a union or tuple, where one of the elements has
the type alias as a type parameter), by not allowing the compiler
to continue after it has detected a recursion.
A possible downside of this change is that *all* name resolution
pass errors will be treated as fatal, meaning that users may no
longer see parallel name resolution pass errors in the output.
In practice, this is probably not a big deal, and its easier than
the alternative of trying to complicate the codebase by differentiating
between type alias recursion and other name resolution pass errors.
Resolves #901.
> Fix compiler crash on "exotic" recursive type alias.

- .travis.yml
This PR removes LLVM 3.7 and 3.8 from Travis CI (on Linux), and uses Ubuntu "trusty" which provides LLVM 3.6 in the official distro packages.
This is necessary because https://llvm.org/apt was taken down due to heavy load (probably from language project Travis builds like this one).  It's not clear when/if they will find a feasible way to bring it back, but for now we have to do without.
> Fix Travis CI by running only 3.6 (for now) on Ubuntu "trusty".

- src/libponyc/codegen/genopt.cc
This pass needs to run multiple times during optimisation to exploit the transformations realised by the standard LLVM passes and catch as much allocations as possible. We also need to erase replaced instructions manually or they will stay in the program.
> Improve HeapToStack optimisation pass

- CHANGELOG.md
- packages/net/http/serverconnection.pony
In HTTP 1.1, all connections are considered persistent unless declared otherwise.
> Default to persistent connection for HTTP/1.1

- src/libponyc/expr/reference.c
> Fix error messages for misuse of identityof and digestof.

- src/libponyrt/gc/serialise.c
- src/libponyrt/gc/serialise.h
VS2015, for some reason I cannot discover, is mangling the function names in serialise.c, which causes link errors when ponyc is linking on Windows.  This change declares the functions as extern "C" so the exported names are not mangled.
> force vs2015 to not mangle serialise function names

- README.md
This shows the installation process for ponyc using the LLVM downloads page since the apt server is down. The install process has been tested on fresh installs of Ubuntu versions 14.04 and 16.04 without LLVM pre-installed.
> Update build instructions for Ubuntu

- CHANGELOG.md
- src/libponyc/type/alias.c
- test/libponyc/sugar.cc
Fixes issue #929.
Please review. Just getting my toes wet in the compiler. Builds on Linux; do not have a Windows environment at the moment.
Does this need a test? If so, please advise as to its proper location.
The `alias()` function was missing the `TK_LAMBDATYPE`; this has been added.
> Fix #929 compiler bug where 'as' causes seg fault

- CHANGELOG.md
- Makefile
- premake5.lua
- src/ponyc/main.c
This adds the type of build after the version number when running `ponyc -v`.
e.g.
```
0.2.1-944-ga9585df [debug]
```
> Add the build type to ponyc -v output

- src/libponyc/codegen/codegen.c
- src/libponyc/codegen/genopt.cc
- src/libponyc/codegen/genprim.c
LLVM optimises calls to its intrinsics better than calls to standard libc functions.
> Use LLVM intrinsics for memcpy/memmove in codegen

- src/libponyc/codegen/codegen.c
- src/libponyc/codegen/gentype.c
In codegen_pushscope, use the existing frame->di_file rather than
trying to create a new one, as that can lead to incorrect results.
In make_debug_info, if the type being generated has a definition
(i.e. it is a nominal type), use the file the definition is in,
rather than whatever random source file the use-site AST node
happens to be in.
> Set correct source file for debug info

- src/libponyrt/actor/actor.c
- src/libponyrt/gc/gc.c
Remote immutable objects used to be traced in their entirety. Their
heap size was added to the local actor heap size. This was optimised
so that they need not be traced, but this resulted in the accumulated
heap size being far too low.
This change introduces a heuristic for remote immutable memory use. It
also stops accounting for remote objects in the effective local heap
size, so that only only local objects count as heap size after a GC
pass. As a result, remote objects and actors provoke GC, but never
delay it.
As part of this change, message batching on an actor is terminated
early if the actor's queue when it was scheduled is exhausted. This
prevents a batch from handling messages that the batch itself has
generated, or that arrive while a batch is in progress.
> Heuristics for GC when receiving immutable objects

- .travis.yml
We previously disabled Travis CI Linux builds for most versions of LLVM, because LLVM [turned off their apt repo](http://lists.llvm.org/pipermail/llvm-dev/2016-May/100303.html) and we had to use only the LLVM available through the official Ubuntu repos.
EDIT: This PR was originally going to use docker to work around the problem, but I've amended it to take a non-docker approach.
This fixes the Travis CI Linux builds by using LLVM binaries (which are not turned off) instead of apt packages.
> Fix Travis CI Linux builds using LLVM binaries.

- src/libponyc/codegen/gencall.c
- src/libponyc/codegen/genexpr.c
Such intrinsics must correctly generate i1, not i8, now that Bool
is encoded as i8. Arguments passed in must be trunated, and results
returned must be zero-extended.
> LLVM intrinsics with i1 in params or return type

- Makefile
switch to relative link for /bin/ponyc, /lib/libponyrt.a /lib/libponyc.a
and /include/pony.h (instead of absolute link). Ensure that installation using fakeroot (like
makepkg) don't create link to fakeroot directory
> use relative link

- examples/ffi-struct/struct.pony
Was broken a while back. Reading a field on a class through
an iso (like Inner here on Outer) results in it being a tag.
Aka doesn't work. Explicitly make Outer a ref rather than an iso.
> Fix ffi example

- Makefile
`/bin/ln` on mac does not support the `-r` option.
Fix #948
> Fix #948 for Mac OS X

- packages/builtin/array.pony
- packages/collections/ringbuffer.pony
Rather than rely on Pointer[A]._realloc, Array[A] now grows its
allocated space geometrically. This results in fewer calls into
the runtime, improving performance.
> Grow Array[A] geometrically

- CHANGELOG.md
- packages/builtin/string.pony
This change reduces the following program from 12.5 secs to 9.5 secs runtime on my machine and memory usage with about 60%.
```pony
use "collections"
actor Main
var _env: Env
_env = env
_start_benchmark()
fun _start_benchmark() =>
for j in Range(0, 1000) do
_run_test()
end
be _run_test() =>
let s = String
for i in Range(0, 100000) do
s.append(I8(0).string())
end
for i in Range(0, 100000) do
s.truncate(100000 - i - 1)
end
```
> Use geometric growth when reserving space for new length

- .appveyor.yml
- packages/net/test.pony
- src/libponyc/platform/vcvars.c
This pull request enables running the normal ponyc automated tests (that run for linux/osx) on every commit in Appveyor for Windows builds.
See https://ci.appveyor.com/project/dipinhora/ponyc for a build run with Appveyor with these changes included. Currently a couple of tests fail so the build fails.
This pull request also includes changes to how the Visual Studio installation location is determined by ponyc for finding libraries and executables needed to include support for systems where only the command line Visual C++ Build Tools 2015 (https://blogs.msdn.microsoft.com/vcblog/2016/03/31/announcing-the-official-release-of-the-visual-c-build-tools-2015/) are installed but a full copy of Visual Studio isn't installed. This change should have no negative impact to normal Visual Studio …
> Run automated tests in Appveyor

- Makefile
- examples/tests.pony
Currently the examples are not included in the CI process, this leads to
this kind of commit messages :
4eb42e2 Fix ffi example (#949) Was broken a while back.
I added a separate make target `test-examples`though I believe this
tests should be run with the full tests suite.
The package is minimal at the moment, it just tries to use all examples.
Unit tests should be added later, demonstrating some testing techniques.
Some example packages are commented at the moment as they don't build on
my laptop. I still have to figure out what is broken: the example or my
pony build chain.
> Added minimal tests for examples.

- packages/time/time.pony
- packages/time/timer.pony
There was no docstring for the time package, so I added one with a
brief description of what the classes in the package do.
There was no example code in the Timer docstring, so I fleshed out the
description of the class and added an example.
> Add docstrings for time package and Timer class

- .appveyor.yml
This is a bugfix for PR #957 where it hangs if the LLVM cache is restored and causes the build to time out in Appveyor.
> Fix appveyor LLVM caching issue.

- packages/builtin/array.pony
- packages/builtin/string.pony
lstrip, rstrip, and split were relying on Array.find(), which was causing them to unnecessarily call pony_throw.  This change fixes that.  I've updated Array.contains() so it doesn't need to call pony_throw and rely on that instead.
> Fix lstrip, rstrip, and split so they don't call pony_throw

- src/libponyc/codegen/gencall.c
- src/libponyc/codegen/gendesc.c
- src/libponyc/expr/reference.c
- src/libponyc/type/matchtype.c
- src/libponyc/type/reify.c
- src/libponyc/type/subtype.c
A struct exists to mirror the C struct ABI. As a result, it has no
type descriptor, so no runtime type information is available for a
struct. As a result, an instance of a struct cannot be used in a
type where runtime type information may be requested.
* A struct can't be a subtype of a trait or interface
* A struct can't be a subtype of a union or intersection
* A struct can't be a type argument
* A struct can't be a pattern unless it always matches
> Can't use a struct as a type argument

- .appveyor.yml
- Makefile
This will allow us to detect breaking changes to the code generator and get useful diagnostics in the CI.
> Verify generated LLVM IR when building tests

- packages/collections/persistent/test.pony
- packages/collections/test.pony
- src/libponyc/ast/id.c
- src/libponyc/expr/lambda.c
The pass_syntax compiler pass was skipping lambda functions because
the child nodes of the lambda function are all intially flagged as
AST_FLAG_PRESERVE when pass_syntax is run in module_passes; this
flag is removed in a later step. This fix calls pass_syntax again
after the flag is removed in order to catch any issues that were
missed on the first call to pass_syntax.
In order for this to work correctly, `check_id` was changed to allow
any identifier that starts with a "$" character. The reasoning is
that variables with these names are only used in hygienic variables
that are created by the compiler, and in certain tests. We don't want
to disallow them, so we assume that if you use them then you know what
you are doing. This has been discussed with @sylvanc.
Once this change was made the …
> Check syntax in lambdas

- src/libponyc/expr/reference.c
In expr_param, we can always set the type of the param AST, even
when the initialiser is invalid.
> Always set param type

- src/libponyc/codegen/gencontrol.c
- src/libponyc/codegen/genmatch.c
- src/libponyc/expr/match.c
A structural equality pattern was being assigned the type of the
parameter instead of the receiver. This is fixed, and the the full
type of the match pattern is stored with the case for use in the
code generator.
> Store the match pattern type in the case

- src/libponyc/expr/call.c
- src/libponyc/expr/reference.c
Previously, incompleteness checks were applied in call.c and were
inconsistent. Now, incompleteness is checked in expr_this, with an
exception made for field lookups. Field lookups are still checked
for individual completeness via is_valid_reference.
> Consistently type an incomplete `this` as tag

- src/libponyc/pass/finalisers.c
- src/libponyc/reach/reach.c
A _final field is now allowed. A _final method must still be a fun
rather than a new or a be, and must have the correct signature for
a finaliser, to avoid a situation where a programmer believes they
have written a finaliser, but the compiler doesn't recognise it and
so the runtime doesn't call it.
> Allow _final as a field name

- packages/builtin/float.pony
- src/libponyc/codegen/codegen.h
- src/libponyc/codegen/genprim.c
- src/libponyc/codegen/host.cc
The LLVM sqrt intrinsic has undefined behaviour for negative arguments. We now check the argument and return NaN if it is below 0.
> Fix F32.sqrt and F64.sqrt

- src/libponyc/codegen/gencall.c
It's possible for a structural equality pattern to not be a nominal
type. When it isn't, it also can't be a machine word, so that clause
can be skipped.
> Check for a nominal type in gen_pattern_eq

- src/libponyc/codegen/codegen.c
- src/libponyc/codegen/codegen.h
- src/libponyc/codegen/gendesc.c
- src/libponyc/codegen/genfun.c
- src/libponyc/codegen/genprim.c
- src/libponyc/codegen/genreference.c
- src/libponyc/codegen/genserialise.c
- src/libponyc/codegen/gentype.c
- src/libponyc/pass/pass.h
- src/ponyc/main.c
This is advised in LLVM's "[Performance tips for frontend authors](http://llvm.org/docs/Frontend/PerformanceTips.html)".
Functions called from the runtime (finalisers and trace functions) are still generated with an external linkage.
This is only enabled in optimised builds of standalone programs and can be disabled with the new `--extfun` compiler flag.
I've observed a 10% to 30% decrease in executable sizes with this change.
> Set symbol linkage type to private by default

- packages/net/writebuffer.pony
This adds a new reserve chunks method to WriteBuffer. When WriteBuffer was written, we missed a performance improvement. Many times when using a writebuffer, we know the number of elements we are writing ahead of time, by reserving those chunks, we can save on allocations and increase performance.
> Reserve chunks

- CHANGELOG.md
- packages/json/doc.pony
- packages/json/json.pony
- packages/json/print.pony
- packages/json/tests.pony
Pretty printing JSON creates a slightly larger data structure than
a non-pretty printed version. When dealing with large aggregates,
this can result in large differences that can have a noticeable
impact on performance when sending over the network.
This change makes pretty printing optional in a way that maintains
compatibility with the existing API.
> Performance enhancements for JSON printing

- packages/collections/map.pony
- packages/collections/test.pony
Map.upsert() combines a provided value with the current value for the provided key
using the provided function. If the provided key has not been added to
the map yet, it sets its value to the provided value. 
This avoids having to lookup the old value twice when you want to use the old value to calculate the new value.
> Add upsert method to Map for updating by combining current with new value

- packages/net/net.pony
- packages/net/readbuffer.pony
- packages/net/tcpconnection.pony
- packages/net/tcplistener.pony
- packages/net/tcpnotify.pony
- packages/net/udpnotify.pony
- packages/net/udpsocket.pony
The documentation for the `net` package was sparse. This commit adds
package-level documenation and adds example code for UDPSocket,
TCPListener, and TCPConnection. It also adds notes to the document
strings for supporting classes indicating that examples of their use
can be found in other places.
> Add documentation for the `net` package.

- src/libponyc/expr/lambda.c
- src/libponyc/expr/reference.c
- src/libponyc/expr/reference.h
- test/libponyc/badpony.cc
Hello, 
I tried to fix the issue I opened the other day (#1018) and I wrote a failing test for it. I found that this was already working correctly unless the type was to be inferred. 
I am not entirely sure I put the rather small fix in the correct location, so please point me in the correct direction if it is not, or let me know if I went at it entirely the wrong way.
The test suite passes on Linux.
> Improve error msg for lambda capture before their declaration (Issue #1018)

- packages/builtin/pointer.pony
- src/libponyc/codegen/gendesc.c
- src/libponyc/codegen/genident.c
- src/libponyc/codegen/genmatch.c
- src/libponyc/codegen/genprim.c
- src/libponyc/codegen/genserialise.c
- Use `getelementptr` instead of `ptrtoint`/`inttoptr` for pointer arithmetic to keep aliasing information.
- Directly compare pointers instead of converting to integers before comparison.
> Remove pointer/integer conversions in generated code

- src/libponyc/codegen/genfun.c
- src/libponyc/codegen/genfun.h
- src/libponyc/codegen/genprim.c
- src/libponyc/reach/reach.c
- src/libponyc/reach/reach.h
- An iso parameter gets the `noalias` attribute. This is safe because LLVM pointer aliasing only takes into account writes to the pointed memory.
- A val or box parameter gets the `readonly` attribute.
- A tag parameter gets the `readnone` attribute.
The box and tag modifiers don't apply to actors because the pointer can still be dereferenced by message sending. All modifiers are disabled for the receiver in a constructor.
> Set LLVM parameter attributes according to refcaps

- src/libponyc/codegen/codegen.c
- src/libponyc/codegen/codegen.h
- src/libponyc/codegen/genfun.c
- src/libponyc/codegen/genprim.c
- src/libponyc/codegen/host.cc
Add `noalias` to every allocation function and `dereferenceable` or `dereferenceable_or_null` depending on the function.
> Add more LLVM attributes to allocators

- CHANGELOG.md
- packages/builtin/string.pony
- packages/builtin_test/_test.pony
The UTF-8 encoder has been extracted and refactored from String.from_utf32 into a private primitive. Some unit tests are provided.
> add String.push_utf32

- src/libponyc/codegen/genfun.c
Follows bbacbe1 (Set LLVM parameter attributes according to refcaps).
- Set `tag` parameters to `noalias readonly` instead of `readnone`. A `tag` can be dereferenced by a match expression to access the type descriptor so `readnone` isn't safe.
- Add `noalias` to `val` parameters in addition to `readonly`. Only read-only pointers to `val` objects can exist and read-only pointers never alias between each other in LLVM.
> Use more accurate LLVM parameter attributes

- packages/serialise/_test.pony
- src/libponyc/codegen/genserialise.c
- src/libponyrt/gc/gc.c
- src/libponyrt/gc/gc.h
- src/libponyrt/gc/serialise.c
Previously, the descriptor wasn't being set correctly. It was still
the type ID, not the pointer to the descriptor.
This change also fixes an error where an aborted serialisation or
deserialisation left junk in the context that could cause a future
serialisation or deserialisation to fail unexpectedly.
> Deserialise boxed machine words correctly

- src/libponyc/codegen/genopt.cc
Reading LLVM IR processed by MergeFunctions can get really tedious.
> Disable the MergeFunctions pass in debug builds

- .appveyor.yml
One step forward...  (You can see it in action [here](https://ci.appveyor.com/project/killerswan/ponyc/build/1.0.23): the job for each configuration will build a uniquely named artifact which contains a minimum [I think] viable ponyc.)
~~Next on my list: to fix the numbering!~~ 😅 
@SeanTAllen @jemc
> Create ZIP artifacts in Win64 AppVeyor builds and use versions from the repository

- src/libponyc/expr/control.c
- src/libponyc/pass/syntax.c
- test/libponyc/badpony.cc
Previously, invalid uses of control flow statements were only checked on the AST node for the statement itself. We now check parent sequence nodes to catch errors if the statement is in parenthesis.
Closes #1050.
> Recursively check control flow AST errors

- src/libponyc/codegen/codegen.c
- src/libponyc/codegen/codegen.h
- src/libponyc/codegen/gencall.c
- src/libponyc/codegen/gencall.h
- src/libponyc/codegen/gencontrol.c
- src/libponyc/codegen/genexpr.c
- src/libponyc/codegen/genfun.c
- src/libponyc/codegen/genmatch.c
- src/libponyc/codegen/genoperator.c
Describing variables lifetime can help optimise the program (e.g. in register allocation).
> Use llvm.lifetime intrinsics

- CHANGELOG.md
- src/libponyc/codegen/gencall.c
- src/libponyc/expr/operator.c
Previously, embedded fields had to be assigned to by a constructor expression. We now allow any expression returning a constructor as the right hand side of an embedded field assignment.
Closes #635.
> Allow complex expressions in embed construction

- packages/builtin/float.pony
- packages/builtin/real.pony
- packages/builtin/signed.pony
- packages/builtin/unsigned.pony
- src/libponyc/pass/expr.c
Also fixes a bug to allow said functions to be turned into constructors.
Closes #966.
> Convert functions to constructors in numeric primitives

- src/libponyc/type/alias.c
This removes the need to consume a trn or ref when recovering to iso.
Closes #744.
> Set recover cap to ephemeral for trn and ref

- CHANGELOG.md
- Makefile
- src/libponyc/codegen/codegen.c
- src/libponyc/codegen/codegen.h
- src/libponyc/codegen/gencall.c
- src/libponyc/codegen/gendebug.cc
- src/libponyc/codegen/genexe.c
- src/libponyc/codegen/genlib.c
- src/libponyc/codegen/genopt.cc
- src/libponyc/codegen/genopt.h
- src/libponyc/codegen/host.cc
- src/libponyc/pass/pass.h
- src/libponyc/pkg/package.c
- src/libponyc/pkg/package.h
- src/ponyc/main.c
As discussed (briefly) on the dev mailing list a while back.
This change adds a compiler flag (`--runtimebc`) to use a bitcode file instead of a static library for libponyrt. The bitcode file can be built alongside the compiler by passing `runtime-bitcode=yes` to the Makefile. Building the bitcode file requires Clang.
Using a bitcode file allows to run the optimiser on the user and runtime code at the same time, which enables very aggressive interprocedural optimisations. Because of restrictions caused by some optimisation passes, the optimiser is executed twice, one time before and one time after merging the runtime module. Compilation times can get really high so this option is mainly recommended for final release builds.
This change also fixes two bugs as a side effect:
- Set the …
> Allow the use of a LLVM bitcode file for libponyrt

- src/libponyc/codegen/codegen.c
The size of the descriptor pointer wasn't included in the previous value.
> Set the right dereferenceable value for pony_create

- CHANGELOG.md
- src/libponyc/expr/postfix.c
- src/libponyc/expr/reference.c
- test/libponyc/recover.cc
This implements @sylvanc's idea for fields in #728. I also added function access, which is allowed if the receiver capability of the function isn't mutable and if the parameters and return value are sendable. I think I got the requirements right but I'm not entirely sure.
> Allow use of sendable members in recover expressions

- CHANGELOG.md
- src/libponyc/pkg/program.c
This PR fixes a bug on Windows (#1059) where library paths (among others) are silently ignored if they contain parentheses, which are legal in Windows filenames.
> Do not silently ignore paths containing parens on Windows (#1059)

- src/libponyc/ast/parser.c
resolves #870 
Example:
```
[chris@heimdall ponyc]$ cat main.pony 
class Wombat
let fur
[chris@heimdall ponyc]$ make && ./build/debug/ponyc
Building builtin -> /home/chris/devel/ponyc/packages/builtin
Building . -> /home/chris/devel/ponyc
Error:
/home/chris/devel/ponyc/main.pony:2:7: syntax error: expected mandatory type declaration on field after fur
let fur
^
```
> issue 870 - improving compile error message for class fields missing type declarations

- CHANGELOG.md
- packages/term/ansi_notify.pony
- packages/term/ansi_term.pony
This change:
* creates a signal handler for the window size change signal
* sends a notification to the terminal notification object when the terminal is
first created and when the signal is received
A call to `ioctl` is used to retrieve the window size.
> Add terminal resize notification

- src/libponyc/codegen/genexe.c
Previously the `opt` parameter of the `lookup` function could be `NULL` because errors were carried in global state. Since the error state is now part of `pass_opt_t`, the `opt` parameter can be dereferenced when reporting errors and we must pass a valid `pass_opt_t*` to `lookup`.
Closes #1089.
> Call lookup correctly when searching for Main.create

- CHANGELOG.md
- packages/builtin/format_settings.pony
- packages/builtin_test/_test.pony
If a number was converted to a string with either a hex or octal
representation, and a precision was specified, then the resulting
string had `0`s before the hex or octal prefix. For example, `10`,
when converted to hex with a precision of 5, resulted in "00000xA";
the expected result is "0x0000A".
This is now fixed. The fix involved rearranging the way the string was
generated so that the prefix is added after extending the digits (the
string is constructed backwards and then reversed). A test has also
been added that uses different formatting options to format a string
and then checks the results.
Closes #1093
> Correctly add prefixes for hex and octal strings

- src/libponyc/codegen/codegen.c
- src/libponyc/codegen/codegen.h
- src/libponyc/codegen/gencall.c
- src/libponyc/codegen/gencall.h
- src/libponyc/codegen/genexpr.c
- src/libponyc/codegen/genprim.c
- src/libponyc/codegen/genreference.c
- src/libponyc/codegen/genreference.h
- src/libponyc/codegen/host.cc
Having these informations allows the optimiser to reason about object immutability and eliminate redundant reads from memory.
We now
- add the `invariant.load` metadata on loads from non-rebindable fields/locals (`let` binding or `val` parent object).
- use the `llvm.invariant.start` intrinsic when referencing immutable objects. `llvm.invariant.end` isn't used since an immutable Pony object can't become mutable.
As a part of this change, LLVM intrinsic declarations are now retreived through the `Intrinsic::getDeclaration` API instead of being declared by hand.
> Add invariant informations in generated LLVM IR

- packages/builtin/string.pony
The previous version didn't take the null terminator into account.
> Fix String.compact()

- CHANGELOG.md
- src/common/vcvars.h
- src/libponyc/codegen/genexe.c
- src/libponyc/platform/vcvars.c
There was a bug in `vcvars.c` when parsing existing Windows 10 SDK version numbers.  This PR fixes that bug.
In addition, Windows 10 SDKs require linking with a new library called UCRT (https://blogs.msdn.microsoft.com/vcblog/2015/03/03/introducing-the-universal-crt/).  This PR adds this library to the default libs when linking with a Windows 10 SDK.
> Fix windows sdk lookup

- Makefile
I used the naming convention detected for `llvm-config` but I don't know if it is consistent for every tool and LLVM installation. Please add a comment if your LLVM isn't handled here.
> Handle various possible names for LLVM tools

- src/libponyc/codegen/genoperator.c
llvm.lifetime.start should precede any store.
Closes #1092.
> Call llvm.lifetime.start at the correct moment

- CHANGELOG.md
- packages/assert/assert.pony
- packages/builtin/array.pony
- packages/builtin/string.pony
- packages/builtin_test/_test.pony
- packages/debug/debug.pony
- packages/files/directory.pony
- packages/files/file.pony
- packages/files/file_info.pony
- packages/files/file_path.pony
- packages/files/path.pony
- packages/net/dns.pony
- packages/net/ssl/ssl.pony
- packages/net/ssl/ssl_context.pony
- packages/net/tcp_connection.pony
- packages/net/tcp_listener.pony
- packages/net/udp_socket.pony
- packages/process/process_monitor.pony
- packages/regex/regex.pony
- packages/time/date.pony
This PR implements part of https://github.com/ponylang/rfcs/pull/2 / https://github.com/ponylang/ponyc/issues/1023.
It implements `trim` and `trim_in_place`, but does not yet remove `truncate`, since `truncate` is part of the `Seq` interface and is thus a wider-reaching change than the RFC originally intended.
It adds `String.is_null_terminated` as per the RFC, but also adds `String.null_terminated`, which does the work of checking `is_null_terminated`, and calling `clone` if that check returns false.  This turned out to be much less cumbersome in practice for all of the FFI calls that need to ensure a null-terminated string.
> Add String and Array trim and trim_in_place.

- packages/builtin/string.pony
This PR fixes an unfinished docstring in String.from_cstring method.
I accidentally didn't finish this dosctring before filing #1104, and it wasn't noticed until after merge (when it was noticed by @aturley - thanks!).
> Fix unfinished docstring in String.from_cstring method.

- CHANGELOG.md
- packages/builtin/array.pony
- packages/builtin_test/_test.pony
This PR fixes performance of `Array.append` and `Array.concat` by avoiding overhead from calls to `Array.push` internally if a concrete size can be reserved ahead of time.
Resolves #1108.
> Fix performance of Array.append and Array.concat.

- packages/process/process_monitor.pony
The ProcessNotify methods in the example code just needed the newly defined parameter.
> Update example with new ProcessNotify interface

- packages/net/tcp_connection.pony
In two spots in doc strings, "as" seemed to have been typed instead of "us". Also added some backticks around identifier names to make the PR a tiny bit more worthwhile.
Please let me know if PRs this small are too trivial and should be avoided.
> Fix 2 typos and add some backticks in doc strings

- CONTRIBUTING.md
Updates CONTRIBUTING.md to add a requirement to highlight identifier names in documentation.
> Add note to use code highlighting in docstrings

- src/libponyc/codegen/codegen.c
`pony_traceknown` and `pony_traceunknown` return `void`.
> Declare the right signature for runtime functions

- .appveyor.yml
Seems the API key I had set up didn't work:
https://ci.appveyor.com/project/ponylang/ponyc/build/job/b7sv66mwvda6185l
Trying again, this time using a the https://ci.appveyor.com/tools/encrypt page after a login with ponylang (via GH) instead of killerswan.
CC @SeanTAllen
> Update the AppVeyor-encrypted Bintray API key (after logging in to AV with ponylang)

- CHANGELOG.md
- src/libponyc/codegen/genexe.c
- src/libponyc/pass/pass.h
- src/ponyc/main.c
* Make use of `-mcx16` dynamic based on whether target platform
triple is 32 bit or not.
* Make use of `-fuse-ld=gold` and `-ldl` dynamic based on whether
target platform triple is Linux or not.
* Allow overriding linker command with new `--linker` option but
default to using compiler from when ponyc was compiled.
* Allow overriding linking cpu architecture with new `--link-arch`
option but default it to using cpu architecture from when ponyc
was compiled.
> Make cross compiling easier by making linking more dynamic

- packages/json/_json_print.pony
- packages/json/_test.pony
- packages/json/json_doc.pony
- packages/json/json_type.pony
This commit adds a `_show` method to the `JsonArray` and `JsonObject` types.
This method is responsible for printing the string representation to a
string buffer that it receives as an argument. The method also receives
the desired indentation style, and the current level of indentation.
The indentation is managed by a new `_JsonPrint._indent` method, which
prints the leading newline and the indentation as many times as the
given level requires.
The `_JsonPrint._string` method has been updated to also receive the
buffer and will either pass the string representation of the primitive
to it, or will forward it to the `_show` method of `JsonArray` or
`JsonObject`.
This greatly reduces the amount of allocation that takes place.
The `I64` and `String` types in the `_JsonPrint` match expression …
> Make composite types print to mutable string

- src/libponyc/codegen/codegen.c
- src/libponyc/codegen/codegen.h
- src/libponyc/codegen/genname.c
- src/libponyc/codegen/genname.h
- src/libponyc/codegen/genoperator.c
- src/libponyc/codegen/genreference.c
- src/libponyc/codegen/gentype.c
- src/libponyc/codegen/gentype.h
These metadatas make LLVM aware of the aliasing guarantees of the Pony type system. It will allow a more precise alias analysis, which will lead to better optimisations.
Metadatas are added on loads and stores of fields. Since fields of interfaces, union types, etc. are inaccessible, only base types are considered. Each type has its own subtree (objects of different types can never alias) which is arranged in the following way:
```text
----R----
/    |    \
iso   box   val
/   \
ref   trn
```
In LLVM, an object of a given type can alias with objects of any child or parent type. The tree is a simple transposition of the reference capabilities rules. The only difference is `val` ; it isn't a child of `box` here because LLVM aliasing only cares about writes. `tag` is left out since it can …
> Add LLVM type-based alias analysis metadatas

- CHANGELOG.md
- packages/collections/map.pony
Both Map.upsert and Map.update were replacing the key with the new key value. This has
a rather drastic performance impact. In testing on my machine, this change results in up
to a 10x performance improvement. At minimum I saw 4x performance improvement from
both of these changes.
> Make Map.upsert and Map.update much faster

- src/libponyc/codegen/gencall.c
Prevents a segmentation fault in `gencall_allocstruct` when trying to compute a heap index for an empty Struct.
> Force minimal Struct size to 1

- src/libponyc/pass/casemethod.c
Popping an AST node modifies sibling links, which screws up parameter counting for error checking in `param_without_type`.
Closes #1140.
> Duplicate AST node instead of popping it

- README.md
On windows, the Windows 10 SDK is required in order to link to the Universal Windows App C Runtime Library (ucrt.lib)
> added note about win10-sdk dependency

- .docs/extra.js
- .travis.yml
Irregardless of which section was viewed, the navbar would be displayed _scrolled to the top_.   With this, it will scroll to the currently viewed section.
(The fix is adding a `$(document).ready()` to what was proposed in https://github.com/mkdocs/mkdocs/issues/803, because I found that this was needed to make it not fail. No JS expert, sorry.)
I've tried placing the file at its right place (`stdlib-docs/docs/`), but that directory apparently gets nuked by `ponyc ... --docs`, so it'll be copied there when it's needed.
> mkdocs: auto-scroll to current section

- CHANGELOG.md
- examples/gups_basic/main.pony
- examples/gups_opt/main.pony
- examples/mandelbrot/mandelbrot.pony
- examples/yield/main.pony
- packages/options/_test.pony
- packages/options/options.pony
The unit tests has been simplified to use the new constructor, and so a new unit test has been added to still test the constructor with an `Env`.
Implemention notes:
- the two constructors have some duplicated lines, but I wasn't able to make one constructor call the other without having ponyc complain about uninitialized fields
- I am not at ease with miwing refcaps and generics, maybe the signature of the suggested new constructor could be improved
> Add a constructor for `Options` with a simple `String` array

- src/libponyc/codegen/codegen.h
- src/libponyc/codegen/gencall.c
- src/libponyc/codegen/genexe.c
- src/libponyc/codegen/genfun.c
- src/libponyc/codegen/genopt.cc
- src/libponyc/codegen/host.cc
This is an improvement for the heap2stack optimisation pass, which replaces heap allocations by stack allocations when possible. This modification allows the optimiser to know that the parent object of a given field is stack-allocated, which gives it more information to stack-allocate the field itself.
In order to get correct nocapture info in LLVM, which greatly helps the analysis in heap2stack, class constructors in generated code now return `void` instead of their receiver.
> Force constructor inlining when stack-allocating objects

- src/libponyc/ast/ast.c
- src/libponyc/ast/ast.h
This data structure will allow us to create ASTs on the fly, pass them to code expecting attached ASTs (i.e. not freeing them after use) and free them afterwards.
This is not used anywhere in the compiler yet but it will be used in upcoming bugfixes.
> Add a data structure managing unattached ASTs

- packages/builtin/format_settings.pony
The FormatSettings class (and associated classes) can be a little
intimidating. This commit adds some example code to the documentation
to show how the different options can be used.
> Add example code to FormatSettings documentation

- CHANGELOG.md
- src/libponyc/type/subtype.c
This fix prevents an assertion failure that may occur if a program contains errors.
Closes #1163.
> Handle invalid types in is_x_subtype_x functions

- packages/files/path.pony
This is part of the failures in the PR for the `files.Path` tests.
> Fix Path.join invalid negative indexing on string

- packages/files/path.pony
Fixed invalid negative indexing on a string, and made the deletion of
the trailing separator future-proof by using the .size() of the
separator instead of the fixed value of 1.
----
Could have just included this with the `.join()` fix, since it's the same issue!
> Fix and future-proof Path.clean separator removal

- CHANGELOG.md
- packages/builtin/string.pony
- packages/builtin_test/_test.pony
Update docstring and optimize edge case
The `offset` parameter is now included in the docstring.
A search pattern that is an empty string would previously cycle through
the entire string, and always fail in the end. This is now checked
before the loops.
Resolves #1164
> Fix String.rfind failure and add tests

- packages/files/_test.pony
Some tests are commented out because of `String.rfind` issue #1164. If that can be resolved first, I'll update this commit before it is merged.
> Add tests for Path methods

- CHANGELOG.md
- src/libponyrt/asio/asio.c
- src/libponyrt/asio/asio.h
- src/libponyrt/sched/cpu.c
- src/libponyrt/sched/cpu.h
- src/libponyrt/sched/scheduler.c
- src/libponyrt/sched/scheduler.h
- src/libponyrt/sched/start.c
- src/ponyc/main.c
* Currently, the main/initial scheduler thread when not running in
library mode is not pinned to a CPU core on Linux/FreeBSD and it
is also not assigned to the most appropriate stack space for
NUMA efficiency. This PR changes behavior so the main thread
is not used as a scheduler thread any longer and instead starts
up another scheduler thread which is properly CPU pinned and
NUMA space aligned ensuring that all scheduler threads are
appropriately CPU pinned and NUMA space aligned.
* Add `--ponypinasio` runtime option for cpu pinning asio thread
* Behavior when the option is not specified is same as always which
is that the asio thread is not pinned to a cpu core/numa node
and can be moved from one core to another by the OS scheduler.
* When the option is specified, the asio thread is …
> CPU pinning enhancements

- packages/files/path.pony
The changes in this commit include using the `String.trim()` method
instead of `substring()` in order to avoid extra allocation, using
`let` instead of `var` when able, and avoiding variable declarations
when readability isn't compromised.
All changes are in `"files/path"`.
> Optimize by using let and trim() when able

- packages/builtin/string.pony
This mostly replaces `var` with `let` where possible.
Other minor changes include avoiding looping to search for an empty
string since it'll never be found, and avoiding a repeated assignment
in a loop that is only needed on the first iteration.
> Add minor optimizations

- CHANGELOG.md
This PR moves the changelog entries for PR#1168 from `0.3.0` to `unreleased` since the PR was merged after the release was made.
The two additional PRs that were merged after the release was made are PR#1174 and PR#1166. These PRs didn't include changelog entries so there were no corresponding changelog entry changes required for them but it is probably a good idea to add changelog entries for them into the `unreleased` section.
> Fix changelog for 0.3.0 to remote PRs merged after the release.

- .gitignore
- CHANGELOG.md
- src/common/threads.h
- src/libponyrt/platform/threads.c
- src/libponyrt/sched/cpu.c
- src/libponyrt/sched/cpu.h
- src/libponyrt/sched/scheduler.c
- src/libponyrt/sched/scheduler.h
- src/libponyrt/sched/start.c
- src/ponyc/main.c
Correctly pay attention to taskset and cgroups by using
sched_getaffinity() to determine an initial CPU set.
When building the available CPU list, pay attention to
both the distinction between physical and hyperthreaded
cores and NUMA core grouping.
Add --ponynopin to disable all thread pinning.
> Thread pinning on Linux

- CHANGELOG.md
- packages/files/_test.pony
- packages/files/path.pony
This commit adds an optional `with_ext` method to `Path.base` in the
files package. The default retains the current behavior. If `false` is
passed, the extension is elided if present, as defined by the `ext()`
method.
Tests for `Path.base` are included in this commit.
> Add option to elide extension in Path.base

- src/common/atomics.h
- src/libponyrt/actor/actor.c
- src/libponyrt/actor/messageq.c
- src/libponyrt/asio/asio.c
- src/libponyrt/asio/epoll.c
- src/libponyrt/mem/pagemap.c
- src/libponyrt/mem/pool.c
- src/libponyrt/sched/mpmcq.c
- src/libponyrt/sched/scheduler.c
- src/libponyrt/sched/start.c
Having the memory order right next to the atomic operation really helps clarity. Additionally, we may want to use different memory orders for the same operation type.
No functional changes here.
> Make atomic memory orders explicit

- src/libponyc/codegen/codegen.h
- src/libponyc/codegen/genprim.c
- src/libponyc/codegen/host.cc
DoNotOptimise now only affects objects passed as arguments to `apply`.
> Avoid inhibiting too much optimisations in DoNotOptimise

- CHANGELOG.md
- src/libponyc/codegen/codegen.h
- src/libponyc/codegen/gencall.c
- src/libponyc/codegen/gencall.h
- src/libponyc/codegen/genprim.c
- src/libponyc/codegen/genreference.c
- src/libponyc/codegen/host.cc
This intrinsic is causing problems in generated code.
Closes #1186.
> Remove llvm.invariant.start from code generation

- CHANGELOG.md
- Makefile
- premake5.lua
- src/ponyc/main.c
- It's an important piece of information in bug reports
- It's not trivial to find.
- Multiple llvm versions are installed on some systems
- I had to read the Makefile when I was asked (#901, #1186)
Maybe this change requires a further discussion (What if some tools rely on the output of --version? Is it better to add another option, say --debug-info containing more informations? ...)
> Display llvm version in --version output

- CHANGELOG.md
- src/libponyc/codegen/gencall.c
- src/libponyc/codegen/genopt.cc
This can happen because of embedded fields and other passes merging function calls.
Closes #1191.
> Handle multiple constructor calls in heap2stack

- CHANGELOG.md
- src/libponyrt/sched/mpmcq.c
A memory barrier on both side of a concurrent operation is required when publishing data.
@pdtwonotes Can you try and see if it fixes #1000 for you?
> Use a store-release in ponyint_mpmc_push_single

- CHANGELOG.md
- Makefile
- README.md
This is a workaround for the CI failures of #1206 on OSX. The default compiler in Travis builds is too old and doesn't support the C features used in #1206. We have to use a more recent compiler, which introduces incompatiblities with libLTO.
> Disable LTO by default on OSX

- .travis.yml
- src/common/atomics.h
- src/common/platform.h
- src/libponyrt/actor/actor.c
- src/libponyrt/actor/messageq.c
- src/libponyrt/actor/messageq.h
- src/libponyrt/asio/asio.c
- src/libponyrt/asio/epoll.c
- src/libponyrt/asio/iocp.c
- src/libponyrt/mem/pagemap.c
- src/libponyrt/mem/pool.c
- src/libponyrt/pony.h
- src/libponyrt/sched/mpmcq.c
- src/libponyrt/sched/mpmcq.h
- src/libponyrt/sched/scheduler.c
- src/libponyrt/sched/start.c
We now use standard C11 functions with `_Atomic` types. In addition, some atomic operations have been strengthened.
- In `pagemap`, loads of the data structure have been changed from plain loads to loads with acquire semantics to make sure the allocation of the data structure _happens-before_ its usage in other threads.
- Before entering the ABA protected CAS loops (`ponyint_mpmc_pop`, `pool_push` and `pool_pull`), we now load the whole ABA data structure in one atomic operation instead of loading each member separately. This ensures the shared data isn't modified between member loading and that the value seen is the last value in the modification order.
- Every access of a shared variable is now atomic. We use relaxed ordering whenever possible so there should be almost no overhead on …
> Refactor atomic operations usage

- CHANGELOG.md
- Makefile
- premake5.lua
The version assigned when building was coming from `git describe --tags
--always` when `.git` was present, otherwise from `VERSION`. This can
get out of sync with `VERSION` if the git tags are not up to date.
This commit makes the `tag` variable come version come exclusively from
the `VERSION` file, which then is used to set the build version.
This rendered the `setversion` command, which used the `tag` variable
to set the `VERSION`, file recursive and nonsensical, so the
`setversion` command has been removed. The `git` variable was also
removed, since it was only use was for `setversion`.
The `setversion` was also removed from the `release` command.
This resolves issue #1220.
> Make version come from VERSION file, not git tags

- CHANGELOG.md
- Makefile
Prior to this commit, the default when
running `make` was to create a debug
build. This is fine for pony developers
but pony first time users might be unaware.
Our stated guiding principle for defaults
is to use the best performing option that
wouldn't violate the principal of least
surprise. And so, this commit.
> Make `release` the default build type

- .travis.yml
A change in Homebrew is breaking OSX builds.
This fix handles the problems we are now having
installing GMP. Specifically, we are hitting errors
were it can't be linked into /usr/local when
being installed as a dependency for various
llvm version. This ends up failing the llvm installs
and from that, the build.
This fixes by "manually" installing gmp and then
forcing the link overwrite.
> Fix Travis OSX builds

- .travis.yml
- CHANGELOG.md
- Makefile
Commit #1207 turned off LTO as a default. Subsequent
testing by Sendence found a ~ 10% performance
degradation for some operations with the change.
The change was made in order to get the Travis CI
builds working. Not a wonderful trade-off. This change
turns LTO back on by default on OSX and fixes our
Travis issue.
Eventually, Travis should have a compiler that doesn't
have issue with LTO and we can remove the Travis portion
of this.
This fixes issue #1223.
> Enable LTO by default for OSX builds

- CHANGELOG.md
- src/libponyc/codegen/genreference.c
Resolves #1222.
As we saw in issue #1222, the load invariant doesn't necessarily hold true
for let references in Pony. Particularly it doesn't seem to hold for `for`
loops, which are `let` in Pony semantics, but the value changes between
iterations of the loop, so the optimizer can't see them as invariant.
With more research it might be possible to exclude the `for` loop case
(and any other problematic cases) but for now the best course of action
is to remove it for all `let` references.
> Stop generating `llvm.invariant.load` intrinsic for "let" references.

- CHANGELOG.md
- premake5.lua
Hopefully handles the error case correctly when fetching build number on Windows for #1237
> Handle build number failure

- src/libponyrt/mem/pool.c
- src/libponyrt/sched/mpmcq.c
- src/libponyrt/sched/mpmcq.h
The ABA bits are now the 5 (`POOL_MIN_BITS`) lowest bits of the pointers. I used a fixed number to avoid runtime computations, even though more bits are available in `pool_push` and `pool_pull` as the pool index goes up. I think 5 bits should be sufficient in every case.
I benchmarked this change on x86_64, the benchmark program can be found [here](https://gist.github.com/Praetonus/b4ceb633de887fb069e79e3ab1208efb) (it uses the [benchmark](https://github.com/google/benchmark) lib). The old version takes ~50ns per iteration while the new one takes ~30ns per iteration. I don't know how it would perform on ARM or other platforms but I expect similar ratios.
> Use less bits for ABA protection in CAS loops

- CHANGELOG.md
- src/libponyc/codegen/genexe.c
The priority order for the linker is now
1. The argument of the `--linker` flag
2. The value of `$CC`
3. The compiler used to build ponyc
If the last option is used, a warning is issued to make the user aware of that default behaviour.
This change only affects Linux and FreeBSD since Windows and OSX call the system linker directly.
Closes #1218.
> Use $CC as the linker in ponyc

- CHANGELOG.md
- src/libponyc/codegen/genprim.c
- src/libponyc/codegen/genreference.c
The semantics can be wrong if an object allocated in a loop is turned into a stack allocation.
> Stop generating LLVM invariant.load metadatas

- src/libponyrt/mem/pool.c
- src/libponyrt/sched/mpmcq.h
This is an oversight from 83bc2aa. The ABA data structures aren't used anymore.
> Remove unused types in the runtime

- src/libponyc/expr/call.c
- src/libponyc/expr/postfix.c
- src/libponyc/pass/names.c
- src/libponyc/pass/traits.c
- src/libponyc/reach/reach.c
- src/libponyc/type/lookup.c
- src/libponyc/type/reify.c
- src/libponyc/type/reify.h
- src/libponyc/type/subtype.c
This change avoids unnecessary duplications of AST nodes. Compilation times are reduced, mainly for the reachability pass.
Closes #1062.
> Duplicate fewer AST nodes during reification

- packages/process/process_monitor.pony
Before this change, `_read_len` would not be reset to zero for the `stderr` case, meaning that the next chunk of data would be read into a wrong location.
> Fix intermittent process monitor test failures

- src/libponyc/codegen/codegen.h
- src/libponyc/codegen/genbox.c
- src/libponyc/codegen/gencall.c
- src/libponyc/codegen/gendesc.c
- src/libponyc/codegen/genprim.c
- src/libponyc/codegen/gentype.c
- src/libponyc/codegen/gentype.h
We now generate metadatas for load and stores on
- Pony `Pointer`s
- Boxed values
- Type descriptors and descriptor pointers
The TBAA tree now looks like this (see 3beb8c5 for details on the types subtrees).
```text
root
|
|--- type subtrees (including Pointer)
|
|--- boxed types (separate metadata for each type)
|
|--- any type descriptor (unique metadata with immutability)
|
|--- any descriptor pointer (unique metadata)
```
> Add more type-based alias analysis metadatas

- CHANGELOG.md
- packages/process/_test.pony
- packages/process/process_monitor.pony
So, imagine you are an intrepid Pony user on IRC.
Let's call you "polypus74". You have some code that
does something like this:
pm.writev(some_data)
pm.done_writing()
You reasonably expect that your data will be written
and then shutdown because you told it you were done
writing. Sadly, before this commit you would be wrong.
You might even go on IRC and ask folks about it. You
might in fact, point out what you think is the issue
to a core team member and be told you were wrong.
But, of course, you weren't wrong. Therefore, this is
hereby called "the polypus74 fix".
The issue is, that before this commit, writev calls
write which is itself a behavior. Because behaviors
run to completion we get something like this...
original behavior: enqueues writev
original behavior: enguques done_writing …
> Fix unexpected message ordering in ProcessManager

- premake5.lua
- src/common/platform.h
- src/libponyc/codegen/host.cc
Looks like LLVM 3.9 decided to change the output format of `llvm-config --libs`.  This PR changes the build script to account for this and supresses a warning from LLVM headers.
> fix llvm3.9 builds on windows

- src/libponyrt/actor/actor.c
- src/libponyrt/pony.h
The function is safe only when an actor pushes a continuation to itself.
This commit also relaxes the atomic memory ordering for the continuation operations from sequentially consistent to relaxed. This is an oversight from the refactoring in 33caa7f.
Closes #1256.
> Fix documentation of pony_continuation

- CHANGELOG.md
- packages/builtin/string.pony
- packages/builtin_test/_test.pony
This PR fixes copy bounds for `String.clone` (avoiding a possible segfault for trimmed strings).
We are calling `_set(len, 0)` to set the null terminator on the new
string, so there is no reason to copy `len + 1` bytes from the original
string pointer. In fact, for trimmed strings this may not be safe -
in some situations, `len + 1` bytes may end in a chunk of memory that
we don't actually own, causing a segmentation fault.
> Fix copy bounds for String.clone (avoid segfault for trimmed strings).

- CHANGELOG.md
- packages/process/_test.pony
- packages/process/process_monitor.pony
There are several errors in ProcessError that are unused in the
ProcessMonitor. This commit removed unused errors with the
exception of ExecveError which is being used in #1180.
This PR fixes #1291.
> Removed unneeded errors from ProcessError

- CHANGELOG.md
- src/libponyc/pass/docgen.c
Bar separated lists were causing an ugly horizontal scrollbar in the docs. This commit fixes #1263 by including a new line every three list elements if the separator is a bar. The behavior is added as a boolean flag to the doc_type_list function to be easily applied to other lists if the need arises. A screenshot of the docs generated with this change is included below.
> Add line breaks for bar separated lists

- CHANGELOG.md
- packages/process/_test.pony
- packages/process/auth.pony
- packages/process/process_monitor.pony
Add an auth token for being able to start a process.
Additionally, it verifies that the file you are attempting
to start is in fact executable.
**This is a breaking API change.**
**This is a high priority bug fix and should be released ASAP after being merged.**
Closes #1180
> Require authorization to start processes

- packages/files/_test.pony
Given that running in a docker container means "run as root",
it was decided to remove this test. See GitHub issue for
complete conversation.
Resolves #1261
> Remove test that will always fail if run as root

- CHANGELOG.md
- packages/net/ssl/ssl_connection.pony
Prior to cfe579f252be8b9f6b48c5731e88b5c25213fb89, code
using SSLConnection would work correctly. With the
aforementioned change, by default, if you supplied no
`sentv` notifier method, the `sent` method code was applied.
However, this was done via `error` being triggered and was
quite slow for all code.
When the fix for that performance issue went in, I missed
that SSLConnection needed to have a `sentv` added that
replicated the old behavior.
Resolves #1282
> Fix SSLConnection bugs caused by missing sentv method

- src/libponyc/pass/finalisers.c
- test/libponyc/finalisers.cc
This PR simply adds some tests for the `finaliser` compiler pass for some error reporting that was previously untested (and thus vulnerable to regression).
It also makes a minor fix to the way errors are reported in the finaliser pass, using the `ast_error_continue` function for error messages that add more information to the current error.  This avoids the additional information lines from being reported as additional errors, and makes it easier for the user to see what was going on.  The `ast_error_continue` function did not exist at the original time this code was written, or it would have been used from the start.
No changelog entry should be necessary, as this doesn't really change anything a user should care about.
> Add tests for the finaliser compiler pass and improve error reporting.

- src/libponyc/pkg/use.c
I ran into this error because I had a source file that began with:
```pony
2use "ponytest" // sic
```
> Must normalize "IFDEF" node before evaluating

- src/libponyc/codegen/codegen.c
- src/libponyc/codegen/codegen.h
- src/libponyc/codegen/gencall.c
- src/libponyc/codegen/genfun.c
- src/libponyc/codegen/genfun.h
- src/libponyc/codegen/genprim.c
- src/libponyc/codegen/host.cc
The `LLVMAttribute` API is deprecated in LLVM 3.9 and is replaced by the `AttributeRef` API.
> Use the new AttributeRef API for LLVM 3.9

- README.md
This commit makes a few minor documentation adjustments for the Mac OS X build
instructions:
- Add link to MacPorts project for consistency with homebrew
instructions
- Move options for dependency installation to immediately follow
description.
- Reword lead-ins to instructions.
> Adjust formatting for OS X build instructions

- src/ponyc/main.c
This adds information of the C compiler that ponyc was built with in the output of `ponyc --version`
example output:
```
0.4.0-580906c [release] (llvm 3.8.0) (cc (Ubuntu 5.4.0-6ubuntu1~16.04.2) 5.4.0 20160609)
```
resolves #1245
> Show C compiler info in --version output

- CHANGELOG.md
- packages/net/ssl/ssl_connection.pony
Before this commit, due to a bug in `SSLConnection`, `sent` on
a `TCPConnectionNotify` wouldn't be called.
Resolves #1268
> Call `sent` on TCPConnectionNotify when using SSL

- CHANGELOG.md
- src/libponyrt/mem/pool.c
- src/libponyrt/sched/mpmcq.c
We were using one bit too many for the ABA counter.
Closes #1319.
> Fix MPMCQ crash

- packages/builtin/unsigned.pony
- packages/builtin_test/_test.pony
- src/common/platform.h
- src/libponyrt/ds/fun.c
We now use the count-leading-zeros compiler builtins, which lower to hardware instructions on modern platforms. This change yields consistent performance gains on x86. ARM wasn't benchmarked but similar
results are expected.
The benchmark program can be found [here](https://gist.github.com/Praetonus/0e0ddb03c70c3cec72c14c5f22a0305a).
> Improve performance of power of 2 computations

- README.md
We only support the latest releases of 3.6, 3.7 and 3.8
as the latest version has the most bugs fixed.
For example, we know of bugs that are fixed in 3.8.1 that
if a user is using 3.8.0 will cause errors.
> Update README to only reference supported LLVM versions

- CHANGELOG.md
- src/common/pony/detail/atomics.h
This PR fixes a small typo in reference to `__clang_major__` in `atomics.h`.
The typo was referencing this "magic define" without the two trailing underscores.  This was causing all Clangs `< 3.6` to be seen as `< 3.3`.
> Fix typo in reference to __clang_major__ in atomics.h.

- CHANGELOG.md
- packages/assert/assert.pony
- packages/builtin/array.pony
- packages/builtin/std_stream.pony
- packages/builtin/stdin.pony
- packages/builtin/string.pony
- packages/builtin_test/_test.pony
- packages/collections/hashable.pony
- packages/crypto/digest.pony
- packages/crypto/hash_fn.pony
- packages/debug/debug.pony
- packages/files/directory.pony
- packages/files/file.pony
- packages/files/file_info.pony
- packages/files/file_path.pony
- packages/files/path.pony
- packages/net/dns.pony
- packages/net/ssl/ssl.pony
- packages/net/ssl/ssl_context.pony
- packages/net/tcp_connection.pony
- packages/net/tcp_listener.pony
- packages/net/udp_socket.pony
- packages/process/process_monitor.pony
- packages/regex/match.pony
- packages/regex/regex.pony
- packages/time/date.pony
> Use 'cpointer' instead of 'cstring' where applicable

- CHANGELOG.md
- src/libponyc/type/alias.c
- src/libponyc/type/alias.h
- src/libponyc/type/cap.c
- src/libponyc/type/cap.h
- test/libponyc/recover.cc
This is a fix for #1123. Recovery of tuples is now completely forbidden. We could allow some tuples and rcap combinations while keeping it safe but I'm not sure if it would be a good thing.
EDIT by @jemc: This PR now allows some tuple recovery, while disallowing the problematic combinations.
> Restrict mutable tuple recovery

- CHANGELOG.md
- src/common/pony/detail/atomics.h
- src/libponyrt/mem/pool.c
- src/libponyrt/sched/mpmcq.c
- src/libponyrt/sched/mpmcq.h
We now use a spinlock with starvation-free guarantees instead of a CAS loop (lock-free) in the scheduler MPMC queues. The same change is made to the pool allocator free-list storage. This change removes issues with the ABA problem handling.
> Use a starvation-free algorithm in the MPMC queues

- CHANGELOG.md
- src/libponyc/ast/token.c
- src/libponyc/pass/casemethod.c
This PR adds code to concatenate the docstrings of individual case methods into the generated wrapper function (#575).  It grabs the text of each method's parameters and prepends it to the docstrings.
Is OK to change the ID of an AST node as I do in casemethod.c:819ff?  I don't think this should leak, since I've checked that the string is empty.
fun my_case_func(p: Array[USize] iso, q: USize) =>
"""
This case takes an array of integers and another integer.
"""
None
fun my_case_func(p: String, q: U32) =>
"""
This takes a string and an integer.
"""
None
becomes
`my_case_func(p: Array[USize] iso, q: USize)`: This case takes an array of integers and another integer.
`my_case_func(p: String, q: U32)`: This takes a string and an integer.
```pony
fun box my_case_func(
p: (Array[USize val] iso | …
```
> Include case method docstrings in doc output

- .appveyor.yml
- .travis.yml
- README.md
- src/libponyc/codegen/gendebug.cc
- src/libponyc/codegen/genopt.cc
Before this can be merged, [ponyc-windows-llvm](https://github.com/ponylang/ponyc-windows-llvm) will have to be updated with LLVM 3.9 binaries. I don't have a Windows system at hand so I don't think I'll be able to do it.
The final release builds still use LLVM 3.8 until we're certain there are no regressions with LLVM 3.9.
> Add LLVM 3.9 builds in CI

- packages/net/_test.pony
Example of an intermittent failure:
https://travis-ci.org/ponylang/ponyc/jobs/169033918
> Mark TCPExpect as unreliable on OSX

- CHANGELOG.md
- packages/net/_test.pony
- packages/net/tcp_connection.pony
- packages/net/tcp_connection_notify.pony
Implements RFC #17:
https://github.com/ponylang/rfcs/blob/master/text/0017-tcp-backpressure.md
TCP provides backpressure to signal to applications that they need to
slow down sending, however, currently Pony while itself being signaled
that backpressure is being applied, doesn't surface that to application
code. This means that even a well meaning, diligent programmer is unable
to respond to backpressure by slowing down.
Additionally, currently Pony applications that are TCP receivers can't
participate in this system as they have no way of preventing
TCPConnection from continuing to read all available data.
This commit add support for TCP backpressure to TCPConnection.
> Add TCP backpressure hooks

- packages/net/_test.pony
The net tests all require external resources. As integration
tests, its possible that they might interfere with each other.
By placing them in an exclusion group together, Ponytest will
run them sequentially rather than concurrently.
> Run `net` tests in an exclusion group

- .appveyor.yml
- Makefile
See if this solves our flakey test problem. My theory is that we have
failing tests because, we are running more tests and have more
contention on the scheduler so we are more likely to hit timeouts.
If flakey tests disappear when running sequentially then adding a
facility to exclude certain groups from tests would work well.
Something like:
run all tests except X, Y, Z "groups"
run X
run Y
run Z
This could be jammed into existing label and exclusion group support
but I think that address it head on via some new addition to PonyTest
would make sense.
This initial commit to test sequentiality is meant to:
* Verify that it doesn't take too long to run all our tests in a
sequential fashion
* Verify that running sequentially fixes our problem
If this commit doesn't increase CI times by too …
> Run tests sequentially

- CHANGELOG.md
- src/libponyrt/gc/trace.c
- src/libponyrt/pony.h
This new function allows switching to a new message when tracing message contents before sending. The two following code snippets are equivalent.
```c
pony_gc_send(ctx);                | pony_gc_send(ctx);
pony_trace(ctx, obj);             | pony_trace(ctx, obj);
pony_send_done();                 | pony_send_next(ctx);
pony_sendp(ctx, to, mid, obj);    | pony_trace(ctx, obj2);
pony_gc_send(ctx);                | pony_send_done();
pony_trace(ctx, obj2);            | pony_sendp(ctx, to, mid, obj);
pony_send_done();                 | pony_sendp(ctx, to2, mid2, obj2);
pony_sendp(ctx, to2, mid2, obj2); |
```
Using `pony_send_next` can reduce the amount of GC acquire messages that must be sent. Using the function never results in more work being performed.
An optimisation pass taking advantage …
> Add pony_send_next runtime function

- CHANGELOG.md
- Makefile
- src/libponyc/codegen/genexe.c
The normal version of libponyrt was linked even when compiling with `--pic`. Now, libponyrt-pic is linked when appropriate.
Closes #1359.
> Link libponyrt correctly with --pic on Linux

- packages/collections/map.pony
The current example is unclear as to which value is the old value
and which is the new value when setting up the lambda. By switching
from addition to subtraction in the example, this becomes clear.
This documentation could be improved further but this is a decent
start towards resolving that possible confusion without having
to look at the source code.
Close #1337
> Clarify lambda interface to map.upsert

- Makefile
dtrace_probes.h won't always be present. Use `-f` to remove
if present and otherwise, don't error out.
> Fix broken `make clean`

- Dockerfile
The Dockerfile was using the apt package llvm-dev which installed llvm 3.8.0. This change will Install the prebuilt binary of llvm 3.9.0 instead.
> Update Dockerfile to use LLVM 3.9

- CHANGELOG.md
- packages/builtin/float.pony
- packages/builtin/real.pony
`min_value` was previously returning the smallest normalised positive number, which wasn't consistent with `min_value` on integers. `min_value` now returns the smallest negative number, and a `min_normalised` function returning the smallest normalised positive number has been added.
Closes #1351.
> Rename FloatingPoint min_value to min_normalised

- src/libponyc/codegen/gencall.c
- src/libponyc/codegen/gencall.h
- src/libponyc/codegen/genfun.c
- src/libponyc/codegen/genprim.c
- src/libponyc/codegen/gentrace.c
- src/libponyc/codegen/gentrace.h
- src/libponyc/codegen/gentype.c
- src/libponyc/reach/reach.h
This change inlines message tracing and sending in caller functions. It will allow tracing the most precise object type possible, for performance. If the call is made through an interface and it cannot be proven that it is a message send, a virtual call is made.
> Trace message contents in the sender context

- CHANGELOG.md
- Makefile
- premake5.lua
- src/ponyc/main.c
This PR shows the c compiler used to build Pony for the `--version` output rather than getting the version at run time. resolves #1245
> Get compiler version at build time

- CHANGELOG.md
- Makefile
This PR fixes detection of `llvmconfig39` in the `Makefile`.
Previously, only `llvm-config-3.9` was being detected.
> Fix detection of llvmconfig39 in Makefile.

- Makefile
This PR adds a warning in the `Makefile` when an unsupported LLVM version is used to compile Pony.  This adds additional visibility to the current list of supported LLVM versions in the README.
> Issue warning in Makefile when unsupported LLVM version is used.

- packages/net/http/payload.pony
as documentation says, `method` already includes status code for response
> Do not duplicate status code in HTTP response

- README.md
Even though the prebuilt binaries work on Oracle Linux just like in other RHEL-compatible Linux distributions, it ain't mentioned in the README yet.
Also, the word "available" is currently misspelled a couple of times in the README.
> Mention Oracle Linux Support in README

- src/libponyc/expr/reference.c
- test/libponyc/badpony.cc
This PR fixes a compiler assert fail on circular type inference error.
Resolves #1334.
> Fix compiler assert fail on circular type inference error (issue #1334)

- CONTRIBUTING.md
This PR adds documentation for a new way of dealing with the changelog entries for new PRs.
Pony team members who merge PRs should review the new system.  The TLDR is:
- stop requiring users to include a changelog entry in their PR.
- instead, just be sure the PR has an appropriate title and any applicable "changelog - *" label(s) before merging.
Theoretically this system should already be usable at the time of this writing, though I haven't tested the bot on the "real" ponyc repository yet.
Note that the old system will still continue to work.  For existing PRs where the user already included a changelog entry in the diff, simply avoid applying the "changelog - *" label and the bot will leave the changelog alone.
> Automated changelog entry system for PR merges.

- src/libponyc/expr/postfix.c
- test/libponyc/badpony.cc
This PR fixes a compiler assert failure when constructor is called on type intersection.
Resolves issue #1398.
> Fixed compiler assert failure when constructor is called on type intersection (issue #1398)

- src/libponyc/expr/call.c
This PR resolves #1396 by passing the funref ast node to `reify_defaults` so that it may be used in error reporting in the case that no type arguments are given.
> Fixed error message when no type arguments are given (issue #1396)

- CHANGELOG.md
- src/libponyrt/sched/mpmcq.c
- src/libponyrt/sched/mpmcq.h
- src/libponyrt/sched/scheduler.c
This fixes a huge performance problem when running with many threads. The inject queue is empty most of the time, but all schedulers will regularly try to pop from it. This change removes the synchronisation operations if the queue is empty.
> Avoid unnecessary synchronisation in the inject queue

- .travis.yml
- CHANGELOG.md
- Makefile
- README.md
Homebrew now supports LLVM 3.9.
> Enable LLVM 3.9 in Travis OSX builds

- CHANGELOG.md
- src/libponyc/codegen/genname.c
We now prefix the name with e.g. `t2` instead of `2t`. This change was made because identifiers can't start with numbers in C, and that rule was problematic for generated library headers.
-----
I haven't been able to come up with an ambiguous case with this new mangling, so I think the change is fine. But maybe I'm horribly wrong and there is something I've missed.
> Change internal mangling for complex types

- examples/delegates/main.pony
- examples/echo/echo.pony
- examples/mixed/main.pony
- examples/producer-consumer/consumer.pony
- examples/yield/main.pony
- packages/net/tcp_connection_notify.pony
- packages/ponytest/pony_test.pony
- packages/process/_test.pony
Many of the examples were using whitespace in a way that was
inconsistent with the established normative code style for the
official codebase. This is particularly problematic, since
the examples are often the first place a user will go to learn
Pony and normative code style.
> Whitespace fixes in Pony code style.

- pony.g
- src/libponyc/ast/lexer.c
- src/libponyc/ast/parser.c
- src/libponyc/ast/token.h
- src/libponyc/codegen/gencall.c
- src/libponyc/expr/call.c
- src/libponyc/expr/literal.c
- src/libponyc/expr/postfix.c
- src/libponyc/expr/postfix.h
- src/libponyc/pass/expr.c
- src/libponyc/type/alias.c
- src/libponyc/type/alias.h
- test/libponyc/chain.cc
This change provides a way to chain calls on an object without depending on the method's API.
Closes #1409.
> Method chaining (RFC #25)

- src/libponyrt/gc/serialise.c
Prior to this commit, serializing a pony object would leak memory.
By using "pool alloc" rather than "pony alloc", we were directly
allocating memory that would need to be manually freed. What we
wanted to do was use "pony alloc" so that the GC would track
usage of the memory and free it when needed.
> Stop leaking memory during serialization (issue #1413)

- src/libponyrt/actor/actor.c
- src/libponyrt/actor/messageq.c
- src/libponyrt/asio/epoll.c
- src/libponyrt/mem/pagemap.c
- src/libponyrt/mem/pool.c
- src/libponyrt/sched/mpmcq.c
By default, Helgrind doesn't know about the happens-before relationships introduced by atomic operations and can report subsequent normal operations as false positives. With this change, Helgrind should only report the atomic operations themselves, which also are false positives but Helgrind has no way to know that.
> Make Helgrind aware of atomic memory operations

- CHANGELOG.md
- examples/dtrace/scheduling.d
- examples/systemtap/scheduling.stp
- src/common/dtrace.h
- src/common/dtrace_probes.d
- src/libponyrt/actor/actor.c
- src/libponyrt/mem/heap.c
- src/libponyrt/sched/cpu.c
- src/libponyrt/sched/scheduler.c
- src/libponyrt/sched/start.c
This pull request adds new probes to the DTrace/SystemTap implementation which are focused on the scheduling of actors. Using these probes you should be able to get a direct view of how different actors are scheduled.
The use of these probes has been shown in the scheduling scripts in the respective `dtrace` and `systemtap` folders in the `examples` directory.
Contribution by @mkdubik, @DarkLog1x and me.
> Add DTrace/SystemTap scheduling probes

- CHANGELOG.md
The last line of the `unreleased` log contains the heading of the previous release. This PR adds that missing newline, restoring proper formatting.
> Add missing newline before the previous release.

- packages/builtin/string.pony
- packages/builtin_test/_test.pony
When the `Array[U8]` passed to `String.from_iso_array` has pre-allocated
space, the first pre-allocated byte (the one at the `_size` index) should
be set to `0` in order to be compliant with how `is_null_terminated`
does its check. This PR sets that byte in such a case.
Fixes #1435
> Set null terminator in String.from_iso_array (issue #1435)

- src/libponyc/ast/stringtab.c
- src/libponyc/ast/symtab.c
- src/libponyc/codegen/codegen.c
- src/libponyc/codegen/gentype.c
- src/libponyc/pkg/buildflagset.c
- src/libponyc/reach/paint.c
- src/libponyc/reach/reach.c
- src/libponyrt/ds/hash.c
- src/libponyrt/ds/hash.h
- src/libponyrt/gc/actormap.c
- src/libponyrt/gc/actormap.h
- src/libponyrt/gc/cycle.c
- src/libponyrt/gc/delta.c
- src/libponyrt/gc/gc.c
- src/libponyrt/gc/objectmap.c
- src/libponyrt/gc/objectmap.h
- src/libponyrt/gc/serialise.c
- test/libponyc/paint.cc
- test/libponyrt/ds/hash.cc
This change was motivated by profiling using linux `perf` and
`FlameGraphs` which revealed that `ponyint_objectmap_getorput`
was an expensive operation of which `search` in hashmap was taking
up almost all the processing time. The `FlameGraphs` also revealed
that `search` was being called twice by `ponyint_objectmap_getorput`,
once for `get` and again for `put` where the object wasn't found.
This change allows `ponyint_objectmap_getorput` to only do the `search`
once and reuse the `index` returned by `search` for the subsequent `put`
operation via the new `putindex` function. In addition to changing
`ponyint_objectmap_getorput`, this PR also changes all instances
where a `get` was followed by a subsequent `put` to reuse the `index`
from `search` via `putindex` for all hashmaps in the …
> hashmap: Add new putindex function and make everything use it

- packages/builtin/string.pony
- packages/builtin_test/_test.pony
When `_alloc` is equal to `_size`, the `is_null_terminated` method will
point to arbitrary memory when checking for the `0` byte. This PR makes
that method first check that `_alloc != _size` before reading the
`_size` byte of the `Pointer[U8]`.
Fixes #1425
> Fix is_null_terminated reading arbitrary memory (issue #1425)

- src/libponyrt/actor/actor.c
On weakly ordered architectures (e.g ARM), this change results in less hardware fences being issued. On strongly ordered architectures (e.g. x86), this change has no effect since acquire fences aren't explicit.
> Synchronise on success only in ponyint_actor_destroy

- packages/builtin/string.pony
The `space()` method assumes that the string is null termianted, and so
it always returns `_alloc - 1`. When not null terminated, the space
should return the full `_alloc`.
This PR assumes PR #1429 is correct and has been merged.
Fixes #1426
> Make space() check if string is null terminated (issue #1426)

- packages/builtin/string.pony
- packages/builtin_test/_test.pony
The signature is almost the same as `String.split`, we don't have any default value here. I'm not sure what'd make sense, `\n`, `' '`?
There are some users of `String.split` in the stdlib and this can't be a drop-in replacement for those. If it's acceptable we can replace the current String.split uses with a Regex or move the current logic under another name (tokenize?).
> Added String.split_by, which uses a string delimiter (issue #1399)

- src/common/platform.h
- src/libponyrt/mem/heap.c
- src/libponyrt/mem/pool.c
This change replaces some bit counting operations in the runtime by more efficient ones.
- ponyint_heap_alloc_small: The slot search now uses CTZ instead of FFS. A slot mask with free slots isn't zero so this is safe.
- ponyint_pool_index: Now uses CLZ instead of rounding to next power of 2 followed by FFS. The size can't be zero on this code path so this is safe.
This results in less instructions being issued on both x86 and ARM.
> Optimise count zeros operations in the runtime

- README.md
Turns out the Windows 10 SDK doesn't include the linker; Visual Studio 2015 is required; [Microsoft says](https://developer.microsoft.com/en-us/windows/downloads/windows-10-sdk):
By installing this SDK, the latest Visual Studio 2015 release, and your IDE environment you will be able to access the new Windows 10 APIs.
This PR adds a comment to the README that VS2015 is required.
> Add a comment to the README requiring Visual Studio 2015 to run Pony on Windows (#1440).

- .appveyor.yml
This PR adds a comment to .appveyor.yml in order to invalidate the AppVeyor build cache to see if the cached LLVM is bad.
Please do not merge unless the AppVeyor build actually works.
> Change appveyor.yml to rebuild the build cache (#1444)

- packages/builtin/string.pony
- packages/builtin_test/_test.pony
The `String.recalc` method would truncate the final byte in a string
where no null terminator was found. The behavior and documentation
has been changed so that in the case of no null terminator, the
`_size` of the string remains unchanged.
Fixes #1446
> Fix String.recalc method for cases where no null terminator is found (issue #1446)

- src/libponyc/ast/ast.c
- src/libponyc/ast/ast.h
- src/libponyc/type/typeparam.c
- test/libponyc/type_check_bind.cc
Check a stack of typeparam defs instead of just the original. Fixes #918.
> Fix compiler handling of type params in stacks (issue #918)

- README.md
It turns out that pcre2 is available using apt under the name `libpcre2-dev`. The Ubuntu install instructions have been changed to reflect this.
> Add libpcre2-dev to Ubuntu install list

- packages/builtin/string.pony
- packages/builtin_test/_test.pony
When `String.truncate` is called on a String where `_size` is
to `_alloc`, the last byte would be lost since it set the null
terminator without first checking.
Because the docs guarantee that the result is null terminated,
when the `len` passed to `truncate` is greater than or equal to
the `_alloc`, extra space is reserved to accommodate the null
terminator.
While this resolves the issue without changing documented behavior,
it has the undesirable effect that in this specific case, a call to
`truncate` can actually allocate, which may be surprising.
Fixes #1427
> Prevent `String.truncate` from chopping last byte

- .appveyor.yml
I have an unsubstantiated theory about #1444 that the cached directory for the LLVM libarary is being corrupted by being confused with a standard LLVM install that doesn't include llvm-config.exe.
This PR makes the AppVeyor build use a pony-specific name for the LLVM build directory in order to test this theory.
> Make AppVeyor build cache use pony-specific name for LLVM directory

- .appveyor.yml
This PR disables the AppVeyor build cache for LLVM.  Experiments in changing the directory name (#1458) did not work; it seems that something is corrupting the build cache for LLVM.
> Disable cache for LLVM for AppVeyor build (#1444)

- src/libponyc/codegen/gencall.c
This change makes sure that chained behaviours are candidate for the local message sending optimisation.
> Check chained behaviours for local message sending

- .appveyor.yml
It looks like the AppVeyor cache problem (#1444) is not just for LLVM.  This PR turns off build cacheing for everything.
> turn off appveyor build cache for all directories

- src/libponyc/pass/finalisers.c
- src/libponyc/pass/verify.c
- src/libponyc/reach/reach.c
- src/libponyc/verify/call.c
- test/libponyc/finalisers.cc
- test/libponyc/verify.cc
This fix covers partial method checking and message sending in finalisers.
> Check errors correctly for method chaining

- src/libponyc/codegen/genprim.c
Looking up the function with `TK_NONE` instead of `TK_BOX` resulted in the wrong metadata being generated.
> Correctly generate TBAA metadatas for box intrinsics

- src/libponyc/verify/fun.c
- test/libponyc/verify.cc
The previous error message said that a function must be partial in order to raise an error. This was confusing for behaviours (which can't be partial) and the error message has been changed to "a behaviour must handle any potential error".
> Change error message for erroring behaviour bodies

- README.md
This PR adds the [pony plugin](https://github.com/Theodus/micro-pony-plugin) for [micro](https://github.com/zyedidia/micro) to the list of supported text editors.
> Add micro to supported editors

- src/libponyc/expr/operator.c
- test/libponyc/badpony.cc
When assigning to a field, the incoming value must be a subtype of
the field type _without_ viewpoint adaptation.
This addresses #1469.
> Don't violate reference capabilities when assigning via a field

- packages/ponybench/_auto_bench.pony
- packages/ponybench/_bench.pony
- packages/ponybench/_bench_async.pony
- packages/ponybench/pony_bench.pony
This PR makes a few small changes to the ponybench package:
- Update docstring example so it compiles now that behaviors return None
- Notify the user if a benchmark failed due to a timeout
- Fix a bug in the ordering of asynchronous benchmarks
- Attempt to resolve #1420  by creating a separate `_AutoBenchAsync` actor and cleaning up the mess of lambdas in `PonyBench`
> Clean up ponybench

- packages/net/tcp_connection.pony
Prior to this commit, if we were in TCPConnection's _pending_reads
and encountered discovered that the connection was muted, we would
call read_again to requeue another read and would then return.
This results in a lot of extra, unneeded work. Until the connection
is unmuted, there's no point to calling read_again, we'll just keep
repeating the same cycle over and over again; pointlessly putting
messages on the TCPConnection's queue.
With the commit, we now return from _pending_reads when discovering
that the connection is muted without calling read_again. Instead,
when we unmute the connection, we will then immediately call
_pending_reads to start processing any unhandled data.
There is probably a similar improvement that can be made on Windows,
however, I'm not a Windows programmer, …
> Improve efficiency of muted TCPConnection on non Windows platforms

- CHANGELOG.md
- packages/net/tcp_connection.pony
Looks like I missed this case when first adding backpressure
notifications to TCPConnection. What's missing?
If a connection has pending data to send after experiencing backpressure
and encounters more backpressure while trying to send after the previous
backpressure was released, no notification of the new backpressure was
given.
> Apply backpressure on TCPConnection during pending write calls

- RELEASE_PROCESS.md
- release.sh
This PR automates a large portion of the release process to reduce human error and move toward a fully automated release process. The script has been tested on my branch of ponyc with multiple changelogs and tags from past pony releases.
> Automate release versioning

- CHANGELOG.md
- packages/builtin/asio_event.pony
- packages/net/tcp_connection.pony
- src/libponyrt/asio/asio.h
- src/libponyrt/asio/epoll.c
- src/libponyrt/lang/socket.c
Using asio one shot can be much more efficient than the current edge
polling. We started using at Sendence with TCPConnection and saw a
large drop in the number of events being sent to TCPConnection
instances. This in turn lead to performance improvements.
This commit contains support in the linux asio code, as well as
the linux tcp socket code to use one shot.
Support for OSX/FreeBSD can be added as kqueue supports the same
fundamental options.
> Add ASIO one shot support when using epoll

- CHANGELOG.md
- src/libponyc/expr/call.c
- src/libponyc/expr/postfix.c
- src/libponyc/expr/reference.c
- test/libponyc/recover.cc
Locals and parameters are now accessible as `tag` inside of recover expressions instead of being completely unreferenceable. This change also fixes #1385 as a side-effect.
Closes #1385.
> Make non-sendable objects accessible as tag in recover

- packages/collections/map.pony
This commit introduces a change so that, when a key isn't found during
a `get_or_else` call, that we do not have an error thrown. Instead,
we do a search for the key directly rather than going through the
`apply` method that might throw said error.
> Improve Map.get_or_else performance

- pony.g
- src/libponyc/ast/ast.c
- src/libponyc/ast/ast.h
- src/libponyc/ast/astbuild.h
- src/libponyc/ast/bnfprint.c
- src/libponyc/ast/lexer.c
- src/libponyc/ast/parser.c
- src/libponyc/ast/parserapi.c
- src/libponyc/ast/parserapi.h
- src/libponyc/ast/token.h
- src/libponyc/expr/lambda.c
- src/libponyc/pass/sugar.c
- test/libponyc/annotations.cc
Scoping keywords can now be annotated with arbitrary Pony identifiers. The current format for annotations is `\foo, bar\`. In the actual implementation, any grammar rule can easily be used as an annotation if we need that flexibility in the future.
Closes #1442.
> AST annotations (RFC 27)

- CHANGELOG.md
- src/libponyc/type/alias.c
This fixes an assertion failure when chaining an `#any` receiver.
Because of other bugs in the implementation (namely #1328), non-tag methods can currently be called on an `#any` receiver. Another assertion has been added to prevent this case to silently pass.
> Handle #any in chain_type

- src/libponyc/expr/reference.c
- test/libponyc/recover.cc
After the aforementioned change, non-sendable locals could be assigned to inside of recover expressions, violating the isolation boundary of recover.
No changelog entry since the bug isn't in a released version.
> Fix type system hole introduced by fee5e5c

- src/libponyc/expr/reference.c
This was an oversight from previous changes involving method chaining and non-sendable objects in recover.
> Allow method chaining on non-sendable objects in recover

- CHANGELOG.md
- packages/net/tcp_connection.pony
- src/libponyrt/asio/kqueue.c
- src/libponyrt/lang/socket.c
When using EV_ONESHOT, after the user retrieves the event from the kqueue, it is deleted. This way, when the `pony_asio_event_resubscribe` is called, we need to recreate the events.
> Add ASIO one shot support when using kqueue

- src/libponyc/pass/syntax.c
- test/libponyc/badpony.cc
This PR resolves #1493  by improving the error message for indexing into an array with square brackets like `some_array[1]` as you would in many other languages. Previously the error was `Value formal parameters not yet supported`.
> Improved error for array indexing with brackets

- packages/builtin/builtin.pony
- packages/builtin/platform.pony
This PR moves the builtin package documentation which was previously in `platform.pony` into a separate file `builtin.pony` and updates it to include the rules defined in #286.
> Update builtin package documentation

- .travis.yml
- README.md
No longer available via homebrew.
> Deprecate LLVM 3.6 OSX support

- src/libponyrt/sched/scheduler.c
In the case where choose_victim returns NULL, we set the
scheduler trying to do stealing as the victim. This caused
it to check the inject queue and then its own queue for work.
The latter check is pointless. We are doing work stealing
because our queue is empty.
This commit switches to only checking the inject queue if
we are "stealing from ourselves".
> Slightly more efficient work stealing

- packages/term/readline.pony
This PR makes the readline handler interpret C-d on an empty line as EOF, as described in the [Readline docs](https://cnswww.cns.cwru.edu/php/chet/readline/rluserman.html#SEC16).
> Readline interpret C-d on empty line as EOF

- wscript
This PR adds the LibreSSL includes directory to the INCLUDES environment variable in the Windows build.  This allows PR #1510 to build on Windows.
> Add LibreSSL include directory to INCLUDES on Windows build (allows PR #1510 to build)

- src/libponyc/expr/match.c
- test/libponyc/badpony.cc
This PR resolves #1506 by improving the error message given on a match expression on a union of types with different capabilities. The previous error in this case vaguely stated that "this capture violates capabilities".
> Improved error for match over union of different capabilities

- packages/net/tcp_connection.pony
The previous one shot code for resubscribing was incorrect.
It could end up subscribing to an event more than once.
From what I've read for epoll, its undefined behavior if
you do that.
> Don't double resubscribe to asio events in TCPConnection

- src/libponyc/pkg/use.c
Before this change, using "package:" scheme resulted in compilation
error due to incorrect scheme length in the handlers table.
> Fix "package:" scheme

- src/libponyc/pass/names.c
- test/libponyc/badpony.cc
(I'm opening this PR as is, but admittedly this is probably the wrong way to solve this, thus my explicit use of WIP in the commit message.  If I can get some guidance on the right way to fix this, I'd be more than happy to contribute a suitable fix, including a more detailed commit message.)
So, this started with me trying to do something stupid (and getting a segfault, on the release compiler), but boiled down, this is sufficient to cause an assert with a debug compiler:
```pony
class A[I8]
let b: U8 = 0
```
What seems to happen is that if the type parameter for `A` is any of the types named in `_str_uif_types` in `libponyc/expr/literals.c`, when we then go to look up `U8` (which can be any _other_ type from that same set of builtin types) in `uifset_simple_type()`, the structure of the …
> Disallow type parameter names shadowing other types.

- src/libponyc/codegen/codegen.c
- src/libponyc/codegen/codegen.h
- test/libponyc/util.cc
- test/libponyc/util.h
This change will allow testing various functionalities of the code generator. In particular, it will be useful to test RFC 32 (packed structures).
> Add code generation to the compiler test framework

- src/libponyc/codegen/gencall.c
Previously in `special_case_operator`, a no-op and a failure were reported in the same way. This change ensures that we detect errors and that we don't proceed through the final stages of compilation.
This doesn't fix any program correctness issue. The only error that could be detected here is a division by 0 error which was reported even though compilation didn't stop and wasn't inhibiting the runtime check, because of the way the code generator is architectured.
> Correctly detect compile errors from arithmetic operations

- src/libponyc/codegen/gencontrol.c
- src/libponyc/codegen/gencontrol.h
- src/libponyc/codegen/genmatch.c
This change adds annotations to control structures allowing programmers to make the optimiser aware of the likelihood of a given condition.
Closes #1500.
> Branch prediction annotations (RFC 30)

- README.md
- packages/collections/_test.pony
- packages/collections/map.pony
Allows for a speed improvement by saving a Map lookup when using
this pattern:
```pony
if not my_map.contains(my_key) then
my_map(my_key) = my_value
end
```
> Add `insert_if_absent` method to Map

- src/libponyc/codegen/gentype.c
- test/libponyc/util.cc
- Use a default file name for debug information when we compile from a string and have no input file name
- Make sure to reach `None` in the fake builtin package for the tests
- Set verbosity to quiet during tests
> Make codegen tests run smoothly

- src/libponyc/codegen/gentype.c
- test/libponyc/codegen.cc
This change adds program annotations allowing programmers to declare packed structures, i.e. structures without implementation-specific padding between members.
Closes #1523.
> Packed structures (RFC 32)

- .gitignore
- wscript
The new Windows build did not correctly include symbol information (*.pdb files) for debug builds.  This PR changes the build script to do this.  It also adds a couple of entries to the .gitignore to ignore files used for VS2017 "Open Folder" functionality.
> Correctly emit debugging info for Windows debug builds

- src/libponyc/codegen/codegen.h
- src/libponyc/codegen/genexe.c
- src/libponyc/codegen/genfun.c
- src/libponyc/codegen/genfun.h
- src/libponyc/codegen/genheader.c
- src/libponyc/codegen/genname.c
- src/libponyc/codegen/genname.h
- src/libponyc/codegen/gentype.c
This new function is generated for both executables and libraries. In the latter case, it allows users to initialise and finalise primitives with a single function call.
> Call primitive _init and _final through a global function

- src/libponyc/ast/lexer.c
- src/libponyc/ast/parser.c
- src/libponyc/ast/token.h
- src/libponyc/ast/treecheckdef.h
- src/libponyc/pass/sugar.c
- src/libponyc/type/alias.c
- src/libponyc/type/cap.c
- src/libponyc/type/reify.c
- src/libponyc/type/typeparam.c
- src/libponyc/type/viewpoint.c
- test/libponyc/sugar.cc
The standard term in the tutorial for `!` is "aliased type". Using `TK_ALIASED` in the compiler is more consistent with this.
> Rename TK_BORROWED to TK_ALIASED in the compiler

- src/libponyrt/sched/mpmcq.c
- src/libponyrt/sched/mpmcq.h
- src/libponyrt/sched/scheduler.c
The original testing for performance impact of the ticketing
algo change was done at Sendence. At the time, we didn't see
any impact. However, we weren't looking in the right place.
We have since found that the ticketing algo under some workloads
can result in very long pauses (up to a second) getting a ticket.
Further, we regularly see pauses while waiting to get a ticket
measured in the 100's of micro-seconds.
This commit reverts to the prior double word cas algo that we
found has far better performance characteristics in the "bad"
scenarios we found and the same or slightly better characteristics
under normal circumstances.
The reversion includes the work in a later commit to support GCC
4.7.
It does not include the VALGRIND awareness that was added later.
I'm not sure where to put …
> Performance fix in the runtime actor schedule

- CHANGELOG.md
- src/libponyc/codegen/gentrace.c
This change fixes a code generator crash on generating behaviour calls with tuples as arguments.
Closes #1546.
> Generate trace correctly for tuples

- examples/net/ping.pony
- examples/net/pong.pony
- packages/net/_test.pony
- packages/net/dns.pony
- packages/net/http/server.pony
- packages/net/net_address.pony
- packages/net/tcp_connection.pony
- packages/net/tcp_listener.pony
- packages/net/udp_notify.pony
- packages/net/udp_socket.pony
As was discussed in https://github.com/ponylang/ponyc/pull/1524,
IPAddress is poorly named as it doesn't represent just the IP address,
it incorporates additional information such as port, protocol etc.
This change renamed IPAddress to more applicable NetAddress.
> Rename IPAddress to NetAddress

- packages/net/tcp_connection.pony
As part of the TCPConnection/EPoll One Shot changes that I previously
submitted, there was a bug where when the TCPConnection experiences
throttling, it won't ever get notified when we are ready to send again.
This patch addresses that in the short term. There's a PR coming from
Dipin Hora that addresses this in a better fashion and handles a
subtle race condition in One Shot ASIO events. This small patch
should suffice in the meantime and get master back to a correct state.
Close #1539
> Correctly resubscribe TCPConnection to ASIO events after throttling

- packages/net/tcp_connection.pony
- src/libponyrt/asio/epoll.c
- src/libponyrt/asio/event.c
- src/libponyrt/asio/event.h
- src/libponyrt/asio/kqueue.c
- src/libponyrt/lang/socket.c
Prior to this change, if ONE_SHOT is enabled, linux epoll based
asio wouldn't be subscribed for certain events after another
event was fired on the same FD.
The specific scenario was the following:
* Register event E for READ/WRITE with ONE_SHOT.
* E fires for READ and a message is placed on the message queue
for the TCPConnection actor.
* TCPConnection actor eventually gets to processing this message
(after processing any other messages ahread of this one on the
queue) and then goes through the work of `_event_notify`. At
the end of `_event_notify`, `_resubscribe_event` is called and
epoll is told to resubscribe for READ and/or WRITE events as
required.
Normally, this wouldn't be an issue but the behavior we're seen
is that with ONE_SHOT, if a READ (or WRITE) event is fired, all
events …
> Fix Linux epoll event resubscribe performance and race condition.

- src/libponyrt/gc/gc.c
Force `mutability` to trigger recursion.
DO NOT MERGE
I've been unable to reproduce #1118 locally. Can someone confirm that they can reproduce it, and that this change fixes it? Thanks!
> Recurse when tracing an iso that has become a val

- CHANGELOG.md
- src/libponyc/codegen/codegen.c
- src/libponyc/codegen/gendesc.c
- src/libponyc/codegen/genexe.c
- src/libponyrt/gc/serialise.c
- src/libponyrt/gc/serialise.h
- src/libponyrt/pony.h
- src/libponyrt/sched/start.c
The `__DescTable` and `__DescTableSize` defined by Pony programs and generated by the compiler are now accessed dynamically by the runtime (with `dlsym` on POSIX and `GetProcAddress` on Windows).
This change was made for two reasons:
- To avoid link errors from of compiler-generated symbols when using the runtime library directly in a C program.
- JIT compilation is being worked on for the compiler test framework. Since we'll want to run more than one JIT'ed programs in the test suite, the symbol addresses must be dynamic.
As part of this change, the `pony_start` runtime function now takes an additional parameter indicating whether the language-specific features of the Pony runtime should be intialised. This solves the first concern stated above by avoiding referencing the symbols.
> Load program symbols dynamically in the runtime

- src/libponyc/type/lookup.c
- src/libponyc/type/subtype.c
- src/libponyc/type/subtype.h
In subtype checking we now avoid some costly allocation operations
associated with viewpoint adaptation and reification by checking
first if the type could be a subtype of the other if caps were ignored.
If not, then there's no point in moving forward with comparisons
that take the cap into account, but require costly allocations.
Reduces compile time drastically for programs requiring a lot of type
unions to be flattened, where those types involve viewpoint adaptation.
For the real-world package under test, compile time was reduced by 23x.
For comparison, standard library test compile time was not affected by this change.
> Performance improvement in subtype checking.

- benchmark/libponyrt/ds/hash.cc
Fixes compiling issues on 32 bit platforms for the hashmap benchmarks by switching from `printf` to `cout` because `%zu` isn't as portable (http://stackoverflow.com/a/2524673).
> Fix benchmark build on 32 bit platforms.

- packages/ponytest/_test_runner.pony
Prior to this commit, PonyTest would register multiple timers
for a long test but only keep track of the last one. This would
result in not all timers getting cancelled on successful
completion of a test. This would mean that PonyTest would not
exit immediately after all tests passed but would still wait for
uncancelled timers to expire even though the tests for these
timers had already successfully passed.
This commit fixes the issue by having PonyTest keep track of all
timers it creates in an array and then cancelling every timer when
a test successfully completed. As a result, now, PonyTest exits
immediately after all tests have passed.
> Fix PonyTest timer cancel logic

- packages/net/tcp_connection.pony
Prior to this commit, when we `_accept`ed a new connection
or completed a connection via `_event_notify` there was a race
condition around reading data that the other party sent to us.
This existed because we didn't check to see if any data was
waiting on the socket for us already and instead only subscribed
to ASIO events for new read notifications. If the other party sent
us data after we signed up for ASIO events, we would successfully
receive notification and read the data. However, if the other
party sent us data before we signed up for ASIO events, we would
not read the data already on the socket and would wait for an ASIO
event telling us that we have data to read.
This commit fixes this race condition by ensuring that we try to
read from the socket whenever we `_accept` or …
> Fix TCP Connection data receive race condition

- packages/builtin/string.pony
- packages/builtin_test/_test.pony
This PR adds a check for null terminator in String._append. Previously, this method assumed that all strings were null terminated.
resolves #1579
> Check for null terminator in String._append

- src/libponyrt/ds/fun.c
This PR adds fallthrough comments to keep GCC >= 7.x happy.
Resolves #1581.
> Add fallthrough comments to keep GCC >= 7.x happy.

- src/libponyc/pass/sugar.c
- src/libponyrt/ds/fun.c
These changes solve the problem and allows a build using GCC 7 on Fedora Rawhide.
> Amend the fallthrough comments to keep GCC 7 on Fedora Rawhide happy.

- minimal-cases/finalisers/finalisers.pony
- src/libponyc/codegen/genfun.c
- src/libponyc/reach/reach.c
Previously, finalisers of embedded fields would never be called due to embedded fields being transparent to the runtime. This change adds calls to the adequate finalisers in parent objects' finalisers when said parents contain embedded fields.
Closes #1551.
> Always call finalisers for embedded fields

- src/common/platform.h
- src/common/pony/detail/atomics.h
- src/libponyrt/actor/actor.h
- src/libponyrt/sched/mpmcq.c
- src/libponyrt/sched/mpmcq.h
- src/libponyrt/sched/scheduler.h
This change adds a cross-platform implementation for big atomics (2 machine words in size) used for ABA protection in the MPMC queue. The ABA structure is now declared and used via macros. This change also
restores support for GCC 4.7 and 4.8 and Clang 3.3 through 3.5, which was temporarily dropped in 81e727a.
> Tidy up big atomic operations

- src/libponyc/codegen/codegen.c
- src/libponyc/codegen/codegen.h
- src/libponyc/codegen/host.cc
- src/ponyc/main.c
This PR fixes #1176 using the proposed approach discussed in that ticket.
Specifically, if the user does not specify specific `--features` in the invocation, we use LLVM's `getHostCPUFeatures` function to get the list of features (and format them into the expected features string format).
> Use LLVM to detect CPU features by default if --features aren't specified.

- packages/collections/persistent/_map_node.pony
- packages/collections/persistent/map.pony
This PR simply make the persistent Map more general by allowing the value to be `Any #share` rather than `Any val`.
> Make persistent map more general

- CHANGELOG.md
- packages/net/net_address.pony
Provides two types of equality.
1: "basic equality"
Compares all the fields of NetAddress to see if they are equal. This
is the comparison if we use `==` or `eq`.
2: "address equality"
Compares based on the ip address portion of NetAddress. Does not
take port, family, length or scope into account. We are using
"address equality" at Sendence to compare, "is this IP for a local
or remote address" which is in turn used to decide whether to turn
on TCP_NODELAY (on Linux, using TCP_NODELAY on local addresses has
a negative impact on our performance/stability. Using it on
remote addresses helps our performance/stability).
> Makes NetAddress comparable

- CHANGELOG.md
- src/libponyc/reach/reach.c
- test/libponyc/reach.cc
This change ensures that unions and intersections pick up their subtypes during the reachability analysis.
Closes #1474.
> Add subtypes to unions/isects in the reach pass

- src/libponyc/codegen/gencall.c
- src/libponyc/codegen/gencall.h
- src/libponyc/codegen/genfun.c
- src/libponyc/codegen/genprim.c
- src/libponyc/codegen/gentrace.c
- src/libponyc/codegen/gentrace.h
- src/libponyc/codegen/gentype.c
- test/libponyc/badpony.cc
- Add a new trace pattern, static tracing. This is used when tracing a nominal type in order to trace it in the most efficient way possible (type in the sending context and capability in the receiving context).
- Enhance dynamic tracing of nominal types with that same type/capability logic.
- Trace boxed tuples correctly.
Even though this fixes a compiler crash, there is no new changelog entry since there is already one that also covers this fix in the unreleased part of the changelog.
> Refactor GC trace generation in the compiler

- packages/files/file_info.pony
- src/libponyrt/lang/stat.c
Makes possible to access `device` and `inode` value from pony's FileInfo type
> Expose `st_dev` and `st_ino` fields of stat structure

- src/libponyc/codegen/gentrace.c
This change fixes the logic in the code generator handling trace generation for machine words.
If this gets merged before the upcoming release, this shouldn't get a changelog entry since there is already one covering a very related case.
> Fix GC tracing for numeric primitives boxed in unions

- packages/net/_test.pony
Previously, when I added mute and throttle related tests, I
inadvertently had each set up two long tests as I didn't realize
that `_TestTCP` was setting up a long test.
This change removes the extra `long_test` calls.
> Removes duplicate long test calls from net/_test.pony

- packages/ponytest/test_helper.pony
I was surprised when not finding this function in the package. I don't think this requires an RFC since it looks like an oversight.
> Add assert_no_error test condition to PonyTest

- CHANGELOG.md
- src/libponyc/codegen/gencall.c
- src/libponyc/reach/reach.c
- src/libponyc/reach/reach.h
Previously, a message send was inlined in the caller when every possible instantiation of the method was a behaviour. This logic turned out to be incorrect when sending a message through an interface, with the interface expecting an unboxed value as a parameter and one of the subtypes expecting a boxed value. This change suppresses the inlining of message sends when such a case arises.
> Fix message sending of boxed types through interfaces

- packages/builtin_test/_test.pony
- src/libponyrt/lang/paths.c
- test/libponyc/codegen.cc
- test/libponyc/util.cc
- test/libponyc/util.h
Now that we have JIT tests, this is the most logical place for this test and moving it allows removing the pony_test_callback from libponyrt.
> Move the CCallback test to the compiler tests

- src/libponyc/codegen/genfun.c
Generating these prototypes caused issues with debug informations since a declared but undefined LLVM function can't have debug information, and the handler of a forwarding behaviour is always left undefined.
> Don't declare forwarding behaviour handlers in codegen

- src/libponyc/codegen/codegen.c
- src/libponyc/codegen/genexe.c
- src/libponyrt/pony.h
- src/libponyrt/sched/start.c
Previously, a primitive finaliser calling `pony_exitcode` wouldn't affect the actual exit code of the program. This occurred because the value used was the value returned from `pony_start`, and finalisers were ran after returning from `pony_start`.
This change adds the `pony_get_exitcode` function, which returns the current value of the exit code as set by `pony_exitcode`.
> Pick up changes to the exit code from primitive finalisers

- src/libponyc/pass/casemethod.c
Prior to this commit the `add_docstring` function had a
buffer overlow issue that was causing memory to be
clobbered.
This commit changes the `add_docstring` function to
use a `printbuf` to accumulate the string ensuring
no more buffer overflow issues.
Fixes #1609
> Fix buffer overlow in case method docstring

- Makefile
- packages/builtin/array.pony
- packages/builtin/string.pony
- packages/files/_test.pony
- packages/files/file.pony
- src/libponyrt/lang/directory.c
- src/libponyrt/lang/io.c
- src/libponyrt/platform/threads.c
The motivation behind this is to improve performance to file i/o
operations. The C standard stdio functions do user space
buffering prior to sending the data to the OS kernel via a system
call. On most operating system, the OS kernel also does additional
buffering on top of the user level buffering by the C functions.
Unfortunately, if the C functions are buffering data, they prevent
the OS kernal from taking advantage of some potential performance
enhancements if they're available (namely Vectored I/O so the
OS can offload work to hardward and never has to combine multiple
user buffers into a single buffer for writing to disk).
The commit changes the File class to use low level i/o functions
that map to system calls on Linux and other posix based systems
and to C lib calls on Windows. On …
> Change File class to use low level and vectored i/o functions

- packages/collections/persistent/_map_node.pony
This PR replaces some math operations in the `_MapNode` methods `_set_bit`, `_clear_bit`, `_has_bit`, and `_mask` with the unsafe versions. This change should not cause issues because the argument `i` is never greater than 31 and the argument `l` is never greater than 6. The purpose of this change is to improve the overall performance of the persistent map.
> Use unsafe math operations in persistent map

- src/libponyc/type/subtype.c
- test/libponyc/type_check_subtype.cc
Previously, we assumed nominal <: structural to avoid infinite recursion
when checking structural types. This change assumes nominal <: nominal
(i.e. assumes more often) in order to avoid the same problem with other
edge cases, such as a constraint bound to itself.
> Assume nominal subtyping

- src/libponyrt/actor/messageq.c
There is no need to synchronise on failure. Using less synchronisation can result in better performance, particularly on architectures with weak memory ordering such as ARM.
> Synchronise on success only in ponyint_messageq_pop

- src/libponyrt/sched/mpmcq.c
This is a change originally suggested by @sylvanc in #1621. On x86, this results in less occurrences of the expensive cmpxchg16b instruction.
> Load the initial tail non-atomically in ponyint_mpmcq_pop

- packages/builtin/array.pony
- packages/builtin/string.pony
- packages/net/tcp_connection.pony
- src/libponyrt/lang/io.c
- src/libponyrt/lang/socket.c
The motivation behind this is to improve performance of network
i/o operations. Vectored I/O is more efficient because it offloads
the combining of multiple user buffers into a single buffer for
sending to the network hardware when possible.
------------
This change required getting the pointer to a specific element in an `array` like PR #1598 and it should become a no-op for whichever PR is merged second. In order to get that offset as cleanly and safely as possible the change in commit 34d71201339c7254b4723c68ff687aaf52efe274 was introduced. The commit message for the change is:
>Prior to this change getting an offset for a pointer into an
`array` or a `string` required doing pointer arithmetic after
geting the pointer to the start. This is problematic because
in most cases we want the …
> Change TCPConnection to use vectored i/o functions

- packages/net/tcp_listener.pony
This commit changes TCPListener to unsubscribe asio events
prior to closing the socket and file descriptor.
This prevents events from being reported for closed sockets
due to any race conditions related to socket close and
epoll receiving an event between the socket close request
and the actual close occurring.
See: http://stackoverflow.com/questions/8707601/is-it-necessary-to-deregister-a-socket-from-epoll-before-closing-it
---------------
In my limited testing, this change results in less failures in the TCP tests with the following output where the server never accepts a connection:
```
**** FAILED: net/TCPMute
Test timed out without completing
Action never completed: receiver accepted
Action never completed: receiver muted
Action never completed: receiver asks for data
Action never …
```
> TCPListener: unsubscribe asio before socket close

- src/common/pony/detail/atomics.h
- src/libponyrt/platform/ponyassert.c
Clang 3.5 has support of atomics for C++ but not for C. When compiling a C++ file, the atomic_flag preprocessor define in the Pony source files was conflicting with std::atomic_flag from the C++ standard library.
@jemc Can you try and see if it fixes the build for you?
> Fix build for Clang 3.5

- README.md
A tiny change to the README to note the requirement for at least Update 2 of Visual Studio 2015 on Windows.
> Note requirement for VS2015 Update 2 in README.md

- src/libponyc/expr/match.c
- test/libponyc/badpony.cc
A nice attempt to produce a much friendlier error message when a union
type pattern is involved and a match expression doesn't type check is
sadly removed in this commit.
Unfortunately, it assumed union types would be composed of nominal types
(not true), and that the problem with the match was a union type with
varying capabilities (this is actually allowed).
A nicer error message would indeed be useful here. The right approach
would be to emit errors in `matchtype.c` when they are needed, i.e. on
DENY.
> Remove the check for union types on match error

- .travis.yml
This will keep the online API docs in sync with the last release.
This feels like a less surprising thing to happen then to
have the docs change with each commit to master.
We could invest more time in the future to keep multiple versions
of the docs online + latest build docs but that is more than I
have time for at the moment.
If someone wanted to take that on, I'd be happy to guide them.
> Only update online API docs when releasing

- src/common/pony/detail/atomics.h
- src/libponyrt/asio/epoll.c
- src/libponyrt/asio/iocp.c
- src/libponyrt/asio/kqueue.c
- src/libponyrt/mem/pool.c
- src/libponyrt/mem/pool.h
- src/libponyrt/pony.h
- src/libponyrt/sched/mpmcq.c
- src/libponyrt/sched/mpmcq.h
- src/libponyrt/sched/scheduler.c
This change adds a global list of free blocks to the pool allocator, similar to the existing global list of free lists. When a runtime thread terminates, it will push its local free blocks to the global list, which can then be retreived by other threads.
The goal of this change is to avoid memory leaks when starting and stopping the runtime multiple times in a program, for example in the compiler test suite.
This pool allocator cleanup functionnality is exposed to user threads through the new `pony_unregister_thread` function.
PS: I expect that this change will introduce a performance penalty to the runtime termination, especially for long-running programs with lots of memory in free lists. I haven't done any real measurements so I don't have a precise estimate for this slowdown. If …
> Push local pool memory to a global list at thread termination

- src/libponyc/type/sanitise.c
- test/libponyc/verify.cc
Currently the following code does not compile:
type Foo[T] is { (T): T }
The compiler gives the error:
lambdaalias.pony:1:19: can't find definition of 'T'
type Foo[T] is { (T): T }
This PR allows the lambda type to find type parameters from an enclosing type alias, as well as class, actor, etc.
I don't think this should affect anything else, since the only other use of the `collect_type_params()` function is for sugaring object literals, which aren't allowed in a type alias.  Please let me know if this change will have wider implications.
> Fix type parameters not being visible to a lambda type in a type alias

- packages/format/format.pony
This commit adds a short example to the format package that
demonstrates how the package can be used to format strings. The
example is not meant to be comprehensive, only to demonstrate usage in
order ot make it easier to start using the package.
> Add example code for the format package

- packages/files/files.pony
This commit adds a package-level doc string that describes the file
package and talks briefly about what the different actors, classes,
and primitives do. It also includes an example program to demonstrate
package works.
> Add a package-level doc string for the files package

- packages/buffered/buffered.pony
This commit adds a package-level doc string for the `buffered` package
in a few file called `buffered.pony`. The doc string contains a short
example program.
> Add a package-level doc string for buffered and example program

- src/libponyc/ast/ast.c
Now annotation and type are both stored, while only using one pointer
(and one flag) rather than two pointers on the ast_t struct.
This saves size in allocations, and particularly puts us in a smaller
size class when it comes to the next-power-of-two size that dictates
which memory pool we allocate from.
This was discussed in #1531.
> Refactor ast internal structure to store annotation more efficiently.

- Makefile
While working on a Gentoo ebuild, where I make sure that the environment CFLAGS and LDFLAGS are used - as is policy - I encountered a linking failure when having "--as-needed" in LDFLAGS. Turns out it was due to the linking order ("-ldl" appearing before "-lponyrt").
This patch changes the order of the "whole archive" and the regular libraries, thus fixing the problem.
> Fix linking with '--as-needed' (sensitive to linking order)

- .appveyor.yml
Appveyor differs from TravisCI in that Appveyor will
kick off a CI run for a push to GitHub that is only
tags, no new commits.
As detailed in issue #1655, this combined with the
two pushes to release we do in `release.sh` means that
we do two release to bintray for each Windows release.
Initially I was going to merge the two git pushes into
a single push to solve the problem. After some thought,
I decided that the best solution is to make TravisCI and
Appveyor behave the same. If they continue to behave
differently in this regard, we might encounter additional
odd errors in the future.
Closes #1655
> Prevent duplicate Windows releases

- .travis.yml
- Dockerfile
- README.md
We regularly get issues opened from people having problems
with the prebuilt pony packages where their platform
doesn't support AVX or AVX2 and the prebuilt packages were
built with that on.
This commit should get us building with the simplest of baselines
for users and allow them to run without issue.
The `arch=` idea is Sylvan's.
> Fix AVX/AVX2 issues with prebuilt ponyc

- RELEASE_PROCESS.md
Homebrew doesn't follow a normal GitHub PR process.
This commit adds a note to release process documentation
so that the uninitiated aren't taken by surprise.
> Clarify Homebrew release process

- Dockerfile
In previous commit, it was being passed with `-arch=`
rather than the correct `arch=`
> Correctly pass `arch=` when building docker image

- README.md
MacPorts now has LLVM 3.9 available
Homebrew changed how you install LLVM 3.8
> Update OSX from source install instructions

- packages/buffered/reader.pony
This is an issue of principle-of-least-surprise, since `buffered.Writer`
emits `ByteSeq`s in its output, so having `buffered.Reader` accept `ByteSeq`s
at its input makes it symmetrical and least surprising.
This doesn't break any user code, since it only makes an argument type
more general, and does not make any return types more general.
This came up in a discussion in #1639.
> Make buffered.Reader.append accept any ByteSeq.

- .travis.yml
- Dockerfile
This should be followed by modifying the makefile to allow
setting -mtune to intel.
This should however fix issue #1682.
> Fix illegal instruction errors on older cpus when using packaged Pony

- benchmark/libponyc/common/common.cc
- benchmark/libponyrt/common/common.cc
- benchmark/libponyrt/ds/hash.cc
- benchmark/libponyrt/mem/heap.cc
- benchmark/libponyrt/mem/pool.cc
- lib/gbenchmark/gbenchmark_main.cc
This change was precipitated by @SeanTAllen pointing me to: https://probablydance.com/2017/02/26/i-wrote-the-fastest-hashtable/ where the numbers for different hashmap implementations were significantly different from the previous benchmark numbers we had.
--------------
I'm not exactly happy with everything and would appreciate any feedback/suggestions for improvements if anyone has any ideas.
--------------
According to the Google Benchmark library issue:
google/benchmark#179
The `PauseTiming`/`ResumeTiming` functions introduce a large
amount of overhead and are not recommended to be used for
microbenchmarks without understanding the overheads involved.
This commit is an attempt to minimise use of these functions along
with adding a disclaimer for when these functions are used and
a …
> Change benchmarks to limit use of `PauseTiming`/`ResumeTiming`

- src/libponyc/codegen/codegen.c
- src/libponyc/codegen/gencall.c
- src/libponyrt/actor/actor.c
- src/libponyrt/gc/gc.c
- src/libponyrt/gc/gc.h
- src/libponyrt/gc/objectmap.c
- src/libponyrt/gc/objectmap.h
- src/libponyrt/mem/heap.c
- src/libponyrt/mem/heap.h
- src/libponyrt/pony.h
- src/libponyrt/sched/scheduler.h
This PR includes 2 changes
* Ponybench arguments + finaliser benchmarks
This commit enhances `ponybench` to use `options` to take
optional command line arguments to change `autobench_time`
and `autobench_max_ops` dynamically at runtime.
This commit also adds benchmarks for objects with and without
finalisers to `minimal-cates/finalisers`.
* More efficient object finalising implementation
Thanks to @sylvanc  and @aturley for their ideas.
* The old finaliser implementation used the object hashmap to keep
track of finalisers that needed to be run. This was not ideal
because while the hashmap provides constant time operations,
the constant time was still much larger than the time for a normal
no finaliser allocation. Additionally, keeping track of finalisers
in the object hashmap meant that …
> More efficient object finalising implementation

- .travis.yml
Before this change, when releasing to bintray, we would run
`make deploy arch=x86-64 ... deploy`
with the intent of building a pony compiler and runtime that targets
the x68-64 instruction set. Unfortunately that isn't what would happen.
Because we had previously run
`make test-ci`
Which doesnt specify an architecture and therefore uses features
available on the build machine, we were in fact uploading an arch
specific build- the one created by `make test-ci`.
With this change, we will remove all `make test-ci` related items and
then rebuild for release with the correct make settings.
Fixes #1696
> Build Linux release binaries correctly

- release.sh
This will work for Travis. I need to see if Appveyor supports
something similar. You can read more about this at:
https://docs.travis-ci.com/user/customizing-the-build#Skipping-a-build
[skip ci]
> Skip ci for release commands that don't touch CI-able files

- src/libponyc/pass/flatten.c
- src/libponyc/pass/syntax.c
- test/libponyc/badpony.cc
Fixes by moving "in constraint" checks for arrow and tupletype
from the flatten pass to the syntax pass, so that they are guaranteed
to happen before we try to set the cap on the typeparamref.
It's also more appropriate to run them there since they are syntax-level
checks that require no knowledge of name resolution, or anything else
beyond simple syntax frame lookups.
Resolves #1694.
> Fix compiler assert on arrow to typeparam in constraint.

- .travis.yml
- Dockerfile
- Makefile
This PR closes #1695 by adding Makefile support for `-mtune` and updates the .travis.yml and Dockerfile files to include `tune=intel`.
> Improve packaged Linux binary performance

- Makefile
This has been built with some extra credential changes (https://github.com/killerswan/ponyc/compare/deps_upstream_only...deps) so it could be deployed to my own Bintray repo for some experiments, as described in #1208.
This will be safe to merge *after* https://github.com/killerswan/ponydep-ncurses is moved to ponylang and getting deployed OK to Bintray.
> Add an RPM dependency on ponydep-ncurses

- packages/collections/persistent/_test.pony
- packages/collections/persistent/map.pony
The tests for the collections/persistent package are also cleaned up a bit to be consistent with other packages.
Closes #1692
> Improved persistent map api (RFC 36)

- src/libponyc/codegen/genjit.c
This PR fixes the compile error under 32-bit systems, as described in issue #1693.
> Fix compiling errors for 32-bit

- .appveyor.yml
If the only file changed is `.travis.yml`, there's no point in
doing an Appveyor run.
See:
https://www.appveyor.com/docs/how-to/filtering-commits/#commit-files-github-and-bitbucket-only
for more information
> Don't run appveyor CI for TravisCI only change

- CHANGELOG.md
- src/libponyrt/pony.h
- src/libponyrt/sched/scheduler.c
Previously, the thread initialising the runtime would use the runtime context of one of the scheduler threads. Now that the pony_unregister_thread function exists and is freeing the runtime context of the schedulers when the runtime exits, the initialising thread must have its own context.
This should fix the segfault encountered by #1629.
> Register the thread calling pony_init

- Makefile
- src/libponyc/codegen/genfun.c
- src/libponyc/reach/reach.c
- test/libponyc/codegen_final.cc
This fixes a case overlooked in 087ebc7. In that commit, the finaliser of an embedded field was only called if the parent object (or actor) had an explicit finaliser. This change adds implicit finalisers to objects that must finalise an embedded field, including recursively.
PS: If this gets merged before the pending release this shouldn't get a changelog entry since it is covered by the one from #1586.
> Call finalisers for embedded fields when parent type has no finalizer.

- .appveyor.yml
- .bintray.sh
- .travis.yml
- Makefile
- README.md
Simplifies a bunch of finicky little things.
Note, this would also require renaming (if possible) or creating new packages on Bintray with the name "ponyc" instead of "ponyc-release".  😅 
As noted on #1713.
> Rename packages from "ponyc-release" to "ponyc"

- .travis.yml
We noticed an error in builds like [this one](https://travis-ci.org/ponylang/ponyc/builds/212313591):
```
gcc -MMD -MP -march=x86-64 -mtune=intel -Werror -Wconversion -Wno-sign-conversion -Wextra -Wall -mcx16 -O3 -DNDEBUG -std=gnu11 -fexceptions -DPONY_VERSION=\"0.11.3-853c3e7\" -DLLVM_VERSION=\"3.9.1\" -DPONY_COMPILER=\"gcc\" -DPONY_ARCH=\"x86-64\" -DBUILD_COMPILER=\""gcc (Ubuntu 4.8.4-2ubuntu1~14.04.3) 4.8.4"\" -DPONY_BUILD_CONFIG=\"release\" -D_FILE_OFFSET_BITS=64  -DPONY_NO_ASSERT -c -o build/release/obj/libponyrt/platform/threads.o src/libponyrt/platform/threads.c  -I src/common/ -I src/libponyrt/
src/libponyrt/platform/threads.c:1:0: error: bad value (intel) for -mtune= switch
#ifdef __linux__
^
make: *** [build/release/obj/libponyrt/platform/threads.o] Error 1
```
And @sylvanc …
> Build with a newer GCC on Travis

- CONTRIBUTING.md
From time-to-time we have folks wanting to contribute who have never
contributed via GitHub before. The process can be very daunting. This
commit adds a basic overview of the process to our CONTRIBUTING doc.
Additionally, it links to more detailed instructions on GitHub's site as
well as giving information on how the potential contributor can reach
out to the Pony community for help contributing.
[skip ci]
> Add "getting started with GitHub" info to CONTRIBUTING

- src/libponyc/type/reify.c
- test/libponyc/traits.cc
Previously, a trait that had a method body that used a typearg as
a class to call a constructor on would fail when the method body
was inherited, as the TK_REFERENCE wasn't reified. Now the
TK_REFERENCE is reified as a TK_TYPEREF.
> Reify type refs in inherited method bodies

- src/libponyrt/mem/alloc.c
- src/libponyrt/mem/pool.c
We currently commit all memory allocated from VirtualAlloc immediately. Allocating huge blocks at once can make memory exhaustion more probable.
> Allocate less memory from VirtualAlloc on Windows

- .bintray.bash
- .travis.yml
- Makefile
Note that this won't run on a master build, just release.
Conveniently: #1738 is coming...
@SeanTAllen Have I fat-fingered anything here?
> Rename the bintray descriptor script, ShellCheck it, and note it makes JSON not YAML [skip ci]

- .travis_script.bash
- CHANGELOG.md
The Dockerfile still specifies this, but we're seeing Travis builds fail
on this setting (see #1738) and will revisit this soon.
@SeanTAllen I'm going to merge this, then merge it over to 'release' and shift the tag manually, to avoid cutting 0.11.5, if I can.
> Rollback the addition of 'tune=intel' to ponyc release builds

- .bintray.bash
In the 0.11.4 release effort I've noticed that:
> Travis build has a Travis->Bintray deployment regex problem resulting in a message: `[Bintray Upload] Warning: Path: \/home\/travis\/build\/ponylang\/ponyc\/build\/bin\/ does not exist.` which causes nothing to be deployed (just like I've fixed [elsewhere](https://github.com/ponylang/ponyc/issues/1732#issuecomment-288615392), but which I don't understand how it could be introduced when the pattern in bintray.[ba]sh [hasn't changed](https://github.com/ponylang/ponyc/compare/917610c48c82e5138153bba30c470def5a550601...eaf9a8676f7f584ec5823ff3b512cc9d7fd87695#diff-8611111525017e2f47651e71edc92e9a)),
The biggest change related to this is not the .YML to .JSON rename, but converting the script from .SH to .BASH: …
> Reduce the escaping in Bintray descriptor files

- src/libponyc/codegen/gendesc.c
- src/libponyc/codegen/genident.c
- src/libponyc/reach/reach.c
- src/libponyc/reach/reach.h
- Don't assign type IDs to structs
- Use a distinct numbering for traits and concrete types
The main goal of this change is to reduce the size of the type descriptor table used for serialisation: type IDs for serialisable types are less sparse, which results in less "holes" in the table.
> Optimise type IDs assignment

- CHANGELOG.md
- release.sh
This PR removes a bad sed command introduced in c249faf that has been
destroying our changelog since release 0.11.1. The changelog is also
restored by piecing together versions from commits just prior to each
release after 0.11.0.
Resolves #1745
> Repair changelog and fix release script

- src/libponyrt/gc/gc.c
This makes the same change to `send_remote_object` that was previously
made to `mark_remote_object`.
> Trace when "freezing on send"

- src/libponyc/ast/ast.c
- test/libponyc/badpony.cc
This PR fixes #1751, a compiler assertion error related to the efficient storage system for AST annotations and types, introduced in #1649.
This PR also changes the system somewhat, to rely on the token type that annotations use (`TK_BACKSLASH`), instead of using the `AST_ANNOTATED` flag.
> Fix annotation-related compiler assertion failure (issue #1751)

- src/libponyc/codegen/codegen.c
- src/libponyc/codegen/codegen.h
- src/libponyc/codegen/gendesc.c
- src/libponyc/codegen/genreference.c
`unnamed_addr` means that identical constants can be merged. This change reduces the size of optimised binaries by avoiding duplicated constants. Constants with meaningful addresses (e.g. type descriptors) still aren't marked as `unnamed_addr`.
As a side-effect of this change, different instances of the same string literal now have the same identity. `gen_string` now caches generated strings in order to have a consistent behaviour on string literal
identity between debug and release builds, since `unnamed_addr` constants aren't merged in non-optimised builds.
> Mark generated constants as unnamed_addr when appropriate

- packages/term/ansi_term.pony
Bugfix: SIGWINCH does not exist on Windows, so the ANSITerm library
failed to compile.  
Addresses #1764
> Ifdef out ANSITerm signal handler for SIGWINCH

- Makefile
Previously, we used llvm-ar-3.8 if it was available. This doesn't work
with XCode 8.3, which will issue a link error. Instead, we now pick up
the llvm-ar from the `llvm-config --bindir` directory if it is
available, and otherwise fall back.
As part of this change, the homebrew location for llvm@3.9's llvm-config
is tried if no LLVM_CONFIG is specified.
> Support XCode 8.3 and LLVM 3.9

- .appveyor.yml
There's no reason to run an Appveyor CI run for any of
these files changing.
Note according to Appveyor folks
`**/*.md` should match ANY .md files. We should verify that
turns out to be true. I'll keep an eye out for that. Same for
`**/*.txt`
Resolves #1707
> Add additional files to Appveyor skip list

- src/libponyrt/lang/stdfd.c
As a left-over from when Pony strings where null terminated,
pony_os_std_print wasn't checking the length of the passed in
buffer and would print the entire buffer and beyond until it
hit a null terminator.
This PR fixes that issue so that we will now correctly only
print `len` elements from the buffer.
> Don't ignore buffer length when printing

- CHANGELOG.md
- packages/ponytest/pony_test.pony
Adds --exclude command line option that can be used to
exclude any tests whose name starts with the given prefix.
Renames existing --filter command line option to --only to provide
better symmetry with --exclude.
> Allow Ponytest to exclude or include tests by name

- .travis.yml
Our scripts expect FAVORITE_CONFIG to be defined for
each env. Otherwise they error out rather than exiting with
a "green" 0 return code.
> Prevent Travis jobs from failing during release builds

- .travis_script.bash
the make deploy step ends up removing all created ponyc binaries,
this means if make docs comes after that, it will fail.
this commit makes each of the steps explicitly handle dependencies.
in the case of "deploy" this means running `make clean` first to
verify a clean working environment before building for deploy.
in the case of "make docs" this means building a ponyc installation
to use for creating docs from.
> Fix Linux release scripts

- packages/ponytest/pony_test.pony
A recent change to `pony_test` (51c11a3c80974847fa49931907ea76f5ef34419f) compares test names to an `_exclude` field using `name.at(_exclude, 0)`.  On Windows at least, `String.at("", 0)` always returns `true` (which is maybe a bug?), so all tests get excluded.
This PR only excludes tests if the `_exclude` field (and its related field `_only`) are non-empty.
> Fix tests being excluded or skipped unnecessarily.

- packages/ponytest/pony_test.pony
Wasn't recognized because string size was wrong.
Manually tested from what I am sure is the correct directory this time. I have no idea what I did to mess this up so it didnt work when testing the first time but I thought I did.
> Fix broken ponytest "only" filter

- .gitignore
- benchmark/libponyrt/mem/pool.cc
- lib/gbenchmark/src/commandlineflags.cc
- wscript
This PR makes the Windows build system build the `libponyc.benchmarks` and `libponyrt.benchmarks` executables.
The ignored files are Visual Studio profiler outputs.
Microsoft C++ doesn't have variable-length arrays, so I replaced a few instances of these with calls to `alloca()`.
> Build libponyc and libponyrt benchmarks on Windows

- examples/httpget/httpget.pony
- packages/net/http/_client_connection.pony
- packages/net/http/_server_connection.pony
- packages/net/http/http_notify.pony
This fixes a problem reported on the user mailing list, wherein the examples/htttpget program hangs at the end rather than exiting.
> Add dispose method to HTTPSession actors

- src/libponyrt/sched/cpu.c
This PR fixes #1625 (50% CPU usage for a simple timer demo) for Windows.
Inspired by the [ancient wisdom of Joe Duffy](http://joeduffyblog.com/2006/08/22/priorityinduced-starvation-why-sleep1-is-better-than-sleep0-and-the-windows-balance-set-manager/), we now yield a Pony scheduler thread by calling `Sleep(1)` instead of `Sleep(0)`.  This results in a sleep of anywhere from 1 to 16 milliseconds, depending on the global value of the system timer.
The example in #1625 now runs with minimal CPU usage on my system.  Comparing `libponyrt.benchmarks` before and after the change doesn't seem to show a significant difference.
> Fix extreme CPU use in scheduler on Windows

- README.md
- src/common/vcvars.h
- src/libponyc/codegen/genexe.c
- src/libponyc/codegen/genlib.c
- src/libponyc/platform/vcvars.c
Previously `ponyc` would only look for a linker from the version of Visual Studio with which it was compiled, and only looked at one registry key for install information.  A recent change (44b2d56c5618142fe0fd628eeadbd5975157d62f) broke support for Visual Build Tools C++ 2015.
This change provides registry key and path configuration information for several configurations, regardless of how `ponyc` was compiled for Windows:
- Visual Studio 2017 full install
- Visual C++ Build Tools 2017
- Visual Studio 2015 full install
- Visual C++ Build Tools 2015
The change also removes support for Windows SDKs prior to version 10, as `README.md` now specifies version 10.
> Improve Visual Studio and Microsoft C++ Build Tools detection.

- Makefile
Hi !
I was packaging ponyc for the distribution I use (Exherbo, a source based distribution) when I ran into some troubles. We don't authorize our build system to use un-prefixed build tools (like `cc` or `gcc-ar`). Instead, we use a prefixed tool which makes cross-compilation easier (like `x86_64-pc-linux-gnu-cc`).
For `cc`, you already use `$(CC)` everywhere else so I guessed it was OK to use it here too.
For `AR`, our build tool also defines `AR` environment variable with the prefixed tool as its value (which is `x86_64-pc-linux-gnu-ar` for us). I'm really not sure about that fix, my logic was "don't override the AR environment variable if already defined".
Tell me if there is something wrong in there, in the meantime, I'll continue to explore pony :-)
> Build: use AR if already defined and avoid the direct use of cc

- packages/collections/persistent/_map_node.pony
- packages/collections/persistent/map.pony
This change allows the persistent map to use any given hash function like the mutable hash map. I consider this to be under the principle of least surprise, especially since existing code will not be broken.
> Allow persistent map to use any hash function

- .travis_script.bash
[skip ci]
This is already an exported envvar, and the default in the makefile, too.
> Remove the redundant config=release from 'make deploy'

- release.sh
Before this change, it was possible that if you had local changes on `master` ahead of `origin/master`, those changes would be released.  For example:
```
kevin-ponyc $ git fetch origin
kevin-ponyc $ git ll --oneline -2 master
* 685d1a97 (HEAD -> master) WHOOOEEEE
* e7e5ca7d (origin/master, origin/HEAD) Add unreleased section to CHANGELOG post 0.12.4 release prep
kevin-ponyc $   
kevin-ponyc $ bash release.bash 0.12.5 685d1a97
...
kevin-ponyc $ git ll --oneline -3 master
* 2daf67fa (HEAD -> master, origin/master, origin/HEAD) Add unreleased section to CHANGELOG post 0.12.5 release prep
* b689a862 (release-0.12.5) Prep for 0.12.5 release
* 685d1a97 WHOOOEEEE
```
Now the release script should fail with an error describing the problem.
> Abort releasing if there are local-only changes to master or release

- Makefile
[skip ci]
Tested locally with:
```bash
make deploy && make deploy
```
🦑
> Allow repeat calls to 'deploy' by forcing links and clearing build/bin

- packages/itertools/iter.pony
The original example is misleading in that it may lead one to assume the correct order for the lambda is `(iter_val, acc)` while the code uses `(acc, iter_val)`.
Changing the order in the code may break backwards compatibility for anyone already using this, so I think just fixing the example to use the correct order is a good option in this case.
> Use correct parameter order in Itertools Iter.Fold example

- examples/echo/echo.pony
- examples/net/client.pony
- examples/net/server.pony
- packages/net/_test.pony
- packages/net/http/_client_conn_handler.pony
- packages/net/http/_server_conn_handler.pony
- packages/net/ssl/ssl_connection.pony
- packages/net/tcp_connection.pony
- packages/net/tcp_connection_notify.pony
On non-Windows platforms, TCPConnection will read data off of a socket
until:
- there's no more data to read
- a max size is hit
- `TCPConnectionNotify.received` returns false
The last option was introduced via [RFC
to give the programmer more control of when to yield the scheduler. This
was a noble goal but is weakly implemented. In order to exercise better
control, the programmer needs an additional bit of information: the
number of times during *this scheduler run* that `received` has been
called.
As we began to use RFC #19 at Sendence it became clear that is wasn't
doing what we wanted. What we hoped to be able to do was read up to X
number of messages off the socket, inject them into our application and
then give up the scheduler.
Our initial implementation was to keep a counter of …
> Pass # of times called to TCPConnectionNotify.received

- .travis.yml
- .travis_install.bash
LLVM's Debian/Ubuntu packaging hosted on http://apt.llvm.org is
available through Travis' APT whitelist!
> Build ponyc for Linux with the upstream LLVM 3.9[.1] APT distro

- src/libponyc/type/subtype.c
- test/libponyc/badpony.cc
The compiler currently allows contravariant constraint for type arguments. When
doing so it allows capability subtyping.
In other words, it allows the following, where `X` is a type variable, `λ` a
capability and `DS` is a type name.
```
λ' ≤ λ
----------------------------------------
fun m[X: DS λ]() ≤ fun m[X: DS λ']()
```
This is however unsound, as shown in the example below. Bar's `alias` method is
able to create an `X^` from a `X!`, since `X` is a tag. However, Foo's `alias`
method is callable with an iso argument.
As a result, this can be used to duplicate an iso reference, as shown in `Main`
```pony
trait Foo
fun alias[X: Any iso](x: X!) : X^
class Bar is Foo
fun alias[X: Any tag](x: X!) : X^ => x
class Baz
actor Main
let foo : Foo = Bar
let x : Baz iso = …
```
> Do not allow capability subtyping when checking constraint subtyping.

- CHANGELOG.md
This change makes the Fixed, Added, and Changed sections of each release occur in that order. This is done to simplify parsing the changelog.
> Make changelog easier to parse

- src/libponyrt/gc/gc.c
Prior to this commit, foreign objects were accounted for upon
receive but then their impact on the heap was lost whenever GC
ran. This commit resolves that by making sure that foreign objects
are properly accounted in the heap during the marking phase of GC
in a manner similar to how they're accounted for upon receive.
Resolves #1550
> Properly account for foreign objects in GC

- README.md
If a user's machine does not have `ld.gold`, then compilation with
`ponyc` can fail. This adds a section to the linux installation
instructions explaining what the error means and how to fix it.
I spoke with Sean about this in [#1812](https://github.com/ponylang/ponyc/issues/1812), but I wasn't sure whether to put this in the "Building on Linux" section or "Installing on Linux" section, because `ponyc` will actually build fine if `ld.gold` is not present, it only occurs when trying to use `ponyc` to build pony programs.
> Add ld.gold to linux installation instructions

- README.md
The latest Windows 10 update installs an incomplete version of the latest Windows 10 SDK (https://developercommunity.visualstudio.com/content/problem/41913/link-fatal-error-lnk1104-in-empty-c-project.html), which `ponyc` then tries unsuccessfully to use for linking.
> Add a note to the README regarding how to get the latest Windows 10 SDK.

- README.md
Also:
* use `apt-get`'s `--verbose-versions` flag so people see what's
happening more clearly, and
* provide some hints to get people unstuck faster.
This should close #1825 by documenting what key should be set up.  Although the other two issues I spun out will remain.
> Instruct Debian/Ubuntu users to install Bintray's GPG key

- .travis_install.bash
- .travis_script.bash
- RELEASE_PROCESS.md
- release.bash
This PR uses the new changelog tool to modify the changelog and check that it is valid every time CI is run on travis.
> Add changelog tool to release process and CI

- src/libponyc/codegen/gendesc.c
- src/libponyc/codegen/genexe.c
- src/libponyc/codegen/genjit.c
- src/libponyc/codegen/genjit.h
- src/libponyrt/gc/serialise.c
- test/libponyc/util.cc
When loading symbols from a JITed program in `gen_jit_and_run`, the value stored is now the contents instead of the address. This avoids an incorrect level of indirection.
In order to avoid copying big arrays, the compiler tests now load a pointer to the generated descriptor table instead of the table itself. The `__DescTable*` symbols are now `__PonyDescTable*` symbols to avoid potential name conflicts.
Closes #1843.
No changelog entry since this doesn't affect any existing test.
> Fix JIT symbol load

- pony.g
- src/libponyc/ast/frame.c
- src/libponyc/ast/frame.h
- src/libponyc/ast/lexer.c
- src/libponyc/ast/parser.c
- src/libponyc/ast/token.h
- src/libponyc/codegen/gencontrol.c
- src/libponyc/codegen/gencontrol.h
- src/libponyc/codegen/genexpr.c
- src/libponyc/expr/control.c
- src/libponyc/expr/control.h
- src/libponyc/expr/reference.c
- src/libponyc/pass/expr.c
- src/libponyc/pass/flatten.c
- src/libponyc/pass/names.c
- src/libponyc/pass/pass.c
- src/libponyc/pass/pass.h
- src/libponyc/pass/refer.c
- src/libponyc/pass/scope.c
- src/libponyc/pass/sugar.c
- src/libponyc/pass/syntax.c
- src/libponyc/reach/reach.c
- src/libponyc/type/reify.c
- src/libponyc/type/typeparam.c
- src/libponyc/type/typeparam.h
- test/libponyc/iftype.cc
These new conditions allow programmers to get information on subtyping relationships of type parameters at compile time to conditionally compile code.
Most of the work is done during the scope pass, where the definition assigned to a type parameter reference differs based on whether the reference occurs in the then clause of an iftype condition.
This change implements only a part of RFC 26. Method specialisation is still to be implemented.
> Iftype conditions (RFC 26)

- CHANGELOG.md
- src/libponyc/expr/call.c
- src/libponyc/expr/call.h
- src/libponyc/expr/reference.c
- test/libponyc/badpony.cc
Previously, a function reference used as the operand of `addressof` was only reified in `expr_qualify`. Since this function is only called when there is at least one type argument, a function referenced with no type arguments wouldn't be checked. This change fixes the issue by reifying the function in `expr_addressof` if the function reference wasn't already reified.
> Reify function references used as addressof operands correctly

- release.bash
This will now work as intended with the most recent changes to the changelog tool.
closes #1860 
[skip-ci]
> Add unreleased section after release prep

- .travis_script.bash
[skip ci] because this needs testing on:
* a release branch build, and
* a pull request to the release branch.
According to [Travis docs](https://docs.travis-ci.com/user/environment-variables/#Default-Environment-Variables):
> * `TRAVIS_BRANCH`:
>   * for push builds, or builds not triggered by a pull request, this is the name of the branch.
>   * for builds triggered by a pull request this is the name of the branch targeted by the pull request.
> ...
> * `TRAVIS_PULL_REQUEST`: The pull request number if the current job is a pull request, “false” if it’s not a pull request.
@SeanTAllen this is what I mentioned yesterday! 😅
> Avoid building packages and docs on pull requests to 'release'

- src/libponyc/ast/frame.c
- src/libponyc/pass/syntax.c
- test/libponyc/badpony.cc
This better reflects their use. It allows arrow types and tuples to
appear in these positions. It also denies capability sets from appearing
in these positions. These have an extremely limited use, and are unlikely
to be used by anyone.
As a side effect, the default capability in these positions now
corresponds to the type default, rather than #any.
Also properly deny arrow types from appearing in constraints,
fixing #1809.
-----
I'd like to add some positive tests for arrows and tuples in these positions,
but I'm not sure where they fit.
> Don’t consider type arguments inside a constraint as constraints.

- CHANGELOG.md
- src/libponyc/type/reify.c
- test/libponyc/iftype.cc
Closes #1869.
The changelog entry is included in the PR since the commit message/PR title would be too technical for a changelog entry.
> Reify unconstrained type parameters in iftype conditions correctly

- src/libponyc/expr/match.c
- test/libponyc/badpony.cc
This compiler crash occurs when the user accidentally used the non-`let` format of a case pattern, where the case is trying to instantiate the type and match with `eq` instead of matching on type,, *and* there was an earlier error when type-checking the case pattern expression (for example, too few arguments, as we have here..
```pony
class C
new create(key: String) => None
actor Main
let c: (C | None) = None
match c
| C => None
end
```
This crash was originally encountered by @funkybob in #1878, but it was found to be a completely different bug.
> Compiler error instead of crash for too few args to constructor in case pattern.

- src/libponyc/pass/refer.c
- test/libponyc/badpony.cc
> Compiler error instead of crash for invalid this-dot reference in a trait.

- examples/echo/echo.pony
- examples/net/server.pony
- packages/net/_test.pony
- packages/net/http/_server_conn_handler.pony
- packages/net/tcp_connection.pony
- packages/net/tcp_connection_notify.pony
- packages/net/tcp_listen_notify.pony
- packages/net/tcp_listener.pony
- packages/net/udp_notify.pony
- packages/net/udp_socket.pony
This is second attempt to this PR.
> rfc: require programmer to implement network failure handling

- CHANGELOG.md
- src/libponyrt/ds/hash.c
If you were being facetious, you could describe the Pony runtime as
a  series of hashmaps that are held together by some code. Hash
performance  and correctness can have a great impact on everything
else in the runtime because they are at the basis of most everything
else in the runtime.
This change fixes a number of issues that appears to be garbage
collection bugs but were in fact, problems with invariant violation
in the underlying hash implementation. It should be noted that while
the rest of this comment discuss invariant violations that exist in
our Robin Hood hash implementation, some of the bugs that this closes
predate the Robin Hood implementation. This leads me to believe that
the previous implementation had some subtle problem that could occur
under some rare interleaving of …
> Fix invariant violation in Pony runtime hashes

- CHANGELOG.md
- src/libponyc/codegen/genheader.c
Closes #1881.
I've made a manual changelog entry to better reflect the problem fixed on the user's side.
> Don't emit internal methods to library headers

- src/libponyc/ast/ast.c
- src/libponyc/codegen/genmatch.c
- src/libponyc/expr/match.c
- src/libponyc/pass/refer.c
- src/libponyc/pass/sugar.c
- test/libponyc/codegen.cc
- test/libponyc/sugar.cc
- test/libponyc/sugar_expr.cc
This PR implements [RFC 40](https://github.com/ponylang/rfcs/blob/master/text/0040-exhaustive-match.md).
Construct a union type of all cases in the match that match on type alone,
and if this union is a supertype of the match expression type,
then the match is exhaustive so we don't need to sugar the `else None`.
As a result, users won't have to deal with the type system possibility of a `None`
result for match blocks which can easily be shown to never reach the `else` case.
Closes #1772.
> Exhaustive match (RFC 40)

- src/ponyc/main.c
Having commands for outputting help text from the compiler
enables using help2man to generate a man page.
> Add command line options for printing help (-h, --help)

- packages/collections/persistent/map.pony
This PR removes some references to outdated methods in the docstring for `persistent.Map`.
> Fix outdated methods in persistent.Map docstring.

- src/ponyc/main.c
A side effect of #1899 was that the usage string literal became too long for ISO C99. See https://github.com/ponylang/ponyc/pull/1899#issuecomment-300801255
This PR fixes that issue by breaking up the string into multiple string literals, joined by `printf`.
No changelog entry is necesary since this fixes a build issue on master, which has not been released yet.
> Fix usage string not complying with -Woverlength-strings.

- src/libponyc/expr/match.c
- src/libponyc/pass/refer.c
- test/libponyc/badpony.cc
- test/libponyc/sugar_expr.cc
Theoretically, it would be possible to detect and take advantage of
exhaustive match when all exhaustive cases jump away, and treat the
entire match block as jumping away. Unfortunately there is a circular
dependency between the code that determines which expressions jump away
and the code that detects an exhaustive match.
For now, we simply disable exhaustive match detection in such cases.
In practice, you should still be able to do what you're trying to do -
if you move the "jump away" code to outside the match block, then
exhaustive match can be detected on the match block.
Resolves #1898.
No changelog entry needed, since this fixes a bug in code that hasn't been in a release yet.
> Disallow exhaustive match when all cases jump away.

- packages/net/tcp_connection.pony
It's possible under rare circumstances to call `throttled` and
`unthrottled` on a `TCPConnectionNotify` at the incorrect time. This
happens because we were not explicitly tracking whether our connection
was throttled or not.
If you were to be running without one shot enabled (unlikely now), this
code would spuriously call `unthrottled`. With this change, we no longer
have to worry that some other change might inadvertently start calling
`throttled` or `unthrottled` incorrectly.
> Don't call TCPConnection backpressure notifies incorrectly

- pony.g
- src/libponyc/ast/lexer.c
- src/libponyc/ast/parser.c
- src/libponyc/ast/token.h
- test/libponyc/iftype.cc
This PR changes one of the keywords used in the new `iftype` syntax introduced in #1855.
Specifically, it changes the use of `elseiftype` to `elseif`. This is more consistent with `ifdef`, which uses `elseif` and not `elseifdef`.
The detail of what keyword to use for this wasn't included in [the RFC](https://github.com/ponylang/rfcs/blob/master/text/0026-subtype-checking.md), and I doubt very many people are using this feature yet given that the plan was to not formally announce it until the rest of the RFC was complete, so it seems like fair game to change.
Also, there were no tests using `elseiftype`, so I added a test using `elseif`.
> Change iftype to use elseif instead of elseiftype as next keyword.

- src/libponyrt/mem/heap.c
Previously, the finaliser bitmap was being checked against the slot
bitmap, and if the slot had not been freed, the loop continued. This
resulted in an infinite loop for a small chunk with allocations that
were both still in use and had finalisers. This change ANDs the
finaliser bitmap with the slot bitmap before running finalisers,
fixing this problem.
> Fix a bug in finaliser handling

- packages/random/mt.pony
- packages/random/random.pony
- packages/random/xoroshiro.pony
- packages/random/xorshift.pony
This adds both xoroshiro128+ and xorshift128+ implementations.
The XorOshiro128Plus type should be used as the default
non-cryptographic PRNG. To make this simpler, a new Rand type
that aliases the preferred PRNG has been added, so that if a
new PRNG becomes preferred, the type alias can be changed.
> xoroshiro128+ implementation

- src/libponyc/codegen/genopt.cc
"Move hep allocations to the stack" optimization pass depends on `DominatorTreeWrapperPass`, which wasn't initialized.
> Resolved compiler segfault on optimization pass (issue #1225)

- packages/collections/persistent/_map_node.pony
- packages/collections/persistent/benchmarks/main.pony
- packages/collections/persistent/map.pony
This PR simplifies some of the _MapNode code with the recent addition of exhaustive match expressions. The benchmarks for persistent map is also updated so that it compiles.
> Update persistent map benchmarks

- src/libponyc/codegen/genprim.c
This doesn't fix any correctness issues, only consistency issues.
> Use the correct name for Array/String deserialise functions

- src/libponyc/codegen/gencontrol.c
- src/libponyc/codegen/genident.c
- src/libponyc/codegen/genmatch.c
- src/libponyc/codegen/genprim.c
- src/libponyc/codegen/gentrace.c
This commit changes the ordering of basic blocks in generated LLVM IR to better reflect the high level control structures of Pony. This makes the resulting IR much more easier to understand.
This commit doesn't contain any functional changes.
> Order basic blocks in LLVM IR in a logical way

- src/libponyc/expr/call.c
Improves compiler error messages for too many / not enough arguments cases.
Resolves issue #1676
> Improve compiler error messages for wrong argument count cases.

- src/libponyc/type/subtype.c
- test/libponyc/dontcare.cc
> Fix compiler crash on "_" as argument in a case expression.

- src/libponyc/codegen/genopt.cc
This crash occurred when the LLVM passes decided to optimise out the declaration of a runtime function needed by the MergeRealloc pass.
This change fixes the bug by redeclaring the functions when MergeRealloc needs them and can't find them.
PS: No changelog entry since we don't support LLVM 4 officially yet.
> Fix crash in MergeRealloc on LLVM 4

- src/libponyc/codegen/genident.c
- src/libponyc/codegen/genreference.c
- src/libponyc/reach/reach.c
- src/libponyc/reach/reach.h
- src/libponyc/reach/subtype.c
- src/libponyc/reach/subtype.h
This change is an optimisation allowing the compiler to generate the `__is` and `__digestof` methods for a type only when needed. This saves a vtable slot for each method which isn't generated.
> Only generate internal methods when needed

- packages/format/_format_int.pony
- packages/format/_test.pony
- packages/format/format.pony
Fixes formatting of I32.min_value().
TODO: the u32 and u64 funs in `_format_int.pony` could probably be largely re-unified.
Fixes: #1920
> Customize format for I32/U32 (issue #1920)

- src/libponyc/pass/refer.c
- test/libponyc/badpony.cc
This PR fixes a compiler crash on non-existent field reference in constructor.
Resolves #1932.
> Fix compiler crash on non-existent field reference in constructor.

- packages/builtin/signed.pony
- packages/builtin/unsigned.pony
- packages/serialise/_test.pony
This is meant to prevent confusion/surprise with respect to other primitives
whose value can be compared using `is ${PrimitiveName}`. Machine words
are special primitives that can have multiple values, and comparing
with `is ${MachineWord}` is currently equivalent to comparing to zero.
Incidentally, fixing this also alerts us to the bug in #1920.
We should hold off on merging this PR until after #1927 is merged.
> Change machine word constructors to have no default argument.

- src/libponyc/expr/reference.c
- test/libponyc/badpony.cc
This PR fixes a compiler crash when a field is used in a default argument.
This was broken as a side effect the placement of a check
introduced in #1858, and was fixed by just changing the order
of the checks so that we don't expect to be in a method body frame
if we are in a default argument frame.
> Fix compiler crash when a field is used in a default argument.

- packages/serialise/_test.pony
- src/libponyc/codegen/codegen.c
- src/libponyc/codegen/codegen.h
- src/libponyc/codegen/gendesc.c
- src/libponyc/codegen/genfun.c
- src/libponyc/codegen/genserialise.c
- src/libponyc/pass/pass.c
- src/libponyc/pass/serialisers.c
- src/libponyc/pass/serialisers.h
- src/libponyc/reach/reach.c
- src/libponyc/reach/reach.h
- src/libponyc/verify/fun.c
- src/libponyrt/gc/cycle.c
- src/libponyrt/gc/serialise.c
- src/libponyrt/pony.h
- test/libponyc/codegen.cc
This commit adds support for custom serialisation. Custom
serialisation lets the user provide methods that are called by Pony's
serialisation and deserialisation system in order to add additional
information that otherwise would not be serialized. The primary goal
of this system is to provide a means of serialising data stored in
`Pointer` member variables.
> Add support for custom serialisation (RFC 21)

- packages/serialise/serialise.pony
- src/libponyrt/gc/serialise.c
- src/libponyrt/gc/serialise.h
- src/libponyrt/sched/scheduler.h
This change allows custom allocation and exception raising strategies to be used in the serialisation API.
This is preliminary work for AST and reachability map serialisation (which is itself preliminary work for separate compilation). Serialising these data structures requires custom allocations (since compiler objects can't be allocated with `pony_alloc`) and custom exception raising (since C code can't catch Pony exceptions).
> Parameterise allocations and exceptions in serialisation

- .travis.yml
- .travis_install.bash
as it will link ponyc against libllvm3.9 which is not available on most vanilla ubuntu distributions
and must be installed via http://apt.llvm.org/
Using the prebuilt binaries links llvm libs statically into the ponyc binary so we end up with a package
without (implicit) dependency on libllvm3.9
resolves #1833
---
i was not able to test the actual packaging process.
> Don't use llvm toolchain from apt.llvm.org for LLVM 3.9.1

- STYLE_GUIDE.md
I think that it could otherwise be misleading and confusing as the style
guide previously had "not ok" formatting.
> Indent "blank lines" STYLE GUIDE examples

- src/libponyc/pass/verify.c
- test/libponyc/verify.cc
TK_IFTYPE handling was not added to the verify pass, which leads to
errors in iftype blocks to not be propagated.
This commit makes inheriting of flags the default, so it is not forgotten
when adding more features.
Fixes #1954
> Inherit AST flags by default.

- src/libponyrt/gc/serialise.c
This function is only used in `serialise.c`.
> Define the custom_deserialise function as static

- src/libponyc/codegen/codegen.h
- src/libponyc/codegen/gendesc.c
- src/libponyc/codegen/genname.c
- src/libponyc/codegen/genname.h
- src/libponyc/codegen/gentype.c
- src/libponyc/reach/paint.c
- src/libponyrt/gc/cycle.c
- src/libponyrt/pony.h
The previous algorithm for subtyping tests (used e.g. in pattern matching) used an array of provided types in each type descriptor. The array was iterated looking for the tested type, resulting in O(n) complexity.
The algorithm implemented in this commit uses a bitmap of provided types. A type provides a trait if the bit for that trait (determined using the trait ID) is set. This results in O(1) complexity, with no branching and a shorter code sequence.
The space complexity is now O(n) on the total number of traits instead of the number of provided traits.
> Use a constant-time algorithm for trait subtyping tests

- packages/ponytest/_test_runner.pony
Currently it is possible to call `long_test` more than once for a given
test. This results in more than 1 timer being registered, however, we
only keep track of 1 of timers registered so when the test is completed,
all timers are not cancelled and tests will continue "to run" until the
timer finishes.
This PR prevents duplicate long tests from being registered by only
setting up a long test if one hasn't already been registered. If one is
already registered, we skip the normal setup procedure and log a
warning.
> Prevent duplicate long_tests from being registered

- src/libponyc/ast/ast.c
- src/libponyc/ast/ast.h
- src/libponyc/reach/reach.c
This change fixes an issue in the reachability map where a previously freed AST was still being referenced by other ASTs.
This wasn't causing any problem in the current version of the compiler, but resulted in an use-after-free bug in the upcoming AST serialisation work.
> Fix reference-after-free in reachability map

- packages/collections/persistent/_vec_node.pony
- packages/collections/persistent/vec.pony
This PR fixes a bug in the persistent Vec where values are duplicated when `pop` is called and the tail is empty.
> Fix value duplication bug in persistent Vec

- src/libponyc/pass/syntax.c
- src/libponyc/verify/fun.c
- test/libponyc/badpony.cc
This PR adds a compile error for a Main actor with type parameters.
closes #1936
> Add compile error for generic Main

- packages/collections/persistent/_map_node.pony
This bug was due to an incorrect assumption in the update algorithm for the persistent HashMap.
> Fix bug in persistent HashMap where size may be inaccurate on update

- CHANGELOG.md
- packages/time/nanos.pony
- packages/time/time.pony
- packages/time/timer.pony
Based on its description and name, one would be reasonable in expecting
`Time.wall_to_nanos` to take a wall clock time and convert it the number
of nanoseconds since the "start of time". That isn't however what it
does. It was getting an absolute time to fire a timer setup in
Timer.abs.
This PR correct this problem by moving the functionality that previously
existed in `wall_to_nanos` into Timer as a private method and adds a
function to `Nanos` to convert from a wall clock time to nanoseconds.
> Remove and replace misleading Time.wall_to_nanos

- examples/commandline/main.pony
- examples/gups_basic/main.pony
- examples/gups_opt/main.pony
- examples/httpget/httpget.pony
- examples/main.pony
- examples/mandelbrot/mandelbrot.pony
- examples/printargs/printargs.pony
- examples/yield/main.pony
- packages/cli/_test.pony
- packages/cli/command.pony
- packages/cli/command_help.pony
- packages/cli/command_parser.pony
- packages/cli/command_spec.pony
- packages/cli/env_vars.pony
Implementation of https://github.com/ponylang/rfcs/blob/master/text/0038-cli-format.md.
All rules and syntaxes are supported, and a help command and option are supported.
One small example is included, but the tests are pretty thorough as far as specs and command line combinations go.
I still need to deprecate the options package (I'm not sure how to do that). And update existing examples and the tutorial.
As a follow up, I also want to add support for list types, (lists of String, etc.), and a 'no' prefix to negate bool options.
I'm open to suggestions, especially regarding Pony usage, and how the value types are handled.
> Initial CLI package implementation w/ tests and updated examples

- src/libponyc/reach/reach.c
- test/libponyc/codegen_identity.cc
This fixes a bug introduced in 9b9c084 caused by the `__is` method of a tuple nested in another tuple not being reached.
This should only get a changelog entry if we do a new release before merging this, since the bug exists only in the unreleased version.
> Fix assertion failure on nested tuple identity

- src/libponyc/type/subtype.c
- test/libponyc/type_check_subtype.cc
After this commit, a tuple is considered a subtype of `Any ${cap}`
if all of the elements of the tuple are subcaps of the cap.
This is a principle of least surprise issue, as it is surprising
that a type param constraint of `Any #any` does not behave the same
as an unconstrained type param, with the latter accepting tuple
type args, and the latter not doing so.
Previously, there was no way to allow tuples of any cardinality
as a type argument, while restricting what caps were allowed to
be in those tuples (such as for the concerns of aliasing or
sendability). For example, `class List[A]` in the `collections`
package allowed tuples as type args, but `class List[A: Any #share]`
in the `collections/persistent` package did not. Now they both
allow tuple type args, and the `Any #share` …
> Make tuples be subtypes of empty interfaces (like Any).

- packages/collections/persistent/_map_node.pony
- packages/collections/persistent/_vec_node.pony
- packages/collections/persistent/vec.pony
This PR removes unnecessary allocation of full nodes (size 32). These allocations have no benefit since the nodes are copied when modified.
> Remove unnecessary allocation of full nodes in persistent collections

- packages/builtin/string.pony
- packages/builtin_test/_test.pony
String.trim_in_place wasn't written to work correctly if you were
to trim the string down to nothing and then append a size less than the
"alloc" value that is left. This combination could result in incorrect
handling for strings that end up with a size of 0.
This is because, a new pointer was created, but we retained incorrect
alloc info. This wouldn't cause an error so long as when you used the
string for something like an append, reserve allocated new memory.
However, if the appended value was less than the perceived alloc size,
no additional memory would be added and kaboom.
Closes #1996
> Fix segfault in String.trim_in_place

- packages/builtin/array.pony
- packages/builtin_test/_test.pony
This is the mirror update to Array.trim_in_place that was made
previously in String. Relevant commit comment from String:
Array.trim_in_place wasn't written to work correctly if you were
to trim the array down to nothing and then append a size less than the
"alloc" value that is left. This combination could result in incorrect
handling for arrays that end up with a size of 0.
This is because, a new pointer was created, but we retained incorrect
alloc info. This wouldn't cause an error so long as when you used the
array for something like an append, reserve allocated new memory.
However, if the appended value was less than the perceived alloc size,
no additional memory would be added and kaboom.
see 381b2816c6581dd2441f879d81ed9890ca181f4e
> Fix segfault in Array.trim_in_place

- src/libponyc/ast/frame.c
- src/libponyc/ast/lexer.c
- src/libponyc/ast/parser.c
- src/libponyc/ast/token.h
- src/libponyc/codegen/gencontrol.c
- src/libponyc/codegen/genexpr.c
- src/libponyc/expr/control.c
- src/libponyc/pass/expr.c
- src/libponyc/pass/refer.c
- src/libponyc/pass/scope.c
- src/libponyc/pass/sugar.c
- src/libponyc/reach/reach.c
- src/libponyc/type/reify.c
- test/libponyc/iftype.cc
By defining the shadowing TK_TYPEPARAM on the entire iftype clause, which
contains both the constraint and the body, the appropriate definition
of the type variable is used when it appears in the constraint.
Fixes #1960
---
Iftype is implemented by creating a new definition of the typeparameter with a constraint which combines both the original constraint and the RHS of the iftype. This TK_TYPEPARAM shadows the original definition inside the iftype body.
The third commit moves the shadowing constraint from the body to the entire iftype, so it gets picked up by the constraint as well. This allows recursive constraints such as the examples in #1960.
However we don't want it to get used by the else clause of the iftype. The second commit creates a new AST node, TK_IFTYPE_CLAUSE, containing …
> Fix support for recursive constraints in iftype conditions.

- src/libponyc/ast/ast.c
- src/libponyc/ast/ast.h
This was intended to be used for a fix, but wasn't used at all in the end.
> Remove the unattached_asts data structure

- src/libponyc/ast/lexer.c
- src/libponyc/codegen/gencall.c
- src/libponyrt/mem/pool.c
- src/libponyrt/mem/pool.h
This function has the same functionality as C's realloc but for the pool allocator.
Manual pool reallocation patterns in the compiler have been updated to use the new function.
> Add the ponyint_pool_realloc_size function

- src/libponyrt/mem/pool.c
- src/libponyrt/sched/mpmcq.c
The duplicate brackets due to ifdefs were rendering badly in some text editors.
> Enhance brackets in CAS loops

- packages/net/tcp_listener.pony
It fell behind the actual working code. It would be nice if we could
figure out a way to be able to extract and compile examples from
documentation during CI so we could catch these things.
> Update TCPListener example code to one that compiles.

- pony.g
- src/libponyc/ast/lexer.c
- src/libponyc/ast/parser.c
- src/libponyc/pass/syntax.c
- test/libponyc/lambda.cc
In version 0.9, the concise lambda syntax from RFC 24 was implemented, removing the `lambda ... end` syntax from the language. This syntax was kept in the compiler to help report a helpful compiler error to aid users in the transition.
Version 0.9 happened a while ago and users had time to adapt. Removing the syntax altogether (treating old lambdas as plain parsing errors) cleans up the compiler and doesn't have ill effects at that point.
> Remove the old lambda syntax from the compiler

- src/libponyc/codegen/codegen.c
- src/libponyc/codegen/gencall.c
- src/libponyc/codegen/genjit.c
- src/libponyc/codegen/genopt.cc
- test/libponyc/codegen_optimisation.cc
This optimisation pass uses the `pony_send_next` runtime function to group tracing of message contents for messages sent in the same basic block. This can reduce the amount of GC INC messages sent if successive messages send objects allocated by the same actor.
In equivalent C code, the following transformation is performed:
```c
void* ctx = pony_ctx();
void* msg_a = pony_alloc_msg(...);
pony_gc_send(ctx);
// Trace contents of message A
pony_send_done(ctx);
pony_sendv(ctx, actor_1, msg_a);
void* msg_b = pony_alloc_msg(...);
pony_gc_send(ctx);
// Trace contents of message B
pony_send_done(ctx);
pony_sendv(ctx, actor_2, msg_b);
```
|
v
```c
void* ctx = pony_ctx();
void* msg_a = pony_alloc_msg(...);
void* msg_b = pony_alloc_msg(...);
pony_gc_send(ctx);
// Trace contents of message A …
```
> Add the MergeMessageTrace optimisation pass

- src/libponyc/codegen/genident.c
- src/libponyc/reach/reach.c
- src/libponyc/reach/reach.h
- src/libponyc/reach/subtype.c
- test/libponyc/codegen_identity.cc
Previously, boxed tuples with different type identifiers wouldn't be considered as having the same identity even when containing the same objects, for example when comparing `(U32(0), U32(0))` through `(U32, U32)` and `(Any, Any)` tuples.
The new identity algorithm for boxed values follows. "unchanged" means that this step of the algorithm didn't need any changes.
- Check if the addresses are the same (unchanged)
- If they are, the identities are the same (unchanged)
- Otherwise, check the kind of the LHS object
- If it's an unboxed type, the identities are different (unchanged)
- If it's a boxed number, check the type of the RHS object
- If the types are the same, check the values via `memcmp` (unchanged)
- Otherwise, the identities are different
- If it's a boxed tuple, check the kind …
> Fix boxed tuple identity when type identifiers differ

- CONTRIBUTING.md
- Makefile
- wscript
cc @ponylang/committer When merging a pull request that contain changes to the grammar (i.e. a change to the grammar rules in `parser.c` or to token symbols in `lexer.c`), we should ensure that it also contains an update of the pony.g file.
> Test for grammar changes in CI

- src/libponyc/expr/operator.c
- test/libponyc/badpony.cc
> Fix: compiler crash when using the `as` operator with an uninferrable reference.

- src/libponyc/codegen/gencall.c
- src/libponyc/expr/ffi.c
- test/libponyc/badpony.cc
Passing complex objects by value in C is hard: there are many different calling conventions depending on the platform. For example, a C compiler is allowed to split the members of an object into different parameters, or to change the return value into an out parameter.
The Pony compiler currently uses a naive implementation to pass objects to FFI functions and isn't able to use the correct calling convention for every call. Ideally, we'd want to rely on a C compiler API (like LibClang) to generate the correct signatures and calls.
This change is a temporary measure to avoid spurious FFI bugs until we have the interoperability detailed above. LLVM intrinsics are still allowed to return and be passed tuples since their signatures are defined by LLVM.
> Forbid returning and passing tuples to FFI functions

- src/common/pony/detail/atomics.h
- src/libponyrt/pony.h
This was accidentally broken in 8820171.
No changelog entry since the breakage is unreleased.
> Fix build on old compilers

- src/libponyrt/sched/scheduler.c
Not reinitialising the context could result in the runtime referencing an invalid actor if the runtime was stopped and restarted.
> Reset the actor context on runtime initialisation

- src/libponyc/type/subtype.c
> Improve error message where subtype is less ephemeral than supertype.

- src/libponyrt/lang/stdfd.c
I noticed this in StdStream.print("") not writing a newline.
> Make pony_os_std_print() write a newline when given empty input.

- CHANGELOG.md
- README.md
- src/common/pony/detail/atomics.h
- src/libponyrt/mem/pagemap.c
Also deprecate support of Clang 3.3 since it doesn't support the `-mcx16` flag.
Manual changelog entry for Clang 3.3. No changelog entry for the build fix since the breakage is unreleased.
> Correctly fix build on old compilers

- src/libponyc/ast/lexer.c
- test/libponyc/badpony.cc
Trim the leading NL first to simplify subsequent leading whitespace measurement.
Fixes: https://github.com/ponylang/ponyc/issues/2027
From "Low Hanging Fruit"
> Fixed compiler segfault on empty triple quote comment.

- src/libponyrt/actor/actor.c
- src/libponyrt/actor/actor.h
The flags can be accessed concurrently so they have to be atomic. Specifically, a given actor can change any of its GC-related flags while any other actor is sending it a message and reading its UNSCHEDULED flag.
Since there are no actual race conditions on flag accesses, all operations on flags are done with a relaxed memory ordering and no atomic RMW operations are introduced. For these reasons, there is no performance penalty on both x86 and ARM.
> Make actor flag accesses atomic

- src/libponyc/codegen/genbox.c
- src/libponyc/codegen/gencall.c
- src/libponyc/codegen/gencontrol.c
- src/libponyc/codegen/gendesc.c
- src/libponyc/codegen/genexe.c
- src/libponyc/codegen/genfun.c
- src/libponyc/codegen/genfun.h
- src/libponyc/codegen/genident.c
- src/libponyc/codegen/genmatch.c
- src/libponyc/codegen/genprim.c
- src/libponyc/codegen/genreference.c
- src/libponyc/codegen/genserialise.c
- src/libponyc/codegen/genserialise.h
- src/libponyc/codegen/gentrace.c
- src/libponyc/codegen/gentype.c
- src/libponyc/codegen/gentype.h
- src/libponyc/reach/reach.c
- src/libponyc/reach/reach.h
- test/libponyc/codegen.cc
This change adds the `compile_type_t` and `compile_method_t`, which contains the LLVM-specific data for `reach_type_t` and `reach_method_t`, respectively. These new objects are accessed through opaque members on `reach_type_t` and `reach_method_t`.
There are two main goals for this change.
1. Do not depend on LLVM for anything other than codegen. This will make things easier if we ever need to add an alternative backend.
2. Avoid using up unnecessary space for unserialised LLVM data when serialising the reachability map.
I'm putting this up for initial review. It shouldn't be merged yet.
> Split reach types into generic and LLVM-specific ones

- src/libponyrt/gc/cycle.c
The memory for actors that were still alive on runtime termination wasn't being freed, leading to memory leaks.
> Destroy all actors on runtime termination

- src/libponyrt/gc/gc.c
- src/libponyrt/gc/objectmap.c
- src/libponyrt/mem/heap.c
- src/libponyrt/mem/pagemap.c
- src/libponyrt/mem/pagemap.h
- test/libponyrt/mem/pagemap.cc
This change renames many elements in pagemap.c to use more explicit names. In addition, the description of the pagemap has been extended to better explain how the data structure works.
This change also adds a test for `ponyint_pagemap_set_bulk`, as this function wasn't covered yet.
> Refactor pagemap

- src/libponyc/codegen/genopt.cc
- test/libponyc/codegen_optimisation.cc
This change fixes an edge case in MergeTrace that occurred on "cross-messaging", for example:
```pony
x.m(y)
y.m(x)
```
In those cases, IR instructions were reordered such that some instructions were defined after they were being used, resulting in invalid IR.
No changelog entry since the optimisation pass is unreleased.
> Fix invalid IR generation in the MergeTrace pass

- src/libponyrt/gc/cycle.c
A view of the cycle detector can never refer to a NULL actor.
> Replace always false checks with assertions

- src/libponyrt/mem/pool.c
The current pool allocator algorithms can work with pool indices greater than POOL_COUNT. Allowing such indices allows us to remove a conditional in ponyint_pool_index.
> Do not clamp pool indices to POOL_COUNT

- src/libponyc/expr/operator.c
- src/libponyc/pass/syntax.c
- test/libponyc/badpony.cc
Fix #2037, adding a check for `as` on numeric literals to syntax pass.
Also, it shows following message as "info"
To give a numeric literal a specific type, use constructor of primitive
If wording is strange, please let me know.
> Fix: Compiler crash when using `as` on numeric literal

- src/libponyrt/mem/pool.c
This change avoids an unnecessary sign extension with GCC on both x86_64 and ARM64.
> Move an explicit cast in ponyint_pool_index

- Makefile
- src/common/platform.h
- src/common/pony/detail/atomics.h
- src/common/ponyassert.h
- src/libponyc/codegen/genexe.c
- src/libponyrt/asio/asio.c
- src/libponyrt/asio/asio.h
- src/libponyrt/asio/epoll.c
- src/libponyrt/asio/iocp.c
- src/libponyrt/asio/kqueue.c
- src/libponyrt/platform/threads.c
- src/libponyrt/sched/cpu.c
- src/libponyrt/sched/scheduler.c
Changes related to getting pony compiling and running on Alpine
Linux Edge.
* Define `_GNU_SOURCE` so musl glibc compatibility is enabled.
* Makefile changes to detect Alpine Linux and link in `libexecinfo`
* Changes to stop using glibc specific `__GNUC_PREREQ` macro
* Changes to genexe linking to link in `libexecinfo` if on Alpine
or FreeBSD (this is likely also needed but untested)
* Changes to move Linux cpu affinity setting outside of thread
creation function and into same set affinity function as for
other platforms. This also includes enabling asio thread affinity
setting for non-linux platforms.
* Rename `SCHED_BATCH` to `PONY_SCHED_BATCH` to avoid conflict with
musl.
* Set `this_scheduler` thread-local variable to `NULL` on
`ponyint_sched_init` to avoid segfault in running codegen …
> Alpine Linux compatibility for pony

- src/libponyc/codegen/genexe.c
- src/libponyrt/sched/scheduler.c
This change stops an instance of a Pony program from retaining a reference to one of the actors it created. This prevents compiler JIT tests from having a dangling reference to an actor from the previous JIT test.
This also reverts 6f0c33a and a part of 1e1c484 since these changes fixed symptoms of the problem and not the problem itself.
> pony_become() the null actor on program termination

- src/libponyrt/mem/pagemap.c
This was accidentaly broken in 6e9f310.
> Fix valgrind build

- src/libponyc/verify/fun.c
This message displayed as
"the create constructor of the Main actor must take only a single Envparameter"
> Add missing space in error message

- test/libponyc/verify.cc
The space was added in the compiler in #2077, but the corresponding test
was not updated.
> Add missing space in expected error message.

- src/libponyc/codegen/codegen.h
- src/libponyc/codegen/genexpr.c
- test/libponyc/badpony.cc
> Fix compiler assertion failure on unused reference to `_`

- src/libponyrt/mem/pool.c
Previously, the index-based pool free function was always called, which was wrong for oversized pool allocations.
> Fix memory freeing in ponyint_pool_realloc

- wscript
> Make the Windows build not depend on the source being a git repository.

- src/libponyc/codegen/genfun.c
- test/libponyc/badpony.cc
This change fixes an assertion failure that occurred when generating forwarding functions boxing non-ref tuples. The tuple AST without reference capabilities was being used, which could be a non-reachable type, resulting in an assertion failure in `gen_box`.
Closes #2097.
> Fix compiler assertion failure at code generation

- src/libponyrt/mem/pool.c
Based on measurements on Pony programs, calculating a non-zero pool index is much more likely than calculating a  zero pool index. Since compilers will often treat the then part of a condition as more likely, reversing the condition in `ponyint_pool_index` can help with branch prediction when the branch isn't in the branch prediction cache.
> Reverse the condition in ponyint_pool_index

- src/libponyc/reach/reach.c
This change fixes a bug where methods on members of intersection types sometimes weren't being reached.
Closes #2102.
I haven't been able to produce a minimal test case for the bug.
> Fix reachability analysis for intersection types

- Makefile
Prior to this commit freebsd builds weren't properly linking
`libponyrt.tests` due to not being able to find `pthread` related
symbols.
Resolves #2105 (it would be ideal to wait until after @tschuxxi is able to confirm this works for him before merging).
> Fix freebsd build

- packages/builtin/string.pony
The exisiting `copy_cstring` method could be used for either
null-terminated or fixed size strings. The string was considered
null-terminated when the given length was 0, leading to surprising
behaviour when copying a 0 sized string.
Instead the method is split in two, `copy_cstring` for null-terminated
and `copy_cpointer` for fixed size, following the existing naming
convention used by other methods.
> Add copy_cpointer to String class to copy fixed number of bytes.

- Makefile
- README.md
- src/ponyc/main.c
This commit allows folks compiling from source (for packaging or
for their own use) to easily specify that `ponyc` should always
compile programs using Position Independent Code (PIC). The main
driving force behind this is a smoother user experience for folks
on distributions where PIC is enabled by default so they don't
have to always remember to pass `--pic` to `ponyc` when compiling
programs. Alpine Edge is one such example. With this change,
packaging for Alpine Edge is as simple as `make force_pic=true`
and then users of `ponyc` on Alpine Edge don't need to be aware
of PIC being enabled by default at all and don't have to remember
to pass `--pic` to every invocation of `ponyc`.
NOTE: This does not change the default behavior of `ponyc` when
not compiling with `force_pic=true` and it …
> Add ability to default enable PIC when compiling ponyc

- src/libponyc/type/typeparam.c
Can cause compilation errors.
Closes #2118
> Fix implicit fallthrough in break statement

- src/libponyc/pass/docgen.c
- src/libponyc/pass/pass.h
- src/ponyc/main.c
This PR changes the docgen pass (invoked by calling ``ponyc --docs``) to ignore all types that are considered to be test related. That is:
* private types with names starting with ``_Test``
* ``TestList`` and ``UnitTest`` implementations
* whole packages called ``builtin_test`` (static check to filter out stdlib package) or ``test``
A new command-line flag "--docs-public" is introduced to only generate documentation for public types, behaviors, constructors and methods.
This fixes #2092 and #2089
> docgen: ingore test types and only document public types by default

- packages/promises/_test.pony
- packages/promises/promise.pony
This PR expands the promises API. Closes #1691.
> Add more promise methods (RFC 35)

- src/libponyrt/actor/actor.c
- src/libponyrt/actor/actor.h
- src/libponyrt/pony.h
The goal of this check is to avoid uncatched bugs in case the runtime layout of actors ever changes.
The size of the actor pad was reduced to an optimal size. This doesn't fix any correctness issue.
> Add a compile-time check for the actor pad size

- CHANGELOG.md
I am sorry, but my commit message/PR title does not reflect what this PR contained.
This was due to changes that were introduced due to helpful remarks from @SeanTAllen in the process.
i hope this does not break the changelog tool that automatically generates those messages.
> fix changelog message for docgen PR 2112

- src/libponyc/expr/array.c
- test/libponyc/sugar_expr.cc
> Treat `as` type of array literals as the alias of the element type.

- src/libponyc/expr/ffi.c
- test/libponyc/badpony.cc
Running this build of ponyc on the code I posted in this issue https://github.com/ponylang/ponyc/issues/2114 results in a type error instead of a core dump.
```
Error:
/home/charles/code/stars/bindings.pony:13:21: can't take the address of a let local
@glutInit[None](addressof argc, argv)
```
Is `return false` all that's needed?
> Fix compiler crash on typecheck error in FFI call.

- benchmark/libponyrt/ds/hash.cc
- src/libponyc/ast/stringtab.c
- src/libponyc/ast/symtab.c
- src/libponyc/codegen/codegen.c
- src/libponyc/codegen/genreference.c
- src/libponyc/codegen/gentype.c
- src/libponyc/pkg/buildflagset.c
- src/libponyc/reach/paint.c
- src/libponyc/reach/reach.c
- src/libponyrt/ds/hash.c
- src/libponyrt/ds/hash.h
- src/libponyrt/gc/actormap.c
- src/libponyrt/gc/cycle.c
- src/libponyrt/gc/delta.c
- src/libponyrt/gc/objectmap.c
- src/libponyrt/gc/serialise.c
- test/libponyc/compiler_serialisation.cc
- test/libponyrt/ds/hash.cc
This change removes the ability to customise the allocation function used by different instances of runtime hashmaps. The pool allocator is now always used.
In an early version of libponyrt, hashmaps were being used with both `malloc` and the pool allocator. Now, every hashmap instance uses the pool allocator so the parameterisation isn't needed anymore.
Closes #2068.
> Remove the allocation parameterisation of runtime hashmaps

- src/libponyc/ast/lexer.c
- test/libponyc/lexer.cc
> Fix indent detection when lexing docstrings that contain whitespace-only lines.

- src/libponyc/ast/parserapi.c
- src/libponyc/ast/parserapi.h
In PR #2039 (explicit partial calls), one of the changes I made was
to make it so that the cursor, when reporting on an error for a token
that was missing (like the missing '?' for an explicit partial call,
would be placed under the token to the left of where the missing
token should be, instead of under the token to the right (which
was often on the next line).
However, in doing this, I accidentally made it so that many other
(non-missing) tokens were also being reported one token to the left
instead of under the actual token itself. For example:
main.pony:5:5: can't find declaration of 'present'
until present end
^
Which should be displayed as:
main.pony:5:5: can't find declaration of 'present'
until present end
^
This PR fixes the accidental breakage, while retaining the desired …
> Fix cursor location for displaying compiler errors and info.

- Makefile
- src/libponyc/codegen/genexe.c
Our only GCC7 issue appears to that it needs to be linked against
libatomic explicitly. This commit links to libamotic explicitly on any
Linux platform regardless of compiler version.
Closes #1756
> Support GCC7 on Linux

- src/libponyrt/mem/pool.c
This change fixes `ponyint_pool_realloc_size`, which was reading past the end of the old buffer, which in some circumstances triggered a page fault.
> Fix read past the end of a buffer in `pool.c`.

- packages/promises/_test.pony
- packages/promises/promise.pony
Previously, the unit test for `Promise.add` wasn't testing the correct method. This change resolves that problem and modifies `add` rejection so that it behaves as described in the documentation.
> fix promise tests

- src/libponyc/codegen/codegen.c
- src/libponyc/codegen/codegen.h
- src/libponyc/codegen/genbox.c
- src/libponyc/codegen/gencall.c
- src/libponyc/codegen/gencall.h
- src/libponyc/codegen/gencontrol.c
- src/libponyc/codegen/gendesc.c
- src/libponyc/codegen/genexpr.c
- src/libponyc/codegen/genfun.c
- src/libponyc/codegen/genident.c
- src/libponyc/codegen/genmatch.c
- src/libponyc/codegen/genoperator.c
- src/libponyc/codegen/genopt.cc
- src/libponyc/codegen/genopt.h
- src/libponyc/codegen/genprim.c
- src/libponyc/codegen/genreference.c
- src/libponyc/codegen/genserialise.c
- src/libponyc/codegen/gentype.c
- src/libponyc/codegen/gentype.h
This change adds a new distinction in object types in the code generator between a type's memory representation type and value type. For example, Bool previously used LLVM's `i8` and now uses LLVM's `i1` as its value type and either `i8` or `i32` as its memory representation type depending on the platform. This currently is the only type whose value and memory types differ.
The motivation for this change is to improve Pony's compatiblity with the C ABI, which has the same kind of distinctions (for example, Clang uses the same LLVM types as above to express C's boolean type).
> Codegen: Use distinct memory representation types

- README.md
Someone had updated them to match Xenial which isn't correct.
[skip ci]
> Fix Ubuntu Trusty instructions

- packages/builtin/string.pony
- packages/builtin_test/_test.pony
- packages/debug/debug.pony
- packages/ponybench/pony_bench.pony
- packages/ponytest/test_helper.pony
- packages/promises/_test.pony
Implements RFC #48. For full details see
https://github.com/ponylang/rfcs/blob/master/text/0048-change-String-join-to-take-iterable.md.
The Iterator interface places fewer requirements on the implementation
when compared to ReadSeq. The ReadSeq requires that your implementation
have random access (apply(USize): T), have a known size (size(): USize)
and support sequential (ordered) access by returning an Iterator from
the values() function. Where as the Iterator only requires that the
implementation have sequential access, so is a subset of the
functionality if ReadSeq. There are a number of cases where supporting
an Iterator interface rather than ReadSeq would be desirable. Supporting
a database cursor or a stream from a network service are two that come
immediately to mind.
The other …
> RFC #48 Change String.join to take Iterable

- .travis.yml
- .travis_install.bash
- CHANGELOG.md
This should default the pony compiler when installed from bintray to
looking for "gcc" rather than "gcc-6". That should be a much better user
experience.
> Have travis build Pony binaries using "gcc" as PONY_COMPILER

- src/libponyc/expr/match.c
The current "this caputre violates capabilities" message is not very
beginner friendly. It frequently trips up new Pony users. This commit
will change from the current message format:
```
Error:
main.pony:15:13: this capture violates capabilities
| let ch: U8 =>
^
Info:
main.pony:13:21: match type: this->ReadSeq[T #read] box->T #read
for item in _expected.values() do
^
main.pony:15:13: pattern type: U8 val
| let ch: U8 =>
```
To the more verbose and hopefully more informative:
```
Error:
main.pony:15:13: this capture violates capabilities, because the match would need to differentiate by capability at runtime instead of matching on type alone
| let ch: U8 =>
^
Info:
main.pony:13:21: the match type allows for more than one possibility with the same type as pattern type, but different …
```
> Make "this capture violates capabilities" msg more beginner friendly

- src/libponyc/expr/lambda.c
- test/libponyc/lambda.cc
> Fix compiler error on lambda capture of '_'

- packages/files/directory.pony
- src/libponyc/ast/printbuf.c
- src/libponyrt/lang/directory.c
- src/libponyrt/lang/ssl.c
- src/libponyrt/sched/cpu.c
- test/libponyc/codegen.cc
- test/libponyrt/ds/fun.cc
This change replaces calls to the libc's `malloc` function by calls to allocation functions from the runtime pool allocator.
The remaining `malloc` calls weren't replaced because the allocated memory is used to interact with APIs that require the memory to be `malloc`ed.
> Replace calls to malloc by calls to the pool allocator

- src/libponyc/codegen/codegen.c
- src/libponyc/codegen/gencall.c
- src/libponyc/codegen/genexe.c
- src/libponyc/codegen/genopt.cc
- src/libponyrt/actor/actor.c
- src/libponyrt/actor/messageq.c
- src/libponyrt/actor/messageq.h
- src/libponyrt/pony.h
- src/libponyrt/sched/scheduler.c
This function is a more efficient push operation in the single producer case, but is unsafe to use in the multiple producers case. The goal of this function is to enable more efficiency with message queues when
pushes are known to be single producers.
In the public interface of the runtime, a `pony_sendv_single` function has been added, which behaves in the same way `pony_sendv` does but calls `ponyint_messageq_push_single` (and is therefore unsafe to use with
multiple producers).
The compiler now generates `pony_sendv_single` calls when sending actor constructor messages, since these messages are always in the single producer case.
> Add the ponyint_messageq_push_single runtime function

- CHANGELOG.md
- packages/builtin_test/_test_valtrace.pony
- packages/ponybench/_bench.pony
- packages/ponybench/_bench_async.pony
- src/libponyrt/actor/actor.c
- src/libponyrt/gc/trace.c
- src/libponyrt/pony.h
- src/libponyrt/sched/scheduler.c
- test/libponyc/codegen_trace.cc
This changes the signature of the public runtime functions `pony_continuation` and `pony_triggergc` to take the execution context instead of an actor as a parameter. Since these functions are only safe to use on the current actor, this signature change better conveys the function contract and can avoid misuse.
This also adds assertion checks on public runtime functions expecting a current actor.
Manual changelog entry for a complete explanation of the change.
> Change the signature of runtime functions to take a pony_ctx_t

- src/libponyc/codegen/genexpr.c
- test/libponyc/codegen.cc
This change fixes a compiler crash when converting a union of tuples to a tuple.
Closes #1513.
> Fix compiler crash on union-of-tuples to tuple conversions

- src/libponyrt/actor/messageq.c
- src/libponyrt/sched/mpmcq.c
This change fixes a race condition in the runtime atomic MPSC and MPMC queues where the initialisation of a node in a push operation could conflict with the modification of that node in the next push operation,
resulting in pop operations incorrectly seeing the queue as empty.
This problem couldn't occur on x86 because of platform-specific memory ordering constraints. It could theoretically occur on ARM but no actual case has been reported.
This change doesn't incur any performance impact on x86. It could incur a small performance penalty on ARM but no benchmarking has been done.
> Fix race condition in runtime atomic queues

- Makefile
- src/libponyrt/actor/actor.c
- src/libponyrt/actor/actor.h
- src/libponyrt/pony.h
The Encore project uses the Pony runtime and has implemented
continuations for actors. There's a small amount of code in the Pony
runtime to support these continuations. It's a fairly unobtrusive bit of
code except for one small point. There's a check for continuation in a
hot path when actors are handling messages. This commit makes actor
continuation support a compile time option.
To get previous actor continuation support, USE_ACTOR_CONTINUATIONS
should be defined. Support for this exists in the Makefile as a "use"
directive.
> Make actor continuations a build time option

- src/libponyc/pass/docgen.c
Per https://github.com/ponylang/ponyc/issues/2145#issuecomment-321131037,
this shouldn't be allowed as its not legal Pony. As #2145 generally
comments on we only want legal code output in the documentation.
This addresses the specific issue in #2145, however, there are other
instances we might want to expand this to. I decided to limit to this
specifically as I think any change we make in other sections of docgen
would require a thorough auditing of output documentation to make sure
there weren't any unintended consquences.
Prior to this change, generated documentation for:
```pony
type Set[A: (Hashable #read & Equatable[A] #read)] is HashSet[A,
HashEq[A]]
```
would be
```pony
type Set[A: (Hashable #read & Equatable[A #read] #read)] is
HashSet[A #read, HashEq[A #read] val] ref
```
now it …
> Don't print capabilities for type params when generating docs

- packages/process/_test.pony
- packages/process/process_monitor.pony
Based on work originally done by @lispmeister. I brought it up to date
and fixed problematic test failures.
Add write buffering and asio events for writes to STDIN of the child
We now register an asio event on the STDIN file descriptor.
We write as much as possible. If we can't write everything we store the
ByteSeq in a list together with an offset and set the _stdin_writeable
flag to false. Once the OS signals STDIN is writeable again we try to
write the chunks stored in the list starting with the head chunk.
Closes #945
> Process monitor async write buffering

- packages/signals/signal_notify.pony
As of Sierra, `@raise` delivers signals to the current thread, not
the process. Use `@kill` on Darwin instead to deliver to the process,
as EVFILT_SIGNAL never sees signals delivered to specific threads.
> Fix signals on Sierra

- src/libponyc/expr/reference.c
- src/libponyc/pass/verify.c
- test/libponyc/dontcare.cc
This change moves a check from the verify pass to the expr pass in order to catch an illegal read from '_' in a function argument before trying to use said argument.
Closes #2157.
> Fix compiler crash on illegal read from '_'

- src/libponyc/codegen/codegen.c
- src/libponyc/codegen/genfun.c
This change allows better optimisations, particularly from the LLVM MergeFunctions pass. Bare functions aren't affected by this change since their addresses are significant for identification.
> Codegen: Mark non-bare functions unnamed_addr

- src/libponyc/type/lookup.c
- test/libponyc/badpony.cc
Working on learning more about the compiler...
This fixes the bug noted in #394, where named parameters can be used with methods in a union type whose parameter names differ.
The change makes it a compile-time error to call a method on a union type using named arguments when the methods in the union types have differently-named parameters.
Was:
This fixes the bug noted in #394, where named parameters can be used with
methods in a union type whose parameter names differ.
The change makes it a compile-time error to call a method on a union type
(whether using named parameters or not) when the methods in the union types
have differently-named parameters.
> Disallow named arguments for methods of a type union where parameter names differ

- src/libponyc/codegen/codegen.c
- src/libponyc/codegen/codegen.h
- src/libponyc/codegen/gencall.c
- src/libponyc/codegen/gendesc.c
- src/libponyc/codegen/genfun.c
- src/libponyc/codegen/genident.c
- src/libponyc/codegen/genprim.c
- src/libponyc/codegen/genreference.c
- src/libponyc/codegen/genserialise.c
- src/libponyc/codegen/gentrace.c
- src/libponyc/codegen/gentype.c
- src/libponyc/codegen/host.cc
- test/libponyc/badpony.cc
- test/libponyc/codegen_ffi.cc
- test/libponyc/dontcare.cc
- test/libponyc/finalisers.cc
- test/libponyc/util.cc
This change fixes a bug where the same FFI function was being declared with incompatible signatures in different packages without being validated, causing various crashes from both ponyc and LLVM.
Closes #1552.
> Fix codegen failures on incompatible FFI declarations

- src/libponyrt/mem/pool.c
This change allows compiler optimisations to be less conservative. This doesn't include any functional change.
> Fix read-after-write dependencies in pool_block_remove

- src/libponyc/ast/lexer.c
- test/libponyc/lexer.cc
This PR will treat empty character literals as invalid syntax
and handle weird utf8 character literals like `'🎠'` correctly.
The root cause was the casting from `char` to `int` which created ints like `0xFFFFFF9F` for a lexer char `\x9F`. This was treated as negative and thus ignored by the lexer.
This fixes #2198 in that it treats multi-byte input correctly byte by byte.
> Fix handling of empty and multi-byte character literals

- packages/itertools/_test.pony
- packages/itertools/iter.pony
Previously, the `take` method on an infinite stream, such as `Rand`,
would cause infinite recursion.
> Fix Iter.take to handle infinite iterator

- src/libponyc/codegen/genlib.c
The compiler was not allocating a big enough buffer for the linker command line on Windows.  This change makes it allocate more than enough space.
Fixes #2222.
> Fix undersized string buffer for library link command in Windows.

- src/libponyc/ast/lexer.c
- test/libponyc/lexer.cc
* strip trailing whitespaces from the last line (but keep the linebreak) if the last line contains only of whitespaces 
* require multi-line triple-quoted strings to start on the line below the opening triple-quote (while tolerating whitespace characters on the same line)
This fixes #2178
> Fix inconsistencies in multi-line triple-quoted strings

- Makefile
My PR to introduce support for DragonFlyBSD added /usr/local/lib to the
linker search path. We assumed this would be harmless, however it was
not. Because /usr/local/lib was added to the path in a fashion where it
would appear before the local "build" directory then the following would
happen:
- Run `make`
- Get a linker failure if you'd previously installed ponyc
Whereas
- Run `make` install
- No linker error
The problem occured because the pony libraries in /usr/local/lib were
being used instead of those in build.
This PR moves the addition of /usr/local/lib to being AFTER build path.
Closes #2219
> Fix broken "make" command

- src/libponyc/codegen/genexe.c
Ponyc on Windows was ignoring the value passed by the `--linker` command-line flag.  This PR makes ponyc use the value if present.
> Make Windows link step use the command-line `--linker` value if present.

- CONTRIBUTING.md
- Makefile
from runs of ponyc or the test commands
both for gcc (using gcov and lcov) and for clang (using llvm-cov).
```bash
CC=gcc CXX="g++" make config=debug use=coverage
./build/debug-coverage/libponyc.tests --gtest_filter='LexerTest.*'
lcov --directory .build/debug-coverage/obj –zerocounters
lcov --directory .build/debug-coverage/obj --capture --output-file ponyc.info
genhtml -o build/debug-coverage/coverage ponyc.info
```
```bash
CC=clang CXX="clang++" VERBOSE=true make clean all config=debug use=coverage
LLVM_PROFILE_FILE="build/debug-coverage/coverage.profraw" ./build/debug-coverage/libponyc.tests --gtest_filter='LexerTest.*'
llvm-profdata merge -sparse -output=build/debug-coverage/coverage.profdata build/debug-coverage/coverage.profraw
llvm-cov show ./build/debug-coverage/libponyc.tests …
```
> add use=coverage option to Make to obtain coverage information

- src/libponyc/pass/pass.h
- src/libponyc/pkg/package.c
- src/ponyc/main.c
This option forces the compiler to use a minimal builtin package instead of the real package. This is intended for debugging purposes only.
> Add the --simplebuiltin compiler option

- .appveyor.yml
- src/libponyc/codegen/genexe.c
- src/libponyc/platform/vcvars.c
- wscript
This change includes the following:
- Uses the latest LibreSSL (2.6.1) and PCRE2 (10.30) library packages for Windows.
- Stores the Windows library packages so they aren't deleted by `make clean`.
- Builds in release mode (`make --config=release`) by default to conform with *nix.
- To speed up builds, does not build the `stdlib` tests unless running `make test`.
> Minor updates and improvements to Windows build

- Makefile
- src/libponyc/ast/lexer.c
- src/libponyc/ast/parser.c
- src/libponyc/ast/treecheck.c
- src/libponyc/ast/treecheckdef.h
- src/libponyc/expr/array.c
- src/libponyc/expr/call.c
- src/libponyc/pass/pass.c
- src/libponyc/pass/scope.c
- src/libponyc/pass/sugar.c
- src/libponyc/pass/traits.c
- src/libponyc/pkg/ifdef.c
- src/libponyc/type/lookup.c
- src/ponyc/main.c
- test/libponyc/util.cc
- wscript
This change updates the AST checking pass in `treecheckdef.h` with the newer language constructs and fixes some discrepancies with existing constructs.
The AST checking pass is now enabled in the compiler and standard library tests.
Closes #2240.
> Bring treecheckdef up to date

- packages/random/random.pony
In the description of the new random signed integer methods from #2128, the values were one bit off.
> Fix signed integer limits in documentation (#2128)

- src/libponyc/reach/reach.c
- test/libponyc/codegen.cc
This fixes a bug occurring when accessing a field with a viewpoint-adapted type that wasn't being reached.
Closes #2238.
> Fix codegen failure on field access

- src/libponyc/codegen/genprim.c
- test/libponyc/codegen.cc
This commit fixes a bug in how empty strings are serialised.
Resolves #2245.
----------
This PR is based on @Praetonus's PR #2246 and includes the codegen test he added. It is an implementation of the diff I suggested in my comment on that PR.
> Fix empty string serialisation

- src/libponyc/expr/array.c
Without these returns, these switches fail to compile on a Debian system with gcc 7.2.0 because of `-Werror=implicit-fallthrough`.  I didn't spend any time scrutinizing this part of the code to determine if the fallthroughs were intentional, and it's possible that there's something strange about my setup that causes this to be a problem, but I figured the best course of action was just to open a PR and see what happens.
I don't think it makes a difference, but the command I used to build was:
```
make config=release prefix=$HOME/lib/pony all install
```
> Fix implicit fallthrough in array inference.

- src/libponyc/pass/casemethod.c
- test/libponyc/sugar.cc
it was failing for `_` as a case method argument.
Case method docstrings contain the signature and docstrings of each case method concatenated.
The method of printing the signature didn't work for `_`, the dont care symbol.
With this PR it still won't print every possible expression correctly (e.g. recover expressions) but it won't fail anymore.
This fixes #2249.
> Fix compiler crash on case methods with `_` as a method parameter.

- src/libponyrt/sched/cpu.c
Fixes #1787
Interestingly, all the info needed to solve this issue a while ago was
already in the issue but it wasn't until @slfritchie put his additional
comments in
https://github.com/ponylang/ponyc/issues/1787#issuecomment-333010911
that it all clicked for me.
The excess CPU time is from us doing too much work stealing. In a normal
scenario, with nothing to do, we'd not doing anything for a long time
and we'd end up sleeping for quite a while.
With the timer that goes off every few seconds as seen in the issue,
that isn't what happens. We regularly get woken and end up in a work
stealing cycle.
Then, due to the lack of an `else` block for yielding, on OSX, we'd
nanosleep for 0 which is the same as an immediate return. To see what
the impact of that would be on any platform change the: …
> Fix excess work stealing under low loads

- src/libponyrt/mem/heap.c
- test/libponyc/codegen.cc
Prior to this commit there was a bug which prevented the finaliser
from running for the first slot of a small `chunk` in an actors
`heap`. This would result in incorrect behavior but only on a subset
of all objects created depending on which slot in a small chunk the
object happened to occupy.
This commit fixes this issue and also adds a test to catch the
issue to prevent regression.
---------
This bugfix is the last remaining hurdle preventing completion of WallarooLabs/wallaroo/issues/1605
> Fix small chunk finaliser bug

- src/libponyc/pass/docgen.c
Before, many `from()` methods' docs were broken, because markdown
doesn't allow you to have line breaks in your headers, e.g.
[I64](builtin-I64) val | [I128](builtin-I128) val | [ILong](builtin-ILong) val |
Now, it'll not insert breaks for unions (introduced in #1294) when it is
a method header, but leaves it as one long line. (It certainly isn't
beautiful, but it is less broken...)
Turns out this bug has another instance in document headers:
[U64](builtin-U64) val | [U128](builtin-U128) val | [ULong](builtin-ULong) val |
...will also be one long line now.
--------
Before:
After:
> Fix broken method and type headings in generated documentation

- src/libponyc/verify/call.c
- test/libponyc/verify.cc
> Don't verify partial calls for method bodies inherited from a trait.

- examples/dtrace/gc.d
- examples/dtrace/mbox-size.d
- examples/dtrace/message-types.d
- examples/dtrace/nanosleep.d
- src/common/dtrace_probes.d
- src/libponyrt/actor/actor.c
Hi, everyone.  I'm a Pony newbie.  I tried using Pony's DTrace probes for understanding a behavior problem inside of Wallaroo and found that a couple of probe descriptions had omitted some useful information.  This PR contains changes to a couple of existing DTrace probe definitions, a change to the `gc.d` script, and add several new scripts.
The `actor-alloc` and `actor-msg-send` probes were missing information about the actor(s) involved with the probe.  I added actor information to the end of their respective argument lists.
The `gc.d` script was leaking memory by not clearing the `self->start_gc` variable.  I also added a pragma to reduce the number of error messages that I saw, casued by the small default dynamic variable buffer size.
Driven equally by sheer curiosity and by a real …
> DTrace actor additions

- src/libponyc/expr/match.c
- src/libponyc/expr/reference.c
- src/libponyc/pass/casemethod.c
- test/libponyc/dontcare.cc
- test/libponyc/sugar.cc
as the else clause is equivalent. Error messages for case expr tell users to use an else clause.
For case methods there is no equivalent, but this has not been workin before anyways.
This fixes a part of #2253
> Forbid single '_' in case expr and case methods

- packages/buffered/writer.pony
Prior to this commit, multiple calls to `Writer.reserve` would
allocate more and more memory in `_current` even if a sufficient
amount of unused memory was already available and allocated in
`_current`.
This commit changes the logic in `reserve` to call `_check` as
that has similar logic to confirm/reserve memory required but
without the memory leak.
----------------
For context:
We had a piece of code with a memory leak related to `Writer.reserve` calls. Removing the calls removed the leak. We were calling `Writer.reserve` right after `create` and `Writer.done` and then filling the `Writer` using `Writer.write` in between. This resulted in a memory leak because `Writer.write` doesn't use `_current` and `Writer.done` doesn't change/reallocate `_current` if there was no data written to it. …
> Replace memory-leak-inciting `Writer.reserve` with more intuitive `Writer.reserve_current` method.

- src/common/platform.h
- src/libponyrt/actor/actor.c
The macro static_assert fails to compile as detailed in issue #2271
Since static_assert expands to _Static_assert, this should be a suitable replacement
to circumvent the failure while compiling.
**Update:** Due to the failure on Windows, added a definition to `platform.h` for `pony_static_assert` which uses `static_assert` or `_Static_assert` dependent on what's defined for `clang`. Defaults to `static_assert` for all others. Thanks to @dipinhora for the help on that.
> Replace static_assert with _Static_assert in actor.c

- test/libponyc/codegen.cc
- test/libponyc/util.cc
This makes the test run a lot faster as there is much less code to compile.
> Use fake stdlib packages in the SmallFinaliser test

- Makefile
- README.md
This turns off LTO by default on MacOS. This will have performance
implications for default installs, however, turning on LTO by default
can lead users to have broken installs via "spookey action at a
distance".
Here's the scenario. For LTO to work, you need to be using the same
bitcode for the linker in both the Pony runtime and the currently
installed linker. Ways that having LTO can lead to a broken install:
1) install Pony
2) upgrade XCode such that the linker bitcode version changes
In that scenario, you no longer can compile programs.
Another scenerio (which can happen via homebrew).
1) build pony and its runtime on a machine that has XCode version X
2) install onto a machine that has an older version of XCode
The pony will fail to build programs and fail with a fairly inscrutable …
> Turn off LTO by default on OSX

- Makefile
- lib/blake2/blake2-impl.h
- lib/blake2/blake2.h
- lib/blake2/blake2b-ref.c
- packages/serialise/serialise.pony
- src/libponyc/ast/ast.c
- src/libponyc/ast/ast.h
- src/libponyc/ast/token.c
- src/libponyc/ast/token.h
- src/libponyc/codegen/genprim.c
- src/libponyc/codegen/genprim.h
- src/libponyc/codegen/gentype.c
- src/libponyc/pass/pass.c
- src/libponyc/pass/scope.c
- src/libponyc/pkg/package.c
- src/libponyc/pkg/package.h
- src/libponyc/pkg/program.c
- src/libponyc/pkg/program.h
- src/libponyrt/ds/list.c
- src/libponyrt/ds/list.h
- src/libponyrt/gc/serialise.c
- src/libponyrt/gc/serialise.h
- test/libponyc/compiler_serialisation.cc
- test/libponyc/signature.cc
- test/libponyrt/ds/hash.cc
- wscript
This change implements deterministic package and program signatures based on the contents and dependencies of the packages. Signatures are computed by hashing the serialised package ASTs with the BLAKE2 hash function. This hash function was chosen for its good speed and low collision rate.
The signature computation handles circular dependencies by computing signatures per package cycle instead of per package. Packages in the same group are discriminated by a group index.
In order to allow deterministic signatures, file parsing order is now always alphabetical inside of a package.
The compiler now outputs the package groups and dependencies when the `-V3` or `-V4` flags are enabled.
Signatures will be used for future work on separate package compilation in order to validate package …
> Implement RFC 47 (Serialise signature)

- packages/itertools/iter.pony
The example for the fold function had its arguments swapped.
> Fix the docstring for the fold function

- packages/process/_test.pony
We are relying on external processes that sometimes get
scheduled oddly by our test environment. I don't want to
make these incredibly long but, this should help remove
some spurious failures.
> Increase process monitor test timeouts

- packages/net/net_address.pony
and about the name method possibly doing a DNS lookup.
This is not obvious but is a big point of confusion, especially when trying to retrieve the numeric port, which is in network byte-order. 
[skip ci]
> add notes about net.NetAddress representing sockaddr_in4/6

- src/libponyc/expr/call.c
This PR adds info message on the argument subtyping as described by @Praetonus on #2211.
Obs.: I tried to add tests for this PR on test file `badpony.cc`, but I could not find any way of testing "Info". For the code below:
```C
TEST_F(BadPonyTest, SequencesSeparatedByComma)
{
// From issue #2211
const char* src =
"actor Main\n"
"  new create(env: Env) =>\n"
"    let t: U64 = 0\n"
"    foo(\n"
"      \"foo\"\n"
"      t)\n"
"  fun foo(str: String, t: U64) =>\n"
"    None";
TEST_ERRORS_3(src,
"argument not a subtype of parameter",
"U64 val is not a subtype of String val",
"note that arguments must be separated by a comma");
}
```
The test fails with the message:
I know that it makes sense, as it is __indeed__ `1 error message` with `2 info messages`.
I am sorry if here is the wrong place to …
> Add info message for TK_SEQ (arguments must be separated by a comma)

- packages/files/_test.pony
This PR fixes 2 issues:
1) some tests never called dispose on files they opened, thereby, not
guaranteeing to close them.
2) some tests did call dispose but might encounter exceptions before the
dispose call that would prevent it from being called.
This PR changes the File package tests to use Pony's `with` blocks to
guarantee that `dispose` gets called on opened files.
> Verify all files get closed when running File tests

- packages/itertools/_test.pony
- packages/itertools/iter.pony
This change prevents the has_next method from returning true when the
underlying iterator is spent but still yields values.
> Fix possible repetition in Iter.flat_map

- packages/collections/persistent/_map_node.pony
- packages/files/file_path.pony
- packages/itertools/iter.pony
- packages/process/_test.pony
- src/libponyc/expr/match.c
- src/libponyc/expr/operator.c
- test/libponyc/badpony.cc
- test/libponyc/dontcare.cc
- test/libponyc/sugar.cc
- test/libponyc/sugar_expr.cc
this checks for exhaustive matches that have an else clause, which is unreachable,
this also checks for cases that are unreachable because previous cases are already exhaustive,
this also affects the 'as' clause as it is rewritten to a match internally:
this checks for 'as' clauses that try to cast to the same type or a subtype
which would result in an exhaustive match internally and can be considered illegal use of 'as'.
This is a breaking change, ***but for good***. If it affects any pony codebase, then it had a possible source of bugs.
The following examples will be invalid with this PR:
```pony
class Foo
fun ex_match(a: (String| Bool)): String => 
match a
| let a: Stringable => a.string()
| let b: Bool => if b then "true" else "false" end // unreachable already
else
"unreachable"
end …
```
> Error on unreachable cases in match expressions and illegal as expressions.

- src/libponyrt/asio/kqueue.c
We might try to add up to 4 items to the array but we only sized for 3.
This bug date back a couple years to when signal handling support was
added.
> Fix incorrect kevent structure size

- src/libponyc/type/lookup.c
- test/libponyc/finalisers.cc
These functions are meant for automatic FFI-related initialisation and forbidding access to them can avoid mistakes from the programmer.
> Forbid lookup on primitive _init functions

- src/libponyrt/actor/actor.c
Prior to this commit, actors wouldn't be garbage collected when using
--ponynoblock. With this change, any actors that aren't part of a cycle
will be garbage collected if they can no longer do work.
Before this change, using `--ponynoblock` with an application that
created transient actors would result in never ending memory growth as
the actors would never be gc'd. You can see an example of this by taking
a Pony program that listens for TCP connections and do a repeating cycle
of open/close. None of the created `TCPConnection` actors would be
garbage collected.
Closes #2306
> Garbage collect actors when --ponynoblock is in use

- Makefile
- src/libponyrt/sched/start.c
- src/ponyc/main.c
- wscript
Allow pony applications to print the version of ponyc that compiled it
and exit with the `--ponyversion` option.
resolves #2285
> Add --ponyversion option to compiled binary

- src/libponyrt/mem/heap.c
Prior to this commit, if a small chunk was partially used after GC
and had finalisers to be run for the freed slots, the execution of
the finaliser could end up reusing the slots for which finalisers
were being run. If this occurred, it would lead to unpredictable
results (a segfault in my case).
This commit changes the order of operations to ensure that all the
finalisers are run prior to the chunk being added back to the
available list ensuring that the execution of the finaliser cannot
allocate slots that are still to be finalised.
> Fix small chunk finaliser premature re-use bug

- packages/builtin/array.pony
- packages/builtin/string.pony
- packages/builtin_test/_test.pony
Prior to this commit, the trim/trim_in_place functions of Array
and String incorrectly calculated the new `_alloc` value.
This commit changes the logic to set `_alloc` to be the same
as the new `_size` if the last byte is not included and to
only included extra allocated bytes if we're including the
last byte.
This commit also changes how `String.from_cpointer` calculates
the `_alloc` value as it was incorrectly adding a byte when it
shouldn't have been (this was likely due to an assumption of a
null terminator being present that doesn't hold any longer).
Tests have also been enhanced to prevent regressions.
> Fix alloc bug in String/Array trimming functions

- packages/net/http/common_log.pony
- packages/net/http/contents_log.pony
- packages/net/http/discard_log.pony
- packages/net/http/server_notify.pony
Previously, `ContentsLogger` did not implement the `Logge`r interface. There
were also some inconsistencies between the parameter names in the `Logger`
apply method across its implementations.
> Make ContentsLogger implement the Logger interface

- src/libponyc/codegen/genfun.c
- src/libponyc/reach/reach.c
- src/libponyc/reach/reach.h
Implicit finalisers are added to types without an explicit finaliser but with embedded fields with a finaliser (either implicit or explicit).
Previously, ASTs for these finalisers were sugared during reachability analysis, which wasn't very clean since the main program AST isn't supposed to be mutated during code generation.
Now implicit finalisers are directly added as internal methods without mutating the AST.
> Do not mutate the AST when adding implicit finalisers

- README.md
Since there are problems with compiling `ponyc` on FreeBSD 10, and since those problems disappear when using FreeBSD 11, I've created a patch to the top README file to strongly suggest using FreeBSD 11.  Then perhaps a handful of people may avoid the rabbit hole I just fell into.  `^_^`  This is a suggestion: reviewers are welcome to bend this in another direction if they wish.
This is a workaround for #2339, not a fix ... unless someone decides to abandon hope on FreeBSD 10 support.
> Add explicit OS version + amd64/64-bit prerequisites to FreeBSD section

- packages/net/tcp_connection.pony
On Windows, the TCPConnection actor waits for leftover IOCP messages (e.g. from a second happy eyeballs connection when IPv4 or IPv6 is unspecified) before closing, but does not check if it should shut down after such messages are received.  This change makes it check again.
This fixes #2322.
> Fully close unspecified family TCP connections on Windows.

- packages/builtin/array.pony
- packages/builtin/string.pony
- packages/builtin_test/_test.pony
For context, my main use case for this functionality is efficient buffer manipulations (i.e. minimal or no copying). I had hoped to be able to accomplish this without modifying `stdlib` but the pointer manipulations required are only possible in `builtin`.
NOTE: This functionality is not safe until the bugs related to `_alloc` for `String` and `Array` trimming are fixed by #2336.
--------------------
This commit adds a `chop` function to both String and Array
that works on an `iso` and chops it in two with the left half
being a new `iso` String/Array reusing the same pointer
and the right half being a `trim_in_place` version of the original
String/Array. Both are returned as `iso` and mutable and do not
share any memory. The operation does not allocate a new pointer
nor copy elements …
> Add `chop` function for chopping `iso` Strings and Arrays

- packages/random/mt.pony
- packages/random/xoroshiro.pony
- packages/random/xorshift.pony
The current implementations of XorOshiro128Plus and XorShift128Plus return the sum of input seed values for the first value, which is unsafe. Rather than telling people to discard the first value, skip past it in the actual implementation.
This commit also fixes the documentation of current implementations for consistency with the Random trait.
Resolves #2320
> Fix poor randomness properties of first call to `Rand.next()`.

- README.md
Change the urls from pointing at ponyc-rpm in github.com/winksaville to
aur.archlinux.org
> Update README.md ponyc-rpm urls

- src/libponyc/expr/match.c
- test/libponyc/sugar_expr.cc
for primitives that have custom 'eq' methods or implement Equatable[T] where T is a subtype of the primitive.
The type was inferred by looking at the type of the full case AST which was inferred
from the first argument of the eq method. Now the exhaustive match logic is
considering the actual type of the case expression.
This should fix #2327
> Fix incorrect detection of exhaustive matches for structural equality comparisons on some primitives.

- src/libponyc/codegen/genexe.c
On Linux, it is a bit annoying that the warning about
the CC environment variable not being set gets printed
when compiling, even if the fallback works fine - which
it should do on all standard distributions since the
value of CC gets compiled in via the Makefile.
It seems to make more sense to only print this message
if linking actually fails, to help the user figure out
why the failure happened.
> Only print CC usage warning if linking fails

- .gitignore
To go along with the `.gitignore` files added for the examples, we now ignore intermediate files created during Windows compiles.
> Update root .gitignore to ignore Windows generated output files.  [skip ci]

- src/libponyc/codegen/codegen.h
- src/libponyc/codegen/gendebug.cc
- src/libponyc/codegen/gendebug.h
- src/libponyc/codegen/genfun.c
- src/ponyc/main.c
@oraoto mentioned in #2331 that debug information is not output for Pony programs on Windows.
This PR implements CodeView debug information so that you can see functions and variables when debugging in Windows.
> Enable CodeView debug information with MSVC on Windows

- packages/net/http/_client_connection.pony
- packages/net/http/_test.pony
- packages/net/http/client.pony
The _conn: TCPConnection was used before it was opened.
Added an extra state _ConnConnecting for proper handling.
Also fixed _ClientConnection not closing the connection
when not work needed to be done by calling _send_pending
after having received the body part of the HTTP response.
Added one trick pony http server for testing
>  Fixed state handling of HTTP client connections

- Dockerfile
This allows users of the docker image to do the following:
* `docker run -it ponylang/ponyc stable fetch` to fetch dependencies
* `docker run -it ponylang/ponyc stable env ponyc` to build with
dependencies
> Add pony stable to docker image

- packages/collections/_test.pony
- packages/collections/set.pony
Previously, `Set.intersect` would modify the underlying datastructure
during iteration. This would result in the operation skipping over
values and producing an incorrect result.
closes #2359
> Fix Set.intersect

- Makefile
- src/libponyc/codegen/genexe.c
The current build procedure for 'make use=dtrace' is working
correctly for OS X and Linux+SystemTap because both are hybrids
compared to the original Solaris implementation.  FreeBSD's
implementation is very close to Solaris's.
The original implemntation requires a two-stage process for compiling
the USDT probe specification file, e.g., `src/common/dtrace_probes.d`).
The first stage, `dtrace -h`, creates the C header file prerequisite
for compilation.  The second stage, `dtrace -G`, analyzes the object
files for DTrace probe data and creates a new object file that must
also be linked into the executable.
The `Makefile` procedure for the second stage for Linux is apparently
sufficient for Linux+SystemTap but isn't sufficient for FreeBSD.
The FreeBSD linker does not automatically add the …
> Fix compilation error with 'use=dtrace' for FreeBSD 11

- packages/itertools/_test.pony
- packages/itertools/iter.pony
This change makes `Iter.take_while` short-circuit the first time that
the predicate `f` returns false or raises an error. Previously, this
adapter would infinitely pull from an infinite iterator after the
predicate had already returned false.
resolves #2356
> Make take_while short-circuit

- src/libponyrt/sched/scheduler.c
Prior to this commit, we sent actor block and unblock messages each time
we entered and left `steal`. Every instance of work stealing resulted in
a block/unblock message pair being sent; even if stealing was
immediately successful.
This was wasteful in a number of ways:
1. extra memory allocations
2. extra message sends
3. extra handling and processing of pointless block/unblock messages
This commit changes block/unblock message sending logic. Hat tip to
Scott Fritchie for pointing out to be how bad the issue was. He spent
some time with DTrace and come up with some truly terrifying numbers for
how much extra work was being done. Dipin Hora and I independently came
up with what was effectively the same solution for this problem. This
commit melds the best of his implementation with the …
> Improve work-stealing "scheduler is blocked" logic

- packages/collections/_test.pony
- packages/collections/range.pony
Add is_infinite method to check whether a given Range would iterate infinitely (having an inc-step which does not move min towards max).
Previously Range would also not iterate over given intervals where min > max irrelevant of the sign of the inc-step.
> fix Range with negative or 0 step and allow backward Ranges (having `min > max`)

- Makefile
Right now, as an artifact of when we did uploads to bintray for every
commit to master, we have version numbers that look like:
0.20.0-4003.0b2a2d2
This is needed if we are doing multiple releases per version like we
once were with the commits to master but, it isn't otherwise.
It's hostile in fact to doing an install.
If I wanted to install ponyc version 0.20.0 from bintray I can't do:
apt-get install ponyc=0.20.0
I have to look up the specific release that corresponds to 0.20.0 and
do:
apt-get install ponyc=0.20.0-4003.0b2a2d2
I noticed this as part of setting up Wallaroo Labs CI to be able to test
against multiple versions of Ponyc. Definitely unfriendly. Additionally,
it makes it harder on software that wants to give a specific version of
ponyc it works with.
You have to go look up …
> Use user friendly release names in bintray

- src/libponyrt/asio/epoll.c
- src/libponyrt/asio/iocp.c
- src/libponyrt/asio/kqueue.c
- src/libponyrt/sched/scheduler.c
Prior to this commit, the shutdown process could potentially cause
the runtime to end up in an invalid state where the ASIO backend
had been stopped but the shutdown of the runtime was aborted. If
this occurred and any actor subsequently tried to subscribe to
an ASIO event, it would cause a segfault because the ASIO backend
would be `NULL` instead of an actual `asio_backend_t*`.
This commit changes things so that if the shutdown is aborted due
to the receipt of a new `UNBLOCK` message and the ASIO backend
has already been stopped, we try and restart the ASIO backend.
This commit also adds some extra assertions around the use of the
ASIO backend to ensure it is not `NULL` when it shouldn't be.
This should resolve WallarooLabs/wallaroo#1608.
> Restart ASIO if needed while runtime is attempting to terminate.

- .appveyor.yml
- .travis.yml
- .travis_install.bash
- .travis_script.bash
- Makefile
- README.md
- src/libponyc/codegen/codegen.h
- src/libponyc/codegen/genbox.c
- src/libponyc/codegen/gencall.c
- src/libponyc/codegen/gendebug.cc
- src/libponyc/codegen/gendesc.c
- src/libponyc/codegen/genexpr.c
- src/libponyc/codegen/genoperator.c
- src/libponyc/codegen/genopt.cc
- src/libponyc/codegen/genprim.c
- src/libponyc/codegen/genreference.c
- src/libponyc/codegen/gentype.c
- src/libponyc/codegen/gentype.h
- src/libponyc/codegen/host.cc
- src/libponyc/pass/pass.h
- src/ponyc/main.c
- wscript
This change includes the following:
- Compiler code updates for changes to the LLVM 4.0.0 and 5.0.0 API.
- Updates to Type-Based Alias Analysis metadata format for LLVM 4.0.0 and up.
> Experimental support for LLVM 4.0.1 (#1592) and 5.0.0.

- src/libponyrt/asio/asio.c
- src/libponyrt/asio/asio.h
- src/libponyrt/asio/epoll.c
- src/libponyrt/asio/iocp.c
- src/libponyrt/asio/kqueue.c
- src/libponyrt/sched/scheduler.c
- src/libponyrt/sched/scheduler.h
Prior to this commit, we sent scheduler block/unblock messages even
if there were noisy actors registered with the ASIO thread/subsystem
and there was no chance the program was ready to terminate (because
the program is not allowed to terminate as long as there are any
noisy actors registered with the ASIO thread/subsystem).
This commit changes the block/unblock sending logic to only send
these messages if there are no noisy actors registered with the
ASIO thread/subsystem (in addition to all the logic that already
existed prior to this commit).
> Make work-stealing "scheduler is blocked" logic smarterer

- src/libponyc/codegen/genoperator.c
> Prevent incorrect GCC uninitialized error in genoperator.c

- src/libponyrt/sched/scheduler.c
NOTE: @SeanTAllen is aware of and has done a quick confirmation that this change is acceptable and doesn't seem to negatively impact the memory/stability related gains from the original PR.
NOTE: This also resolves the original issue that prompted both PR #2369 and PR #2370.
-------------------
PR #2355 included a change that improved runtime performance at
the cost of significantly delaying program termination using a
magic value of `10000000000`. After some additional testing, it
was discovered that a smaller magic value of `1000000` is equally
effective without unnecessary termination delay.
This commit changes the magic value from `10000000000` to
`1000000`.
> Change steal magic value to 1000000

- packages/itertools/_test.pony
- packages/itertools/iter.pony
Before this change `Iter.take` would continue iterating until `n` elements were taken or a call to `next()` of the inner iterator would error. `has_next()` has never been called.
The same is true for `Iter.nth` and `Iter.skip`. 
While this works e.g. on Iterators over `Array` (i.e. `ArrayValues`) it does not for Iterators that continue returning elements in `next()` although `has_next()` already returned `false` (e.g. `collections.Range`).
> Fix Iter.{skip,take,nth} to check '.has_next()' of their inner iterator

- src/libponyrt/mem/pool.c
NOTE: The new sizes before sharing might need some tweaking but in general, sharing the smaller pool size classes at smaller thresholds seems to be good for memory usage without too much overhead.
---------------
Prior to this commit, all thread pools (regardless of size class)
would only share memory with other threads (scheduler or ASIO) once
they passed the `POOL_MAX` size (1048576 bytes) had been accumulated.
This is not ideal for the smaller size classes which are used for
things like message sending between scheduler threads and actors
as it requires a large amount of message sending prior to
memory stabilization.
This commit changes things so that the amount of memory before the
thread local pools start sharing with other threads is different
depending on the size class. …
> Make scheduler threads share memory more quickly

- src/libponyrt/sched/cpu.c
Prior to this commit, we would always only sleep for 1 ms on windows
if yielding was allowed regardless of how much idle time had passed
while on non-windows, we would sleep for larger amounts of time as
more idle time has passed.
This commit changes the logic so that windows and non-windows both
sleep for similar amounts of time as more and more idle time passes.
> Make windows sleep consistent with non-windows sleep

- src/libponyrt/asio/asio.c
- src/libponyrt/sched/scheduler.c
Prior to this commit, the ASIO backend could fail initialization
but the runtime would continue to start up anyway resulting in
segfaults or assertion failures.
This commit changes things so that if the backend initialization
fails, the runtime exits immediately with an error.
This commit also fixes the asio restart logic from PR #2373 to
properly re-initialize the backend first.
> Fail pony_start if ASIO backend wasn't successfully initialized

- .travis_script.bash
- Makefile
This fixes #2316 
This pull request is broken into two commits. One makes possible to run the current `make docs` on BSD and OSX as well as Linux. The second one breaks them up as suggested in the issue.
> More platform agnostic `make docs`

- benchmark/libponyrt/ds/hash.cc
This fixes an oversight from dbd777a where allocation sizes weren't adapted when replacing `new` with `ponyint_pool_alloc_size`.
Closes #2313.
> Fix allocation sizes in runtime benchmarks

- src/libponyc/ast/ast.c
- src/libponyc/ast/ast.h
- src/libponyc/ast/token.c
- src/libponyc/ast/token.h
- src/libponyc/pass/pass.c
- src/libponyc/type/reify.c
This change adds an `ast_freeze` function that sets an AST as immutable. Mutable AST functions will then assert if called on a frozen AST.
The program AST is frozen after all AST passes are done, before reachability analysis and code generation.
The eventual goal of this change is to help with ensuring correctness when implementing ad-hoc AST reification in code generation to reduce memory usage.
> Forbid AST modifications during code generation

- .travis.yml
- .travis_script.bash
Prior to this commit, OSX builds for travis would run two separate
jobs for `config=debug` and `config=release` for each LLVM version
supported.
This commit combines the two `config=debug` and `config=release`
builds for each LLVM version supported into a single job. This is
mainly because recently Travis has been overloaded on the OSX
side of things and jobs end up waiting for a long time to start.
This change halves the number of jobs that need to run with no loss
of coverage. This is only possible as long as both builds combined
finish in under travis' job timeout of 50 minutes.
> Combine release and debug OSX builds into one travis job

- lib/blake2/blake2b-ref.c
- lib/gtest/gtest/gtest-param-test.h
- lib/gtest/gtest/gtest-param-test.h.pump
- lib/gtest/gtest/gtest-printers.h
- lib/gtest/gtest/gtest-spi.h
- lib/gtest/gtest/gtest-typed-test.h
- lib/gtest/gtest/gtest.h
- lib/gtest/gtest/internal/custom/gtest-port.h
- lib/gtest/gtest/internal/custom/gtest-printers.h
- lib/gtest/gtest/internal/custom/gtest.h
- lib/gtest/gtest/internal/gtest-filepath.h
- lib/gtest/gtest/internal/gtest-internal.h
- lib/gtest/gtest/internal/gtest-linked_ptr.h
- lib/gtest/gtest/internal/gtest-param-util-generated.h
- lib/gtest/gtest/internal/gtest-param-util-generated.h.pump
- lib/gtest/gtest/internal/gtest-param-util.h
- lib/gtest/gtest/internal/gtest-port-arch.h
- lib/gtest/gtest/internal/gtest-port.h
- lib/gtest/gtest/internal/gtest-tuple.h
- lib/gtest/gtest/internal/gtest-tuple.h.pump
- lib/gtest/src/gtest-death-test.cc
- lib/gtest/src/gtest-filepath.cc
- lib/gtest/src/gtest-internal-inl.h
- lib/gtest/src/gtest-port.cc
- lib/gtest/src/gtest-printers.cc
- lib/gtest/src/gtest-test-part.cc
- lib/gtest/src/gtest-typed-test.cc
- lib/gtest/src/gtest.cc
- lib/gtest/src/gtest_main.cc
- wscript
- Update Google Test and implement a workaround for deprecated TR1 usage.
- Turn the `ROUND()` and `G()` macros in the Blake2 code to inline functions to work around a MS compiler bug.
> Updates to fix building using Visual Studio 15.5

- src/libponyc/ast/lexer.c
- src/libponyc/ast/source.c
I ran into an issue where when writing back source to file where garbage appeared on some file. Looking at the code it seems there wasn't a null terminator put.
> Add null terminator for file source read

- examples/dtrace/mbox-size-all-actor-messages.d
- examples/dtrace/mbox-size-all-thread-messages.d
- src/common/dtrace_probes.d
- src/libponyrt/actor/actor.c
- src/libponyrt/actor/messageq.c
- src/libponyrt/actor/messageq.h
- src/libponyrt/asio/epoll.c
- src/libponyrt/asio/iocp.c
- src/libponyrt/asio/kqueue.c
- src/libponyrt/gc/cycle.c
- src/libponyrt/sched/scheduler.c
- src/libponyrt/sched/scheduler.h
Existing DTrace probes for message sending & receiving / push&pop are
placed in an ad hoc fashion.  As a result, many actor messages are
not visible to DTrace.  This patch places new DTrace probes within the
lowest-level code for adding & removing messages from queues.
The same queue functions are used for communication between threads.
New probes are also added to observe inter-thread communication.
I've introduced C preprocessor macros to wrap the message push & pop
operations.  The purposes of the macros are:
* Encode the queue category into the function call: actor or thread.
* Avoid cluttering the runtime's code by hiding the casting of
various args to uintptr_t.
Also added are two new scripts in the `examples/dtrace` directory:
* mbox-size-all-actor-messages.d: count probe firings …
> Add DTrace probes for all message push and pop operations

- CHANGELOG.md
To compensate for lack of `changelog - added` label on #2295, sorry.
> Manual Update CHANGELOG for PR #2295 [skip ci]

- src/libponyc/verify/fun.c
- test/libponyc/util.cc
- test/libponyc/util.h
- test/libponyc/verify.cc
Fix for #2146. Created a testing procedure for inspecting all error messages in a reported error.
> Remove redundant error message for unhandled partial calls that are actually in a try block.

- examples/net/listener.pony
- examples/net/net.pony
- packages/net/ssl/ssl_context.pony
The additional output is for greater visibility on the status of SSL.
> Fix examples/net and add additional output

- .appveyor.yml
This is the AppVeyor part of #2291.
> Add the contents of `.docs` to a `docs-support` directory in Windows packages.

- src/libponyc/codegen/gentrace.c
- test/libponyc/codegen_trace.cc
Previously, tracing functions weren't being generated for structs, which caused their fields to never be traced, resulting in various bugs including premature GC collection.
Closes #2308.
> Fix GC tracing of struct fields

- src/libponyc/codegen/genfun.c
This change ensures that all implicit finalisers are correctly registered before generating user functions. This ensures that every type with an implicit finaliser is correctly recognised as such when generating object allocations.
This doesn't contain a test case because the bug occurs because of the non-deterministic iteration of the reachability map.
> Fix codegen ordering of implicit finalisers

- src/libponyc/pass/verify.c
- src/libponyc/verify/type.c
- src/libponyc/verify/type.h
- test/libponyc/verify.cc
This fixes an oversight from b16d61a. This forbids cases where an implicit finaliser would be added to a struct.
> Forbid structs with embed fields with finalisers

- Makefile
As part of issue #2291, we've decided to create a `docs-support`
directory as part of the standard install that can be used to include
additional javascript, css, and other content used when building package
documentation.
This PR fulfills that when building from source on MacOS and Linux.
Additionally, it should install when using homebrew. RPM and Debian
packages will require another PR.
> Install doc creation support files on install

- Makefile
As part of #2291, we decided that we would package the documentation
generation support files that are located in .docs/ into the installed
packages in `docs-support`. This will allow them to be used not only
when Pony is released to update the standard library website but also
when users are running for known ponyc projects.
> Add documentation generation support files to Linux packages

- .appveyor.yml
- make.bat
Also fixes errorlevel returns in the `make.bat` build script.
> Use human-friendly package version numbers in AppVeyor.

- src/libponyc/codegen/codegen.c
- src/libponyc/codegen/codegen.h
- src/libponyc/codegen/genexe.c
- src/libponyc/codegen/genreference.c
This change is handled in generated code and doesn't affect the runtime itself.
> Print an error message if the runtime couldn't be started

- src/libponyc/codegen/genmatch.c
- src/libponyc/expr/call.c
- src/libponyc/expr/match.c
- src/libponyc/expr/postfix.c
- src/libponyc/expr/reference.c
- src/libponyc/pass/expr.c
- src/libponyc/reach/reach.c
- src/libponyc/type/lookup.c
- src/libponyc/type/lookup.h
- src/libponyc/type/reify.c
- src/libponyc/type/reify.h
- src/libponyc/type/subtype.c
- src/libponyc/type/viewpoint.c
- src/libponyc/type/viewpoint.h
- src/libponyc/verify/call.c
This change adds support for deferred reification to the compiler. This allows AST reifications to be delayed until the reified version is actually needed.
For now this is only used for the `lookup` function. In the future, this will be used during code generation in order to avoid unnecessary AST copying and to reduce the amount of simultaneous copies, as these are the main culprits of the high memory usage of the compiler.
> Add deferred reification

- src/libponyrt/sched/scheduler.c
Prior to this commit, a scheduler thread could potentially suspend even
if it was supposed to be terminating. This commit makes it so that it
only goes down the suspend path if the thread is not terminating.
Additionally, we now set `steal_attempts = 0` on waking from a suspend
to ensure that the scheduler thread will try to steal from all other
threads prior to suspending again.
--------------
@winksaville In theory, this might fix #2445 if somehow a scheduler thread was being suspended again after being woken when it should have terminated instead.
> Don't suspend schedulers if terminating and reset steal_attempts on wake

- src/libponyc/codegen/codegen.c
- src/libponyc/codegen/genexe.c
- src/libponyrt/pony.h
- src/libponyrt/sched/start.c
This change fixes an oversight from c2557a9. If the runtime had successfully been started but exited with an exit code of -1, the error message saying that the runtime couldn't be started would be printed. This was caused by the way `pony_start` propagates errors, with a startup failure and an exit code of -1 both resulting in `pony_start` returning -1.
`pony_start` now returns a boolean indicating whether the runtime was successfully started and returns the exit code in an output parameter.
> Fix wrong runtime error message on exit code assignment

- packages/process/process_monitor.pony
This provides a fix for #2297. I was able to replicate two spurious
failures. The first was KillError thrown by _kill_child, I've changed
the code so KillError is not thrown as there is really no reasonable
recovery that can be performed.
The second spurious error I saw was in _close where @waitpid would
return an error because the _child_pid was -1. This occurs in
packages/process/_test.pony::TestFileExecCapabilityIsRequired and
::_TestNonExecutablePathResultsInExecveError which are designed to fail
and _child_pid is always -1. This causes a failure to be always be
sent asynchronously and sometimes is actually gets reported.
failure is reported
> Fix some spurious process manager test failures

- Makefile
The targets can be used to test issue #2451
These use the sub-targets stdlib-debug, stdlib to compile stdlib either
in debug or not. And stdlib-loop will execute stdlib in a forever while
loop capturing the output to stdlib-xxxx.txt where xxx is the current
date and time.
> Add test-stdlib and test-stdlib-debug targets to Makefile

- src/libponyc/pass/pass.c
- test/libponyc/lambda.cc
Lambdas and Object Literals have been marked with `AST_FLAG_PRESERVE` in order to delay their evaluation until the type of the lambda or object literal is available in the `expr` pass.
The generated type AST was never run through the syntax pass.
It seems safe to run the syntax pass on those flagged AST nodes but no other passes, as the syntax pass is not mutating the AST and only checking for syntax errors.
This fixes #2413
> Run the syntax pass on lambdas and object literals

- src/libponyc/expr/reference.c
`ast_settype` automatically frees the previous type AST so we shouldn't call `ast_free` manually afterwards.
> Fix double free in expr_typeref

- src/libponyc/codegen/gencall.c
- src/libponyc/codegen/gendesc.c
- src/libponyc/codegen/genfun.c
- src/libponyc/codegen/genheader.c
- src/libponyc/reach/reach.c
- src/libponyc/reach/reach.h
- src/libponyc/type/reify.c
- src/libponyc/type/reify.h
- test/libponyc/paint.cc
This change is a followup to abdcf2e. Instead of fully reifying functions during reachability analysis, the pass now uses deferred reification as needed.
Functions are now fully reified one at a time during code generation, instead of all at once during reachability analysis. In the future, code generation will use deferred reification as well.
This change results in a huge improvement in the memory usage of the compiler.
> Use deferred reification during reachability analysis

- README.md
- src/libponyc/codegen/codegen.c
- src/libponyc/codegen/host.cc
Prior to this commit, we could accidentally trigger llvm bug 30542
(https://bugs.llvm.org/show_bug.cgi?id=30542) on a cpu with the
`avx512f` feature. See https://github.com/WallarooLabs/wallaroo/issues/1925
for one particular example of this occurring.
This commit automagically disables `avx512f` if the LLVM in use is
below version 5.0.0 to work around the issue.
> Disable -avx512f on LLVM < 5.0.0 to avoid LLVM bug 30542

- src/libponyrt/actor/actor.c
- src/libponyrt/gc/cycle.c
- src/libponyrt/gc/cycle.h
Prior to this commit, the cycle detector would try and check for
cycles while processing actor `block` messages. This resulted in
a memory backup because the cycle detector was not able to keep
up with the incoming block/unblock messages.
This commit changes how the cycle detector works so that it no
longer tries to check for cycles while processing `block` messages.
Now, it queues all actors that need checking for cycles in its
deferred hashmap and then processes them once after it has gone
through all block/unblock messages that were waiting in its queue
when it started.
------------------------
NOTE: I don't believe this does anything to fundamentally change the behavior of cycle detector (i.e. I don't think I broke it), but it would be great if @sylvanc (or someone else knowledgeable) …
> Fix cycle detector memory issue with actor block/unblock messages

- src/common/threads.h
- src/libponyc/options/options.c
- src/libponyrt/platform/threads.c
- src/libponyrt/sched/scheduler.c
Prior to this commit, the pthreads variant of the dynamic scheduler
scaling functionality didn't use pthread condition variables
correctly for the logic required. It relied on a single pthread
condition variable for all threads to sleep against. Unfortunately,
there's no way to wake up a specific thread when relying on pthread
condition variables and the operating system is free to wake up any
thread that is sleeping against a pthread condition variable. This
resulted in out of order waking of sleeping threads which broke one
of the invariants for how dynamic scheduler scaling is supposed to
work.
This commit fixes the code to create a separate pthread condition
variable for each scheduler thread ensure that we can wake up a
specific single thread at a time correctly.
This commit also …
> Fix pthread condition variable usage for dynamic scheduler scaling

- .travis.yml
packages are unavailable for download.
For normal CI, when I can, I'll move to a docker image running on
CircleCI. Need to come up with a more reliable location to get 3.9.1
package from for release builds. I'm trying to grab a couple copies from
them asap so we can figure that out.
> Temporarily turn off LLVM 3.9.1 builds on Linux

- examples/producer-consumer/buffer.pony
- examples/producer-consumer/consumer.pony
- examples/producer-consumer/producer.pony
- packages/builtin/env.pony
By making Env expose and rely on the OutStream interface it becomes
possible to create mock environments for testing. For example one can
implement an OutStreamStringAccumulator that accumulates output to a
String that can then be checked in a unit test.
Currently the 'create()' method is provided in order to build an
'artificial' environment. This simply extends this ability to support
providing alternative 'out' and 'err' stream implementations.
> Expose OutStream rather than StdStream in Env

- .ci-dockerfiles/shellcheck/Dockerfile
- .ci-dockerfiles/shellcheck/README.md
- .circleci/config.yml
- .travis_install.bash
CircleCI jobs are quite quick to fire up. TravisCI jobs on the other
hand are not; particularly MacOS jobs.
This commit moves our shellscript validate from running as part of MacOS
CI jobs to it's own CircleCI job.
This means:
If shellcheck reports and error. Other CI tasks will still run.
Additionally, I updated the logic that runs shellcheck to validate all
'*.bash' files rather than the more limited directory based set of our
previous logic.
No longer will we wait a long time to get MacOS resources on CircleCI
and have it fail because a new addition to a shellscript doesn't pass
shellcheck. In the future, the quick to fire up CircleCI task will fail
and standard MacOS CI tasks can run to completion.
> Validate shellscripts in their own CircleCI job

- Makefile
- README.md
- packages/crypto/digest.pony
- packages/net/ssl/_ssl_init.pony
- packages/net/ssl/_ssl_versions.pony
- packages/net/ssl/ssl_context.pony
- packages/net/ssl/ssl_versions.pony
- packages/net/ssl/x509.pony
- src/libponyc/options/options.c
- src/libponyc/pkg/buildflagset.c
- src/libponyc/pkg/buildflagset.h
- src/ponyc/main.c
This resolves issue [#1838](https://github.com/ponylang/ponyc/issues/1838)
> Support OpenSSL 1.1.0

- .ci-dockerfiles/openssl-1.1.0/Dockerfile
- .ci-dockerfiles/openssl-1.1.0/README.md
- .circleci/config.yml
Our standard tests all use OpenSSL 0.9. We don't use the full matrix as
we decided that LLVM version shoudn't matter for what these tests might
catch as failures.
Closes #2501
> Add CircleCI job for testing Pony with OpenSSL 1.1.0

- src/common/threads.h
- src/libponyc/options/options.c
- src/libponyrt/asio/event.c
- src/libponyrt/platform/threads.c
- src/libponyrt/sched/scheduler.c
- src/libponyrt/sched/scheduler.h
Change dynamic scheduler scaling implementation in order to resolve
the hangs encountered in #2451.
The previous implementation assumed that signalling to wake a thread
was a reliable operation. Apparently, that's not necessarily true
(see https://en.wikipedia.org/wiki/Spurious_wakeup and
https://askldjd.com/2010/04/24/the-lost-wakeup-problem/). Seeing
as we couldn't find any other explanation for why the previous
implementation was experiencing hangs, I've assumed it is either
because of lost wake ups or spurious wake ups and redesigned the
logic accordingly.
Now, when a thread is about to suspend, it will decrement the
`active_scheduler_count` and then suspend. When it wakes up, it will
check to see if the `active_scheduler_count` is at least as big as
its `index`. If the …
> Fix and re-enable dynamic scheduler scaling

- src/libponyc/codegen/genprim.c
- test/libponyc/codegen.cc
- test/libponyc/util.cc
This change fixes a bug where an incorrect attribute was being generated on primitive types used with `DoNotOptimise`.
Closes #2493.
> Fix LLVM IR verification with DoNotOptimise
